### ISSUE TITLE
Provide Proguard rules

### ISSUE THREAD

**Issue by owcs** [Adyen/adyen-android#1]
In release builds, `com.adyen.ui.DefaultPaymentRequestListener` and `com.adyen.ui.DefaultPaymentRequestDetailsListener` are removed by Proguard. This causes payment request to fail.

**Comment by timon-langlotz** [comment]
Dear @owcs and @xiaoxiaohua333,

the answer I have given earlier is unfortunately not fully correct. The correct Proguard rules are:
```
-keep public class com.adyen.ui.DefaultPaymentRequestListener {*;}
-keep public class com.adyen.ui.DefaultPaymentRequestDetailsListener {*;}
```

Please let us know if this fixes the issue!

Regards,
Timon

**Comment by xiaoxiaohua333** [comment]
Hi @timon-langlotz ,
thanks, fixes the issue~

**Comment by timon-langlotz** [comment]
We have added ProGuard rules in the Readme!

Regards,
Timon
