### ISSUE TITLE
Adyen 2.4.8 (Threeds) NullPointerException on 'mTransation' when trying to 'presentChallenge'

### ISSUE THREAD

**Issue by gmorales** [Adyen/adyen-android#101]
When calling `presentChallenge` method from `Card3DS2Authenticator` I'm getting this NPE error:
```
java.lang.NullPointerException: Attempt to invoke interface method 'void com.adyen.threeds2.Transaction.doChallenge(android.app.Activity, com.adyen.threeds2.parameters.ChallengeParameters, com.adyen.threeds2.ChallengeStatusReceiver, int)' on a null object reference
        at com.adyen.checkout.threeds.Card3DS2Authenticator.presentChallenge(Card3DS2Authenticator.java:171)
        at com.adyen.checkout.threeds.Card3DS2Authenticator.presentChallenge(Card3DS2Authenticator.java:151)
        at com.shpock.elisa.buynow.checkout.CheckoutActivity.challengeShopper(CheckoutActivity.kt:375)
```
It's because **mTransaction** is null in this line code line:
```
mTransaction.doChallenge(mActivity, challengeParameters, new ListenerDelegate(listener), challengeTimeOut);
```
This is being fired after fingerprint.

I also saw that in code **createTransaction()** is being called after **closeTransaction()** onPostExecute method.

**Comment by caiofaustino** [comment]
Hey, so you are using the standalone module for `threeds`?
Do you have any more information on the flow that happens for that error to occur? Is your Activity being destroyed?

**Comment by gmorales** [comment]
No, activity is not being destroyed.

This are my dependencies:
```
/** Adyen Checkout **/
implementation "com.adyen.checkout:core:2.4.8"
implementation "com.adyen.checkout:core-card:2.4.8"
implementation "com.adyen.checkout:util:2.4.8"
implementation "com.adyen.checkout:threeds:2.4.8"
```

And this are the methods that I'm using:
```
private fun anotherMethod() {
paymentHandler.setAuthenticationHandler(this) {
            when (it.resultCode) {
                PaymentResultCode.IDENTIFY_SHOPPER -> identifyShopper(it.getAuthentication(FingerprintAuthentication::class.java).fingerprintToken)
                PaymentResultCode.CHALLENGE_SHOPPER -> challengeShopper(it.getAuthentication(ChallengeAuthentication::class.java).challengeToken)
                else -> return@setAuthenticationHandler
            }
        }
}

private fun challengeShopper(encodedChallengeToken: String) {
        card3DS2Authenticator.isReleased.let {
            card3DS2Authenticator = Card3DS2Authenticator(this)
        }
        card3DS2Authenticator.presentChallenge(encodedChallengeToken, object : Card3DS2Authenticator.SimpleChallengeListener() {
            override fun onSuccess(challengeResult: ChallengeResult) {
                card3DS2Authenticator.release()
                val challengeDetails = ChallengeDetails(challengeResult.payload)
                paymentHandler.submitAuthenticationDetails(challengeDetails)
            }

            override fun onFailure(exception: ThreeDS2Exception) {
                card3DS2Authenticator.release()
            }
        })
    }
```
Card3DS2Authenticator is not null. Also when checking if `card3DS2Authenticator` has been released `mTransaction` is not null. But after invoke `presentChallenge then `mTransaction` becomes `null`. I also could see that `createFingerprint` create a transaction, but `presentChallenge` never creates a new one. Neither check if is null.

**Comment by caiofaustino** [comment]
So the challenge flow needs to be done with the same instance of the identify flow. `card3DS2Authenticator` can not be released and recreated again.

It seems weird that the `mTransaction` would become null when you call `presentChallenge`. Maybe there is something else happening? Can you check if the `onFailure` is not being called for some reason?

**Comment by gmorales** [comment]
Thank you for your help. It's seems that let operator wasn't working as expected. I changed by normal `if`. Now it's working. Thank you for your time.
