### ISSUE TITLE
3D secure payment display blank screen only on production release version

### ISSUE THREAD

**Issue by logosdeborah** [Adyen/adyen-android#1017]
**Describe the bug**
Our company implemented 3D Secure payment recently and followed the documentation (https://docs.adyen.com/online-payments/3d-secure/native-3ds2/android-component#3ds2-component)

When we call `handleAction` and the screen goes blank. It's working as expected on our test environment and even on the production debug version but it's breaking only on the production release version.
The normal 3DS flow should be like the log below but since it's prod release, we are not able to catch the log or use proxy to identify the issue. Hope to have some help on this issue.

![Screenshot 2023-01-17 at 10 29 36](https://user-images.githubusercontent.com/32288547/212861555-ff277cfd-a5a6-4632-9b04-a04ceb614f2e.png)

**Smartphone (please complete the following information):**
- Device: Pixel 4
- OS: Android
- Android 12.0.0

**Additional context**
- lib version 4.9.1

**Comment by onurkaragunlu** [comment]
Hi @logosdeborah ,
Were you able to resolve this issue? If you solved the issue, could you inform us what the issue was?

**Comment by Anil9870** [comment]
Hi @logosdeborah 
Im facing the same issue in test environment. Were you able to resolve it?
