### ISSUE TITLE
Adyen 3DS 2.0 - Attempt to invoke virtual method 'android.net.Uri com.adyen.threeds2.internal.a.a.b.g.c()' on a null object reference

### ISSUE THREAD

**Issue by nichtemna** [Adyen/adyen-android#102]
Hi, I'm using Adyen checkout SDK (com.adyen.checkout:3ds2:3.2.0) for 3DS 2.0.

It was working perfectly on test credit cards, but when I tried card from Swedbank SDK started crashing while opening challenge screen.
Crash stacktrace:
[Stacktrace.txt](https://github.com/Adyen/adyen-android/files/3546861/Stacktrace.txt)

I have tried to debug but as code is obfuscated it's hard to know the issue for sure.
But I will try to provide some details.

Code that is crashing. var2 is null at this point
![Screenshot 2019-08-27 at 16 46 47](https://user-images.githubusercontent.com/3368594/63783855-f84b4e80-c8ed-11e9-82ee-af2a9a693fe6.png)

Challenge activity extras(maybe it will help to see what is null).
![Screenshot 2019-08-27 at 17 20 46](https://user-images.githubusercontent.com/3368594/63784547-1b2a3280-c8ef-11e9-9739-6418a51ac88b.png)

Lina Shyshova,
Android developer at Booking.com

**Comment by ArmanSo** [comment]
Hi @nichtemna 
We figure out what cause the issue and we're working on it.

I'll update you when version with fix got release.

**Comment by ArmanSo** [comment]
This issue fixed in version `3.2.1` @nichtemna

**Comment by caiofaustino** [comment]
Please reopen the issue if you still see it happening.
