### ISSUE TITLE
Reflect breaking changes on the release notes

### ISSUE THREAD

**Issue by gokhanbarisaker** [Adyen/adyen-android#1047]
**Describe the bug**
This is about a bug in the release process. Warning about a breaking change that is inherited through a transient dependency (adyen-3ds2-android) was missing on the release notes.

[`adyen-android` release note for version 4.9.0](https://github.com/Adyen/adyen-android/releases)
> Upgraded the 3D Secure 2 SDK version to v2.2.10.

[`adyen-3ds2-android` release note for version 2.2.10](https://github.com/Adyen/adyen-3ds2-android/releases)
> Added support for play-services-location v21.0.0. Notice! If your project uses play-services-location library, it's required to use v21.0.0 or newer as from v21.0.0 play-services-location is not backward compatible with older versions. That means that versions below v21.0.0 will not be compatible with 3DS2 SDK v2.2.10.

**To Reproduce**
n/a

**Expected behavior**
Breaking changes for a new release is reflected on the release notes.

**Screenshots**
n/a

**Comment by jreij** [comment]
Hi, thanks for reaching out, we missed this one indeed! We'll add it to the `4.9.0` release notes.

I think we'll be upgrading our 3DS2 SDK version to `2.2.11` in the next release which should not cause a breaking change when migrating to it, so anyone migrating from an version older than `4.9.0` to the upcoming version should not face this breaking change. We'll make sure to mention this in the upcoming release notes as well.

**Comment by caiofaustino** [comment]
Btw, if this is causing issues in your build you can directly declare `adyen-3ds2-android:2.2.11` as a dependency until we release the next version.

**Comment by jreij** [comment]
Release notes for `4.9.0` are updated. We also just released `4.10.0` which doesn't throw an exception when you don't upgrade your Google location library version.

**Comment by gokhanbarisaker** [comment]
Thanks!
