### ISSUE TITLE
Adyen.js exception in Android's WebView

### ISSUE THREAD

**Issue by ar7casper** [Adyen/adyen-android#107]
I'm loading a payment page via WebView on Android and my page crashes cause of adyen.js script.
It happens only on Android, web & iOS are 100% fine.

I'm using the 3.1.0 version of the adyen script.

![09_49_10](https://user-images.githubusercontent.com/5730102/64246007-ad948c80-cf14-11e9-84bd-c308ca9fc14a.jpg)
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/5730102/64246021-b4bb9a80-cf14-11e9-955c-e42cb1991d79.png">

**Comment by ArmanSo** [comment]
Hi @ar7casper as I talked with our frontend developers, they planning to release a version to fix this issue. I'll keep you posted

**Comment by caiofaustino** [comment]
My colleagues said this was fixed in version 3.2 of the Web Components. Please contact support if you still have issues, this is not related to the Android Components.
