### ISSUE TITLE
Handling RedirectShopper with Classic Integration

### ISSUE THREAD

**Issue by sasindroid** [Adyen/adyen-android#108]
Hello team, Can you pls guide me 3ds1 integration for handling RedirectShopper?

Background:
1. We use classic integration for backend.
2. We recently integrated the adyen-3ds2-android for handling 3ds2 using our classic integration and it works fine.

Scenario:
1. The purchase transactions are made on a "**saved card**" only.

Questions:
1. Because of Classic integration, we cannot use the SDK or the RedirectComponent. Is my understanding correct?
2. Any suggestion on how I should proceed with this? The documentation doesn't talk about Classic integration for apps.

Thanks.

**Comment by caiofaustino** [comment]
Sorry can you clarify what you mean by classic integration? What endpoint is being used to make the payment?

**Comment by sasindroid** [comment]
1. A call to /authorise on a 3ds1 card returns the resultCode `RedirectShopper` with `md` and `paRequest`.
2. To handle this `RedirectShopper` in the Android app, I have to take browser based approach. I build a html below and load it in a WebView.

`<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Adyen - Create 3D Secure Payment</title>
</head>
<body onload="document.getElementById('3dform').submit();">
<form method="POST" action="https://test.adyen.com/hpp/3d/validate.shtml" id="3dform">
  <input type="hidden" name="PaReq" value="eNpVUttygjAQ/RXruySk4IVZM4MyY3nQMlYf+tShcUFsuRhCq3/fBKG2yUxmz9lLNmcDu6NEDF5QNBI5rLGu4xQH2WE+9KYuc8dTqg9GGZ0FQw6Rv8Uzhy+UdVYW3LaoxYD0UKdLcYwLxSEW50W44TZ7dNwxkA5CjjIM+A5rFeW5L85NJlECudFQxDnyvf/mLx+8VZrHI1VWTZW+j4paAGm9IMqmUPLKp0yX7QE08pMflao8QtIsSdI4SSxRWs0HEOMCcu8saoxV61KX7MCfg/11s3t11kFob07h9/rku1u/XXMgJgIOsULOqD2jeg9s6jnUYxRIy0Ocmx74ahENbNeimu8YqMxF/g3YrvH8ZUALLrEQ/Ut6BHipygJ1hBb21wZyb3v5ZOQVSivmsJvAk+mMamtihG4dpkqmhdFt07aMAUBMKulmSLpZa+vfH/gBFvKsqg=="/>
  <input type="hidden" name="MD" value="L21SRFg5SVhrZUxXVlFWcXdSRW9rQT09IVh9UIgcraVuPc89l6qxuzN3ElK2Qt-XhGJEp-kAiF83Xxj-9YVGdFV6lG9Sd00vhNvd9czJry3eqB4uEwNY-AcE_9I7XHqReIRRBtQL3TJBL8VZq5PwcFvxhQghuVG4VdLM_LIM_uSVDeqCX1AFdHzIIzQvysgQeahppyCdgKThtymaZoTaPQ844VpRh8ubSajAQSS43mNwauyU1O8M0wvWj2e5JbYQdMWPwJNwZFcurWtO0Z7DiRBj9NETs-TFuaxFRtHL8hcIlww6-QjJKLlJAkbp6YqaH4tvsgWTtE1-6VjVDNYhmTAizuRtU5E6-wqVmUa6leCISKtauosWQPC4WG0Rc5Qir3twgszyzrP8UNrvpsOQoUb25iJfCHkZxs14VMRLfun_FsOYgEJyvqJ30VvpmOaXYQZFt1n-iX1XwtE6D_ktPgHw8qwNNob9XyAAeMrJ"/>
  <input type="hidden" name="TermUrl" value="adyencheckout://com.sasi.threeds1"/>
  <noscript>
    <br>
    <br>
    <div style="text-align: center">
      <h1>Processing your 3D Secure Transaction</h1>
      <p>Please click continue to continue the processing of your 3D Secure transaction.</p>
      <input type="submit" class="button" value="continue"/>
    </div>
  </noscript>
</form>
</body>
</html>
`
3. Once I enter the username and password, I expect a response on my activity deep linked to the TermUrl.

By Classic integration, I mean we use 'authorise' endpoints and not 'Online Payments'.

**Comment by caiofaustino** [comment]
Can you please check if you also get the `issuerUrl` parameter in the response?
I'm not very familiar with the Classic integration flow, but my understanding is that you'd need to open the Browser/WebView to that URL hosted by the issuing bank to perform the authentication.

**Comment by sasindroid** [comment]
Thanks for your inputs @caiofaustino 

Yes, we have the issuerUrl as well. I create a html with form action as below.
`<form method="POST" action="https://test.adyen.com/hpp/3d/validate.shtml" id="3dform">`

The problem is, I provide a `TermUrl` which is basically deep linked to an activity in my app. As per the documentation, on successful authentication adyen will do a http post to the TermUrl.
The http post returns a `md` and `paRes` which will be passed to /authorise3d endpoint.

Any other thoughts on how to approach this?

**Comment by caiofaustino** [comment]
That seems to be correct to me, can you double check how are you doing the deep link? Do you have an `IntentFilter` setup corretly? We have an example [here](https://docs.adyen.com/checkout/3d-secure/redirect-3ds2-3ds1#submit-a-payment) for a similar flow.

Maybe try troubleshooting the webview, add a `setWebViewClient()` and see if it's trying to redirect, and which URL it gets stuck on. If I'm not mistaken on a WebView you need to intercept the redirect and call the intent manually. Alternatively you can try using [Custom Tabs](https://developer.chrome.com/multidevice/android/customtabs).

Hope that helps, let me know if I can help investigate more.

**Comment by sasindroid** [comment]
Thank you, I will give it a try.

**Comment by caiofaustino** [comment]
Hey @sasindroid, did you have any luck?

**Comment by caiofaustino** [comment]
I'm closing the issue since there were no updates, hope you found a fix :)
otherwise feel free to just open it again
