### ISSUE TITLE
ClassNotFoundException androidx.constraintlayout.widget.helper.Flow (Drop-in SDK 3.3.0)

### ISSUE THREAD

**Issue by geertjan-tiqets** [Adyen/adyen-android#109]
I updated to Drop-in SDK 3.3.0, and having some trouble with the new ConstraintLayout beta it's using.

First I got a compile error, but that was quickly solved by updating the version of ConstraintLayout we are using from 1.1.3 to 2.0.0-beta2, to match the version from the Adyen SDK.

Now however I'm getting a crash when I try to open the credit card screen. The relevant parts:

`android.view.InflateException: Binary XML file line #9: Error inflating class com.adyen.checkout.card.DropInCardView`

`java.lang.ClassNotFoundException: Didn't find class "androidx.constraintlayout.widget.helper.Flow" on path: ...`

Possibly the problem comes from Android's Jetifier transform tool. The Adyen SDK is using the old `android.support.constraint.ConstraintLayout`, while our app uses AndroidX. So the Jetifier tool is converting the ConstraintLayout in Adyen to AndroidX. Maybe Jetifier isn't updated to work with the ConstraintLayout 2.0.0 beta yet.

Would it be possible for the Adyen SDK to start using AndroidX too?

**Comment by ArmanSo** [comment]
@geertjan-tiqets we fixed issue in version 3.1.1.

**Comment by geertjan-tiqets** [comment]
Thanks, it's working!
