### ISSUE TITLE
Not Recognize Elo's card

### ISSUE THREAD

**Issue by DiegopalmaRentcars** [Adyen/adyen-android#1106]
**Describe the bug**
Adyen's card view not recognize some elo's card (Test Environment)
Example:
4514 1663 6344 1452

This card number is valided by Elo's regex
https://regex101.com/r/213D6y/1

**Screenshoot**

![Captura de tela de 2023-03-06 13-48-34](https://user-images.githubusercontent.com/52252518/223177155-e5694af6-17cf-4a49-a26f-47a9253ae400.png)

**Expected behavior**
Recognize Elo's card

**Additional context**
We use
  implementation "com.adyen.checkout:card:4.10.0"

**Comment by OscarSpruit** [comment]
Hi @DiegopalmaRentcars, thanks for raising an issue! On the test environment not all (valid) card numbers are recognised. The test Elo card `5066 9911 1111 1118` does work (can be found on [this page](https://docs.adyen.com/development-resources/testing/test-card-numbers#elo). On the live environment this won't be an issue.

**Comment by OscarSpruit** [comment]
Closing this issue because it has been inactive for a while.

Please reopen if you still encounter this issue with the latest version.

Thank you!
