### ISSUE TITLE
Bancontact card holder name focus resets card number error 

### ISSUE THREAD

**Issue by ilian-move** [Adyen/adyen-android#1119]
**Describe the bug**
When displaying the BcmcView (using a configuration with a required holder name required), the focus gained action on of the card holder field resets the card number field instead.

https://github.com/Adyen/adyen-android/blob/4.10.0/bcmc/src/main/java/com/adyen/checkout/bcmc/BcmcView.java#L233

When the user enters an invalid card number and switches to the card holder field, the card number error is briefly shown and then reset. The name on card error however will never be reset when gaining focus.

**Expected behavior**
The card holder field error should be reset instead.

**Version:**
 - Version: `com.adyen.checkout:bcmc:4.10.0`

**Comment by OscarSpruit** [comment]
Hi @ilian-move thank you for raising this issue! That is a sloppy mistake on our side... We will fix it soon, so it can be shipped with next release

**Comment by OscarSpruit** [comment]
The fix is part of `4.11.0`, which was just released. Closing the issue, but feel free to re-open it if you encounter more issues.
