### ISSUE TITLE
How we can get last 4 numbers of  CardNumber and get ExpiryYear for display in UI?

### ISSUE THREAD

**Issue by Kolyall** [Adyen/adyen-android#114]
I we use api-only https://docs.adyen.com/checkout/api-only , and send to our server payment data as encrypted, how we can get last 4 numbers of  CardNumber and get raw ExpiryYear for display in UI?
```
┌────── Request ────────────────
│ URL: https://checkout-test.adyen.com/v49/payments
│
│ Method: @POST
│
│ Headers:
│ ─ x-API-key: API_KEY
│
│ Body:
│ {
│    "additionalData": {
│       "allow3DS2": "false"
│    },
│    "amount": {
│       "currency": "EUR",
│       "value": 1337
│    },
│    "channel": "android",
│    "merchantAccount": "merchantAccount",
│    "paymentMethod": {
│       "encryptedCardNumber": "adyenan0_1_1$",
│       "encryptedExpiryMonth": "adyenan0_1_1$",
│       "encryptedExpiryYear": "adyenan0_1_1$",
│       "encryptedSecurityCode": "adyenan0_1_1$",
│       "holderName": "Holder Name",
│       "type": "scheme"
│    },
│    "reference": "android-test-components",
│    "returnUrl": "adyencheckout:\/\/com.github.adyenexample",
│    "shopperReference": "",
│    "storePaymentMethod": true
│ }
└──────────────────────
```

**Comment by caiofaustino** [comment]
Well, the idea of APi only is that you are using your own UI to gather the credit card information, so you should have gathered that to encrypt.

If you are using the Card Component or the Drop-in, then you are using the Component View, and it will display that to the user.

I'm not sure if I understand your question.

**Comment by Kolyall** [comment]
If we are using the Card Component, after make recurrent payment we send to our server encrypted card data. How we can receive last 4 numbers of Card to display it?
![asd](https://user-images.githubusercontent.com/3495165/65771630-52d00880-e141-11e9-8955-7bea62e6bbde.png)

**Comment by Kolyall** [comment]
@caiofaustino look, pls

**Comment by caiofaustino** [comment]
So if you have saved the card as recurring, when you make the `paymentMethods/` call, if you pass the `shopperReference` in the call it will return to you the stored payment methods for that shopper.
https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v50/paymentMethods__example_paymentMethods-include-oneclick

```json
"storedPaymentMethods": [
    {
      "brand": "visa",
      "expiryMonth": "10",
      "expiryYear": "2020",
      "holderName": "John Smith",
      "id": "8415689021960227",
      "lastFour": "1111",
      "name": "VISA",
      "supportedShopperInteractions": [
        "Ecommerce",
        "ContAuth"
      ],
      "type": "scheme"
    }
  ]
```

Is this what you are looking for?

**Comment by ArmanSo** [comment]
@Kolyall Can you please give us an update about this issue?

**Comment by Kolyall** [comment]
@ArmanSo @caiofaustino sorry, I'm late, was on vacation. 
The sample doesn't work
![FireShot Capture 001 - API Explorer - Adyen Docs - docs adyen com](https://user-images.githubusercontent.com/3495165/66736356-99c43a80-ee71-11e9-8334-362f9fd821ec.png)

**Comment by caiofaustino** [comment]
The JSON I sent you is part of the response, not the request, I was just pointing it out to make it easier to find.
![Screen Shot 2019-10-14 at 10 09 59](https://user-images.githubusercontent.com/3094935/66736961-f40dcd00-ee6a-11e9-9ad0-dfce4d55dfa0.png)

**Comment by Kolyall** [comment]
Oh, ok, now understood. So if we use api-only https://docs.adyen.com/checkout/api-only , and send to our server payment data as encrypted, after that our server should send to Adyen server payment data with UNIQUE ID `shopperReference`, then our server will receive `storedPaymentMethods`?

**Comment by caiofaustino** [comment]
Yes that's right. And since the Component is already meant to be used with the API it shouldn't be a big change for you I assume, you will still use the component to get the encrypted data.

**Comment by kinguru** [comment]
Is there a way to receive some details during drop-in payment.
Session is configured to store payment method. And webhook has some data about it. Could webhook contain more data about stored card (lastFour, expiration date?)

**Comment by jreij** [comment]
Hi @kinguru, please reach out to [our support team](https://support.adyen.com/hc/en-us/requests/new?ticket_form_id=360000705420) and they should be able to help answer your question better.
Web hooks are not managed by the Android SDK but if you have any Android related questions please let us know.
