### ISSUE TITLE
Wrong background color in all Drop-In dialogs

### ISSUE THREAD

**Issue by popov-sa** [Adyen/adyen-android#1141]
**Describe the bug**
Wrong background color in all Drop-In dialogs.
Somehow default background color of all Drop-In dialogs has been overridden by the default background color from our app's theme.

**To Reproduce**
I haven't figured out what's going wrong yet so I can't provide any correct steps to reproduce this bug.
If there will be some new information I'll post it here.

**Expected behavior**
The background color of Drop-In dialogs should be white or light.

**Screenshots**
- https://imgur.com/a/qMQtAou
- https://i.imgur.com/1M9HMkm.jpeg

**Comment by onurkaragunlu** [comment]
Hi @popov-sa, thank you for reaching out! The background is indeed supposed to be white, so your app theming might be overriding our theming somehow. Could you share the setup of your app's theming with us?

**Comment by popov-sa** [comment]
Hi @onurkaragunlu, thank you for your response!
Finally I found the bug 😊
I don't know what is actually going on under the hood, but it looks like it's a bug on the Material Theme side.

So, we have a drawable file in our project.
Here is the content of this file:
```
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <corners
        android:topLeftRadius="16dp"
        android:topRightRadius="16dp"
        android:bottomLeftRadius="16dp"
        android:bottomRightRadius="16dp"/>
    <padding android:top="10dp" />
    <solid android:color="#0B1E28" />
</shape>
```
So, it's a regular shape.
And it's named `bg_bottom_sheet_dialog_fragment.xml`.
And I think that is the reason.
When I renamed this file, the background became white, as it should be.

It looks like Material Theme is using same name for bottom sheet shape, and somehow our shape is overriding default Material Theme shape.

I don't think any modification is required on your part.
You can close the issue.
So that's it.
Thank you for your time.
