### ISSUE TITLE
Card`s info not stored fot next time

### ISSUE THREAD

**Issue by GNNikolov** [Adyen/adyen-android#116]
I do set card`s input successfully, than before committing a payment, I set the toggle to save my card details for next time. However, when I want to commit a payment next time, when I click on Credit Card`s payment method cards`details were not saved, Why is this happening?

**Comment by caiofaustino** [comment]
I assume you are using the Drop-in implementation right?

So the card information is stored for each specific merchant, and you are responsible for making the API calls to `paymentMethods/` `payments/`, where you need to pass the `shopperReferece`. 

So if you made a payment with `shopperReference:"<shopper-id>"`, then for the next time you need to make the `paymentMethods/` call passing that same ID, then on the response it will give you the stored payment method from the previous payment of that specific shopper.

**Comment by GNNikolov** [comment]
> `shopperReference`

Yes, I am using Drop-in. So will my card details will be saved depends on the shopperReference?

**Comment by caiofaustino** [comment]
Yeah, here are some examples.
You make the `payments/` call like [this](https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v50/payments__example_payments-enableOneClick-raw)
And then the next `paymentMethods/` call will be returned like [this](https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v50/paymentMethods__example_paymentMethods-include-oneclick)
You can click on `Run` there to see the format of the response. Notice that on the `paymentMethods/` response you now get a `storedPaymentMethods` array.

**Comment by GNNikolov** [comment]
> 
> 
> Yeah, here are some examples.
> You make the `payments/` call like [this](https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v50/payments__example_payments-enableOneClick-raw)
> And then the next `paymentMethods/` call will be returned like [this](https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v50/paymentMethods__example_paymentMethods-include-oneclick)
> You can click on `Run` there to see the format of the response. Notice that on the `paymentMethods/` response you now get a `storedPaymentMethods` array.

I tried to hardcode the shopperReference field on all calls, but data is not saved

**Comment by caiofaustino** [comment]
Then I'd say try to contact support to see if there is any problem happening on the backend.
From the Drop-in perspective, if there is the `storedPaymentMethods` array in the `PaymentMethodsApiResponse` you pass in the `startPayment()` call, it should show up.

**Comment by GNNikolov** [comment]
> 
> 
> Then I'd say try to contact support to see if there is any problem happening on the backend.
> From the Drop-in perspective, if there is the `storedPaymentMethods` array in the `PaymentMethodsApiResponse` you pass in the `startPayment()` call, it should show up.

I am using your test server for now.

**Comment by GNNikolov** [comment]
> 
> 
> > Then I'd say try to contact support to see if there is any problem happening on the backend.
> > From the Drop-in perspective, if there is the `storedPaymentMethods` array in the `PaymentMethodsApiResponse` you pass in the `startPayment()` call, it should show up.
> 
> I am using your test server for now.

I do receive: storedPaymentMethods

**Comment by GNNikolov** [comment]
> 
> 
> Then I'd say try to contact support to see if there is any problem happening on the backend.
> From the Drop-in perspective, if there is the `storedPaymentMethods` array in the `PaymentMethodsApiResponse` you pass in the `startPayment()` call, it should show up.

Everythink is OK with the storedPaymentMethods - I receive them, but how to display them to user? Is there such a UI inside the library, or I have to provide it by myself?

**Comment by caiofaustino** [comment]
They should be displayed automatically. Here is an example of how they look like.
Can you share a bit more on how you are initializing the DropIn? How you setup the configurations etc...
![image](https://user-images.githubusercontent.com/3094935/66121072-9c56a280-e5dc-11e9-829c-c88fcabf1e17.png)

**Comment by GNNikolov** [comment]
> 
> 
> They should be displayed automatically. Here is an example of how they look like.
> Can you share a bit more on how you are initializing the DropIn? How you setup the configurations etc...
> ![image](https://user-images.githubusercontent.com/3094935/66121072-9c56a280-e5dc-11e9-829c-c88fcabf1e17.png)
- This is what I POST to  /paymentMethods:

  private fun buildJson(paymentSession: PaymentSession) = JSONObject().apply {
        put(MACCOUNT, mContext.getString(R.string.merchant_account))
        put(COUNTRYCODE, paymentSession.countryCode)
        put(CHANNEL, "Android")
        put(REFERENCE, "test_hardcoded_ref")
        put(AMOUNT, Amount.SERIALIZER.serialize(paymentSession.amont))
    }

- This is how init Drop-In:
 val cardConfiguration = CardConfiguration .Builder(Locale.getDefault(), com.adyen.checkout.core.api.Environment.TEST, mContext.getString(R.string.adyen_public_api))
                    .setShowStorePaymentField(true)
                    .build()
            val resultIntent = Intent(mContext, MainActivity::class.java).apply {
                flags = Intent.FLAG_ACTIVITY_CLEAR_TOP or Intent.FLAG_ACTIVITY_SINGLE_TOP
            }
            val googlePayConfiguration = GooglePayConfiguration
                    .Builder(Locale.getDefault(), com.adyen.checkout.core.api.Environment.TEST, mContext.getString(R.string.merchant_account)).build()
            val dropInConfiguration = DropInConfiguration.Builder(mContext, resultIntent, PaymentService::class.java)
                    .addGooglePayConfiguration(googlePayConfiguration)
                    .addCardConfiguration(cardConfiguration).build()
            DropIn.startPayment(mContext, paymentSession.apiResponse!!, dropInConfiguration)

**Comment by caiofaustino** [comment]
Can you check if `paymentSession.apiResponse.storedPaymentMethods[0].isEcommerce()` is true? Or maybe print the result of this
```
val storedDetail:RecurringDetail = paymentSession.apiResponse.storedPaymentMethods[0]
        Log.d("TEST", RecurringDetail.SERIALIZER.serialize(storedDetail).toString(4))
```
```

**Comment by GNNikolov** [comment]
> 
> 
> Can you check if `paymentSession.apiResponse.storedPaymentMethods[0].isEcommerce()` is true? Or maybe print the result of this
> 
> ```
> val storedDetail:RecurringDetail = paymentSession.apiResponse.storedPaymentMethods[0]
> Log.d("TEST", RecurringDetail.SERIALIZER.serialize(storedDetail).toString(4))
> ```

It`s false.

**Comment by GNNikolov** [comment]
> 
> 
> > Can you check if `paymentSession.apiResponse.storedPaymentMethods[0].isEcommerce()` is true? Or maybe print the result of this
> > ```
> > val storedDetail:RecurringDetail = paymentSession.apiResponse.storedPaymentMethods[0]
> > Log.d("TEST", RecurringDetail.SERIALIZER.serialize(storedDetail).toString(4))
> > ```
> 
> It`s false.

The printed JSON is:

  {
        "name": "MasterCard",
        "supportsRecurring": false,
        "type": "scheme",
        "id": "8315700244324231",
        "expiryMonth": "10",
        "expiryYear": "2020",
        "lastFour": "1111",
        "brand": "mc",
        "supportedShopperInteractions": [
            "ContAuth"
        ]
    }

**Comment by caiofaustino** [comment]
Yeah OK so that's the problem. I don't know how the Merchant Account you are using is configured, but it is saving the card for recurring payments, but not for One Click payments.

What test server did you mention you were using?

**Comment by GNNikolov** [comment]
> 
> 
> Yeah OK so that's the problem. I don't know how the Merchant Account you are using is configured, but it is saving the card for recurring payments, but not for One Click payments.
> 
> What test server did you mention you were using?

The classic one: https://checkout-test.adyen.com/v49/paymentMethods

**Comment by caiofaustino** [comment]
Ah OK, that's the Test API endpoint, so you are making the POST call with your API key from the App directly. 

For security reasons we recommend that you make that connection from a server in your final Live setup, so that way you can also make additional processing and only pass to the App the data that is required for user interactions, and you don't pass in sensitive data. While also keeping your data like the API key more safe.

**Comment by GNNikolov** [comment]
> 
> 
> Ah OK, that's the Test API endpoint, so you are making the POST call with your API key from the App directly.
> 
> For security reasons we recommend that you make that connection from a server in your final Live setup, so that way you can also make additional processing and only pass to the App the data that is required for user interactions, and you don't pass in sensitive data. While also keeping your data like the API key more safe.

Yes, but is this the reason for the problem - that I make the request directly from the Test API?

**Comment by caiofaustino** [comment]
No, the problem is in the configuration on the Merchant Account you are using. I think it's easier to contact support, they have the ability to change your account settings.

Just tell them you want to make the recurring contracts available for Ecommerce.

**Comment by GNNikolov** [comment]
> 
> 
> No, the problem is in the configuration on the Merchant Account you are using. I think it's easier to contact support, they have the ability to change your account settings.
> 
> Just tell them you want to make the recurring contracts available for Ecommerce.

Thank you very much!
