### ISSUE TITLE
How to catch cancelation trustly payment type

### ISSUE THREAD

**Issue by dvasea1** [Adyen/adyen-android#117]

**Comment by caiofaustino** [comment]
Can you be a little more specific? Are you using Drop-in or Components? What do you want to do with the cancellation?

**Comment by dvasea1** [comment]
when i click Pay, inside makePayments method i do: 
 return new CallResult(CallResult.ResultType.ACTION, new Gson().toJson(paymentResponse.getValue().getPayment().getAction()));
and new intent with list of banks is open, but when i click cancel, the intent is closing, but the loading still remaining. How to cancel this loading?

**Comment by caiofaustino** [comment]
In the current version there is a timeout of about 10s because on that flow we were not sure if it was a back or if it could be a different scenario with internet delay.

We fixed that for the next version that should be available early next week.

**Comment by dvasea1** [comment]
OK good, thanks

**Comment by ArmanSo** [comment]
@dvasea1 Timeout got removed in version 3.4.1

**Comment by dvasea1** [comment]
Very good. tested now, it's ok. thnx.
