### ISSUE TITLE
Gettin this error "Error(error=com.checkout.threedsecure.error.ThreeDSError: Not Found)"

### ISSUE THREAD

**Issue by khushalvaghasiya** [Adyen/adyen-android#1205]
I am using the below library,

// module gradle file
dependencies {
    implementation 'com.github.checkout:frames-android:<latest_version>'
}

in 3DS redirectin getting this **Error(error=com.checkout.threedsecure.error.ThreeDSError: Not Found)**

![image](https://user-images.githubusercontent.com/48145357/236795201-115b1612-7e5e-4c92-abf4-874ce9ec2369.png)

**Comment by jreij** [comment]
Hi @khushalvaghasiya , this is not the Adyen library, our packages start with `com.adyen.checkout` and `com.adyen.threeds`.

**Comment by khushalvaghasiya** [comment]
Hi @jreij 

hear I have set the wrong URL on Susess or Falier that's why I getting this error.
