### ISSUE TITLE
Drop-in - WeChat Pay

### ISSUE THREAD

**Issue by tinsukE** [Adyen/adyen-android#121]
We're currently using the Drop-in implementation 3.4.1 and trying to enable WeChat Pay as a payment method.

Our Backend is working on their end of things, but we wonder if there is anything we need to do client-side.

The documentation on how to do this In-App seems outdated, as it seems to refer to the Adyen SDK 2:
https://docs.adyen.com/payment-methods/wechat-pay/wechat-pay-in-app-payments

Do we need to follow any of the steps listed there, like [this](https://docs.adyen.com/payment-methods/wechat-pay/wechat-pay-in-app-payments#integrate-wechats-mobile-sdks)? Or can I rely on the [Drop-in description](https://github.com/Adyen/adyen-android#drop-in)?
> The Drop-in is the implementation that handles the presentation of all available payment methods and the subsequent entry of a customer's payment details.

**Comment by caiofaustino** [comment]
Hey, 
Yeah that documentation is from version 2 so it's not applicable to Components/Drop-In.

The WeChat Pay Component is not available yet, so it was not supported, but lucky enough I just finished it last week and we plan to release it this week. Using the Drop-in you should only need to update the version and if the phone has the WeChat App and your account is configure properly it should work out of the box.

Ii would be nice to also get some feedback from your side after we release since WeChat is a bit tricky to setup for us, so let me know if you find any issues.

I'll ping you here once we make the release.

**Comment by tinsukE** [comment]
Great news!

@caiofaustino could you also tell me if Alipay is currently supported or planned to be in Drop-in?

**Comment by caiofaustino** [comment]
As far as I know Alipay is just a redirect so it should already work. Again, let me know if you find any issues.

**Comment by caiofaustino** [comment]
Version `3.5.0` was just released. Please test on your side and let me know how it goes :)

**Comment by arturh** [comment]
@caiofaustino wechatpaySDK is not being returned as a payment option:

`## Request
curl -X "POST" "https://SECRET-Tiqets-checkout-live.adyenpayments.com/checkout/v49/paymentMethods" \
     -H 'Content-Type: application/json' \
     -H 'X-API-Key: SECRET' \
     -d $'{
  "merchantAccount": "TiqetsCOM",
  "countryCode": "CN",
  "shopperLocale": "en_US",
  "amount": {
    "currency": "EUR",
    "value": 1000
  },
  "shopperReference": "XXYYZZ",
  "channel": "Android"
}'
`

results in:

`{"groups":[{"name":"Credit Card","types":["amex","cup","diners","discover","jcb","maestro","mc","visa"]},{"name":"WeChatPay","types":["wechatpayQR","wechatpayWeb"]}],"paymentMethods":[{"brands":["amex","cup","diners","discover","jcb","maestro","mc","visa"],"details":[{"key":"encryptedCardNumber","type":"cardToken"},{"key":"encryptedSecurityCode","type":"cardToken"},{"key":"encryptedExpiryMonth","type":"cardToken"},{"key":"encryptedExpiryYear","type":"cardToken"},{"key":"holderName","optional":true,"type":"text"}],"name":"Credit Card","type":"scheme"},{"details":[{"key":"encryptedCardNumber","type":"cardToken"},{"key":"encryptedSecurityCode","type":"cardToken"},{"key":"encryptedExpiryMonth","type":"cardToken"},{"key":"encryptedExpiryYear","type":"cardToken"},{"key":"holderName","optional":true,"type":"text"},{"key":"telephoneNumber","optional":true,"type":"text"}],"name":"ExpressPay","supportsRecurring":true,"type":"cup"},{"name":"PayPal","supportsRecurring":true,"type":"paypal"},{"name":"UnionPay","supportsRecurring":true,"type":"unionpay"},{"name":"WeChat Pay","supportsRecurring":true,"type":"wechatpayQR"},{"name":"WeChat Pay","supportsRecurring":true,"type":"wechatpayWeb"}]}`

which includes wechatpayWeb, wechatpayQR, but not wechatpaySDK

**Comment by caiofaustino** [comment]
The currency needs to be CNY on the request.

**Comment by arturh** [comment]
@caiofaustino Just contacted Shernaz, thanks.

**Comment by markfili** [comment]
And? What did Shernaz say? Why is there no WeChat Pay SDK listed in the available payments? This thread could be the perfect spot for that answer...
