### ISSUE TITLE
Drop-in card details send to server side

### ISSUE THREAD

**Issue by GNNikolov** [Adyen/adyen-android#122]
Hello, I am implementing Drop-in for Android and I have to provide EncryptedCardNumber , EncryptedExpiryMonth , EncryptedExpiryYear in order to send them to our server (backend implementation on .NET ) in order to commit a payment. The documentation says:
--
var details = new Model.Checkout.DefaultPaymentMethodDetails{
Type = "scheme",
EncryptedCardNumber = "adyenjs_0_1_18$MT6ppy0FAMVMLH...",
EncryptedExpiryMonth = "adyenjs_0_1_18$MT6ppy0FAMVMLH...",
EncryptedExpiryYear = "adyenjs_0_1_18$MT6ppy0FAMVMLH...",
EncryptedSecurityCode = "adyenjs_0_1_18$MT6ppy0FAMVMLH..."
};
The "paymentMethod" jsonObject inside the client (Android ) side contains only type, encryptedSecurityCode and recurringDetailReference, but no encrypted card number, month and year, how can I get them?

**Comment by ArmanSo** [comment]
hi @GNNikolov 
Can you please provide us `DropInService` file?

**Comment by GNNikolov** [comment]
> 
> 
> hi @GNNikolov
> Can you please provide us `DropInService` file?

You want me to provide you the implementaion of the service right? The interesting thing is that the missing fields are provided only once when I commit the first payment, do I have to store card`s encrypted details? Here is the service file:

class PaymentService : DropInService() {

    override fun makeDetailsCall(actionComponentData: JSONObject): CallResult {
        val future = RequestFuture.newFuture<JSONObject>()
        val components = ActionComponentData.SERIALIZER.deserialize(actionComponentData)
        val details = JSONObject()
        details.put(DETAILS, components.details)
        mController.add(object : JsonObjectRequest(Method.POST, Utils.URL_DETAILS, details, future, future) {
            override fun getHeaders(): MutableMap<String, String> = Utils.headers(applicationContext)
        })
        val code = getResponse(future)?.getString(RESULT_CODE)
        return CallResult(CallResult.ResultType.FINISHED, code!!)
    }

    override fun makePaymentsCall(paymentComponentData: JSONObject): CallResult {
        val paymentComponent = PaymentComponentData.SERIALIZER.deserialize(paymentComponentData)
        if (paymentComponent.paymentMethod == null) {
            return CallResult(CallResult.ResultType.ERROR, "Empty payment data")
        }
        val future = RequestFuture.newFuture<JSONObject>()
        val jsonObjectRequest = object : JsonObjectRequest(Method.POST, Utils.URL_PAY_EVENT, jsonBuilder(paymentComponent), future, future) {
            override fun getHeaders(): MutableMap<String, String> = Utils.headers(applicationContext)
        }
        mController.add(jsonObjectRequest)
        val response = getResponse(future)
                ?: return CallResult(CallResult.ResultType.ERROR, "IOException")
        if (response.has(ACTION)) {
            val action = Action.SERIALIZER.deserialize(response.getJSONObject(ACTION))
            return CallResult(CallResult.ResultType.ACTION, Action.SERIALIZER.serialize(action).toString())
        }
        return CallResult(CallResult.ResultType.FINISHED, response.get(RESULT_CODE).toString())
    }

    private fun getResponse(future: RequestFuture<JSONObject>): JSONObject? {
        try {
            return future.get(4, TimeUnit.SECONDS)
        } catch (e: InterruptedException) {
            e.printStackTrace()
        } catch (e: ExecutionException) {
            e.printStackTrace()
        } catch (e: ClientError) {
            e.printStackTrace()
        }
        return null
    }

    private fun jsonBuilder(paymentComponentData: PaymentComponentData<PaymentMethodDetails>) = JSONObject().apply {
        put(AMOUNT, Amount.SERIALIZER.serialize(Utils.getStoredAmount(applicationContext)))
        put(REFERENCE, "payment Android")
        put(SHOPPER_REF, "hardcoded_ref")
        put(STORE_PAY_METHODS, true)
        put(ONE_CLICK_PAY, true)
        put(PAY_METHOD, PaymentMethodDetails.SERIALIZER.serialize(paymentComponentData.paymentMethod!!))
        put(RETURN_URL, RedirectComponent.getReturnUrl(applicationContext))
        put(MER_ACCOUNT, applicationContext.getString(R.string.merchant_account))
    }
}
