### ISSUE TITLE
Field 'brand' is missing in PaymentComponentData (card)

### ISSUE THREAD

**Issue by machiapply** [Adyen/adyen-android#1229]
**Describe the bug**
We noticed the `brand` is missing from our Analytics, using `data.paymentMethod.brand` is not problem on iOS, but it's missing from Android data response.

**To Reproduce**
1. Use any credit card for checkout
2. Click on "Pay" to trigger `onSubmit` method
3. Observe the data response in `onSubmit` method
4. No "brand" under "paymentMethod"

**Expected behavior**
"brand" value in the response like:
```
{
   "paymentMethod":{
      "type":"scheme",
      "encryptedCardNumber":"adyenan0_1_1$TiwDNR7I+L1Fq8s2iU\/CaYx...",
      "encryptedExpiryMonth":"adyenan0_1_1$h5n1EdpojlGUQz\/UxsO3e...",
      "encryptedExpiryYear":"adyenan0_1_1$Spp+JEzQaQB3E15QShHiqpUa...",
      "encryptedSecurityCode":"adyenan0_1_1$JZxyebNX750EVA\/XyC5vwdAP...",
      "holderName":"test",
      "threeDS2SdkVersion":”2.2.5”
      "brand": "mc"

   },
   "storePaymentMethod":false,
   "shopperReference":"Checkout Shopper"
}
```

**Screenshots**
<img width="673" alt="Screenshot 2023-06-02 at 2 08 28 PM" src="https://github.com/Adyen/adyen-android/assets/25356232/0e204af8-0f67-4608-a116-5cf75461c42a">
```
{
   "paymentMethod":{
      "type":"scheme",
      "encryptedCardNumber":"adyenan0_1_1$TiwDNR7I+L1Fq8s2iU\/CaYx...",
      "encryptedExpiryMonth":"adyenan0_1_1$h5n1EdpojlGUQz\/UxsO3e...",
      "encryptedExpiryYear":"adyenan0_1_1$Spp+JEzQaQB3E15QShHiqpUa...",
      "encryptedSecurityCode":"adyenan0_1_1$JZxyebNX750EVA\/XyC5vwdAP...",
      "holderName":"test",
      "threeDS2SdkVersion":”2.2.5”
   },
   "storePaymentMethod":false,
   "shopperReference":"Checkout Shopper"
}
```

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: Android 10
 - Browser NA

**Additional context**
We're using SDK 4.4.0 AdyenCardComponent, integrated with react-native (but not using `@adyen/react-native` for our customization).

Found a similar issue here https://github.com/Adyen/adyen-android/issues/811, but the suggested solution doesn't work for card component, since it doesn't use drop-in service. The partial code for our card component is this:
```
public class AdyenCardComponent extends BaseModule implements PaymentComponentListener, ActionHandlingInterface {
   ...
   public AdyenCardComponent(ReactApplicationContext context) {
        super(context);
    }
    @Override
    public void onSubmit(PaymentComponentData data) {
        JSONObject jsonObject = PaymentComponentData.SERIALIZER.serialize(data);
        Log.i(TAG, jsonObject.toString());
        try {
            ReadableMap map = ReactNativeJson.convertJsonToMap(jsonObject);
            Log.d(TAG, "Paying");
            sendEvent(DID_SUBMIT, map);
        } catch (JSONException e) {
            sendEvent(DID_FAILED, ReactNativeError.mapError(e));
        }
    }
}
```
The log above is from `Log.i(TAG, jsonObject.toString());`

This issue might have been existing even since https://github.com/Adyen/adyen-android/issues/811 (v4.8.0) or later, but wondering if there's a workaround for card component?

**Comment by jreij** [comment]
Hey @machiapply, we just released a fix for this in [5.0.0-alpha02](https://github.com/Adyen/adyen-android/releases/tag/5.0.0-alpha02).
