### ISSUE TITLE
Drop-in Android card` s details(encrypted data) not shown for stored payment methods 

### ISSUE THREAD

**Issue by GNNikolov** [Adyen/adyen-android#123]
Hello, I faced this issue while trying to send paymentMethod`s data to our server. First time when enter card`s input everything is ok, but then paymentMethod contains only: type, storePaymentMethod and shopperReference.

**Comment by ArmanSo** [comment]
Hi @GNNikolov 
Are you using Dropin or just CardComponent?  
Can you please provide us more information about your implementation?

**Comment by GNNikolov** [comment]
> 
> 
> Hi @GNNikolov
> Are you using Dropin or just CardComponent?
> Can you please provide us more information about your implementation?

Yes, I am using Drop-In.

**Comment by GNNikolov** [comment]
> 
> 
> > Hi @GNNikolov
> > Are you using Dropin or just CardComponent?
> > Can you please provide us more information about your implementation?
> 
> Yes, I am using Drop-In.

First time when I set user`s card input the paymentComponentData inside makePaymentsCall(paymentComponentData: JSONObject) in my service has all needed encrypted values. Next time when my I commit a pay with stored payment method inside paymentComponentData there are only: type, storePaymentMethod and shopperReference

**Comment by ArmanSo** [comment]
That's the way it should be.

When you want to have a payment with `storePaymentMethod` you will receive a `id` that is RecurringDetail's id, with that `id` and `CVC` you can do another payment.

You should receive this `JSONObject` in `makePaymentsCall`

```
{
"paymentMethod":{
"type":"scheme",
"encryptedSecurityCode":"adyenan0_1_1$EX5Ii6w1BO2EoBBiLBjPX5NqcaZ5LCkWICcpEpp1kHzjtLSKHgVTLQmEIuYUHQZka1GxsU4bnq6yYnTxY2FcmDMKSj6IMDRM50par7N+ITCAz0hRtIXVs015SWhenV3Xl+TQKAKkpIWLywzCmMDkCq5kA7O1zxy09AovINryx1+wqUdtgOhKBbmlGQyUhayP1+gDRRJp3BN2eEktcC1Mxu9SUu+t50gXU\/i1lSm241w3\/DD16ZvOxjkyjhvmX0MTtneml+kMUGItbqqUv82d0TVffRWGJzJzrJ5duMlTC8qP\/xAKIB76E5KVBWc5ZpAcqbtTL7L9Z6w2bwIAA6lEZQ==$OilH3ADF1kQIlyXSGEyzR0wC+tK6qnI0ADvP5TsCmq9OUNwFzvDTQ3xH7wocyvUABFYWaoQpVvnqpA4Leey7CE\/3ERm+J2WQZX+ksAQ=",
"recurringDetailReference":"8415719094409297"
},
"storePaymentMethod":false,
"shopperReference":"shopper_refrence"
}
```

**Comment by GNNikolov** [comment]
Ok, but do I have to store encrypted card`s details somewhere?

**Comment by caiofaustino** [comment]
No, the encryptedSecurityCode is generated by the DropIn when the shopper enters their CVC for confirmation. You only need to have stored the shopperReference to make the initial paymentMethods/ call, the other information will be in the paymentComponentData.

**Comment by GNNikolov** [comment]
Ok, but the documentation for back-end payment implementation for C# needs EncryptedCardNumber , EncryptedExpiryMonth , EncryptedExpiryYear for creating Model.Checkout.DefaultPaymentMethodDetails in order to submit a payment from the server-side, so
there I have to provide only the paymentMethod from the client(android app) , right?

**Comment by caiofaustino** [comment]
Sorry I'm not familiar with the C# backend part. Do you have a link to that documentation? I'll try to talk to someone here who knows more about that.

**Comment by GNNikolov** [comment]
// Set your X-API-KEY with the API key from the Customer Area.
--
var client = new Client ("YOUR_X-API-KEY", Environment.Test);
var checkout = new Checkout(client);
 
var amount = new Model.Checkout.Amount("EUR", 1000);
var details = new Model.Checkout.DefaultPaymentMethodDetails{
Type = "scheme",
EncryptedCardNumber = "adyenjs_0_1_18$MT6ppy0FAMVMLH...",
EncryptedExpiryMonth = "adyenjs_0_1_18$MT6ppy0FAMVMLH...",
EncryptedExpiryYear = "adyenjs_0_1_18$MT6ppy0FAMVMLH...",
EncryptedSecurityCode = "adyenjs_0_1_18$MT6ppy0FAMVMLH..."
};
var paymentsRequest = new Model.Checkout.PaymentRequest
{
Reference = "YOUR_ORDER_NUMBER",
Amount = amount,
ReturnUrl = @"adyencheckout://your.package.name",
MerchantAccount = "YOUR_MERCHANT_ACCOUNT",
PaymentMethod = details
};
 
var paymentResponse = checkout.Payments(paymentsRequest);

**Comment by GNNikolov** [comment]
> 
> 
> That's the way it should be.
> 
> When you want to have a payment with `storePaymentMethod` you will receive a `id` that is RecurringDetail's id, with that `id` and `CVC` you can do another payment.
> 
> You should receive this `JSONObject` in `makePaymentsCall`
> 
> ```js
> {
> "paymentMethod":{
> "type":"scheme",
> "encryptedSecurityCode":"adyenan0_1_1$EX5Ii6w1B****",
> "recurringDetailReference":"841571909****"
> },
> "storePaymentMethod":true,
> "shopperReference":"shopper_refrence_of_user"
> }
> ```

I do it like this from C# backend and I receive: "{\"status\":422,\"errorCode\":\"101\",\"message\":\"Invalid card number\",\"errorType\":\"validation\"}"

**Comment by caiofaustino** [comment]
So I spoke to a developer who works with the C# library and it basically just mirrors the expected API response.

You are correct to use `DefaultPaymentMethodDetails`, and it has the required fields that you receive from Android. I'm not sure about the syntax but my understanding is that for the recurring payment you should do something like this:
```
var details = new Model.Checkout.DefaultPaymentMethodDetails{
Type = "scheme",
RecurringDetailReference = "84157190..."
EncryptedSecurityCode = "adyenjs_0_1_18$MT6ppy0FAMVMLH..."
};
```

Does that make sense?

**Comment by caiofaustino** [comment]
Here is the class for reference:
https://github.com/Adyen/adyen-dotnet-api-library/blob/2d19a0c1ebc7b46e6f3189f502d0488ac5ca9133/Adyen/Model/Checkout/DefaultPaymentMethodDetails.cs

**Comment by GNNikolov** [comment]
> 
> 
> So I spoke to a developer who works with the C# library and it basically just mirrors the expected API response.
> 
> You are correct to use `DefaultPaymentMethodDetails`, and it has the required fields that you receive from Android. I'm not sure about the syntax but my understanding is that for the recurring payment you should do something like this:
> 
> ```
> var details = new Model.Checkout.DefaultPaymentMethodDetails{
> Type = "scheme",
> RecurringDetailReference = "84157190..."
> EncryptedSecurityCode = "adyenjs_0_1_18$MT6ppy0FAMVMLH..."
> };
> ```
> 
> Does that make sense?

Yes, it makes, and just a little question: does EncryptedSecurityCode  expires after time?

**Comment by caiofaustino** [comment]
I'm not sure, but I don't think it does. But for legal/compliance reasons I think the user needs to be prompted with the CVC depending on the type of payment. I'd have to ask your Account Manager I guess.

**Comment by GNNikolov** [comment]
I`ve figured it out, it was my mistake in on the backend. Thanks for the response!
