### ISSUE TITLE
Problematic transitive Moshi dependency in 4.12.x

### ISSUE THREAD

**Issue by jonekdahl** [Adyen/adyen-android#1248]
**Is your feature request related to a problem? Please describe.**

Hi there!

I am trying to upgrade `com.adyen.checkout:drop-in` to 4.12.1. In our app, we use the Moshi library for JSON serialization, version 1.8.0. After changing the version of drop-in from 4.9.1 the app crashes on startup with the following exception:

```
java.lang.IllegalArgumentException: 
  Cannot serialize Kotlin type [REDACTED CLASS NAME OF ONE OF OUR JSON TYPES]. Reflective serialization of Kotlin classes without using kotlin-reflect has undefined and unexpected behavior. Please use KotlinJsonAdapterFactory from the moshi-kotlin artifact or use code gen from the moshi-kotlin-codegen artifact.
```

The dependency analyzer shows that there is now a moshi dependency (1.13.0) via the `cashapppay` library:

![bild](https://github.com/Adyen/adyen-android/assets/595004/0fb52605-f5a9-4fc6-ad0e-7e3338b9b065)

For comparison, this is the moshi dependencies with 4.9.1:

![bild](https://github.com/Adyen/adyen-android/assets/595004/1b37e64d-4413-4b69-a31f-baf5073ad5de)

My interpretation of the above is that a transitive dependency on moshi has been added in the Adyen `drop-in` library and it is forcing the Moshi library to be upgraded, causing the exception.

**Describe the solution you'd like**
It would be very nice if `com.adyen.checkout:drop-in` did not have a moshi dependency and did not force an upgrade of moshi in our app when upgrading the Adyen library. Ideally, transitive dependencies should be kept at a minimum to avoid dependency resolution issues like these.

**Describe alternatives you've considered**
We could of course go through the changelog from moshi 1.8.0 to 1.13.0 and make sure our app handles the changes, but even if that version of Moshi would work with our other dependencies Retrofit and OkHttp (which is still unclear) we would like to be able to do that at a time of our choosing instead of being forced to upgrade.

Another idea is if there is some way of blocking the transitive cashapppay dependency from being included, since we won't be using that.

**Comment by jonekdahl** [comment]
> if there is some way of blocking the transitive cashapppay dependency from being included

For anyone that is in the same situation as us, it is possible to exclude the `cashapp` dependency like this:

```gradle
    implementation('com.adyen.checkout:drop-in:4.12.1') {
        exclude group: 'com.adyen.checkout', module: 'cashapppay'
    }
```

**Comment by jonekdahl** [comment]
It looks like the exclusion mentioned above didn't work as expected unfortunately.

**Comment by jreij** [comment]
Hi, thanks for reaching out. Excluding cash app from drop-in will indeed not work, we did not consider these use cases when building drop-in. In all cases, the [Moshi version](https://github.com/square/moshi/blob/master/CHANGELOG.md#version-180) you are using dates back to 2018, so the ideal solution in my opinion is to upgrade it to a newer version.

However, if you feel like this requires too much effort from your side, maybe you could try [overriding the Moshi version](https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html#sec:enforcing_dependency_version) and forcing it to be downgraded to the same version you are using?

**Comment by jonekdahl** [comment]
Hi @jreij!

Thanks for your suggestions. We will investigate upgrading Moshi, but I still feel that it would be nice if the drop-in didn't place these kind of limitations on the app, especially for libraries that are commonly used in the Android ecosystem.

Regarding exclusion of unused drop-in dependencies, is that something you would be interested in supporting? If so, do you want me to create a separate issue?

**Comment by jreij** [comment]
We actually implemented this feature already, but we will only include it in the upcoming major release (v5). We will probably make a new alpha release soon which will include this alongside a lot of big and small improvements. Feel free to try it out and give us any feedback! Take a look at [this PR](https://github.com/Adyen/adyen-android/pull/1221) for more info on excluding specific dependencies from drop-in.

**Comment by jonekdahl** [comment]
Oh, that's great, no need for a new issue then.

**Comment by jonekdahl** [comment]
Hi @jreij. I'm on vacation and haven't tested it yet. Feel free to close this issue if you want, or we can keep it open and I'll post an update when I'm back.

**Comment by jonekdahl** [comment]
Hi @jreij. We have updated Moshi to 1.15.0 and that seems to be working with Adyen 4.12.1 so I am closing the issue. Thanks!
