### ISSUE TITLE
When ACH is chosen in DropIn, the SDK immediately calls the DropInService without showing any UI

### ISSUE THREAD

**Issue by assembleMHN** [Adyen/adyen-android#1254]
Hi all.

We have an issue, we need to add ACH (among other) to our Android app. We are using DropIn, and Credit Card is working great, but ACH dont work. Everytime we click the ACH option, it immediately requests the DropInService makePaymentsCall method without showing any UI, this then of cause fails with an error because there is no input to provide to the API.

The error we are getting is that the JSOn dont contain bank details or adress, but Adyen never shows the UI to input these in the DropIn, it just calls DropInService right after ACH option is chosen. We dont know how to move forward on this, it seems Android SDK has a bug or is broken, im not able to find any configuration for ACH that we can change.

Please help
Thank you very much, best regards
Morten

**Comment by jreij** [comment]
Hi Morten, thank you for reaching out. ACH is only supported in the first [alpha version](https://github.com/Adyen/adyen-android/releases/tag/5.0.0-alpha01) of our upcoming major v5 release, it's not available on v4.

Feel free to try out the alpha and give us your feedback!

**Comment by assembleMHN** [comment]
@jreij thank you for quick response, we will leave out ACH for now as we cannot publish something in alpha regarding payments and users credit cards.

Thank you again for fast response and have a great weekend! :)
