### ISSUE TITLE
CardComponent unable to get address data when offline

### ISSUE THREAD

**Issue by luonglegs** [Adyen/adyen-android#1261]
**Describe the bug**
We're currently using the library's card component to generate an encrypted card. We set the AddressConfiguration to FullAddress. The CardComponent works fine when it's online and it's able to fetch and retrieve list of countries and states but if you're offline at any point in that initial fetch it will crash with

```
com.adyen.checkout.core.exception.CheckoutException: Unable to get address data.
  at com.adyen.checkout.card.repository.AddressRepository.getAddressData(AddressRepository.kt:39)
  at com.adyen.checkout.card.repository.AddressRepository$getAddressData$1.invokeSuspend(Unknown Source:18)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
  at android.os.Handler.handleCallback(Handler.java:938)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:223)
  at android.app.ActivityThread.main(ActivityThread.java:7656)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
  Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c3a662e, Dispatchers.Main.immediate]
```

It makes sense why it would throw an exception because you couldn't fetch the list of countries in the AddressRepository but I want to avoid the crash. I can't figure out how to catch this exception and just navigate the user out of the CardComponent screen. Luckily if the user has navigated to this screen before they'll have their lists of countries and states cached. But what about the initial offline case? Is it possible to pre-populate that cache with defaults to fallback on if the AddressRepository fails to get address data?

**To Reproduce**
1. Fetch for a `PaymentMethod`
2. Create a fragment to host a `CardView`
3. Create a button to navigate to that CardViewFragment
4. Turn on airplane mode
5. Navigate to CardViewFragment using that button
6. In the CardViewFragment, it's creating CardComponent and attaching to CardView

```
val cardComponent = CardComponent.PROVIDER.get(
    this,
    paymentMethod,
    CardConfiguration.Builder(requireContext(), "client_key")
        .setHolderNameRequired(true)
        .setShowStorePaymentField(true)
        .setAddressConfiguration(
            AddressConfiguration.FullAddress(
                defaultCountryCode = Locale.getDefault().country
            )
        )
        .build()
  )
binding.cardView.attach(cardComponent, viewLifecycleOwner)
```

7.  Observe crash with a checkout exception for: Unable to get address data.

**Expected behavior**
To be honest, I'm not sure what to expect from the card component itself but I'd like the option to avoid the crash if possible. Unless CardComponent is expected to only work if there's network connectivity.

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Android
 - Version 30

**Comment by OscarSpruit** [comment]
Hi @luonglegs, thank you for reporting this issue! Thanks to your detailed description I was able to reproduce it easily. 

I do agree that it shouldn't crash in this case, but without the address data from this call the component is basically not able to continue. Just catching the error and ignoring it will end up in a situation where the end user is stuck. We will have to think about a proper solution and we will take your fallback suggestion into account.

Once we know more I will update this issue

**Comment by OscarSpruit** [comment]
Hi @luonglegs, we just merged a fix for this issue. It will no longer crash in this case. The CardComponent is indeed not designed to work offline, so we just fail gracefully now. The fix will be shipped with next release.

Closing this issue as fixed, but please feel free to reopen it if you have more questions
