### ISSUE TITLE
Issue with Alipay redirect

### ISSUE THREAD

**Issue by kami4ka** [Adyen/adyen-android#127]
I'm trying to use RedirectComponent for handling Alipay or any other redirect actions in my application and have faced the problem, that my program should rely only on Intent that can be received back, but this approach doesn't allow to handle actions like closing Chrome page or any other opened by RedirectComponent application. I have to handle this action for canceling payment-related orders or navigating a user to another payment method, for example.

My suggestion for resolving this is to use `startActivityForResult` instead of `startActivity` https://github.com/Adyen/adyen-android/blob/b081948afc3175ebf8d1256c415ad67b4a300215/redirect/src/main/java/com/adyen/checkout/redirect/RedirectComponent.java#L70 in RedirectComponent for allowing my program to control more flow cases.

**Comment by caiofaustino** [comment]
That's an interesting suggestion, but I think it doesn't solve the issue.

We start the redirect to either the browser or an installed app that will catch the URL deep link, but neither of those activities are expecting to return a result, so by consequence, when coming back to your activity it will always return `Activity.RESULT_CANCELED`, even if the flow finished correctly.

Currently the only way to differentiate this scenario is to check if the activity was resumed/recreated without any result. In that case I think it's OK to assume that the payment was canceled or failed. Or in case your return URL triggers a different Activity, basically the same concept, just check that the activity resumed was the original one and not the one expecting the result.

What could happen is that the user intentionally opened the browser in a new task (usually Settings -> Open in Chrome) and then came back to the app. That would trigger a cancel scenario, but if they go back to the browser and finish the payment, you will receive the payment result, in which case you can "cancel the cancellation" if that makes sense. How to handle that depends on your setup I guess.

You can try this yourself using `RedirectUtil.createRedirectIntent()` and starting the activity manually instead of using the `RedirectComponent.handleAction()`. Let me know if you have findings.

I hope this helps.

**Comment by kami4ka** [comment]
Thanks for the answer. Unfortunately, I can not rely on activity resumed/recreated state because a user can always open my app from recents screen (case that you have described above) and it will mislead a user.

Probably using `RedirectUtil.createRedirectIntent()` sounds good, but should be investigated a bit more. Thanks for a clue.

Also, any chances for some suggestions about how RedirectComponent can be improved to cover described types of cases in the future?

**Comment by caiofaustino** [comment]
Well this is a bit tricky, I understand the ideal flow is to give the user the feedback on what has just happened, but the redirect payment methods are asynchronous in that regard. I think it makes sense to treat a redirect as "pending" until the result comes in.

Depending on your scenario maybe you can give them the option to try to pay again, but then check that it doesn't create issues with possible double payments.

But if you can find any other way to technically know that they canceled the flow, let me know and maybe we can improve as well :)

**Comment by kami4ka** [comment]
Ok, I've got the idea. Thanks 🙂

**Comment by kami4ka** [comment]
Also, I'm having another issue with Alipay. After start payment with the Alipay payment method, it opens a webpage with 2 possible payment variants: through application and through the web page. Payment using web page working good and I able to receive intent after payment completion, but after successful payment through app it just closes and I can only observe the same page with 2 possible payment variants (through web and through the app) and no intent from web of app, which is also confusing for end-user.

I'm using Sandbox application of Alipay because it's only one possible way to deal with described on Adyen site test credentials. 

Any suggestions on how to deal with it?

**Comment by ArmanSo** [comment]
Hi @kami4ka 
I'll come back to you tomorrow with answer and hopefully a solution.

**Comment by kami4ka** [comment]
Hi @ArmanSo 
Thanks for the response. I hope for a solution as well.

**Comment by ArmanSo** [comment]
@kami4ka as I check it should work if you're passing returnUrl to AliPay
and since you can pay with web flow, it mean that deep linking works as we expected.

is it possible to share your `/payment` request?

**Comment by kami4ka** [comment]
Sure. Here is the request from our BE to /payment:

```
{
    "amount": {
        "currency": "HKD",
        "value": 1000
    },
    "reference": "MA12343121test21",
    "paymentMethod": {
        "type": "alipay_wap"
    },
    "returnUrl": "myappname://adyencheckout",
    "merchantAccount": "MyMerchantAccountName",
    "additionalData": {
        "allow3DS2": true
    },
    "channel": "Android"
}
```
Don't mind the return URL scheme, intent receiving works well, as you understand because it works with the web.

**Comment by kami4ka** [comment]
Hi, @ArmanSo. Had you a chance to take a look at my issue?

**Comment by ArmanSo** [comment]
Hi @kami4ka I'm still working on it, looks like that it's back-end issue and return url is not sending back to AliPay app. I'll back to you with result ASAP

**Comment by ArmanSo** [comment]
I'm back with answer @kami4ka as I checked we're sending returnUrl to AliPay and the screen that user see (option of paying with Web flow or App flow) is hosted by AliPay, not Adyen so what we expecting is to AliPay redirect us to that return URL but as you know it's just working in web flow and it should work for app flow too. so it looks like a bug in AliPay side, not us.

I don't have any solution for it RN. but I would suggest to test it with production to see if it works correctly or not.

Cheers.

**Comment by kami4ka** [comment]
@ArmanSo will you have a chance to contact Alipay for defining is the integration described in Adyen integration docs is right?

**Comment by kami4ka** [comment]
Hi @ArmanSo @caiofaustino 
Any updates about this issue?

**Comment by 2020gaurav** [comment]
@ArmanSo @caiofaustino - We are also waiting for the ideal solution which @caiofaustino explained on 6th Nov. 
Actually our we need to take certain actions if user has canceled the 3DS1 flow in the redirect component. We don't have any way to get that event.

Option 1 (not working)- I my case first onResume()/onRestart() then onNewIntent() receive callback. How we can be sure if onNewIntent() is going to be called in some time so we should not consider it as user canceled case in onResume function ?

option 2 (Not Working) - I try using `RedirectUtil.createRedirectIntent()` But problem is our onActivityResult is being called with cancel result even in the success case. Possible the redirect component is not setting anything in result intent. So we can't able to differentiate b/w user cancel and success in this case as well.

**Comment by ArmanSo** [comment]
Hi @kami4ka I'm again following it up, if I have any update on this will let you know.

**Comment by caiofaustino** [comment]
hey @2020gaurav,

So like I tried to explain, what you are trying to achieve is not so simple. When authenticating the 3DS1 transaction the user is taken outside the scope of your application. They can simply open a browser in a new stack and simply close your app, or close the browser, so there is no such thing as cancel event.

Option 1 is the one that we are currently using to try to give the user some feedback. If we start the 3DS1 redirect, it is expected that the authentication will trigger a call to the Activity with the result. So if the user comes back to the Activity, and we don't have any result, we assume the user canceled the flow and went back, or that some issue happened. In that case, we allow them to start the flow again and try to do a new payment.

Even if the 3DS1 authentication happened, the payment is not completed if you don't send the result to the `/details` endpoint (it stays as an open offer). So it's safe to cancel the previous flow and start over.

**Comment by caiofaustino** [comment]
Hey @kami4ka, are you still experiencing issues with Alipay? 
This issue got kind of left behind here but to me this looks like something that could have been fixed by the backend in the meantime.

**Comment by kami4ka** [comment]
For now, the current behavior with the Alipay production application looks fine for us.

**Comment by caiofaustino** [comment]
That's good to know. Please open a new issue if you find problems again, this one has already become too intertwined with different things.
Cheers
