### ISSUE TITLE
Any Example for individual Components just like in iOS along with DropIn Component

### ISSUE THREAD

**Issue by mkharibalaji** [Adyen/adyen-android#129]
Hi Team,
       Any Example for individual Components just like in iOS along with DropIn Component in the example-app folder.

**Comment by ArmanSo** [comment]
Hi @mkharibalaji 
No, but you can find more information about it at docs 
https://docs.adyen.com/payment-methods/cards/android-component

**Comment by mkharibalaji** [comment]
Thanks @ArmanSo
