### ISSUE TITLE
Payments with Google Pay fail when using Java API Library v21.0.0

### ISSUE THREAD

**Issue by elitalon** [Adyen/adyen-android#1295]
**Describe the bug**
Trying to make a payment through Google Pay fails when [v21.0.0](https://github.com/Adyen/adyen-java-api-library/releases/tag/v21.0.0) of the Java API Library is used in backend. The Android SDK sends an unexpected `googlePayCardNetwork` field in the request's body that is rejected during deserialisation.

**To Reproduce**
1. A web service is configured with [v21.0.0](https://github.com/Adyen/adyen-java-api-library/releases/tag/v21.0.0) of the Java API Library
2. Make a payment with Google Pay using a drop-in integration
    - The payment fails

**Expected behavior**
The Android SDK does not send unnecessary fields in the request body.

**Screenshots**
n/a

**Smartphone (please complete the following information):**

**Additional context**
This problem seems to be similar to another one reported in the iOS SDK: Adyen/adyen-ios#1244. Our guess is that it's caused by the replacement of [GSON](https://github.com/google/gson) with [jackson](https://github.com/FasterXML/jackson) in Adyen's Java API library [v21.0.0](https://github.com/Adyen/adyen-java-api-library/releases/tag/v21.0.0), which does a strict validation of the request payload.

**Comment by elitalon** [comment]
Thanks @jillingk. Looking forward to a release with that patch.

Out of curiosity, would you remove anyway the `googlePayCardNetwork` field from the request's payload?

**Comment by OscarSpruit** [comment]
Hi @elitalon! Yes, we will remove this field from the request as well. I can't say anything about when it will be released yet, but I will notify this issue when we know more

**Comment by OscarSpruit** [comment]
Hi @elitalon, with the release of [Adyen Java API Library v23.0.0](https://github.com/Adyen/adyen-java-api-library/releases/tag/v23.0.0) `googlePayCardNetwork` was added to the API. This field is required for some Google Pay flows, so we will not remove it from the Android SDK.

Closing this issue as it is completed. Feel free to reopen it if you have more questions or feedback!
