### ISSUE TITLE
Error code PI102

### ISSUE THREAD

**Issue by vash15** [Adyen/adyen-android#13]
What is the PI102 error?

This is the response from SDK:
```json
{
"errorCode":"PI102",
"errorMessage":"An error occurred processing the payment",
"type":"error"

}
```

Thank you

**Comment by vash15** [comment]
I found the problem. The error is returned because I have the "cardShouldSave" flag active. Setting it to false, the error is no longer returned by the server.

**Comment by timon-langlotz** [comment]
Hi @vash15,

sorry for the late reply. Could you get in touch with support@adyen.com and provide them with a reference to the payment? I would like to know why you were required to turn of that flag.

Cheers,
Timon

**Comment by vash15** [comment]
Thanks @timon-langlotz, but for now I do not need that feature. However, it would be great to implement a specific error. 
Another question, what's the minimum version of the SDK?

**Comment by timon-langlotz** [comment]
Hi @vash15, 

I will look into how we can improve these error messages.
The minimum SDK version for the latest release is 16 (Jelly Bean).

Cheers,
Timon

**Comment by vash15** [comment]
Thank you @timon-langlotz !
