### ISSUE TITLE
Unity activty with launchMode=“singleTask” and Adyan

### ISSUE THREAD

**Issue by sergestanislavsky** [Adyen/adyen-android#1302]
**Describe the bug**
`Adyen activity` does not send any feedback when closed by the system

**To Reproduce**
1. Open the application and go to the payment method dialog
	We have such a stack of activities:
		OUR `Unity activity` with `launchMode=“singleTask”` 
       		OUR `AdyenResultActivity : AppCompatActivity(), DropInCallback`
		YOUR `Adyen activity`
	
	p.s. We use `AdyenResultActivity` to launch adyen flow (`DropIn.startPayment`) and catch callback (`onDropInResult`)
	
2. Minimize the app and **click on the app icon** (it is improtant)
3. We can see our app and the payment method dialog is closed. Two activities `AdyenResultActivity` and `Adyen activity` are destroyed. And only the first (`Unity activity`) remains, because of the flag `singleTask`. It's all right. **BUT** `Adyen activity` does not send any callback in `onDropInResult` before deletion in this case. This behavior is wrong. We should catch a
`DropInResult.CancelledByUser` callback (or some other) in this case.	

**Expected behavior**
`Adyen activity` sends a callback in `onDropInResult` before deletion in this case.

**Smartphone (please complete the following information):**
 - Device: Pixel 6 
 - OS: Android 13
 - Version: adyen  4.11.0

**Additional context**
Our workaround looks like this. We use a flag `isPrematurelyDestroyed`

```
class AdyenResultActivity : AppCompatActivity(), DropInCallback {

    private var isPrematurelyDestroyed = true

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        startPayment()
    }

    private fun startPayment() {
      	...
    	DropIn.startPayment(this, launcher, paymentMethods, dropInConfig)
    }

    override fun onDropInResult(dropInResult: DropInResult?) {
        if (dropInResult is DropInResult.CancelledByUser) {
            getCallbackInstance()?.onPaymentCancelled()
        }
        isPrematurelyDestroyed = false
        finish()
    }

    override fun onDestroy() {
        if (isPrematurelyDestroyed) {
            getCallbackInstance()?.onPaymentCancelled()
        }
        super.onDestroy()
    }
}
```

**Comment by ozgur00** [comment]
Hi @sergestanislavsky! Thanks for bringing the issue to our attention.

We have investigated the scenario with the information you provided and came to the conclusion of leaving the behavior as is. In this scenario what happens is not a result provided by our SDK, it's rather caused by the OS behavior. That's why we believe it's better to not include this scenario as one of our defined `DropInResult`s. You can check if the result is null or not to differentiate between this case and other valid `DropInResult`s.

**Comment by jreij** [comment]
HI @sergestanislavsky , do you still need any help with this issue?

**Comment by sergestanislavsky** [comment]
No, thanks, in this case we can use "workaround"
