### ISSUE TITLE
After using redirect component, you are prompted with "open with" dialog with duplicated app

### ISSUE THREAD

**Issue by josevsq1** [Adyen/adyen-android#1327]
**To Reproduce**
After entering a card that requires a RedirectComponent to be used, you're taken to the bank screen and then, instead of directly redirecting to your app, you're prompted with a "Open with" dialog that allows you to choose between your app and your app. I mean, it's duplicated. I've checked and there is no duplicated intent filter or something like that

**Screenshots**
<img width="404" alt="Captura de pantalla 2023-08-31 a las 12 15 15" src="https://github.com/Adyen/adyen-android/assets/100414163/d7bbfe1d-c579-4542-b38e-113ab8b205e1">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Android emulator
 - OS: Android 13
 - Browser chrome
 - 4.12.1

**Comment by jreij** [comment]
Hi @josevsq1, thanks for reaching out. I can suggest two points to investigate:
- Could you take a look at your [merged manifest](https://developer.android.com/build/manage-manifests#inspect_the_merged_manifest_and_find_conflicts)? In case if you can find a duplicate intent filter there.
- Check if you are also importing drop-in in your gradle files. Internally drop-in declares an intent filter, so it could be that you declared the same one in your app as well. Generally you shouldn't need to mix components and drop-in.

**Comment by josevsq1** [comment]
Hi @jreij , I'm checking the merged manifest and, although I see other intent filters related to adyen, the only one with the scheme I chose is the one I declared when integrating adyen. In any case, I have just "fixed" the issue by, instead of using "applicationId" as a host, I only use a given string. So in returnUrl and in the intent filter I use the same given string as a host instead of the applicationId. 

This is solving the issue, at least for now. 


And yes, I'm importing drop-in since I use it for other reasons, so maybe that was the reason after all.

**Comment by jreij** [comment]
I think this is the problem indeed, drop-in contains an intent filter for these links: `adyencheckout://your.application.id` so it might clash with what you are declaring.

Closing this issue for now, feel free to reopen if you still need help with it.
