### ISSUE TITLE
Issue with 5.0.0-alpha02 DropIn

### ISSUE THREAD

**Issue by assembleMHN** [Adyen/adyen-android#1332]
Hi All.

To support ACH in dropin we are testing out the 5.0.0-alpha02 branch..

We added it to the build file as such:
Implementation "com.adyen.checkout:drop-in:5.0.0-alpha02"

We followed the documentation and setup app the steps:

<img width="1314" alt="Screenshot 2023-09-06 at 10 18 16" src="https://github.com/Adyen/adyen-android/assets/30831333/5e5176d1-63ef-43c5-92a4-4f6bc0a102d1">

And launching the DropIn

<img width="779" alt="Screenshot 2023-09-06 at 10 18 49" src="https://github.com/Adyen/adyen-android/assets/30831333/264ef6a2-ba19-4112-abad-bae452f32dff">

The DropIn presents just fine, when trying to use ACH or Card (with Adyens test card) it throws an error in the callback, sadly the Error reason is an empty string so there is nothing to go by.

<img width="400" alt="Screenshot 2023-09-06 at 10 20 01" src="https://github.com/Adyen/adyen-android/assets/30831333/afc97d61-a832-4d7a-9509-55e4e2d14099">

In the log i do get some lines, but im unsure if they are related or just random warnings. I have tried to remove the payment amount, and move it from dropin configuration to card configuration nothing seems to make a difference

<img width="652" alt="Screenshot 2023-09-06 at 10 21 19" src="https://github.com/Adyen/adyen-android/assets/30831333/0a61a72d-0f02-4027-91ac-0816c5f2aaf1">

I hope somebody can help us move on so we can be ready when the new SDK launches :)

Best Regards
Morten

**Comment by jreij** [comment]
Hi @assembleMHN, we're very happy to hear that you're using the alpha version already 🚀 

I took a quick look at the backend logs, is there a chance that the device you're testing with does not have the correct date/time/timezone set?

**Comment by assembleMHN** [comment]
Hi @jreij Thank you so much for your quick reply, and you are spot on, for some reason the emulator i was testing on was 2 hours and some minuts behind. I erased the emulator started a brand new one and it worked first time, im so relieved that we got i working :)

Again thank you so much for your help i really appreciate it. Now we just need to wait for the new SDK to launch we are ready 

Best Regards
Morten

**Comment by jreij** [comment]
@assembleMHN glad to hear it works now! We're releasing a beta soon which should be very similar to the final stable version that will follow later.

Feel free to upgrade to the beta when it's out, we'd appreciate any feedback you can give us about the ease of integration and the user experience 🙂
