### ISSUE TITLE
Pay button is not visible in Card Component

### ISSUE THREAD

**Issue by iagorm** [Adyen/adyen-android#135]
I'm trying to integrate the Card Component with React Native, and I've followed the documentation, but the problem is that the Button to pay is not showing, am I doing something wrong?

Follow the code:

```kotlin
            val cardComponent = CardComponent.PROVIDER.get(fragmentActivity, paymentMethod, cardConfiguration.build())

            cardComponent.observe(fragmentActivity, Observer {
                if(it?.isValid == true) {
                    Log.d(REACT_CLASS_TAG, "valid form")
                }
            })

            val cardView = CardView(mContext!!)

            cardView.attach(cardComponent, fragmentActivity)
            cardView.setPadding(0, cardView.paddingTop, 0, cardView.paddingBottom)
            cardView.layoutParams = LayoutParams(LayoutParams.MATCH_PARENT, LayoutParams.WRAP_CONTENT)
            cardView.gravity = Gravity.BOTTOM

            parentView.addView(cardView)

            Log.d(REACT_CLASS_TAG, "mounted")
```

## Actual Behavior
![Screenshot_1574169369](https://user-images.githubusercontent.com/13892132/69149611-9c8bfe00-0ab5-11ea-885c-a50a58468a41.png)

**Comment by ArmanSo** [comment]
Hi @iagorm 
Pay button is part of DropIn not individual components, you need to implement that by your self.

Cheers.

**Comment by iagorm** [comment]
> Hi @iagorm
> Pay button is part of DropIn not individual components, you need to implement that by your self.
> 
> Cheers.

@ArmanSo Thank you to clarify that!
