### ISSUE TITLE
Card Component caching form data

### ISSUE THREAD

**Issue by iagorm** [Adyen/adyen-android#137]
## Description
The Card Component is caching the inserted data in the fields when the component is re-added to the view, it starts with empty fields but the brand is showing and the Observer is retrieving the previous data validated which is not the expected behavior.

## Current Behavior
![Screen Shot 2019-11-19 at 21 03 49](https://user-images.githubusercontent.com/13892132/69197447-19e45c80-0b10-11ea-8896-14ab6a3db8ed.png)

## Expected Behavior
![Screen Shot 2019-11-19 at 21 03 27](https://user-images.githubusercontent.com/13892132/69197448-1bae2000-0b10-11ea-8cfd-dbfc32c18f14.png)

**Comment by kami4ka** [comment]
I've fixed this by passing to view model factory (component provider) my fragment instead of activity, so then it started working as expected.

**Comment by ArmanSo** [comment]
Hi @iagorm 
@kami4ka is right, I think you're passing activity instead fragment. FYI all components are android life cycle aware. not passing correct life cycle owner can cause that issue.

**Comment by iagorm** [comment]
@kami4ka do you have an example of Fragment since in React Native is not common the usage of it, it would be very welcome.
