### ISSUE TITLE
Styling input issue

### ISSUE THREAD

**Issue by iagorm** [Adyen/adyen-android#138]
## Description
I'm trying to style the label but with no success, the property `colorControlActivated` is being inherited from parent `Theme.AppCompat.Light.NoActionBar`, there is a way to make specific selection of this label color in order to override it without making it global?

## Screenshot
![Screen Shot 2019-11-20 at 19 36 15](https://user-images.githubusercontent.com/13892132/69284383-49a56a00-0bcd-11ea-87e1-93b471f85454.png)

**Comment by ArmanSo** [comment]
Hi @iagorm you can override `AdyenCheckout.TextInputLayout` style
```
   <style name="AdyenCheckout.TextInputLayout" parent="Widget.MaterialComponents.TextInputLayout.OutlinedBox">
        <item name="boxStrokeColor">@color/primaryColor</item>
        <item name="hintTextAppearance">@style/AdyenCheckout.HintTextStyle</item>
        <item name="android:minHeight">@dimen/input_layout_height</item>
    </style>
``` 

Cheers

**Comment by iagorm** [comment]
It worked perfectly, Thank you!
