### ISSUE TITLE
Error: "No value for MD"

### ISSUE THREAD

**Issue by Otakenne-SQ1** [Adyen/adyen-android#1383]
Description: While trying to register a 3DS2 card, I get a "No value for MD" error in my "registerForActivityResult" after completing redirection and authentication. I can confirm that the MD value is passed in the intent to the launch method

Other details:
Android emulator
OS: Android 13
Browser chrome
4.12.1

**Comment by OscarSpruit** [comment]
Hi @Otakenne-SQ1, thank you for opening an issue with us! Please reach out to [our support team](https://help.adyen.com/contact) and they should be able to help you troubleshoot this better.
