### ISSUE TITLE
Add readme for example-app setup

### ISSUE THREAD

**Issue by wrozwad** [Adyen/adyen-android#1401]
It took me a while to figure this out, so I'm sharing it here for everyone.
In the `example-app` module, you'll find the `default.local.gradle` setup where you need to replace the following:
- `<YOUR_MERCHANT_ACCOUNT>` with the account displayed near the proper credential
![image](https://github.com/Adyen/adyen-android/assets/2025949/b187d598-a48b-4ae3-b52f-1c5f35c10535)

- `<YOUR_SERVER_URL>` with `https://checkout-test.adyen.com/v71/` or newer [link to api doc](https://docs.adyen.com/api-explorer/Checkout/latest/overview)
![image](https://github.com/Adyen/adyen-android/assets/2025949/407c3ae1-6efa-4f63-a794-f9c67b109768)

- `<API_KEY_HEADER>` with `X-API-Key`
- `<YOUR_API_KEY>` from Developers -> Api Credentials -> your credential -> Server settings section
- `<YOUR_CLIENT_KEY>` from Developers -> Api Credentials -> your credential -> Client settings section
- `<SHOPPER_REFERENCE>` with `testshopper`, kind of because I couldn't find anything else

**Comment by ozgur00** [comment]
Hi @wrozwad! Thanks for your suggestion, we will internally discuss how we can make this information more accessible.

**Comment by jreij** [comment]
HI @wrozwad, we just merged a PR that will improve the usability of the testing app. Please take a look at the [readme](https://github.com/Adyen/adyen-android/tree/develop/example-app#readme).

However note that your current setup will break, sorry for that 😄
To migrate, go to `example-app/local.gradle` and follow these steps:
- Rename `API_KEY_HEADER_NAME` to `AUTHORIZATION_HEADER_NAME`.
- Rename `CHECKOUT_API_KEY` to `AUTHORIZATION_HEADER_VALUE`.
- Remove `SHOPPER_REFERENCE` line. It will now default to `"test-android-components"`, you can change that value in the settings screen if you want.
- Remove unnecessary quote symbol escaping: `"\"SOME_VALUE\""` can be replaced with `'"SOME_VALUE"'`.

Let us know if you have any comments or need more help with this.
