### ISSUE TITLE
Cant inflate cardView with Theme.AppCompat

### ISSUE THREAD

**Issue by Kolyall** [Adyen/adyen-android#142]
my style is 
**app/res/values/styles.xml**
```
 <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar"/>
```

But if i add `com.adyen.checkout.card.CardView` to my layout **activity_main.xml**
```
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.adyen.checkout.card.CardView
        android:id="@+id/adyenCardView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent" />
</androidx.constraintlayout.widget.ConstraintLayout>
```
The app crashes with error:
```
Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).
```

**Comment by caiofaustino** [comment]
Is this something that just started happening? Did you update anything on the project recently? Checkout version or support library version?

**Comment by Kolyall** [comment]
@caiofaustino 
Resolved by overriding your style at `com.adyen.checkout:base-ui/values/values.xml`
```
  <style name="AdyenCheckout.TextInputLayout" parent="Widget.MaterialComponents.TextInputLayout.OutlinedBox">
        <item name="boxStrokeColor">@color/primaryColor</item>
        <item name="hintTextAppearance">@style/AdyenCheckout.HintTextStyle</item>
        <item name="android:minHeight">@dimen/input_layout_height</item>
    </style>
```
to mine `app/res/values/styles.xml`
```
<style name="AdyenCheckout.TextInputLayout" >
        <item name="boxStrokeColor">@color/colorAccent</item>
        <item name="hintTextAppearance">@style/AdyenCheckout.HintTextStyle</item>
        <item name="android:minHeight">@dimen/input_layout_height</item>
    </style>
```

**Comment by caiofaustino** [comment]
Great job finding the fix!
But my question remains, was this issue caused by a version update or is this the first time you are trying to use the CardView?

**Comment by Kolyall** [comment]
it's at ver 3.5.1

**Comment by Kolyall** [comment]
the issues also was at ver 3.4.1

**Comment by caiofaustino** [comment]
Thanks for letting us know :)

**Comment by heikkihautala** [comment]
I ran into this issue on `4.3.0` version of this SDK when trying to present the card details form:
`DropIn.startPayment(...)`
The method list is displayed but selecting the credit card option crashes the app:
```
fragment_card_component: Error inflating class com.adyen.checkout.card.CardView
...
card_view: Error inflating class com.google.android.material.textfield.TextInputLayout
...
IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).
```

We have `Theme.AppCompat.Light.NoActionBar` as our app's theme. Even if I override `AdyenCheckout.TextInputLayout` in our `styles.xml` the crash persists.
```
<style name="AdyenCheckout.TextInputLayout">
        <item name="boxStrokeColor">@color/primaryColor</item>
        <item name="hintTextColor">@color/primaryColor</item>
        <item name="android:minHeight">@dimen/input_layout_height</item>
</style>
```

**Comment by heikkihautala** [comment]
I found an easy solution. Our app's theme was named `AppTheme`:

AndroidManifest.xml:
```
<application
   ...
   android:theme="@style/AppTheme">
...
</application>
```
in `styles.xml`:
```
<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
...
</style>
```
 For some reason that name causes the problem.

Simply changing the name `AppTheme` to something else solved the problem. No need to inherit app theme from`Theme.MaterialComponents` or override style for `AdyenCheckout.TextInputLayout`.

**Comment by caiofaustino** [comment]
Cool, yeah that's because we try to automatically inherit your apps theme from `AppTheme` as you can see [here](https://github.com/Adyen/adyen-android/blob/develop/ui-core/src/main/res/values/styles.xml#L14).

You can also directly override our `AdyenCheckout` instead of renaming your own `AppTheme`.
