### ISSUE TITLE
How to override card icons?

### ISSUE THREAD

**Issue by Kolyall** [Adyen/adyen-android#143]
icon of brand card is displayed in card number field at `com.adyen.checkout.card.CardView`  after type of card number.
The icon is loaded from server for example https://checkoutshopper-test.adyen.com/checkoutshopper/images/logos/small/visa-xxhdpi.png
Is any way to replace the icon?

**Comment by caiofaustino** [comment]
No unfortunately not. What is your use case for replacing the brand icon?

**Comment by Kolyall** [comment]
This icons doesn't suit our App UI guidelines. We use dark ui and it will be fit us to use line icons in one color

**Comment by Kolyall** [comment]
Maybe just add icons to res, like it is with `com.dyen.checkout:card-ui/res/drawable/ic_card`

**Comment by Kolyall** [comment]
Also if it possible provide please the ability to switch the icon set when switching the theme of the application

**Comment by caiofaustino** [comment]
It's an option we can investigate in the future. 

We try to keep the logos as server resources to be able to update with new brands and designs without requiring merchants to update and release new versions of their apps.

From version 3.5.1 we offer the identified `CardType` as a parameter in the `CardComponentState` from the observer of the Component. Maybe you can use that to show the brand on another view in the layout.

You can also override `@style/AdyenCheckout.Card.BrandRecognitionLogo` to have visibility gone. To hide our current Logo.

**Comment by caiofaustino** [comment]
Let us know if you have any more questions.
