### ISSUE TITLE
[4.9.0] Calling CardComponent.PROVIDER.get() with different CardConfiguration always returns initial CardComponent

### ISSUE THREAD

**Issue by JakeSteam** [Adyen/adyen-android#1433]
**Describe the bug**

Inside my app I need to display the card saving toggle on some screens, but not all. All screens are fragments in a single activity, and a mixture of Compose / XML.

When calling `CardComponent.PROVIDER.get(activity, paymentMethod, cardConfiguration)` with *different* `cardConfiguration`s, the same component is returned (with values from the first `cardConfiguration`).

This results in whichever screen type is called first (enabled / disabled) being used for all screens, regardless of configuration.

**To Reproduce**

1. Create a configuration with `setShowStorePaymentField(true)`.
2. Use this to get a `CardComponent`, via `CardComponent.PROVIDER.get(activity, paymentMethod, cardConfiguration)`.
3. Create a configuration with `setShowStorePaymentField(false)`
4. Again use this to get a `CardComponent`, with the same `activity` and `paymentMethod`.
5. Notice that the component from the previous step has `showStorePaymentField` set to `true`.

Performing the steps detailed above (e.g. passing it `false` then `true`), results in these logs:
```
2024-01-03 15:09:16.085: Tried to set to false, set to false
2024-01-03 15:09:26.111: Tried to set to true, set to false
```

I've included an example snippet of code (and debugger screenshot) at the end of this post.

**Expected behavior**

I would expect to get a component purely based on the `cardConfiguration` passed in. 

**Additional context / screenshots**

Example code:
```
    fun getCardComponent(activity: FragmentActivity, paymentMethod: PaymentMethod, isStoreCardEnabled: Boolean): CardComponent {
        val cardConfiguration = CardConfiguration
            .Builder(Locale.getDefault(), env, key)
            .setHolderNameRequired(true)
            .setShowStorePaymentField(isStoreCardEnabled)
            .build()
        val component = CardComponent.PROVIDER.get(activity, paymentMethod, cardConfiguration)
        Log.i("storecardset", "Tried to set to $isStoreCardEnabled, set to ${component.showStorePaymentField()}")
        return component
    }
```

Example debugger screenshot, showing true being passed in, but false returned:
![image](https://github.com/Adyen/adyen-android/assets/12380876/e2bdf50a-e74b-4cb7-a331-622d5db8a5ac)

Libraries used:
```
    implementation "com.adyen.checkout:card:4.9.0"
    implementation "com.adyen.checkout:redirect:4.9.0"
    implementation "com.adyen.checkout:3ds2:4.9.0"
```

Final notes:

I assume there's some sort of map / cache being built up, and the library is avoiding reinitialising a component. 

Migrating to 5.0.0+ and using the `key` parameter would presumably fix this, but ideally there'd be a shorter term solution!

**Comment by OscarSpruit** [comment]
Hi @JakeSteam, thank you for opening an issue! This is a known limitation of version 4.x.x. A component is basically a `ViewModel` which is created with the activity or fragment provided. Trying to re-create a component during the same lifecycle will result in the same instance being returned.

However, there is a workaround for this issue. Wrapping the component in different fragments could work, so the component is tied to different lifecycles. In your case it looks like you are already using fragments, so it could be as easy as passing the fragment instead of the activity:
```Kotlin
CardComponent. PROVIDER.get(this, paymentMethod, cardConfiguration)
```

And indeed as you said the other option would be updating to v5 and using the key param.

Please let us know if this helps or if you have any other questions!

**Comment by JakeSteam** [comment]
Hey @OscarSpruit good to know I'm not missing something obvious, and it is a limitation.

I actually completely missed that the `owner` can be a Fragment, that might work for us. I'll have a bit of a play, definitely looking forward to updating to 5.x later this year 🙂 

Thanks so much!

**Comment by JakeSteam** [comment]
Yep, passing in `Fragment`s worked perfectly. Thanks again.
