### ISSUE TITLE
Acceptable card brands do not get refreshed after payment methods data change

### ISSUE THREAD

**Issue by machiapply** [Adyen/adyen-android#1442]
**Describe the bug**
In the CardComponent, when the shipping country changes, the available card brands do not change instantly. We have shipping form outside of CC payment form, when it's updated, it's getting the new `paymentMethods` in `react-native`, and passing that to native side. The same FE logic is working fine on iOS, but this issue is spotted only with Android. It takes a few minutes or needs to restart the app, then it gets the correct card brands for the country.

We're using the card component like below:
```
private void showComponentView(AppCompatActivity theActivity,
                               ComponentViewModel viewModel,
                               CardConfiguration configuration) {

    CardView componentView = new CardView(theActivity);
    CardComponent component = CardComponent.getPROVIDER().get(theActivity, viewModel.getPaymentMethod(), configuration);

    FragmentManager fragmentManager = theActivity.getSupportFragmentManager();

    dialog = new AdyenBottomSheetDialogFragment(viewModel, componentView, component, this);
    dialog.show(fragmentManager, "Component");
}
```
At first, we thought the `paymentMethods` data might be cached, but in the `getPaymentMethod()`, the log shows the correct payment method data is passed along.
We're dismissing the dialog with `dismiss()`. Now since we spotted the issue, we tried to flush the `componentView` and `component` by setting to `null`. But nothing worked. Would you know why this is happening by chance?

**To Reproduce**
Steps to reproduce the behavior: (example of CB (Carte Bancare) card available only in France)
1. Go to shipping form, set to Canada
2. Open the CC payment, make sure the CB card is not available
3. Do not complete the payment and go back to shipping form, set to France
4. Open the CC payment, CB card is still not available

**Expected behavior**
CB card is available

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: reproduced at least on Android 11 & 13

**Additional context**
react-native `0.66.5`
Android SDK `4.4.0`

**Comment by ozgur00** [comment]
Hi @machiapply! Thanks for bringing the issue into our attention. 

Can you enable the verbose logs by calling `com.adyen.checkout.core.log.Logger.setLogcatLevel(Log.VERBOSE)`, reproduce the issue and share the logs here? Also can you provide the following information for us to investigate issue better:

- The code segment where you create your `CardConfiguration` .
- To make it clear, when the country is changed in shipping form, do you make a new call to `/paymentMethods` end point? If so, can you share the response you get. In addition to that please share the contents of the `PaymentMethod` object that you pass when you call `CardComponent.PROVIDER.get()`.

**Comment by machiapply** [comment]
Thank you for looking @ozgur00 !

The log file is here (sorry, it's long, but included all logs while i chose Canada and changed to France):
[cc-payment-2024-01-22-09-33.log](https://github.com/Adyen/adyen-android/files/14013565/cc-payment-2024-01-22-09-33.log)

- `CardConfiguration` is below:
```
        CardConfiguration componentConfiguration = new CardConfiguration
                .Builder(shopperLocale, environment, clientKey)
                .setHolderNameRequired(true)
                .setShowStorePaymentField(false)
                .setShopperReference(shopperReference)
                .setShopperLocale(shopperLocale)
                .build();
```
- Yes, we're calling  `/paymentMethods` end point again to get the new payment methods object.
with Canada shipping country
```
 {"type":"scheme","name":"Credit Card","brands":["amex","mc","visa"],"brand":"null"}
 ```
 with France shipping country
 ```
 {"type":"scheme","name":"Credit Card","brands":["mc","visa","cartebancaire"],"brand":"null"}
 ```
Logged just before passing to PROVIDER call
```
        Log.d(TAG, viewModel.getPaymentMethod().SERIALIZER.serialize(viewModel.getPaymentMethod()).toString());
        CardComponent component = CardComponent.getPROVIDER().get(theActivity, viewModel.getPaymentMethod(), configuration);
```

Let me know anything else you need.

**Comment by ozgur00** [comment]
Hi @machiapply! Thanks for providing all this information. I have a theory but I need to validate something else in the logs. After choosing France in the shipping form and starting the checkout flow can you input a CB card and share the verbose logs at that point?

**Comment by ozgur00** [comment]
One addition: Can you use `CO.` in logcat to filter the logs and see only the ones coming from Adyen Android SDK? 
![Screenshot 2024-01-23 at 11 51 50](https://github.com/Adyen/adyen-android/assets/6615094/bc4036c0-c9b0-495d-b260-705a8b293f3d)

**Comment by machiapply** [comment]
@ozgur00 here is the log 
[cc-payment-2024-01-23-08-26.log](https://github.com/Adyen/adyen-android/files/14027267/cc-payment-2024-01-23-08-26.log)

**Comment by ozgur00** [comment]
Hi @machiapply! While investigating the issue I have noticed something. While you're initialising the component with the line
```
    CardComponent component = CardComponent.getPROVIDER().get(theActivity, viewModel.getPaymentMethod(), configuration);
```
you're passing an `Activity` as the lifecycle owner. What I'm suspecting is that second time you're calling this `showComponentView` function since you're passing the same activity it gives you the same instance. Since you're using the component in a fragment I suggest passing the fragment as the lifecycle owner.

In addition, we have a [react-native](https://github.com/Adyen/adyen-react-native/) sdk too. There we also provide the card component. It's provided within a bottom sheet however since you're using a bottom sheet fragment already it might be worth checking it out.

Don't hesitate to let us know if you have further questions.

**Comment by ozgur00** [comment]
Closing the issue due to inactivity.
