### ISSUE TITLE
3DS2 e Shopper Locale

### ISSUE THREAD

**Issue by LFMAKER** [Adyen/adyen-android#1448]
**Describe the bug**
The 3DS2 challenge is exclusively shown in en-US. Only the header utilizes the shopper's locale for translation into pt-BR.

**Expected behavior**

The entire page should be presented in pt-BR, with the language and country defined in the shopperLocale.

Displaying this challenge in a language that most users do not speak can negatively impact transactions, leading to confusion and frustration. To optimize user experience and ensure higher transaction success rates, it is crucial to present the 3DS2 challenge in the user's preferred language. 

**Screenshots**

![Screenshot 2024-01-23 at 13 51 48](https://github.com/Adyen/adyen-android/assets/8159987/02b100c5-bb29-4780-bc2e-d2da41d8fa4f)

**Comment by ozgur00** [comment]
Hi @LFMAKER. Thanks for bringing the issue into our attention. Are you using drop-in or components integration? And can you share which version you're using?

**Comment by tkuntubayev** [comment]
Hi @LFMAKER,
Please check this link that explains how the localization of 3DS2 SDK works
https://github.com/Adyen/adyen-3ds2-android/issues/50

In brief, the content language is defined by issuer's ACS.
I hope this helps.

**Comment by jreij** [comment]
Hi @LFMAKER , I'm marking this issue as resolved, please reopen it if you still need help with it.
