### ISSUE TITLE
Drop In new AdyenCheckout, paymentMethodsResponse

### ISSUE THREAD

**Issue by marinaprec** [Adyen/adyen-android#145]
Hello, 

I am using dropin in my web, but I can not paint the response of the /paymentMethods with js.
This is the issue, I have the response in js, likie this:

const paymentMethodsResponse = "{'groups':[{'name':'Credit Card','types':['visa','mc','amex','maestro','diners','discover']}],'paymentMethods':[{'brands':['visa','mc','amex','maestro','diners','discover'],'details':[{'key':'encryptedCardNumber','type':'cardToken'},{'key':'encryptedSecurityCode','type':'cardToken'},{'key':'encryptedExpiryMonth','type':'cardToken'},{'key':'encryptedExpiryYear','type':'cardToken'},{'key':'holderName','optional':true,'type':'text'}],'name':'Credit Card','type':'scheme'},{'name':'PayPal','supportsRecurring':true,'type':'paypal'},{'details':[{'key':'sepa.ownerName','type':'text'},{'key':'sepa.ibanNumber','type':'text'}],'name':'SEPA Direct Debit','supportsRecurring':true,'type':'sepadirectdebit'},{'name':'SEPA Bank Transfer','supportsRecurring':true,'type':'bankTransfer_IBAN'}]}";

then, I create an instance :

        // 1. Create an instance of AdyenCheckout
const checkout = new AdyenCheckout({
      locale:'es-ES',
      environment: 'test',
      originKey: 'my key, // Mandatory. originKey from Costumer Area
      paymentMethodsResponse: paymentMethodsResponse 
 
});
And after that , I mount the rest:

// 2. Create and mount the Component
const dropin = checkout.create('dropin').mount('#dropin-container');
 // 2. Create and mount the Component
 const card = checkout .create('card').mount('#card-container');

But I don´t get draw my payment methods.

What are I doing wrong?

**Comment by caiofaustino** [comment]
Sorry, this is the repository for the Android version of the Drop-in.

Could you please forward your question to Adyen support?

**Comment by marinaprec** [comment]
Of course, sorry.
I am new here, I really don´t know how it works

**Comment by marinaprec** [comment]
Wrong repository

**Comment by caiofaustino** [comment]
No problem, sorry for not being able to help :)
