### ISSUE TITLE
Drop-In dimming doesn't work on Android 13 (API 33)

### ISSUE THREAD

**Issue by wrozwad** [Adyen/adyen-android#1474]
**Describe the bug**
On Android 13 (API 33) dimming / scrim effect doesn't work when we launch Drop-In. Someone from [StackOverflow](https://stackoverflow.com/questions/77053309/cannot-set-dimamount-for-bottomsheetdialogfragment-in-android-13) is also experiencing this issue. We are currently using version `5.2.0` of the Drop-In library.

**To Reproduce**
1. Obtain an Android 13 (API 33) smartphone / emulator
2. Launch Drop-In
3. Observe the missing background dimming

**Expected behavior**
The dimming effect should also be visible on Android 13 (API 33).

**Screenshots**
![image](https://github.com/Adyen/adyen-android/assets/2025949/0ef0612e-512d-45c9-89bc-02e62e9bfb0e)

**Additional context**
Our temporary solution is to override `AdyenCheckout.Translucent` style in the `values-v33` folder for API 33 with the following code:
```xml
<style name="AdyenCheckout.Translucent">
    <item name="android:windowIsTranslucent">true</item>
    <item name="android:backgroundDimEnabled">false</item>
    <item name="android:windowBackground">#3f00</item>
    <item name="windowNoTitle">true</item>
    <item name="windowActionBar">false</item>
</style>
```

**Comment by jreij** [comment]
Hi @wrozwad , thanks for the bug report and the investigation! We will look into it and update you once we have something.

**Comment by filipebrandao** [comment]
Hi, sharing some additional info: I'm seeing this issue on API 29 and above. The temporary solution mentioned by the OP works well for those too, if placed in `values-v29`folder.

**Comment by wrozwad** [comment]
@OscarSpruit Unfortunately I don't have access to physical device with API 33. But I can reproduce this also in our app using yours sdk directly without any changes. My current setup:
- Android Studio Hedgehog | 2023.1.1 Patch 2
- Android SDK Build-Tools 35-rc1
- Android Emulator 33.1.23
- Android SDK Platrofm-Tools 34.0.5

**Comment by OscarSpruit** [comment]
@wrozwad thank you! We are still not able to reproduce though, but we are thinking it might be an emulator issue. In the SO issue you linked earlier someone linked to [this issue tracker](https://issuetracker.google.com/issues/289117017). Could you try to update to the latest emulator version and see if this solves the issue?

@filipebrandao are you perhaps able to reproduce the issue on a physical device?

**Comment by filipebrandao** [comment]
@OscarSpruit your assumptions are right :)

I've quickly tested on an Samsung S20 FE running Android 13 and One UI 5.1  : no issue ✅ 
Then I noticed I could update the Android emulator from v33.1.23 to v33.1.24 , so I did and after testing on the same API 33 emulator I was using before : no issue ✅ 

I recall seeing these kind of issues with Jetpack Compose, I've even +1'd [this issue](https://issuetracker.google.com/issues/270983047) which seems to be converging with the one you mentioned and it's not exclusive to Compose after all.

Thanks for looking into this 👍

**Comment by OscarSpruit** [comment]
@filipebrandao thank you for checking it so quickly!

**Comment by wrozwad** [comment]
I can confirm that updating the Android emulator to v33.1.24 fixes that problem! Thx for quick responses!
