### ISSUE TITLE
Android 3ds secure payment issue on v5.0.0

### ISSUE THREAD

**Issue by janw-ttc** [Adyen/adyen-android#1482]
I am integrating Adyen payment for android with android drop-in using version 5.0.0 where i am able to start payment using DropIn and it is working fine but when it comes to 3d Secure authentication it doesn't do anything just showing loading . I tried to pass action object
val action = Action.SERIALIZER.deserialize(jsonObj.getJSONObject("action"))
DropInServiceResult.Action(action)
but it does not handle anything .

Below is the code snippet which i use to complete 3d secure authentication starting from creating DropinConfiguration object

             val cardConfiguration = CardConfiguration.Builder(this,Environment.TEST, BuildConfig.ADYEN_CLIENT_KEY)
            .setShowStorePaymentField(false)
            .setHolderNameRequired(true)

            .setHideCvc(false)
            .build()

        val dropInConfiguration = DropInConfiguration.Builder(this, Environment.TEST,BuildConfig.ADYEN_CLIENT_KEY)
            .setAmount(amount)
            .add3ds2ActionConfiguration(
                Builder(Locale.US, Environment.TEST, BuildConfig.ADYEN_CLIENT_KEY).setThreeDSRequestorAppURL(RedirectComponent.getReturnUrl(this)).build(),
            )
            .addRedirectActionConfiguration(
                RedirectConfiguration.Builder(Locale.US, Environment.TEST, BuildConfig.ADYEN_CLIENT_KEY).build(),
            )
            .addCardConfiguration(cardConfiguration)
            .build()

        val paymentMethodsApiResponse = paymentMethods?.let { it1 ->
            PaymentMethodsApiResponse.SERIALIZER.deserialize(
                it1
            )
        }
        if (paymentMethodsApiResponse != null) {
            DropIn.startPayment(
                this,
                dropInLauncher,
                paymentMethodsApiResponse,
                dropInConfiguration,
                AdyenDropInService::class.java,
            )
        }
and when i get the response for payment and it contains action object i passed that to DropinServiceResult.Action like below
      val action = Action.SERIALIZER.deserialize(jsonObj.getJSONObject("action"))
      DropInServiceResult.Action(action)

It doesn't redirect me to anywhere where I can complete the 3d secure payment.

**Comment by janw-ttc** [comment]
@jreij i have created issue above

**Comment by jreij** [comment]
Hi @janw-ttc , do you still need help with this issue?

**Comment by janw-ttc** [comment]
@jreij Hi
We can close this ticket
