### ISSUE TITLE
Failure in Release Build when migrating from 4.9.1 to 5.2.0 Adyen SDK (ERROR: R8 Missing Class)

### ISSUE THREAD

**Issue by lilemma** [Adyen/adyen-android#1483]
**Describe the bug**
I am migrating to the newest adyen version from 4.9.1, but my release build is failing with our minifyWithR8 task, here is the output:

adyen-3ds2-2.2.15-runtime.jar -> throws 169 warnings which looks like
```
The companion object Companion could not be found in class atd.v.l
The companion object Companion could not be found in class atd.l.m
```

and these are the errors:
```
AGPBI: {"kind":"error","text":"Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in /app/build/outputs/mapping/prodtest/missing_rules.txt.","sources":[{}]}
Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in /app/build/outputs/mapping/prodtest/missing_rules.txt.

AGPBI: {"kind":"error","text":"Missing class kotlinx.parcelize.Parceler (referenced from: com.adyen.checkout.core.internal.util.JSONObjectParceler)\nMissing class kotlinx.parcelize.Parcelize (referenced from: com.adyen.checkout.ach.ACHDirectDebitAddressConfiguration$FullAddress and 148 other contexts)","sources":[{}],"tool":"R8"}

Missing class kotlinx.parcelize.Parceler (referenced from: com.adyen.checkout.core.internal.util.JSONObjectParceler)
Missing class kotlinx.parcelize.Parcelize (referenced from: com.adyen.checkout.ach.ACHDirectDebitAddressConfiguration$FullAddress and 148 other contexts)
```

I tried the suggestion "https://github.com/Adyen/adyen-android/issues/1394#issuecomment-1822995111" but that option is deprecated.

**To Reproduce**
Create a new project including implementations 'com.adyen.checkout:drop-in-compose:5.2.0' and  'com.adyen.checkout:components-compose:5.2.0', modify release's minifyEnabled to true,

**Expected behavior**
If any proguard rules is needed to build the project, I would expect them to be declared in consumer-rules.ro

**Desktop:**
Independent of desktop

**Smartphone:**
Independent of the device

**Additional context**
gradle-8.6-rc-1
agp = 8.3.0-rc02
(drop-in-compose, components-compose) adyen = "5.2.0"
kotlin = "1.9.0"

**Comment by OscarSpruit** [comment]
Hi @lilemma, thank your for opening this issue! We will investigate the issue more and see if we can fix it. In the mean time you could apply the parcelize plugin as a workaround:
```Groovy
plugins {
    ...
    id 'kotlin-parcelize'
}
```

About the `adyen-3ds2-2.2.15-runtime` warnings I'm not sure what to do with them yet, I'll get back to you when I know more.

Please let us know if the workaround helped

**Comment by OscarSpruit** [comment]
It is safe to ignore the `adyen-3ds2-2.2.15-runtime` warnings. We are also working on fixing these, but that will take some time

**Comment by lilemma** [comment]
Hi @OscarSpruit thanks for the suggestion, the workaround works :)

**Comment by PhilippeBoisney** [comment]
Hey there 👋 
I'm using the `5.9.1` version and I still have the warnings :/

<img width="655" alt="Image" src="https://github.com/user-attachments/assets/db3d44ce-0035-415f-bdf2-4a3952ac2606" />

<img width="544" alt="Image" src="https://github.com/user-attachments/assets/d6cf8572-fbb5-49d3-8ccf-758b2e35cced" />
