### ISSUE TITLE
Localize refusalReasonCodes

### ISSUE THREAD

**Issue by Kolyall** [Adyen/adyen-android#149]
Is it all refusal codes?
https://docs.adyen.com/point-of-sale/refusal-reasons-pos
But there is no code 24, it's "CVC Declined"
```
{
   "additionalData": {
      "recurringProcessingModel": "CardOnFile"
   },
   "pspReference": "882576239000191H",
   "refusalReason": "CVC Declined",
   "resultCode": "Refused",
   "refusalReasonCode": "24",
   "merchantReference": "android-test-components"
}
```
Where we can get all `refusalReasonCodes` for localize them?

**Comment by caiofaustino** [comment]
The documentation you see is for Point of Sale terminals, not online payments.
In general I'd recommend to not show the refusal code to end user at all, but please reach out to  support@adyen.com if you'd like more information as this is not an Android related issue please.
