### ISSUE TITLE
[v5.2.0] Not supported Adobe Commerce (Magento) headles-integration `cc` payment type

### ISSUE THREAD

**Issue by wrozwad** [Adyen/adyen-android#1499]
**Describe the bug**
We are attempting to integrate Adyen into our mobile apps. In the latest Magento headles-integration plugin `9.0.5`, we began receiving the `"cc"` payment method type instead of `"scheme"`. However, initialising Drop-In with `com.adyen.checkout.components.core.PaymentMethod.type = "cc"` does not function as expected. We must manually replace `"cc"` to `"scheme"` due to the value of `com.adyen.checkout.components.core.PaymentMethodTypes.SCHEME`. As far as I know, iOS has a more robust SDK API in this area; their `PaymentMethod.type` is an enum, not a String.

**Expected behavior**
Adyen Android SDK should start supporting the `"cc"` payment type out of the box.

**Screenshots**
This is how Drop-In looks with a single `"cc"` payment method and `setSkipListWhenSinglePaymentMethod(true)` setup:
<img width="385" alt="image" src="https://github.com/Adyen/adyen-android/assets/2025949/dd056f58-4af1-4a7b-a879-e272f2e82330">

**SDK version**
`5.2.0`

**Comment by OscarSpruit** [comment]
Hi @wrozwad, the Android SDK doesn't expect `cc`, so it is not able to deal with this value. I forwarded your issue internally and it seems to be a setup issue with the Magento plugin. Please reach out to [our support team](https://www.adyen.help/hc/en-us/requests/new) as they have more insight in your implementation and can help troubleshoot this better

**Comment by wrozwad** [comment]
@OscarSpruit Does the Magento plugin team already have a ticket created for this, or should we create one on https://github.com/Adyen/adyen-magento2/issues?

**Comment by OscarSpruit** [comment]
@wrozwad I already checked with them internally and they suggested that support would be able to help you better

**Comment by jreij** [comment]
Hi again @wrozwad , do you still need help with this issue from our side?

**Comment by wrozwad** [comment]
@jreij No thank you - we addressed this issue in our Magento team. We wrote a wrapper that dynamically changes these values on the backend side, replacing `adyen_cc` and `cc` with `adyen_scheme` / `scheme`
