### ISSUE TITLE
3DS2 and MBWay payments issues when "Do Not Keep Activities" active

### ISSUE THREAD

**Issue by ruimendesM** [Adyen/adyen-android#1535]
**Describe the bug**
It is impossible to complete a 3DS2 or a MBWay purchase with "Do Not Keep Activities" on with the Drop-In. 
Also there is no error being thrown in this case, Drop-In is restored in an "empty state".

We are now updating from 4.13.3 to 5.2.0 version of the Adyen Drop-In SDK, and we noticed that although this was an already existing issue on the previous version, it got a bit "worse" on the 5.2.0 release.

On the version 4.13.3 with DNKA:
- **3DS2:** After inserting the code, drop-in would go back to the credit card form already pre-filled
- **MBWay:** If you went to the background and then to the foreground it would restore the Drop-In view, but never complete

On the version 5.2.0 with DNKA:
- **3DS2:** After inserting the code, "empty" drop-in is shown
- **MBWay:** If you went to the background and then to the foreground, "empty" drop-in is shown

**To Reproduce**
Steps to reproduce the behavior - 3DS2:
1. Make sure the device is with DNKA active
2. Start a payment that require 3DS2
3. Input the code and proceed
4. "Empty" drop-in is shown

Steps to reproduce the behavior - MBWay:
1. Make sure the device is with DNKA active
2. Start a payment MBWay
3. While the payment is awaiting confirmation (see screenshot) go to background
4. Bring app again back to foreground
5. "Empty" drop-in is shown

**Expected behavior**
Ideally we would be able to restore the activity and proceed in both scenarios. 
However, if not possible, Drop-In should at least throw an error so we could react, instead of simply showing an empty state.

**Screenshots**
<img src="https://github.com/Adyen/adyen-android/assets/19568050/17933220-52a1-40d0-bbde-42576d3046c8" width="200" height="400" />

**Smartphone (please complete the following information):**
 - Device: Any
 - OS: Any
 - Version: 5.2.0 (drop-in)

**Additional context**
We currently are logging every instances in production where an Activity restoration is required while on the Adyen Drop-In and in the last 90 days it happened to 425 users. 
While this does not mean that the user encountered this problem (as in scenarios without 3DS2 or scenarios where user has not yet started the payment also fell into this bucket), it is an indication that the activity restoration is important and should ideally be handled (even if by simple throwing an error, if not fixable).

![image](https://github.com/Adyen/adyen-android/assets/19568050/a1fcfb2a-9f67-4233-8318-abb08e968e71)

**Comment by wrozwad** [comment]
This is related to https://github.com/Adyen/adyen-android/issues/1509 I think

**Comment by araratthehero** [comment]
Hi @ruimendesM, thank you for opening the bug request. I believe we are already working on a fix for this issue.
Thank you @wrozwad for mentioning the related https://github.com/Adyen/adyen-android/issues/1509 issue.

We will keep you updated on both issues, when there is a PR open with the fix.

**Comment by OscarSpruit** [comment]
Hi @ruimendesM, we just released [5.4.0](https://github.com/Adyen/adyen-android/releases/tag/5.4.0) which should fix these issues. Please let us know if you still face any problems.
