### ISSUE TITLE
Drop-in 3.6.0 (Java implementation) paypal redirect

### ISSUE THREAD

**Issue by wilochoa** [Adyen/adyen-android#155]
Hi! i implemented the drop-in in Java (you should support the documentation for java), with the credit cards works without problems. but when i process the payment with paypal, it never comeback from the webview to the app.. instead it go to the url in the same webview. with the response of the process. 

example.  at the end of the process i got this in the same webview

https://my-url/mvl/v1/checkout/ok/QLNYG?payload=Ab02b4c0%21BQABAgBh%2FvJ2FQw2Ki%2F95c%2Bn2ZJpE9zDO30OjeKm2s1pAohuM4V2vBCnphC91%2BPq5axpd1p3x6s7%2B%2BFWpzsKaZ2fEmdpQvqUqUSZn2%2BC9hxdyVgB6cN4YPaxZXI8YWU%2FPmS5BK5%2F4qHZkchPFer5Zcdtb6CJQ5M4xctMdhkkFHlq7vGMwltpOYLOQ34unsrRnCH4DqEJ57wpTwjh4tiK9janyfw56KD9GkuQRku91ZFsMR4%2BGMQN25KVicLDwRkoGRhPCbrC43tk5lrm7k2EQlNUnOLY17VRDa8keQGuXH46Eb%2BJpJJdldf9qHz0%2B6asup%2FTUXjlZGjTro83F9X5bJVv%2BsUjwy55K%2Fs%2FZvmJ%2FXj5JTvxM%2BJ9o9UmYg2Qt4nBdSLP%2FQYjvgoou1vX5LCayMiEFWvEOYH0AoM1r9GkGgoOoxa6k%2BSQEk01GeGjtqYgaM5wn6D8hH5GamYlzJD8zXYyUePd0GxG6snelIeEC7qFF4W6WyuGsIx81rYh28eU7DsF6o5zQqPp%2BcLG5jx4VHHNm3A8WpynkjzOQcIdU%2BSi1YFVH82oNs8ZxiRvs7GfQ5I93r8etiBntt17oBMMR1H%2FWxH9im4xZsZ73fXUbIQ8HHqI4a8UYKrCsfmOtzwinKVBciKfsxdJzpVHU78pJXgKhTrAuX2McOcnLwBmQpBfy1%2BJJxCm0pQzMwU7HhmrwiQGLxZLAEp7ImtleSI6IkFGMEFBQTEwM0NBNTM3RUFFRDg3QzI0REQ1MzkwOUI4MEE3OEE5MjNFMzgyM0Q2OERBQ0M5NEI5RkY4MzA1REMifc4qtKxgF6oJxWwgpnIgn85W%2BKMCf%2BfHM9gLaAWz1aWvEhCSXIftMQ%2Fe2W4oQPaT82Z053k1tjdyoSFdweq%2Bg7l2Ll%2Bh23v3WVFyOrgTKk1GM%2FjoB7PPsP2p2oDDtCLXa1LsMO1j1upufmYCH2hDjihk%2BK5rNXzvurfdjUusyY5KXwC9NVjozCOPD657RRCj6uJTByquV9Bg8GZwnwcom%2F%2FSLA7wmd1LTKgczTKxiIXO5g2K3z86bdTm3pdikICD072Y3g6pLoLWTJnLIP9lAghO5RoyVti74%2BuWa74CeGYJ4RSsGOfYEK8fSizwdL1RNmkwJmUKaTT3Jyxnj2wnGamZ1VuOkg%3D%3D&type=complete&resultCode=authorised

any help?

**Comment by caiofaustino** [comment]
Hey there,

Sorry what do you mean by the documentation for java? On the Adyen Docs website or in the code?

So since you are using the drop-in, the redirect process is handled by the drop-in, you only need to make sure to send the correct `returnUrl` on the `/payments` call. You can get it from `RedirectComponent.getReturnUrl(context)`.

So it seems to me that you are passing something like `https://my-url/mvl/v1/checkout/ok/QLNYG`, when it should be `adyencheckout://your.package.name`

Let me know if that helps.

**Comment by wilochoa** [comment]
Ok, help me to understand a little more. 

I checked the return url as you said. 
and my return url is ok . adyencheckout://my.package.name

but this url https://my-url/mvl/v1/checkout/ok/QLNYG appear in the same webview after the process of paypal. 
so, my backend has to do something to redirect to adyencheckout://my.package.name?

**Comment by caiofaustino** [comment]
Does the redirect work as expected with other payment methods?

If it does, please contact Support and share a PSP reference with them, this could be an issue with the PayPal test environment or something similar.

**Comment by wilochoa** [comment]
the other payments redirect are working well. just happen with paypal.

Ok, i'll do it. Thanks.

**Comment by SMJ93** [comment]
@wilochoa did you manage to get 3DS cards working? I think we are both trying to build this in Java haha

**Comment by wilochoa** [comment]
@SMJ93 yes, we are both trying haha, but in may case i "believe" i have done. the issue with paypal was a backend issue and it were fixed.. and with 3DS works without problem.

**Comment by wilochoa** [comment]
@caiofaustino the issue was fixed. it was a problem with the backend that it dont was redirecting to adyencheckout://your.package.name. issue closed.

**Comment by OgnjenLF** [comment]
Hello, 
quick question: 
Are there any test cards that can open any redirect webview to test this functionality? On our project we could only achieve this on production and the testing becomes kind of impossible. I tried most of the https://docs.adyen.com/development-resources/test-cards/test-card-numbers and non of them worked ("Refused" error code or a generic error toast). 

Also what kind of work do backend need to do to support this, isn't this an SDK only feature?

Also, is the process, **adyencheckout://your.package.name**, the same with Drop-in and the Checkout Android SDK https://docs.adyen.com/online-payments/classic-integrations/checkout-sdks/android-sdk?
@caiofaustino

**Comment by caiofaustino** [comment]
hey @OgnjenLF, is this relevant to the PayPal redirect mentioned on this issue?
If not, please open a new issue so that we don't get the two mixed together, and it might help other people looking for the same question.
