### ISSUE TITLE
Locale es_Es is not working.!

### ISSUE THREAD

**Issue by wilochoa** [Adyen/adyen-android#157]
Hi, its me again.! :) 

i am implementing this.

Locale locale = new Locale("es", "ES");
                        DropInConfiguration dropInConfiguration = new DropInConfiguration.Builder(getActivity(), MyDropInService.class)
                                .setEnvironment(Environment.TEST)
                                .addCardConfiguration(cardConfiguration)
                                .setResultHandlerIntent(resultIntent)
                                .setShopperLocale(locale)
                                .build();

But it still opened in english. 

Any help ?

There is nothing in the android documentation about it.. just for the web drop-in.

**Comment by ArmanSo** [comment]
Hi @wilochoa :)
Currently we're just supporting english, altho you can override strings in your `strings.xml` file.

for example 
```
<string name="checkout_card_number_hint">Número de tarjeta</string>
```
FYI You can use Github's file search https://github.com/Adyen/adyen-android/find/master to find all `strings.xml` files

**Comment by caiofaustino** [comment]
Just to complete the information, right now the Component is not yet using the `Locale` value from the `Configuration` object to set the strings, it will use the default device Locale and get that from the `strings.xml` like Arman said.

We plan to implement that after we support some translations out of the box, but that is still WIP.

**Comment by SMJ93** [comment]
Hey guys, are there any plans to fully support locales? I'm testing French and it shows some of the dropin in French and some in English:

![Screenshot_1579171827](https://user-images.githubusercontent.com/2145641/72519036-7fbe3d80-384e-11ea-889e-1f4542cefee7.png)

**Comment by caiofaustino** [comment]
Yes, the next release next week will contain the localized strings for the locales we support.

Still based on the user device Locale instead of the Configuration object though. That feature will come in the future.

**Comment by SMJ93** [comment]
Nice one! Is there any ETA for the configuration object locale?

**Comment by caiofaustino** [comment]
Not yet, there are some other priorities on the list right now, sry =/

**Comment by caiofaustino** [comment]
@SMJ93 @wilochoa the translated strings are released in `3.6.2`, can you check if it looks as you expect?

**Comment by tinsukE** [comment]
@caiofaustino some popular locales seem to be half-translated, as some entries are still in English:
- https://github.com/Adyen/adyen-android/blob/3.6.2/drop-in/src/main/res/values-de-rDE/strings.xml
- https://github.com/Adyen/adyen-android/blob/3.6.2/drop-in/src/main/res/values-nl-rNL/strings.xml

Is this expected?

**Comment by caiofaustino** [comment]
Thanks for pointing that out @tinsukE, the missing strings are from strings we haven't yet received from the translators, we will update those as they are provided to us, so probably on the next release.

Sorry for the inconvenience.

**Comment by wilochoa** [comment]
Hi, i got almost all the string just overriding it... but i cant find the Expiry Date String. therre is not in droping string, and i dont know where could be.. please can you helpme with this.

**Comment by caiofaustino** [comment]
@wilochoa this one?
https://github.com/Adyen/adyen-android/blob/master/card-ui-core/src/main/res/values/strings.xml#L12

**Comment by caiofaustino** [comment]
Hey all,
New release `3.6.3` is now enforcing the localization on both Drop-in and Components to use the Locale from the `Configuration` object.
Please give it a try and let me know what you think.

**Comment by caiofaustino** [comment]
PS: some strings come from the `/paymentmethods` call as well so make sure to send the shopper locale to that that as well for consistency.

**Comment by caiofaustino** [comment]
Since there wasn't any feedback I assume the update went well. 
If any of you still find any issues related to translation feel free to open a new issue with the specific problem.

Cheers!

**Comment by fleficher** [comment]
Hi, the locale of the dropin is still using the device locale instead of the one provided in the `Configuration` object (tested in 3.6.6 in Italy)

![image](https://user-images.githubusercontent.com/6464646/92920488-a317a780-f432-11ea-8e26-0235d981c8e1.png)
