### ISSUE TITLE
[v5.3.1] `setSkipListWhenSinglePaymentMethod` ignored with `googlepay`

### ISSUE THREAD

**Issue by wrozwad** [Adyen/adyen-android#1580]
**Describe the bug**
HELLo moto ;] We have our own payment method picker, so we use `setSkipListWhenSinglePaymentMethod` with `CheckoutConfiguration`. Unfortunately, if we receive only `googlepay` as the available payment method, the Drop-In still displays a bottom sheet with the payment method selection.

**To Reproduce**
1. Set skipping the payment method list in `CheckoutConfiguration`
```kotlin
dropIn {
    setSkipListWhenSinglePaymentMethod(true)
}
```
2. During Drop-In initialization, only pass `googlepay` as the available payment method.

**Expected behavior**
Drop-In initialization should immediately show the Google Pay system window without an intermediary bottom sheet for payment method selection.

**Screenshots**
![image](https://github.com/Adyen/adyen-android/assets/2025949/bfea868f-e943-406c-a1a1-7197e2e51123)

**Comment by wrozwad** [comment]
@OscarSpruit In our case, the moment of selecting the payment method is split. So the condition you mentioned

>[it is required by Google](https://developers.google.com/pay/api/android/guides/brand-guidelines) to show the Google Pay mark before launching Google Pay

is handled on our side. [The additional implementation](https://docs.adyen.com/payment-methods/google-pay/android-component) required when using the component makes the whole process very complicated, especially when using Jetpack Compose. Therefore, a flag like `setSkipListWhenSinglePaymentMethodEvenIfRobotsAttackEarth` would be very useful.

**Comment by OscarSpruit** [comment]
@wrozwad I understand it complicates the flow for you, but the current `setSkipListWhenSinglePaymentMethod` already gets abused and it was never intended for people to use it to replace components with drop-in. In our opinion the solution is to improve the component.

We are already working on this and one of the improvements for example is to handle the activity result inside of the SDK. What are the pain points you are experiencing with the component currently? And do you have any other improvements in mind for Google Pay?

**Comment by OscarSpruit** [comment]
@wrozwad we are still using `onActivityResult` because previously the Google Pay SDK didn't support Activity Result Contracts. We are currently working on an improvement where we can internally handle the Activity Result. This would fix your problem. We will keep you posted on the progress
