### ISSUE TITLE
Identify 3DS cancellation

### ISSUE THREAD

**Issue by zsoltvilagos** [Adyen/adyen-android#159]
### Why

For reporting & UX purposes, we'd like to identify whether the customer canceled the 3DS customer verification or some error happened.

### What

https://github.com/Adyen/adyen-android/blob/3.6.1/3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2Component.java#L156 gets notified by Adyen 3DS SDK that the customer cancelled (and not some arbitrary error happened) but it responds with a `Authentication3DS2Exception` just like in `timedout`, `protocolError` or `runtimeError` cases, with only the message being different.

For now, we rely on the message to identify cancellation but would like to see an improvement to Adyen SDK to be able to make this identification based on some "programmatically more stable" information.

Suggestion: keeping backward compatibility in mind, what about inheriting some `Authentication3DS2CancelledException` from `Authentication3DS2Exception` so that client code can check for exception type (and also retaining the exact same message as is now).

I would love to create a pull request had the idea been approved.

**Comment by ArmanSo** [comment]
Hi @zsoltvilagos 

I agree with you, definitely it's not a good idea to compare exceptions message to identify state of flow. 

We will consider that, thanks for suggestion.

Cheers.

**Comment by caiofaustino** [comment]
Hey @zsoltvilagos, this change is released in `3.6.2`, can you check if this solves the problem for you?

**Comment by zsoltvilagos** [comment]
@caiofaustino Yepp, I'm about to check it now.

**Comment by zsoltvilagos** [comment]
@caiofaustino Works like a charm!

Resolved. Closing.
