### ISSUE TITLE
Shopify integration + Adyen: how to proceed?

### ISSUE THREAD

**Issue by amanzan** [Adyen/adyen-android#16]
I'm working on an app that has Shopify integration, and I was wondering if there's any way to combine it with Adyen for the checkout process. Any advice about how to proceed would be really appreciated. Thanks a lot!

**Comment by timon-langlotz** [comment]
Hi @amanzan,

For this to work for you (and to have a single UI for checkout), I'd recommend the custom integration. You can find more information in ours documentation: https://docs.adyen.com/developers/in-app-integration/custom-integration

Happy coding!
