### ISSUE TITLE
Google Pay readyToPayRequest return flase

### ISSUE THREAD

**Issue by xiaoxiaohua333** [Adyen/adyen-android#161]
android 10

implementation "com.adyen.checkout:drop-in:3.6.1"
 implementation 'com.google.android.gms:play-services-wallet:18.0.0'

   <meta-data
            android:name="com.google.android.gms.wallet.api.enabled"
            android:value="true" />

---------------------

I found GooglePayProvider check isAvailable(), PaymentsClient.readyToPayRequest always return false, so I use the same readyToPayRequest to check googlePay and return true.

![image](https://user-images.githubusercontent.com/9317990/72504454-cd4fa000-3878-11ea-82df-8c91eb756586.png)

![image](https://user-images.githubusercontent.com/9317990/72504511-e9ebd800-3878-11ea-95f8-c5399068be28.png)

**Comment by xiaoxiaohua333** [comment]
![image](https://user-images.githubusercontent.com/9317990/72504987-e9a00c80-3879-11ea-8b12-75af0947bd8d.png)

The task is successful but task.getResult is flase;

I try other gateway, only check task is successful and pay success.

**Comment by caiofaustino** [comment]
Can you try to remove the google pay dependency and try again?
`implementation 'com.google.android.gms:play-services-wallet:18.0.0'`

We already add a dependency to it inside the Component, but we use an older version because we can't update to AndroidX dependencies yet.

**Comment by xiaoxiaohua333** [comment]
ye I found other Gateway use isReadyToPay just check task.isSuccessful and show GooglePay method, the task.getResult always false but I can pay with GooglePay success .

**Comment by caiofaustino** [comment]
Yes the task will finish successfully with a false result. It means that based on the request we send, GooglePay thinks this user is not able to finish the payment. This could be based on several reasons, if the type of payment is available on that country, or if the account is properly setup or not, etc...

What do you mean with "try other gateway"? Is that on the `tokenizationSpecification:gateway` parameter? Did you put a different value there and then it is successful?
