### ISSUE TITLE
Drop-in UI Incorrectly Displays CVC Field for Saved Maestro Card Without CVC

### ISSUE THREAD

**Issue by timatpam** [Adyen/adyen-android#1616]
Description: When making a payment using the test card number 6703 4444 4444 4449 (from [Test card numbers](https://docs.adyen.com/development-resources/testing/test-card-numbers/#bancontact-bcmc)) with the 'save card' option enabled and using it as Maestro card, the Drop-in payment screen does not request a CVC as expected, since this card has no CVC. However, upon attempting a subsequent payment with the saved card, the Drop-in interface erroneously prompts for a CVC.

Steps to Reproduce:

1. Initiate a payment using the test card number 6703 4444 4444 4449 as Maestro with the 'save card' feature turned on. Note that there is no CVC for this card, and the Drop-in interface does not present a field to enter one.
2. Attempt a second payment using the previously saved card.

Actual Behavior: The Drop-in interface displays a field requesting the CVC/CVV, requiring the user to enter any 3 digits to proceed with the payment.

Expected Behavior: The Drop-in interface should not display a CVC field for the saved card, as it is not applicable for this card type.

Technical Details: Our backend provides a JSON for the saved card with the attribute "cvcRequired": true, which appears to be ignored by the Drop-in when it parses the stored payment method (see [StoredPaymentMethod.kt](https://github.com/Adyen/adyen-android/blob/develop/components-core/src/main/java/com/adyen/checkout/components/core/StoredPaymentMethod.kt) ).

**Comment by jreij** [comment]
Hi @timatpam , thanks for reaching out. We do not support automatically hiding the CVC field based on the brand in the stored card component. As for the `cvcRequired` field, this is not part of our [API response](https://docs.adyen.com/api-explorer/Checkout/71/post/paymentMethods#responses-200-storedPaymentMethods) so we cannot parse it. Do you know where does your backend get this value from?

However we do have a client side configuration flag that allows you to hide the cvc field. If you think the flag you are getting from your backend is reliable, you can call [setHideCvcStoredCard(true)](https://adyen.github.io/adyen-android/card/com.adyen.checkout.card/-card-configuration/-builder/set-hide-cvc-stored-card.html) when you create your configuration:

```kotlin
val checkoutConfiguration = CheckoutConfiguration(
    environment = environment,
    clientKey = clientKey,
    amount = amount,
    ..
){
    card {
        setHideCvcStoredCard(VALUE_FROM_YOUR_BACKEND)
        ..
    }
    ..
}

DropIn.startPayment(.., checkoutConfiguration, ..)
```

**Comment by jreij** [comment]
@timatpam closing this issue for now, feel free to reopen it in case you still have any related questions.
