### ISSUE TITLE
Can't proceed with checkout in US Klarna Sandbox 

### ISSUE THREAD

**Issue by neil-showpo** [Adyen/adyen-android#1631]
**Describe the bug**
Payment in the US Klarna sandbox always fails with "Sorry, we couldn't approve this purchase". However, other using Klarna Pay over time for other countries are okay. 

**To Reproduce**
1. Select Klarna Pay over Time in Drop-in
2. Proceed with checkout
3. See error

**Expected behavior**
Successful checkout 

**Screenshots**
<img width="481" alt="Screenshot 2024-05-17 at 8 19 35 AM" src="https://github.com/Adyen/adyen-android/assets/58998000/5cbc3315-d3a9-43ba-9d74-89fe1dc53856">

**Additional context**
We are experiencing the issue with all SDK, Android, iOS and Web.

**Comment by OscarSpruit** [comment]
Hi @neil-showpo, thank you for opening an issue! This seems to be an issue on the Klarna side. Please reach out to [our support team](https://www.adyen.help/hc/en-us/requests/new) and they should be able to help you troubleshoot this better.

In the mean time I have a wild guess: maybe Klarna's risk checks are failing the payment ([link to our docs](https://docs.adyen.com/payment-methods/klarna/android-drop-in/#present-the-payment-result)). If you try using a different amount, email address, phone number, etc., does that make a difference?

**Comment by OscarSpruit** [comment]
Hi @neil-showpo , did you manage to resolve your problem? Feel free to reopen this issue if you still need help with it
