### ISSUE TITLE
Reconciliation file for Credit Card

### ISSUE THREAD

**Issue by tugal-dev** [Adyen/adyen-android#164]
Hi ,

We have implemented the credit card payment method using Adyen solution.
Still we have one issue regarding the recociliation file that is made available.

We see that the reconcicliation file is made available by Adyen, still the customer complaints that, when it tries to get the file , it i ot available.
The trigger to get the file is a notification that we get from Adyen, and only after that they try to collect it.

Can you let us know if there is any delay between the notification is generated and the file is complete and available for collection ?  Or the notificiation is generated only the complete file is made available ?

thanks

**Comment by caiofaustino** [comment]
Hey @tugal-dev, this looks like a backend question, this is just the Android repository.
Could you please forward that to Adyen support?

Thanks.

**Comment by caiofaustino** [comment]
I'm closing this since this is not related to Android, I hope you were able to find the problem.
