### ISSUE TITLE
Issue Integrating Adyen SDK Android Components with SessionComponentCallback

### ISSUE THREAD

**Issue by Jean-PhilippeDESCAMPS** [Adyen/adyen-android#1663]
Hi Adyen Development Team,

I hope this message finds you well. I am currently working on integrating the Adyen SDK Android Components into our application, but I've encountered an issue with implementing the SessionComponentCallback. Despite following the documentation, I am unable to get the callback to work correctly.

Below is the relevant portion of my implementation:

val paymentMethod = checkoutSession?.getPaymentMethod(PaymentMethodTypes.GOOGLE_PAY)

                val cardComponent = CardComponent.PROVIDER.get(
                    requireActivity(),
                    checkoutSession,
                    paymentMethod,
                    object : SessionComponentCallback<> {

                        override fun onFinished(result: SessionPaymentResult) {
                            // The payment finishes with a result.
                        }
                        override fun onAction(action: Action) {
                            // An additional action needs to be handled. Forward the action to the Component.
                            //cardComponent.handleAction(action, activity)
                        }
                        override fun onError(componentError: ComponentError) {
                            // The Component encounters an error.
                        }
                    },
                    null
                )
                binding.adyenView.attach(cardComponent, requireActivity())
Could you please assist me in identifying what might be wrong or missing in my implementation? Any guidance or examples would be greatly appreciated.

I don't know what to put in SessionComponentCallback<>.

Thank you in advance for your help!

Jean-Philippe

**Comment by ozgur00** [comment]
Hi @Jean-PhilippeDESCAMPS! Thanks for reaching out.

For which payment method do you want to use Adyen Components? I see you're trying to get `google pay` payment method object using following line:
```kotlin
val paymentMethod = checkoutSession?.getPaymentMethod(PaymentMethodTypes.GOOGLE_PAY)
```

However you're using `CardComponent`. Card Component only works for payment method type `PaymentMethodTypes.SCHEME`. If you would like to use Google Pay you should use our `GooglePayComponent`.

Depending on which type of component you use you should put the necessary component state type as the type while using `SessionComponentCallback`. Examples of that would be:

- For `CardComponent` : `SessionComponentCallback<CardComponentState>`
- For `GooglePayComponent` : `SessionComponentCallback<GooglePayComponentState>`

Let us know if you need further assistance!

**Comment by ozgur00** [comment]
Hi @Jean-PhilippeDESCAMPS. Can you check if you're handling the activity result? You can take a look at our documentation for [Google Pay](https://docs.adyen.com/payment-methods/google-pay/android-component/#handle-the-activity-result). I also do not see the availability check in the code snipped you shared, that's also mentioned as Step 1 in our documentation. You can use our documentation to verify your integration and if the issue persists, please let us know.

**Comment by ozgur00** [comment]
Hi @Jean-PhilippeDESCAMPS. Do you still have the issue?

**Comment by ozgur00** [comment]
Closing the issue due to inactivity. Do not hesitate to contact with us if the issue persists.
