### ISSUE TITLE
Integration Adyen advanced flow in android

### ISSUE THREAD

**Issue by PeterHdd** [Adyen/adyen-android#1667]
Hello Adyen development team,

I'm basically following this flow: https://docs.adyen.com/online-payments/build-your-integration/advanced-flow/?platform=Android&integration=Components&version=5.0.0&tab=no-compose-import_2#2-create-the-configuration-object

Everything is done good until I reach the section "Step 4: Launch and show the Component". I added the adyen component view to the xml file:

```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
  android:layout_width="match_parent"
  android:layout_height="match_parent">
  <com.adyen.checkout.ui.core.AdyenComponentView
    android:id="@+id/ADYEN_PLUGIN_VIEW"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
   />
</androidx.constraintlayout.widget.ConstraintLayout>
```
In the java file I'm doing the following:

```
  View view  = LayoutInflater.from(cordova.getActivity().getApplicationContext()).inflate(R.layout.adyen_component_view,null);
  AdyenComponentView adyenComponentView = view.findViewById(R.id.ADYEN_PLUGIN_VIEW);
  GooglePayComponent googlePayComponent.startGooglePayScreen(cordova.getActivity(), REQUEST_CODE);
  adyenComponentView.attach(googlePayComponent, cordova.getActivity());
```
But it crashes the whole app, I can't pin point the issue. I'm not sure if the issue is because of the xml view being different than the one provided in the tutorial `com.adyen.checkout.components.ui.view.AdyenComponentView` but in this case I'm unable to import this view, which library is needed for this view?

I'm using the following dependencies:
```
dependencies {
  implementation 'com.adyen.checkout:googlepay:5.4.0'
  implementation "com.adyen.checkout:card:5.4.0"
  implementation "com.adyen:adyen-java-api-library:21.0.0"
}
```

Update 1:

I was able to figure out the problem and it was because the xml file in the project is called `adyen_component_view.xml` and in the adyen library there is a class called `AdyenComponentViewBinding.java` so somehow it was conflicting, so just changed the name and i was able to solve it. But now when attaching I'm just getting a black screen:

```
View view  = LayoutInflater.from(cordova.getActivity().getApplicationContext()).inflate(R.layout.adyen_component_layout,null);
cordova.getActivity().setContentView(view);
adyenComponentView = cordova.getActivity().findViewById(R.id.ADYEN_PLUGIN_VIEW);
googlePayComponent.startGooglePayScreen(cordova.getActivity(), REQUEST_CODE);
adyenComponentView.attach(googlePayComponent, cordova.getActivity());
```

any idea?

**Comment by OscarSpruit** [comment]
Hi @PeterHdd, thank you for your question! It is difficult to say why this happens, but I have some ideas. Could you try it like this:
```Java
// Use the Activity context to inflate the view. Using the wrong context can result in weird behaviour.
View view  = LayoutInflater.from(cordova.getActivity()).inflate(R.layout.adyen_component_layout,null);
cordova.getActivity().setContentView(view);
adyenComponentView = cordova.getActivity().findViewById(R.id.ADYEN_PLUGIN_VIEW);
// Attach the view before starting the Google Pay screen
adyenComponentView.attach(googlePayComponent, cordova.getActivity());
googlePayComponent.startGooglePayScreen(cordova.getActivity(), REQUEST_CODE);
```

If that doesn't work, could you enable extensive logs by calling `com.adyen.checkout.core.AdyenLogger.setLogLevel(AdyenLogLevel.VERBOSE)` in your application class and filter your logs by `CO.` to see the checkout logs only and send them here? Maybe the logs will reveal something.

**Comment by OscarSpruit** [comment]
@PeterHdd Google Pay is using a bottom sheet to display it's content. We do not control this, so unfortunately there is no way to make it full screen.

**Comment by PeterHdd** [comment]
But is there a way to just open it as a dialog in the same activity? Because now with `startGooglePayScreen` it opens a completely new activity with a different xml and I'm using a hybrid solution for the app not native. Thus when this activity gets opened, I'm seeing half screen as dark and other half as the bottom sheet dialog, now the dark part I can add some splash screen or something, but wondering if there is another way instead of opening a completely new activity? @OscarSpruit

**Comment by OscarSpruit** [comment]
@PeterHdd this screen is controlled by Google, so there is no way to change anything about it. The dark part is supposed to be translucent. It could be that your theming makes it dark or if you are using emulators it can also be a bug and in that case it doesn't happen on real devices.

Hopefully this answers all your questions, but feel free to re-open this issue if you have more.
