### ISSUE TITLE
warn: multiple substitutions specified in non-positional format

### ISSUE THREAD

**Issue by plastiv** [Adyen/adyen-android#167]
Just assembling project with adyen sdk included results in build tools warning during `gradlew :app:mergeDebugResources` task execution

> /Users/username/Projects/app-name/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-nb-rNO/values-nb-rNO.xml:12: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.

Pointing out to `<string name="expires_in">%s/%s</string>` (in every language) from:
https://github.com/Adyen/adyen-android/blob/7d3520d908737b24451d1eef382e1e202632ddbb/card-ui-core/src/main/res/values-da-rDK/strings.xml#L21

It is expected to explicitly mention which is first and which is second parameter, like `<string name="expires_in">%1$s/%2$s</string>`

**Comment by caiofaustino** [comment]
Thanks for pointing this out, we will update on the next release.

**Comment by caiofaustino** [comment]
This was fixed in the latest version `3.6.4`. If the problem still persists feel free to reopen the issue.
