### ISSUE TITLE
DropIn work only in debug version

### ISSUE THREAD

**Issue by Wlf46** [Adyen/adyen-android#168]
Step1 (successful):
Call @post("paymentMethods")

Step 2 (successful):
DropIn.getINSTANCE().startPayment(mActivity, mPaymentMethodsApiResponse, dropInConfiguration, resultIntent).

I could able to see list of payment method and selected Credit Card, fill the test card information
If I use the debug version:
Step 3 (successful)!
I receive paymentComponentData in DropInService and I  can post it to my server then return his response to a callresult.

If I use a signed APK:
Step 3 (NOT successful):
Clicked on "Pay" button and the progressbar is keep loading for indefinite time. 

What is the difference? Why only the debug version work correctly?

**Comment by caiofaustino** [comment]
The progressbar is shown while waiting for the server call to your server in the `DropInService`,  you can do some debug or logging on your service to see if the call is being made or if you see any error.

**Comment by caiofaustino** [comment]
I'm closing this since there was no follow up, I hope you were able to find the problem.
If it still persists feel free to open the issue again.
