### ISSUE TITLE
Get refusal reason to explain to the user

### ISSUE THREAD

**Issue by Gp2mv3** [Adyen/adyen-android#171]
Looking at the official doc (https://docs.adyen.com/checkout/android/drop-in#step-3-make-a-payment), we receive the result code which is Accepted or Refused.
But how can I get the refusal reason to display the right error to the user?

We receive the refusalReason and refusalReasonCode from /payment, so, why don't send it in the CallResult?
Do I miss something?

Thanks a lot !

**Comment by caiofaustino** [comment]
Hey there,
The `payments/` API is meant to be an interface with the merchant server, not with the user, so the data there is not necessarily something that you want to show, there might be sensitive data there etc.

In the case of the `CallResult` interface, `CallResult.ERROR` and `CallResult.ERROR_WITH_MESSAGE` are meant to be used when there was an issue in the connection and there was no concrete result. Those display a more generic error message, or one that you specify.

For payments that were Refused, that is not an error flow, is the result from the payment attempt, so you can finish the Drop-in flow with `CallResult.FINISHED` and display the result of that on your own screen, where you can decide to give some feedback or ask the user to try again for example.

**Comment by Gp2mv3** [comment]
> For payments that were Refused, that is not an error flow, is the result from the payment attempt, so you can finish the Drop-in flow with CallResult.FINISHED and display the result of that on your own screen, where you can decide to give some feedback or ask the user to try again for example.

But, the result of the response is available in the `makePaymentsCall` function. How can I have the result of the payment outside of the Service ?

**Comment by caiofaustino** [comment]
Whatever you pass as the content of the `CallResult.FINISHED` will be passed back to you as the result of the Drop-in. It will be in the `Intent` you provided in the beginning inside the `DropIn.RESULT_KEY` extra.

https://github.com/Adyen/adyen-android/blob/7d3520d908737b24451d1eef382e1e202632ddbb/drop-in/src/main/java/com/adyen/checkout/dropin/ui/DropInActivity.kt#L343

**Comment by caiofaustino** [comment]
I'll close the issue since there wasn't any more messages, let me know if you still have an issue.
