### ISSUE TITLE
Want to show saved credit card details.

### ISSUE THREAD

**Issue by skamble01** [Adyen/adyen-android#1710]
Hi, Adyen Development Team,
Can anyone help me with showing stored credit card details? I didn't understand how to get saved card details and show them on the bottom sheet before showing a card screen on the checkout page.

Thank you in advance for your help!
Sangram

**Comment by araratthehero** [comment]
Hi @skamble01, thanks for your question.

Could you please provide the following details:
- Are you using Drop-in or Component integration?
- Are you using sessions integration?
- Which version of the SDK are you using?
- Can you explain in detail what you want to achieve and which part was unclear?

**Comment by skamble01** [comment]
Hi @araratthehero 
I'm using Component integration and working with advanced flow integration.
Version of SDK : 5.5.0
I wanted to show a list of saved card details while doing card payment for a better experience for the user so they don't have to fill out those details again.
Please let me know if you require any other details from me.

Thanks 
Sangram

**Comment by araratthehero** [comment]
Hi @skamble01,

Please note that with the components integration, you need to display the list of stored payment methods in your app manually, as there is no ready-to-use bottom sheet. Only our Drop-in integration includes a built-in stored payment methods screen that appears before showing the payment methods list.

To implement this in the advanced flow, when making a call to the [/paymentMethods](https://docs.adyen.com/api-explorer/Checkout/latest/post/paymentMethods) endpoint, as mentioned in [the documentation](https://docs.adyen.com/api-explorer/Checkout/latest/post/paymentMethods#responses-200) you will receive two lists: `paymentMethods` and `storedPaymentMethods`, which contain non-stored and stored payment methods, respectively. You can use these lists to render the payment methods as needed.

For components, you can show both stored and non-stored payment methods, as detailed [here](https://docs.adyen.com/online-payments/build-your-integration/advanced-flow/?platform=Android&integration=Components&version=5.5.0):

```
val cardComponent = CardComponent.PROVIDER.get(
    ...
    // Passing the paymentMethod you got in the response of the /paymentMethods call
    paymentMethod = paymentMethod,
    ...
)
```

or

```
val cardComponent = CardComponent.PROVIDER.get(
    ...
    // Passing the storedPaymentMethod you got in the response of the /paymentMethods call
    storedPaymentMethod = storedPaymentMethod,
    ...
)
```

Could you try this approach and let us know if you have any additional questions?

**Comment by skamble01** [comment]
Thanks @araratthehero
This works for me.

**Comment by skamble01** [comment]
Hi @araratthehero 
Im facing one issue with the bottom sheet. When i add any card component and make a payment and want to make another one that time if i open any saved cards it shows me previously added details only. Card not getting cleared after first payment.

Thank you in advance for your help!
Sangram

**Comment by araratthehero** [comment]
Hi @skamble01,

Could you please open a new issue instead of commenting on closed ones?

When creating the new issue, include the following details:
- The integration you're using
- The SDK version
- The code section where you create and display the component
