### ISSUE TITLE
Require Adyen3DS2 configuration in advance flow integration for Card payment

### ISSUE THREAD

**Issue by skamble01** [Adyen/adyen-android#1719]
Can anyone please help me with Adyen3DS2 configuration in advance flow integration?
Please let me know if there is any additional configuration I need to follow because I can not seem to find BrowserInfo or user agent, which are indicated as being necessary for API calls and 3DS2 setup.

I appreciate your assistance in advance.
Sangram

**Comment by skamble01** [comment]
Any updates on this?
We need this as soon as possible.

**Comment by ozgur00** [comment]
Hi @skamble01! For integrating `Adyen3DS2Component`, you can check out our [documentation](https://docs.adyen.com/online-payments/3d-secure/native-3ds2/android-component/) for the current version and if you're using an earlier version you can check out related [documentation](https://docs.adyen.com/online-payments/3d-secure/native-3ds2/android-component/earlier-versions/). 

[Here](https://docs.adyen.com/online-payments/3d-secure/api-reference/#3d-secure-2-additional-data-objects) you can see that full `BrowserInfo` object is only required for `web` integration. It also contains related information for `android` integration as well.

**Comment by skamble01** [comment]
Thanks for replying @ozgur00 
Yes i already went through that document and as i understood, for **android** we are getting User agent and acceptHeader from browser information but for me i `didn't` get browserinfo field only.

**Comment by ozgur00** [comment]
As you can see in the [api documentation](https://docs.adyen.com/api-explorer/Checkout/latest/post/payments#request-browserInfo) you just need to pass `userAgent` and `acceptHeader` inside `browserInfo` object in order to be able to support if 3DS flow gets routed to a redirect flow.

**Comment by skamble01** [comment]
Thank you for your response @ozgur00 
As I found in our internal communication, we don't have to pass browser information for the Android/iOS application. We should proceed without browserinfo.

**Comment by ozgur00** [comment]
Good to hear you came to a conclusion. Do not hesitate to contact if you have further questions.
