### ISSUE TITLE
Class referenced in the layout file, com.adyen.checkout.ideal.IdealSpinnerView, was not found in the project or the libraries

### ISSUE THREAD

**Issue by skamble01** [Adyen/adyen-android#1724]
Hi Team.

We are facing issues with iDeal payment integration with advance flow. I am trying to add IdealSpinnerView to my layout file as per this [document](https://docs.adyen.com/payment-methods/ideal/android-component/), but I am getting an error saying that "Class referenced in the layout file, com.adyen.checkout.ideal.IdealSpinnerView, was not found in the project or the libraries" when I try to access the component.

Kindly take a quick look into this and inform me of the steps and code needed to incorporate the iDeal payment option into my application.

Library used: com.adyen.checkout:ideal:5.6.0
<img width="562" alt="iDeal" src="https://github.com/user-attachments/assets/4efba70e-961c-4b54-bb8a-f10b1fe72cd6">

Thanks in advance
Sangram

**Comment by OscarSpruit** [comment]
Hi @skamble01, this seems to be a mistake in the documentation. The class that should be used is `com.adyen.checkout.ui.core.AdyenComponentView`. Apologies for the inconvenience, we will correct the docs accordingly.

**Comment by skamble01** [comment]
Thank you for your response. @OscarSpruit 
Then, if you could give me a code snippet or instructions on how to accomplish it, that would be really helpful.

Please have a look at this document as well; it appears to be incomplete and can be found at https://docs.adyen.com/payment-methods/online-banking-poland/android-component/.

**Comment by OscarSpruit** [comment]
The bottom part of the page is inapplicable for version 5.x.x as per the block on top. As mention you should follow the [main integration guide](https://docs.adyen.com/online-payments/build-your-integration/sessions-flow/?platform=Android&integration=Components&version=5.6.0) and replace the import and the component name with the one of the payment method you are working with.

<img width="800" alt="image" src="https://github.com/user-attachments/assets/0712d26a-dc0d-4f93-b44f-0a6b7e16fd58">
