### ISSUE TITLE
Google Pay drop-in response

### ISSUE THREAD

**Issue by asdico** [Adyen/adyen-android#173]
Hi here, I need support because I don't understand how to get Google Pay token.
I'm following this guide:
https://docs.adyen.com/payment-methods/google-pay/android-drop-in
and according to https://docs.adyen.com/payment-methods/google-pay/android-drop-in#make-a-payment I send what I get in `paymentComponentData.paymentMethod` through my `DropInService.makePaymentsCall`
The problem is that what I get, is not a token, as documentation say, but I get a Json that seems like:

```
{
  "paymentMethod": {
    "type": "paywithgoogle",
    "googlePayToken": "{\"signature\":\"blablabla\"}",
    "googlePayCardNetwork": "MASTERCARD"
  },
  "storePaymentMethod": false,
  "shopperReference": "",
  "telephoneNumber": "",
  "shopperEmail": "",
  "dateOfBirth": ""
}
```

And obviously, when I try to call the API from my backend:

```
curl https://checkout-test.adyen.com/v51/payments \
--
  | -H "X-API-key: [Your API Key here]" \
  | -H "Content-Type: application/json" \
  | -d '{


```

I get an error:

`{
    status: 422
    errorCode: 5_202
    message: Invalid PayWithGoogle Token
    errorType: validation
    pspReference: null
}`

What am I doing wrong?

**Comment by asdico** [comment]
> Hi here, I need support because I don't understand how to get Google Pay token.
> I'm following this guide:
> https://docs.adyen.com/payment-methods/google-pay/android-drop-in
> and according to https://docs.adyen.com/payment-methods/google-pay/android-drop-in#make-a-payment I send what I get in `paymentComponentData.paymentMethod` through my `DropInService.makePaymentsCall`
> The problem is that what I get, is not a token, as documentation say, but I get a Json that seems like:
> 
> ```
> {
>   "paymentMethod": {
>     "type": "paywithgoogle",
>     "googlePayToken": "{\"signature\":\"AsdasdasadsAASDASDASDdasda\/HYrtyjryuJhKJHkjkN\/3sKH8pW6IGvuLwL\",\"protocolVersion\":\"ECv1\",\"signedMessage\":\"{\\\"encryptedMessage\\\":\\\"AsaciceAcuasdGajsdaCasd\/Bdr8BKP235MJVFhtp4LQz9GUQPgRia\/2cT3g+LBMJojt+mkbmaJZKL8WTXa4ql\/mqXnnG1wjgCGJxThpg1PeD0ndRC5UmEhKywCMND5nwyLHMkuHfjUFtS+EcP\/AsdasdasdASDsadadaSDasdasd\/XIsW0B4ycw5ltU+IdcJFsh9neVu65vLKW1GPHzv+AsdadasdASdasAdasdasASDasdas\/hDe14TPR2B1h+2GW1chBFfPnPRL25+Asdasda+IFs48C\\\",\\\"ephemeralPublicKey\\\":\\\"AascasAasdasd+X4ilyA5o\/3JZdpIy8fClEjAiwy6DzGZwxDR2qRuK25XjB8QlzQCfFOtmiD4+TfCwUOWnxmTUefX4pQ\\\\u003d\\\",\\\"tag\\\":\\\"BBnm71sN\/AsadsAbbrtreD\/5e5py1ldMjOv7fG554bde5g\\\\u003d\\\"}\"}",
>     "googlePayCardNetwork": "MASTERCARD"
>   },
>   "storePaymentMethod": false,
>   "shopperReference": "",
>   "telephoneNumber": "",
>   "shopperEmail": "",
>   "dateOfBirth": ""
> }
> ```
> 
> And obviously, when I try to call the API from my backend:
> 
> ```
> curl https://checkout-test.adyen.com/v51/payments \
> --
>   | -H "X-API-key: [Your API Key here]" \
>   | -H "Content-Type: application/json" \
>   | -d '{
> ```
> 
> I get an error:
> 
> `{ status: 422 errorCode: 5_202 message: Invalid PayWithGoogle Token errorType: validation pspReference: null }`
> 
> What am I doing wrong?

**Comment by wilochoa** [comment]
Hey, you could fixed? i am having the same issue, could you help me?

**Comment by asdico** [comment]
Yes! The merchant ID was wrong. Make sure you are using your Adyen one!

**Comment by wilochoa** [comment]
I am using the same that works good with the normal cards. there is something additional that i have to do?

**Comment by wilochoa** [comment]
I am getting is a 400. not a 422.. :(

**Comment by andre-sonect** [comment]
Also happens to me. Have same issue while expecting a string token but getting json object and end up with a failure response
