### ISSUE TITLE
No response from 3ds2 test numbers using 2.4.9 version with server version v41

### ISSUE THREAD

**Issue by dreamertheat** [Adyen/adyen-android#175]
I'm using classic integration of adyen (create your own UI) in android and been able to do the following:

1. Get payment session from server
2. Create PaymentHandler and call the observables needed: 

- PaymentSessionObservable
- RedirectHandler
- NetworkingStateObservable
- ErrorHandler
- PaymentResultObservable
3. Also, Im able to create CardDetails with encrypted data and finally call initiate payment inside PaymentSessionObservable.

I've tested cards from https://docs.adyen.com/development-resources/test-cards/test-card-numbers
and they are working well! Except for 3ds2 cards which quoted:

_

> Test 3D Secure 2 authentication
> 
> To test how your integration handles different 3D Secure 2 authentication scenarios, use our test card numbers.
> When prompted for 3D Secure 2 text challenges, use the following credentials:
> 
>     For mobile, use password: 1234
>     For web, use password: password

These cards dont give any response. I even checked PaymentResultObservable for challenge response or any response at all but i dont receive anything nor errors.

What am I missing? 

Note: Ive already browsed similar issues posted and you recommended to import 
_com.adyen.checkout:threeds:_ in gradle. Do I need to call something from this library?

Thanks and more power!

**Comment by caiofaustino** [comment]
Hey there,

For 3DS2 there is an `AuthenticationHandler` that will be triggered in case o 3DS2 authentication request. You can do it using ` paymentHandler.setAuthenticationHandler`.

You can check an example use here:
https://github.com/Adyen/adyen-android/blob/da3e8c98190b09e96061dd43f605b062c5bad897/checkout-ui/src/main/java/com/adyen/checkout/ui/internal/card/CardDetailsActivity.java#L336

Also make sure you add the `com.adyen.checkout:checkout-threeds` module to your app. You can also update to version `2.4.11`.

Cheers.

**Comment by dreamertheat** [comment]
This is what I'm looking for! Many thanks mate! :)
