### ISSUE TITLE
PayPal via Adyen

### ISSUE THREAD

**Issue by weshiptunisie** [Adyen/adyen-android#177]
Hi team, 

Im implementingDropIn android SDK to pay with PayPal, it open the webview correctly, I enter email and password and I pay but after I pay it says {"status":"Not found"}.

And Idea how to close the webview automatically and get the answer from the activity?

Thanks in advance.

**Comment by caiofaustino** [comment]
Hey there,

Where are you seeing the `{"status":"Not found"}` result? Looks like an issue related to the payment flow, not with the Android library. I suggest you reach out to Adyen support (support@adyen.com) and there they can take a closer look into the backend to see what's happening.

The webview is just opening the PayPal website, so it's not under our control to close it.

But let us know if you have any other questions or issue.
Cheers,

**Comment by weshiptunisie** [comment]
Hello,

Thank you for your answer.

Cheers,
