### ISSUE TITLE
 java.lang.NullPointerException: Attempt to invoke virtual method ‘void android.view.View.getBoundsOnScreen(android.graphics.Rect)’ on a null object reference

### ISSUE THREAD

**Issue by Trikke** [Adyen/adyen-android#178]
I'm getting this crash on Android 8 every time i switch focus between the inputfields of **com.adyen.checkout.card.CardView**. I type in something in the card number field. Close the keyboard and focus on another field.

This crash seems to be a now occurrence and an example and solution can be found here.

https://stackoverflow.com/questions/45840856/android-8-0-oreo-crash-on-focusing-textinputedittext?rq=1

CardView layout should be fixed with setting **android:importantForAutofill="noExcludeDescendants"** or setting the **hints fields in the parent TextInputLayout where applicable.**

Currently, a lot of our users cannot make payments because of this crash.

**Comment by caiofaustino** [comment]
Hey @Trikke,
Thanks for the detailed input, but I'm not able to reproduce the problem here. Do you have any more information about the issue? Which support library version are you using?

Regards,

**Comment by Trikke** [comment]
- Tried on an Android 8 device.
- Make sure autocomplete is enabled : Settings -> System -> Languages & input -> Advanced -> Auto-fill service.
- Tested with "com.adyen.checkout:card-ui:3.6.4".

Procedure:
- fill in some dummy data in the cardview like 5151
- dismiss the keyboard
- focus again on a cardview input field

Thanks for checking!

**Comment by caiofaustino** [comment]
Yeah I still can't reproduce it. Tried several times, including using the auto-fill to input the data, hiding the keyboard, still looks fine to me.

Maybe this is caused by some dependency or theme related conflict.

**Comment by Trikke** [comment]
It's on a huawei p smart device. It's using the Google auto-fill service if that matters. We've isolated it to your cardview. Might be that Huawei is doing something funky in their themeing.

**Comment by caiofaustino** [comment]
Can you try to run the default example app we have on the repository on that phone to see if that's really the cause? 

Should be easy to setup, just copy [this file](https://github.com/Adyen/adyen-android/blob/master/example-app/local.gradle.example) with your Adyen **TEST** credentials.

Also a full stack-trace of that would be appreciated :)

**Comment by caiofaustino** [comment]
hey @Trikke, did you manage to fix the issue?

**Comment by caiofaustino** [comment]
Feel free to reopen if it still happens.
