### ISSUE TITLE
App crashes targeting android material 1.1.0 

### ISSUE THREAD

**Issue by RicardAparicio** [Adyen/adyen-android#179]
Hello, the issue #174 is closed but the problem is still there, sorry for no answer we where really busy.

The problem is the same I explained in #174. look at this style:

> AdyenCheckout.TextInputLayout

https://github.com/Adyen/adyen-android/blob/master/base-ui/src/main/res/values/styles.xml#L35

Its parent is a subtype of MaterialComponents which makes the app crash if targets `com.google.android.material:material:1.1.0` and you are not inheriting one of the MaterialComponents in your AppTheme.
This version forces inherit one of the MaterialComponents themes in your AppTheme if one of your styles does. We don't want to yet.

**Comment by caiofaustino** [comment]
Please refer to issue #142, just override the `AdyenCheckout.TextInputLayout` style on your application. You will lose the default rounded borders, but you can style them however you like.

**Comment by RicardAparicio** [comment]
I will do the hack, but anyway would be nice if next versions can fix it or at list have it present in your documentation :). Should not be our concern override a style because a crash, inherit or not from MaterialComponent should be still optional.

**Comment by caiofaustino** [comment]
Yeah I took note of this to investigate, this wasn't being tracked by us as an issue that was still happening.

Worst case scenario indeed we will add this exception to the Documentation. Sorry for the inconvenience.
