### ISSUE TITLE
Support of Bancontact (BCMC)

### ISSUE THREAD

**Issue by PhilippeBoisney** [Adyen/adyen-android#181]
When trying to use the Drop-In SDK with a [Bancontact (BCMC) card](https://docs.adyen.com/development-resources/test-cards/test-card-numbers#bancontact-bcmc), **we cannot finish the workflow** (by clicking on the PAY button) because the **CVC input is required**:

![image](https://user-images.githubusercontent.com/6847959/80498929-9c4d3400-896c-11ea-835d-59f73a0e3ae4.png)

However, this type of debit card **doesn't have** a CVC...

Is there any way to support the Bancontact (BCMC) card with the Drop-In SDK?

**Comment by caiofaustino** [comment]
hey @PhilippeBoisney,
BCMC has a separate entry in the Drop-in payment methods list, you should use that one, make sure it's configured on your account.

**Comment by PhilippeBoisney** [comment]
hey @caiofaustino :) Aaaah okay, I thought it was considered as a simple "credit card", and not another payment method. I didn't find much information in the documentation about this subject...

Thanks !
