### ISSUE TITLE
Adyen Component Android

### ISSUE THREAD

**Issue by wellmonge** [Adyen/adyen-android#182]
**Payment/Detail**
I'm trying to create fingerPrint using _3dsComponent_ from android **sdk**... on a `mainthread` using  mainHandler:

`        this.mainHandler = new Handler(this.reactContext.getMainLooper());
`

The implementation of fingerprint process are below, seems okay, but the _LifecycleOwner_ aren't notifying.  I never get to the result of my observer.

```
Threeds2FingerprintAction fingerPrintAction = new Threeds2FingerprintAction();
fingerPrintAction.setToken(token);
fingerPrintAction.setPaymentData(paymentData);

Adyen3DS2Component card = Adyen3DS2Component.PROVIDER.get((FragmentActivity)this.getCurrentActivity());

card.handleAction((Activity) this.getCurrentActivity(), challengeAction);

mainHandler.post(() -> card.observe((LifecycleOwner) this.getCurrentActivity(), (Observer) o -> {
    ActionComponentData res = (ActionComponentData) o;
    promiseAction.resolve(res);
    Log.d("teste", res.toString());
}));

```

**Comment by caiofaustino** [comment]
why are you using the mainHandler there? I don't think that's necessary

also try to call `observe` before calling `handleAction` just to make sure and let me know if you see any different results

**Comment by wellmonge** [comment]
> why are you using the mainHandler there? I don't think that's necessary
> 
> also try to call `observe` before calling `handleAction` just to make sure and let me know if you see any different results

it's necessary, cuz when using observer without them throws error related to background thread. That's why I'm using them... about the order of calling the documentation says to call in that order.

Why call observe before? **handleAction** dispatch and notify the observer? it's asynchronous?

**Comment by wellmonge** [comment]
> why are you using the mainHandler there? I don't think that's necessary
> 
> also try to call `observe` before calling `handleAction` just to make sure and let me know if you see any different results

Well I tried but it didn't work!

**Comment by caiofaustino** [comment]
hey @wellmonge, can you share what the problem was? :)

**Comment by wellmonge** [comment]
@caiofaustino the problem wasn't solved! it was wrongly closed.

**Comment by wellmonge** [comment]
@caiofaustino this WeChat Issue, do you believe that applies to my case?

**Comment by caiofaustino** [comment]
Hey, I'm sorry I missed seeing you had reopened the issue.
No, I don't think the WeChar issue is the same as yours. 

Looking at your code again I think I found the problem. You define `fingerPrintAction` but then you pass `challengeAction`. The 3DS2 SDK can only handle these 2 in the correct sequence, first `fingerPrintAction` and then `challengeAction` if required, because they are tied to the same transaction, so it's no possible to handle a `challengeAction` without first having done the fingerprint.

You can check the `component.observeErrors()` observer to see if the component is returning you an error message. You should also handle other failures there.

Let me know if I'm still missing something. Good luck.

**Comment by wellmonge** [comment]
Hi there! I mistakenly write the in example... the real code are bellow:
![image](https://user-images.githubusercontent.com/5003655/83024298-8fbc0a00-a004-11ea-928c-966f3c584c7c.png)

**Comment by wellmonge** [comment]
@caiofaustino could you please review this code?

**Comment by caiofaustino** [comment]
Oi, foi mal quando voce edita o comentario eu nao recebo notificacao.

Hmmm, eu nao entendo muito de React mas tenta criar o `Adyen3DS2Component` no construtor da classe e salvar numa variavel ao inves de criar dentro de cada metodo. 

Eu acho que quando vc chama `createFingerprint3ds` e depois chama `presentChallenge` ele pode tar criando duas instancias diferentes do Component, e como eu falei antes ele precisa ter feito o fingerprint antes de fazer o challenge, pq faz parte da mesma transaçao.

No `presentChallenge` se vc adicionar esse observer dentro do `mainHandler.post()` ele deve te dar um erro falando que perdeu a referencia:
```kotlin
card.observeErrors(this.getCurrentActivity()) {
    Log.e("TEST", it.errorMessage)
}
```

**Comment by wellmonge** [comment]
thanks @caiofaustino we already find the problem... when creating action we need to specify the type. I found this quite redundant cuz the action it self is a fingerprint type, but it works explicit declare the type:

 ```
Threeds2FingerprintAction fingerPrintAction = new Threeds2FingerprintAction();

fingerPrintAction.setType(Threeds2FingerprintAction.ACTION_TYPE);
 ```
I appreciate the support! 

My best regards.
