### ISSUE TITLE
Adyen redirect to app from Klarna payment

### ISSUE THREAD

**Issue by ilyasdirin** [Adyen/adyen-android#183]
Hi, I set up DropIn SDK 3.6.4 and from time to time getting redirect problem with Klarna. There is no problem in client side with redirectUrl since redirectUrl parameter is sent normally by getting "RedirectComponent.getReturnUrl(applicationContext)" as adyencheckout://packagename without any modification to your side. Generally it redirects but sometimes it just stands in success page of Klarna payment.

**Comment by caiofaustino** [comment]
Hey there, can you please contact Adyen Support? That way you can share a PSP reference and we can look at backend logs to try to see what's happening.

**Comment by ilyasdirin** [comment]
Ok then already contacted with Adyen support and waiting response. Thanks.
