### ISSUE TITLE
WeChatPayComponent not returns "isValid as true immediately"

### ISSUE THREAD

**Issue by kami4ka** [Adyen/adyen-android#185]
Hi.
I'm trying to implement Wechat Pay with Android component by a guide from site.

My code is the following:

```
val component = WeChatPayComponent.PROVIDER.get(
            this@AdyenWechatPaymentFragment,
            dataModel.paymentMethod,
            WeChatPayConfiguration.Builder(unsafeContext).build()
        )

        component.observe(
            this@AdyenWechatPaymentFragment,
            Observer {
                presenter.onWechatPayComponentStateChanged(it)
            }
        )
```

The problem is that `presenter.onWechatPayComponentStateChanged` is not triggered.

Maybe it somehow related with #182

**Comment by caiofaustino** [comment]
Hey there,

Without knowing more about the code it's hard to see the issue clearly, but out the top of my head I can see a few things.

1- Maybe WeChat app is not installed, and you are not checking for availablity, there is an example in the Docs specific to Android [here](https://docs.adyen.com/payment-methods/wechat-pay/wechat-pay-in-app-payments/android-component)

2- Maybe there is some issue related with the presenter, can you add a Log on the observer itself to see if that is triggered?

3- Make sure you are using the correct Payment Method object from the response with type `wechatpaySDK`

**Comment by kami4ka** [comment]
Hello.

Thanks for the answer.
So a bit of details:
1) WeChat app is installed and I'm checking the availability on another screen, as I'm doing it with Google Pay via Adyen.
2) The same behavior reproduces with logging function instead of presenter call as well. As well, I'm debugging this line, and debugger is not stoped there.
`WeChatPayComponent.PROVIDER.get` returns component as expected.
3) Type is `wechatpaySDK` as expected.

The only thing was changed in my implementation is described here:
https://github.com/Adyen/adyen-android/issues/170

But, as I understand, it should not affect this part of the flow.

I'm only aware of the part with an immediate return for the observer.
I will appreciate any clues for further debugging.

**Comment by caiofaustino** [comment]
Hmm, indeed this looks weird. I'll investigate this further since it could be a bug, but in the mean time you can add this line after the observe to trigger the callback that should have been sent.

`component.inputDataChanged(EmptyInputData())`

**Comment by kami4ka** [comment]
Thanks. It works like a charm. But I've faced another one problem:
I'm receiving the following action: 

```
"action":{
      "paymentData":"***",
      "paymentMethodType":"wechatpaySDK",
      "sdkData":{
         "appid":"***",
         "noncestr":"***",
         "packageValue":"***",
         "partnerid":"***",
         "prepayid":"***",
         "sign":"***",
         "timestamp":"1589884598"
      },
      "type":"sdk"
   }
```

But looks like there are no such Action with that type.
As well, tutorial sais about another type:

```

"action": {
--
  | "paymentData": "Ab02b4c0!BQABAgAgx==...",
  | "paymentMethodType": "wechatpaySDK",
  | "type": "wechatpaySDK",
  | "sdkData": {
  | "appid": "wx3aed7fe146f6a57a",
  | "noncestr": "cPY0e83ny4hWyf5O",
  | "packageValue": "Sign=WXPay",
  | "partnerid": "205287714",
  | "prepayid": "wx015678064827111da2e4f0b11005864100",
  | "sign": "169FD3F1E193446D90C45573EBDD4020",
  | "timestamp": "1573033086"
  | }
  | },

```

**Comment by caiofaustino** [comment]
No worries, this action type issue is related to the SDK as well.

Seems like there was a change in the backend system with the action types that we didn't update in the SDK, so this change will require a new release to fix. I'll try to fix both issues and make a release next week.

**Comment by kami4ka** [comment]
Great, thanks for the estimated timelines and help!

**Comment by caiofaustino** [comment]
Hey man, just wanted to let you know the release might take a bit longer, in order to properly test the WeChat flow I need a device that was in the office, so I don't have it available right now.

I'll keep you posted.

**Comment by kami4ka** [comment]
Thanks for the info. The feature is really important for us to implement all the available payment methods in the app with using Adyen and get rid of all other libraries :-)

**Comment by kami4ka** [comment]
Hi, @caiofaustino. Any updates regarding the upcoming release?

**Comment by caiofaustino** [comment]
Hey @kami4ka, the change is already tested and merged, we are in the release process so it shouldn't take long. Sorry for the delay.

**Comment by kami4ka** [comment]
Awesome, thanks for such good news.

**Comment by caiofaustino** [comment]
Hey man, `3.6.6` was just released. Can you please test and let me know how it goes? Sorry for taking so long, we had a few delays.

**Comment by kami4ka** [comment]
Looks like the updated SDK is working for SDK action. Thanks for the update.
