### ISSUE TITLE
threedsComponent UnsupportedOperationException

### ISSUE THREAD

**Issue by gregastley-missionlabs** [Adyen/adyen-android#187]
HI, when trying to handle the ChallengeShopper action for 3DS2 flow as documented here
https://docs.adyen.com/checkout/3d-secure/native-3ds2/android-component#3ds2-native-authentication-flow
I encounter an UnsupportedOperationException when trying to pass the action object to the method threedsComponent.handleAction(activity, action)

**To Reproduce**
1) Encrypt the customer card details using the card component, send this data to the /payments endpoint.
2) On return, given that the resultCode is "IdentifyShopper" pass the action object to threedsComponent.handleAction
3) When the threedsComponent observer fires then call /payments/details with the data contained in actionComponentData
4) On return, given that the resultCode is "ChallengeShopper" pass the action object to threedsComponent.handleAction
5) Observe an UnsupportedOperationException is thrown 

**Expected behavior**
I expect that in step 5 above, a new screen would be loaded requesting a 4 digit code, which upon entering would close this screen and trigger another observer event as per step 3

**Smartphone **
Android Emulator (Pixel 3 API 29)

**Additional context**
The app for which this occurs is written in react native (ejected out of expo), and we are using facebook's react-native bridge to interact with native. There is a substantial number of direct dependencies (which then have their own dependencies of course). Furthermore, though I am avoiding the screens which are troublesome, visiting certains screens brings about the following crash:
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes (screenshot attached). This happens when (and only when) I put the following line into my app build.gradle:
implementation "com.adyen.checkout:3ds2:3.6.5"
(and I have tried lower versions with the same result). I notice that okhttp is lurking in both of these stack traces, but it seems to be used all over the place (not just for adyen)

My guess, given that stack trace attached is that the jar file I import for 3DS is signed, and that some of the dependencies (or transitive dependencies) this app imports also have signed jars, and that the resultant apk manifest has got a confused bag of certs which are causing mischief when this component tries to do whatever it has to do. 
Furthermore, I am able to get this flow working with a toy app (that has only minimal dependencies)

If I'm barking up the right tree here, are there any known workarounds or can you give me some strategies to nail down the dependency (and version) (which might be transitive) that is causing all the pain here? (Note: trying to binary search the problem by commenting out dependencies doesn't help because then I can't even start the app to trigger the issue again). 

![Screenshot 2020-05-17 at 20 44 52](https://user-images.githubusercontent.com/56299896/82500005-8f92aa80-9aea-11ea-8032-b4712fe89d40.png)

**Comment by gregastley-missionlabs** [comment]
![Screenshot 2020-05-20 at 22 39 42](https://user-images.githubusercontent.com/56299896/82500200-da142700-9aea-11ea-843a-1de7ae590c0d.png)

**Comment by gregastley-missionlabs** [comment]
![Screenshot 2020-05-20 at 23 36 48](https://user-images.githubusercontent.com/56299896/82504264-d71d3480-9af2-11ea-9265-60188372f738.png)

**Comment by caiofaustino** [comment]
Hey there,

For Android you can run a gradle task to show your dependencies hierarchy and coflicts, something like this:
`./gradlew :app:dependencies`. [This answer](https://stackoverflow.com/a/48030929/1294008) seems to relate to react-native too.

I have an idea of what it could be but I'll investigate a bit more and come back to you soon.

**Comment by gregastley-missionlabs** [comment]
Hi,
Sorry for the late response on this one; I have been working on something else, and handed over this to another developer who is now also finding himself battling the same issue as I reported here (though it is apparently working on iOS).

Has any progress been made on this one?

**Comment by caiofaustino** [comment]
Hi there, not very much, I think the conflict issue is related to our cryptographic library bouncy castle, `bcprov-jdk15on-1.60.jar` but I don't understand how the build system is behaving to strip the jar signature.

**Comment by gregastley-missionlabs** [comment]
Thanks caiofaustino ... for what its worth I think the security exception comes about from what we had in our packagingOptions in the app/build.gradle. It was set to pickFirst ** (the behaviour of which I expect is kind of random). Relying on the default behaviour of this gradle attribute:
https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html
 gets us past the SecurityException but doesn't solve the problem we're having with 3DS payment though (that it crashes on ChallengeShopper).

We have built a toy app pulling in all the dependencies from the real app, and this issue doesn't occur. Running out of ideas to debug this further

**Comment by gregastley-missionlabs** [comment]
Hi,
Just to update, it turns out that all this mischief was caused by the version of expo we were using (one major version short of the latest). We've now upgraded and locked it to this version (alongside the adyen libraries).

**Comment by caiofaustino** [comment]
Glad to hear! Can you share with me what is expo and which version you were using when the issue happene?

**Comment by gregastley-missionlabs** [comment]
Hi, expo is a platform to allow native development via react-native. Official documentation is here:
https://docs.expo.io/

The version which we were using previously is v36, upgrading to v37 solved the problem.
