### ISSUE TITLE
Support POST redirection for 3DS2

### ISSUE THREAD

**Issue by PhilippeBoisney** [Adyen/adyen-android#189]
**Describe the bug**
When a user tries to use the 3DS2 for a payment, our backend returns this response (deliberately incomplete for better understanding) during the "[make a payment](https://docs.adyen.com/checkout/3d-secure/redirect-3ds2-3ds1/android-drop-in#make-a-payment)" phase:
```
// .... other fields...

"redirect": {
   "data": {
      "PaReq": "ENCRYPTED",
      "TermUrl": "https://TEST",
      "MD": "ENCRYPTED"
  },
  "method": "POST",
  "url": "https://checkoutshopper-test.adyen.com/checkoutshopper/threeDS2.shtml"
}

// .... other fields...
```
As you can see, the `method` field is `POST`. 

Then, the redirection to the web view happens normally **but failed**: it seems that the `RedirectComponent` handles only normal `GET` redirection.

Extract from `RedirectUtil`:
```
if (RedirectUtil.determineResolveResult(context, uri).getType() == APPLICATION) {
   return new Intent(Intent.ACTION_VIEW, uri);
}
```

Is there any reason to not support the `POST` method for the redirection? Did I miss something?🙂

**To Reproduce**
- During the "[make a payment](https://docs.adyen.com/checkout/3d-secure/redirect-3ds2-3ds1/android-drop-in#make-a-payment)" phase, set the backend response in order to return the above response (for the `redirect` field).

**Expected behavior**
When the redirect method is a `POST`, the DropIn should handle it properly.

**Comment by PhilippeBoisney** [comment]
Note that this behavior is the same on the iOS SDK DropIn.

**Comment by caiofaustino** [comment]
hey there,
No that's a normal behavior from our `/payments` API, on mobile we expect a GET redirect and we try to guess based on the `returnUrl` you send, mobile flow usually has a custom scheme URL.

But you don't have to rely on that, you can use [this parameter](https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v52/post/payments__reqParam_redirectToIssuerMethod) `redirectToIssuerMethod` to force it to be a GET.

**Comment by PhilippeBoisney** [comment]
Okay, thanks for this feedback :)
Do you know if it's possible to not redirect the user to an external webview but instead, a custom intent (in order to launch the URL from an internal webview) ?

**Comment by caiofaustino** [comment]
We use CustomTabs to achieve a similar behavior while still giving the security of a full browser. But since you are talking about 3DS2 and not 3DS1, that flow should be handled by our 3DS2 SDK that runs inside your app and is not a redirect.

**Comment by ozgur00** [comment]
Closing the issue since it's been concluded.
