### ISSUE TITLE
Documentation: payment methods naming differs on Android and iOS.

### ISSUE THREAD

**Issue by n-belokopytov** [Adyen/adyen-android#19]
Payment methods naming differs on Android and iOS. On Android it's recurring and others, while in iOS it's preferred and default ones.

Please clarify.

**Comment by timon-langlotz** [comment]
Hi @n-belokopytov,

Generally there are two types of payment methods:
- Preferred payment methods (also sometimes referred to as recurring or one-click payment methods) are payment methods that have been used by the current shopper before and require less or no input by the shopper.
- Available payment methods are those payments methods where all input (if there is any) needs to be entered by the shopper.

Let us know if this clears things up!

Cheers,
Timon

**Comment by n-belokopytov** [comment]
@timon-langlotz we are now reading the documentation for the integration on respective platforms which is where we have encountered the discrepancy. We have not started using the SDKs yet.

**Comment by timon-langlotz** [comment]
We'll take a look at the documentation to make it more consistent, thanks for pointing it out!

**Comment by n-belokopytov** [comment]
@timon-langlotz fyi https://docs.adyen.com/developers/checkout/ios/custom-integration-ios and https://github.com/Adyen/adyen-android#custom-integration
