### ISSUE TITLE
3DS1 is not redirecting to the app after successful 3DS1 challenge

### ISSUE THREAD

**Issue by abdulmannanbutt** [Adyen/adyen-android#190]
**Describe the bug**
Please see and help to resolve the issue. 

I am getting issue while 3DS testing. 3DS2 test cards are working fine and activity is giving results after 3DS challenge. But after 3DS1 there are 2 issues:
1: Test Environmnet -> app is  opening internal webview in TEST environment but after I enter the user and password details, Page don't redirects back to the app.
2: Live Environment -> SDK is opening the External webview and after payment not redirecting to the APP (payment has been made but SDK is not informing to the APP therefore we are getting payment issues.

**Screenshots**
Please see the attached video and screenshots
![Screenshot_2020-06-19-15-19-08-08](https://user-images.githubusercontent.com/960569/85131695-c0ccda80-b250-11ea-8ad1-d81854ad1d52.png)
![Screenshot_2020-06-19-16-44-15-76](https://user-images.githubusercontent.com/960569/85131699-c1fe0780-b250-11ea-8d48-b29416ec808c.png)
![Screenshot_2020-06-19-17-00-07-53](https://user-images.githubusercontent.com/960569/85131702-c3c7cb00-b250-11ea-9ba9-b6013b13e40a.png)

https://drive.google.com/drive/folders/110NDifBUkRUWxTKqThVnekM9Z8_Jtee3?usp=sharing

Adyen Checkout SDK 2.4.11
Tried Following 3DS1 cards
American Express | 3451 7792 5488 348 | International | 10 | 2020 | 7373
Mastercard | 5212 3456 7890 1234 | JP | 10 | 2020 | 737
Visa | 4212 3456 7890 1237 | CA | 10 | 2020 | 737

**Comment by caiofaustino** [comment]
Hi there,
Can you please check if you are correctly sending the `returnUrl` on the [/paymentSession](https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v52/post/paymentSession__reqParam_returnUrl) call to Adyen?

You can get the correct URL on the `CheckoutSetupParametersHandler` with `checkoutSetupParameters.getReturnUrl()`, or check that the format should be `checkout://your.package.name`.

**Comment by abdulmannanbutt** [comment]
OK. Let us check. But please help to see why there is a SDK has different behavior in Live and Test environment? In Live SDK was opening **link in chrome/external browser** but in Text, It was opening in **webview** (withing the app).

**Comment by abdulmannanbutt** [comment]
@caiofaustino after adding return URL, Test SDK is able to get back to the app and we expect that in live environment, it will behave the same. 
Please see, why our users were going to an external browser? If it can happen, can you provide us such a card so that we can test in test environment?

![Screenshot_20200619-165310_Dolphin](https://user-images.githubusercontent.com/960569/85662505-6957c000-b6d1-11ea-8bae-ba566e08f8a3.jpg)
![Screenshot_20200619-165254_Dolphin](https://user-images.githubusercontent.com/960569/85662508-6a88ed00-b6d1-11ea-8111-998c14543405.jpg)
![Screenshot_20200619-165213_Dolphin](https://user-images.githubusercontent.com/960569/85662511-6b218380-b6d1-11ea-8b36-c582ae87a9ea.jpg)

**Comment by caiofaustino** [comment]
So the browser behaviour depends a little on the device used by the user. We never use WebView, instead we redirect using [Chrome CustomTabs](https://developer.chrome.com/multidevice/android/customtabs). But the user can be redirected again by the bank website to the bank app for example, or perhaps to their device default browser if Chrome is not available if I'm not mistaken, although I've never seen that happen before. But in any way, if the `returnUrl` is correct, he will automatically be redirected back to your app and won't need to do that manually.

Let me know if you see any behaviour different than this.

**Comment by caiofaustino** [comment]
hey, since there was no reply I'll close the issue, but feel free to open it again if you still have any problems
