### ISSUE TITLE
Using asynchronous network calls in DropIn component

### ISSUE THREAD

**Issue by ButcheredGenre** [Adyen/adyen-android#191]
The DropIn component currently requires a synchronous network call to be used for e.g. _makePaymentsCall_, making it impossible to use a deferred call. The call I'd like to make here was already written to be used in an asynchronous fashion and can't easily be rewritten.

Is there a way/ workaround to use deferred network calls in the DropIn component?

**Comment by caiofaustino** [comment]
Hi there,
Sorry for the delay, yes there is the option to make the call asynchronous, you can return a `CallResult` with `ResultType.WAIT` and then you can call `asyncCallback(callResult)` when the deferred result is called.

We try to explain this behavior on the method documentation [here](https://github.com/Adyen/adyen-android/blob/27c83da4160fde060aa4ad607785d8610108ed0d/drop-in/src/main/java/com/adyen/checkout/dropin/service/DropInService.kt#L176) but sorry for not being very clear.
