### ISSUE TITLE
Generic placeholder in Android 

### ISSUE THREAD

**Issue by douglasramaldespd** [Adyen/adyen-android#192]
Hello friends, I would like to know if there is a way to replace or add a generic placeholder in the fields CardNumberEditText and  ExpiryDateInput for android?

**Comment by caiofaustino** [comment]
Hey there, yes there is! You can override the style for the EditText changing the `hint` property or override the string we are using. Code for that part is [here](https://github.com/Adyen/adyen-android/blob/27c83da4160fde060aa4ad607785d8610108ed0d/card-ui-core/src/main/res/values/styles.xml#L34).

**Comment by caiofaustino** [comment]
Closing this issue since there is no more reply, hope you managed to do it, feel free to reopen if you still have problems.
