### ISSUE TITLE
No callback from RedirectComponent when the payment is cancelled

### ISSUE THREAD

**Issue by jaejoong-yoo-gtg** [Adyen/adyen-android#1921]
## Description
When I close Google Pay without continuing to pay, it calls the `onError()` callback. So I was able to handle the situation where a user cancels the payment.
And, I expected the same behaviour from RedirectComponent. I tried RedirectComponent with PayPal. PayPal link was opened in the chrome custom tabs. But when I close the custom tabs, there was no callback to the app.
I need a way that I can handle the situation where a user cancels the PayPal payment.

## Steps to Reproduce
1. I am able to consistently reproduce this issue: Yes
2. Steps to reproduce the issue:
    1. Send a payment request with the payment method `paypal`
    2. Pass `action` from the payment response to `handleAction()` of RedirectComponent
    3. Once PayPal website is opened in the chrome custom tabs, close the tabs

## Logs and Crash Reports

<details>
  <summary>Relevant logs</summary>

  ```
Insert your logs (and crash report) here.
  ```
</details>

## Code Snippets
Provide code snippets where the SDK is implemented in your project.

```
    val component = RedirectComponent.PROVIDER.get(
        activity = activity as ComponentActivity,
        checkoutConfiguration = checkoutConfiguration,
        callback = object : ActionComponentCallback {
            override fun onAdditionalDetails(actionComponentData: ActionComponentData) {
                // handle additional details
            }

            override fun onError(componentError: ComponentError) {
                // handle error. i expect this to be called when the component is closed
            }
        },
        key = checkoutSession
    )

------

    fun handleAction(action: Action, activity: Activity) {
        component.handleAction(action, activity)
    }

```

## Integration Information
1. Server-side integration: Advanced flow
2. Client-side integration: /Components
3. SDK version: 5.7.1
5. Android version(s) where issue occurs: Android 15
6. Device model(s) where issue occurs: Pixel 8a

## Additional Context
Provide any other information that might be helpful in diagnosing the issue. This could include environment details, specific configurations, or related issues.

**Comment by OscarSpruit** [comment]
Hi @jaejoong-yoo-gtg, thank you for raising this issue! We are aware and investigated it before. Unfortunately, Chrome custom tabs do not give any sort of notification when they are closed and there is no reliable way to detect it either. That is the reason why we choose to show the loading state below when the redirect is executed. In this view the user has to explicitly cancel the flow and then you will receive an error in `onError`.

Please let us know if that works for you or if you have any other questions.

![Screenshot_20241204_102454](https://github.com/user-attachments/assets/559b9209-0e5a-4a19-a10f-bd71d111269d)

**Comment by jaejoong-yoo-gtg** [comment]
Hi @OscarSpruit , thank you for the reply.
I also encountered the same difficulty dealing with the chrome custom tabs when I worked on the onboarding link, so it's understandable.

I couldn't see the loading state view on the bottom with RedirectComponent, but it was because I didn't add `AdyenComponent()` for PayPal. I thought it's only for the card payment. Anyway, I can see the loading state after adding the composable, and it seems to be enough.

**Comment by jaejoong-yoo-gtg** [comment]
I have another question about `RedirectComponent`. I see it implements the ActionComponent, IntentHandlingComponent and RedirectableActionComponent interfaces. Is there a specific reason for implementing these interfaces separately instead of using the `ActionHandlingComponent` interface?
The ActionHandlingComponent interface includes all the functions of those three interfaces, and both CardComponent and GooglePayComponent implement it.

I am asking because I need to keep a component for passing an action or intent to it outside of a Composable. I store it as an `ActionHandlingComponent` object in common logic. However, since `RedirectComponent` implements a different interface, I have to implement `ActionHandlingComponent` locally to call functions in `RedirectComponent`.

**Comment by OscarSpruit** [comment]
@jaejoong-yoo-gtg the reason is that internally we have a separation between payment method and action components. Card and Google Pay are payment methods and redirect is an action. Payment method components implement `ActionHandlingComponent` and action components don't.

To help you better we need to understand how you are using the `RedirectComponent`. Are you using `RedirectComponent` for payment methods like PayPal, Klarna, etc? Or are you using `RedirectComponent` to handle the action object that is returned in the `/payments` response on a separate screen from where you display for example `CardComponent`?

**Comment by jaejoong-yoo-gtg** [comment]
I'm using the `RedirectComponent` for PayPal and specific components for Cards and Google Pay. Since the action from `/payments` should be handled by different components, I maintain a common interface to call functions in a unified logic. I chose `ActionHandlingComponent` because both CardComponent and GooglePayComponent implement it. However, I later discovered that RedirectComponent does not.

**Comment by OscarSpruit** [comment]
@jaejoong-yoo-gtg in that case you can use the payment components directly to handle actions. For example, you can just pass a `RedirectAction` to `cardComponent.handleAction(...)`. To handle PayPal you can use the `InstantPaymentComponent` and use it the same way you'd use the `CardComponent`. This way the `RedirectComponent` is no longer needed as this will be handled for you under the hood.

**Comment by jaejoong-yoo-gtg** [comment]
@OscarSpruit Thank you for your suggestion. That's how I handle actions.
And, `InstantPaymentComponent` seems to be working. Can I use it for all payment methods that redirect without an input form?
One issue is that it doesn't show the loading state view at the bottom until the action is passed to the component. It would be great if you could improve it to display something when onSubmit is called or when AdyenComponent is launched.

**Comment by OscarSpruit** [comment]
Yes, `InstantPaymentComponent` can be used for all payment methods that have no input with a few exceptions like `ideal` and `twint`.

We recently addressed this issue, so from the next release on a loading state will be shown already from the beginning in `InstantPaymentComponent`

**Comment by jaejoong-yoo-gtg** [comment]
That's a good news. Thank you.

I wonder if the same change was made to `CardComponent`. It continues to display the card details input form when onSubmit is called, making it appear unresponsive.
So I had to manually remove the `AdyenComponent()` when onSubmit is called and add it again when the action is returned.

**Comment by jreij** [comment]
@jaejoong-yoo-gtg currently after `onSubmit` is triggered, we only block user interaction with the component inputs but we do not change the layout. This is done on purpose to give you full flexibility over how to handle the UI. For example, in our Drop-in we keep the card component visible and we show a loading overlay on top of the whole screen.

Let us know if you have any more questions related to the original topic, otherwise please close this issue and open new ones if you have a different topic, it helps us and future users to keep track of the issues in their context 😄

**Comment by jaejoong-yoo-gtg** [comment]
Sure. I will continue to manually add and remove the card component then.

I believe everything is resolved with this issue. Thank you.
