### ISSUE TITLE
Reset Card Component form data

### ISSUE THREAD

**Issue by fabioh8010** [Adyen/adyen-android#193]
Hello, i'm trying to implement a button to reset Card Component form data in the same activity. Look:

[
![Screenshot_1593019944](https://user-images.githubusercontent.com/20051562/85718643-9ebad880-b6e6-11ea-9006-9da94454828f.png)
](url)

The "Alterar método de pagamento" button will reset the form above, in case the user want to change payment method.

How can I achieve this with Card Components? I'm trying to attach a new CardComponent class to view, but it doesn't update the form.

**Comment by caiofaustino** [comment]
Hi Fabio, yeah the view doesn't expect to have different components attached to it. To achieve what you want I think the best approach is to create a new View and a new Component and swap them on the screen, either with visibility or actually removing and adding the view to the layout structure. You could even perhaps make some animation to make it a smoother transition.

Let me know if you need any more help. Cheers.

**Comment by fabioh8010** [comment]
Hi Caio, thank you very much for the help.
