### ISSUE TITLE
Android change colors in DropIn (text/button)

### ISSUE THREAD

**Issue by descorpapps** [Adyen/adyen-android#194]
Hi there . I'm trying to find something for customization. Is it anything available for that?
Like change TextColors , Buttons text/background colors etc. ? I heared for ios it's already available.

**Comment by descorpapps** [comment]
@caiofaustino thanks a lot. Will try soon

**Comment by Abhishekgarg727** [comment]
Hey, got same problem it override these styles by adding in my styles.xml - hope it will helpful to others hopefully adyen will proper documentation for it soon.

`


    <style name="AdyenCheckout.Button.Colored" parent="Widget.AppCompat.Button.Colored">
        <item name="android:layout_width">match_parent</item>
        <item name="android:layout_height">@dimen/pay_button_height</item>
        <item name="android:layout_marginBottom">@dimen/standard_half_margin</item>
        <item name="android:layout_marginLeft">@dimen/standard_margin</item>
        <item name="android:layout_marginRight">@dimen/standard_margin</item>
        <item name="android:textColor">@color/black</item>
        <item name="android:theme">@style/AdyenCheckout.PrimaryFlatButton</item>
    </style>

    <style name="AdyenCheckout.PrimaryFlatButton" parent="Theme.AppCompat.Light">
        <item name="android:buttonStyle">@style/Widget.AppCompat.Button.Borderless.Colored</item>
        <item name="colorAccent">@color/yellow</item>
    </style>

    <style name="AdyenCheckout.BottomSheet" parent="@style/Widget.Design.BottomSheet.Modal">
        <item name="android:background">@drawable/bg_bottom_sheet_dialog_fragment</item>
    </style>

    <style name="AdyenCheckout.BottomSheetIndicator" >
        <item name="android:layout_width">@dimen/indicator_width</item>
        <item name="android:layout_height">@dimen/indicator_height</item>
        <item name="android:layout_gravity">center</item>
        <item name="android:layout_marginTop">@dimen/standard_quarter_margin</item>
        <item name="android:layout_marginBottom">@dimen/standard_half_margin</item>
        <item name="android:background">@drawable/bottom_sheet_indicator</item>
    </style>

    <style name="AdyenCheckout.BaseBottomSheetDialog" parent="@style/Theme.Design.Light.BottomSheetDialog">
        <item name="android:windowIsFloating">false</item>
        <item name="bottomSheetStyle">@style/AdyenCheckout.BottomSheet</item>
        <item name="android:windowSoftInputMode">adjustResize</item>
    </style>

    <style name="AdyenCheckout.BottomSheetDialogTheme" parent="AdyenCheckout.BaseBottomSheetDialog" />

    <style name="AdyenCheckout.TextAppearance.HeaderTitle">
        <item name="android:paddingStart">@dimen/standard_margin</item>
        <item name="android:paddingLeft">@dimen/standard_margin</item>
        <item name="android:paddingTop">@dimen/standard_half_margin</item>
        <item name="android:paddingEnd">@dimen/standard_margin</item>
        <item name="android:paddingRight">@dimen/standard_margin</item>
        <item name="android:textAllCaps">true</item>
        <item name="android:textColor">@color/textColor</item>
        <item name="android:textIsSelectable">false</item>
        <item name="android:textSize">14sp</item>
        <item name="android:textStyle">bold</item>
    </style>

    <style name="AdyenCheckout.TextAppearance.HeaderTitle.Card" parent="AdyenCheckout.TextAppearance.HeaderTitle">
        <item name="android:paddingStart">0dp</item>
        <item name="android:paddingLeft">0dp</item>
    </style>

    <style name="AdyenCheckout.HintTextStyle" parent="TextAppearance.AppCompat">
        <item name="android:textColor">@color/black</item>
    </style>

    <style name="AdyenCheckout.TextInputLayout" parent="Widget.MaterialComponents.TextInputLayout.OutlinedBox">
        <item name="boxStrokeColor">@color/yellow</item>
        <item name="hintTextAppearance">@style/AdyenCheckout.HintTextStyle</item>
        <item name="android:minHeight">@dimen/input_layout_height</item>

        <item name="hintTextColor">@color/black</item>
        <item name="android:textColorHint">@color/black</item>
        
        <item name="colorAccent">@color/black</item>
        <item name="colorControlNormal">@color/black</item>
        <item name="colorControlActivated">@color/black</item>
    </style>

    <style name="AdyenCheckout.TextInputEditText">
        <item name="android:layout_width">match_parent</item>
        <item name="android:layout_height">@dimen/input_height</item>
        <item name="android:textCursorDrawable">@drawable/adyen_cursor_shape</item>
        <item name="android:textSize">16sp</item>
    </style>

    <style name="AdyenCheckout.SwitchTheme" parent="Widget.AppCompat.CompoundButton.Switch">
        <item name="colorControlActivated">@color/yellow</item>
    </style>`
