### ISSUE TITLE
Debit card Option when Users doing Payment

### ISSUE THREAD

**Issue by nishanth9493** [Adyen/adyen-android#195]
When a user is about to perform a payment the user is just shown an option of credit option.

the users are confused if debit cards are accepted.

We understand that credit card option accepts both debit and credit card but it would be better if the user is shown seperate options for credit and debit card.

**Comment by caiofaustino** [comment]
Thanks for the feedback, we already have a feature planned to address that issue so you can expect that behaviour in the following versions. I'll try to reply here once it is released.

**Comment by jreij** [comment]
HI @nishanth9493, we recently changed the name of the payment method from "Credit Card" to "Cards" on [API level 71](https://docs.adyen.com/api-explorer/Checkout/71/post/paymentMethods). Moreover, you can set [splitCardFundingSources = true](https://docs.adyen.com/api-explorer/Checkout/latest/post/paymentMethods#request-splitCardFundingSources) to receive 2 separate payment method entries: "Credit Card" and "Debit Card" (works on all supported API versions not only `v71`).

Let us know if you have any more questions.
