### ISSUE TITLE
Invalid date in the expiration date field

### ISSUE THREAD

**Issue by douglasramaldespd** [Adyen/adyen-android#196]
Hello friends,

I noticed that in your CardView component <card-ui: 3.6.4> in the expiration date field, if the user enters a date such as 00/30 or 19/30, for example, it does not report any error. It looks like there is a bug in this field, can you take a look at this to see if there are any solutions? thanks

**To Reproduce**
1. Go to the expiration date field in CardView
2. Insert the date 00/30

<img width="476" alt="Captura de Tela 2020-07-09 às 10 13 04" src="https://user-images.githubusercontent.com/58473762/87044837-7abec300-c1cd-11ea-8dd2-129b7931e8e6.png">

**Comment by caiofaustino** [comment]
Hey Douglas,
You are right, thanks for pointing this out, we will fix this on the next release.

**Comment by chgsilva** [comment]
any news on this? having the same issue

**Comment by caiofaustino** [comment]
@chgsilva oh yeah, this was fixed on `3.7.0`, I forgot to close the issue, feel free to open a new one if you still have problems
https://github.com/Adyen/adyen-android/blob/develop/CHANGELOG.md#fixed
