### ISSUE TITLE
How to handle error or user cancelled on Adyen3DS2Component?

### ISSUE THREAD

**Issue by Arthur-Tavais-Turbi** [Adyen/adyen-android#199]
Hello.

 I am implementing the 3DS2 on the comapanys app and i am having no problem handling the "happy ending flow", where the user do the challenge and all goes just fine. It triggs the threedsComponent.observe and i am able to continue my application flow. But i cant find on the documentation how to treat an user cancellation on the challenge screen or any error on the presentation of the challenge. What i am already doing:

            threedsComponent = Adyen3DS2Component.PROVIDER.get(this);

            threedsComponent.observe(this, actionComponentData -> {
                        
                 //sending the payment data and details to server
                          
            });
        }

How do i handle some error or user cancelation of the challenge? I am using version 3.6.2 of the sdk.

**Comment by caiofaustino** [comment]
Hi @Arthur-Tavais-Turbi,

Indeed our documentation could improve on how to handle the error scenarios here.
All components also have an observer for errors `observeErrors(lifecycleOwner, Observer<ComponentError>)`
The `ComponentError` object that you receive will have more information on the type of issue that occurred with `getErrorMessage` and `getException`.

We tried to simplify the error handling for 3DS2 with only to exception types, `Cancelled3DS2Exception` for when the user canceled the flow, and `Authentication3DS2Exception` for other errors that might have happened inside the 3DS2 SDK like protocol errors, time outs and other exceptions. Other errors on the component will likely be simple `ComponentException`.

Hope that helps, let me know if you have any other questions.

**Comment by caiofaustino** [comment]
hey, since there was no reply I'll close the issue, but feel free to open it again if you still have any problems
