### ISSUE TITLE
Where to find the server secret for the test server?

### ISSUE THREAD

**Issue by tjerkw** [Adyen/adyen-android#2]
Its unclear where to find the "app id" and the "merchant server secret" for testing payments in app without a backend.

This also doesnt help me:
https://checkoutshopper-test.adyen.com/checkoutshopper/demoserver/

Where exactly can this be found?

**Comment by wvdriel** [comment]
Hi Tjerk,

Thanks for asking. The app-id can be a dummy value, we don't perform any checks on that field. You can find the X-MerchantServer-App-SecretKey in the Customer Area.
Go to the Customer Area (https://ca-test.adyen.com/ca/ca/login.shtml) -> Merchant account -> settings -> users -> your webservice user (ws@company.yourCompany). In this screen you will see a block "Checkout token", in this block there is the "Checkout API key" and the "Checkout Demo Secret". The Checkout API key is used in your own server implementation: X-API-KEY. The Checkout Demo Secret is when you want to use our test server: x-demo-server-api-key.

If you don't see the "Checkout token" we need to do some configuration on your account. Please send an email to support@adyen.com.

We're currently aligning the naming of these variables between the test apps and Customer Area. So moving forward, it should be easier to get the right credentials in place.

Cheers,
Willem

**Comment by tjerkw** [comment]
Indeed i didn't see it there, because I had to ask Adyen Support to enable the feature. 
Thanks! Its more clear now.

If you don't see the token: Ask adyen support to enable it for your account.
