### ISSUE TITLE
Link to in-app integration broken

### ISSUE THREAD

**Issue by GrzegorzFeather** [Adyen/adyen-android#20]
Link to in-app integration guide throws 404: https://github.com/Adyen/adyen-android

![screen shot 2018-03-05 at 4 58 47 pm](https://user-images.githubusercontent.com/3044632/37008352-81946638-2096-11e8-815b-f5777306de24.png)

**Comment by timon-langlotz** [comment]
Hi @GrzegorzFeather,

thanks for letting us know, we will update the link.

For now, you can find the integration guide here:
https://docs.adyen.com/developers/checkout/android-sdk/quick-start-android/get-api-key-android

Cheers,
Timon

**Comment by GrzegorzFeather** [comment]
Thanks for the info @timon-langlotz !

**Comment by timon-langlotz** [comment]
The link is fixed!

Regards,
Timon
