### ISSUE TITLE
[Drop In Android] Show input billing or shipping address in drop in with save support as well.

### ISSUE THREAD

**Issue by Abhishekgarg727** [Adyen/adyen-android#201]
**Is your feature request related to a problem? Please describe.**
How i can show enter billing or shipping address or as well passing stored one to show in drop in android UI

**Comment by Abhishekgarg727** [comment]
@descorp @caiofaustino any of you can provide help in this. basically we want to show billing and shipping address options jn UI for card drop in

**Comment by descorp** [comment]
Hi @Abhishekgarg727 

Could you provide more details about your use-case and describe the goal you are striving to?

Some payment methods requires those parameters (GooglePay, ApplePay, AfterPay e.t.c) but the UI is handled by payment system, not Adyen DropIn.

Unfortunately, latest version of Adyen SDK do not provide any UI for  billing or shipping address. 
We also have no plans to offer this functionality.
For now, I could only suggest to build your own UI. 
You could alternate our code to build in a custom steps for address, or use similar technics to build your own UI outside of DropIn.

**Comment by Abhishekgarg727** [comment]
@descorp noted. thanks

**Comment by descorp** [comment]
@Abhishekgarg727 don't get me wrong!

The fact that we don't have plans, does not mean it is never going to happen :D 
If we see a good use-case - we can re-evaluate our roadmap. In general. 
We are always very curious about how community uses our SDK and how we can make your experience better.

Adyen do provide some Shopper Address functionality, it is just not part of our mobile SDK offering.
