### ISSUE TITLE
[DropIn Android] setAction like iOS

### ISSUE THREAD

**Issue by badredaha** [Adyen/adyen-android#203]
Hi,

why in Android there is no way to set action (from response API came from React native bridge)?

**Comment by descorp** [comment]
Hi @badredaha 

Could you be more specific?

What SDK API you mean? Could you provide an example of how it is right now and how you would like it to be?

**Comment by badredaha** [comment]
Hi @descorp 

Thank you for the replay :) as usual you answer fast

I will try to explain:

we commmunicate between our API (Adyen API included into our API) and Android Adyen SDK Through React Native Module (Bridge between RN and Native) to pass all information needed by SDK.

iOS All Work: Show DropIn, Challenge, etc ...

But, Android:
- Show DropIn -> Ok

Challenge Ko -> Because we need to return a CallResult even we waiting response from RN

My Question is : Why we need do a call API into Adyen SDK ! not like iOS (listening to delegate with payemtData and Details)

**Comment by caiofaustino** [comment]
Hey @badredaha,

Sorry I'm not sure if I follow your question fully, the iOS and Android SDKs were built trying to leverage each platform architecture in different ways, so maybe that's why the difference in behavior.

From this message 
>Because we need to return a CallResult even we waiting response from RN"

I think you are trying to make an asynchronous call instead of returning right? That's fine, you can achieve that by returning `CallResult` with `ResultType.WAIT`. This will tell the Drop-in to stand by and wait for a callback, then later when you receive the API result you can call `asyncCallback(callResult)` in your `DropInService`.

I'm not familiar with the React native part but I assume you could build that as part of your bridge right?

**Comment by badredaha** [comment]
@caiofaustino exactly 👍  i tried this ! i returned ResultType.WAIT and when i receive the response i set action to makePaymentsCall with action from our API and i return ResultType.Action.

When i use asyncCallback(callResult) i get this : 
`java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference`

**Comment by badredaha** [comment]
@caiofaustino @descorp any help ?

**Comment by caiofaustino** [comment]
Ah, sorry do you have a full stacktrace of the issue? I don't see anything that would be directly related to that.

**Comment by badredaha** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
        at android.content.ContextWrapper.getPackageName(ContextWrapper.java:133)
        at com.adyen.checkout.dropin.service.DropInService$Companion.getServiceResultAction(DropInService.kt:58)
        at com.adyen.checkout.dropin.service.DropInService.handleCallResult(DropInService.kt:155)
        at com.adyen.checkout.dropin.service.DropInService.asyncCallback(DropInService.kt:122)
        at com.apps.bridges.adyen.AdyenDropInService.setAction(AdyenDropInService.kt:22)
        at com.apps.bridges.adyen.AdyenBridge.challenge(AdyenBridge.java:64)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:148)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:818)

**Comment by badredaha** [comment]
From Class Java i set the action from the challenge received from RN (our API) : 
`Class AdyenBridge{
....
@ReactMethod
  void challenge(String action,Callback result,Callback error){
    DropInWorker.Companion.getAdyenDropInService().setAction(action);
}
...
}
`

show DropIn from Activity : 
`...

public void dropIn() {

    Intent resultIntent = new Intent(this, AdyenActivity.class);
    resultIntent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);

    DropInConfiguration dropInConfiguration = DropInWorker.Companion.setupDropInComonent(this, resultIntent);
    try {

      PaymentMethodsApiResponse paymentMethodsApiResponse = PaymentMethodsApiResponse.SERIALIZER.deserialize(new JSONObject(this.paymentMethods));
      final AdyenActivity adyenActivity = this;
      DropIn.startPayment(adyenActivity, paymentMethodsApiResponse, dropInConfiguration);

    } catch (JSONException jsoe) {
      Log.d("AdyenBridge", "JSONException " + jsoe.getMessage());
    }
  }
...`

And my worker who setup my DropinConfiguration : 
`
class DropInWorker {

  companion object {
    val adyenDropInService = AdyenDropInService()
    fun setupDropInComonent(activity: Activity, intent: Intent): DropInConfiguration {

      val isDev = Utils.isModeDev(activity.application);
      var key = Config.CARD_PUBLIC_KEY_LIVE
      var adyenENV: Environment = Environment.EUROPE
      if (isDev) {
        key = Config.CARD_PUBLIC_KEY_FOR_TEST
        adyenENV = Environment.TEST
      }

      var cardConfiguration =
        CardConfiguration.Builder(activity, key).setHolderNameRequire(true)
          .build()

      val dropInConfiguration = DropInConfiguration.Builder(activity, intent, adyenDropInService::class.java)
        // When you're ready to accept live payments, change the value to one of our live environments.
        .setEnvironment(adyenENV)
        .addCardConfiguration(cardConfiguration)
        .build()
      return dropInConfiguration
    }
  }
}`

**Comment by caiofaustino** [comment]
Can you check inside `DropInWorker.Companion.getAdyenDropInService().setAction(action);`?

The NPE is really strange, the `DropInService` passes itself as the Context for that call, so I'm assuming it could be some issue with the Bridge part, which I assume you implemented right?

This is the part throwing the NPE:
https://github.com/Adyen/adyen-android/blob/27c83da4160fde060aa4ad607785d8610108ed0d/drop-in/src/main/java/com/adyen/checkout/dropin/service/DropInService.kt#L155
https://github.com/Adyen/adyen-android/blob/27c83da4160fde060aa4ad607785d8610108ed0d/drop-in/src/main/java/com/adyen/checkout/dropin/service/DropInService.kt#L58

**Comment by badredaha** [comment]
@caiofaustino this my AdyenBridgeService:

```
package com.apps.bridges.adyen.services

import com.adyen.checkout.base.ActionComponentData
import com.adyen.checkout.base.model.payments.request.PaymentComponentData
import com.adyen.checkout.base.model.payments.request.PaymentMethodDetails
import com.adyen.checkout.base.model.payments.response.Action
import com.adyen.checkout.core.log.LogUtil
import com.adyen.checkout.core.log.Logger
import com.adyen.checkout.core.model.JsonUtils
import com.adyen.checkout.dropin.service.CallResult
import com.adyen.checkout.dropin.service.DropInService
import com.apps.bridges.adyen.AdyenBridge
import com.apps.bridges.adyen.utils.JsonToReadableMap
import org.json.JSONObject
import java.io.IOException


class AdyenDropInService : DropInService() {

  fun setAction(action: String) {
    //makeDetailsCall(StringToJSONObject(action).json)
    val callResult = CallResult(CallResult.ResultType.ACTION, action)
    asyncCallback(callResult)
  }

  companion object {
    private val TAG = LogUtil.getTag()
    var authorized = "authorized"
  }

  override fun makeDetailsCall(actionComponentData: JSONObject): CallResult {
    return handleResponse(actionComponentData)
  }

  override fun makePaymentsCall(paymentComponentData: JSONObject): CallResult {
    return handleResponse(paymentComponentData)
  }

  @Suppress("NestedBlockDepth")
  private fun handleResponse(jsonObject: JSONObject): CallResult {
    return try {

      if (jsonObject != null && jsonObject.length() > 0) {
        if (isAction(jsonObject)) {
          handleAction(jsonObject)
        } else {
          Logger.d(TAG, "Final result - ${JsonUtils.indent(jsonObject)}")

          var content = "EMPTY"
          if (jsonObject.has("resultCode")) {
            content = jsonObject.get("resultCode").toString()
            CallResult(CallResult.ResultType.FINISHED, content)
          } else {
            content = "paymentMethod"
            val paymentComponentData = PaymentComponentData.SERIALIZER.deserialize(jsonObject)

            val paymentMethod = paymentComponentData.paymentMethod
            paymentMethod?.let {
              val paymentData = PaymentMethodDetails.SERIALIZER.serialize(paymentMethod)
              val newMap = JsonToReadableMap(paymentData).newMap
              AdyenBridge.AdyenBridgeCallbacks.instance.didSetPaymentWithData.invoke(newMap)
            }
            CallResult(CallResult.ResultType.WAIT, content)
          }

        }
      } else {
        Logger.e(TAG, "FAILED - jsonObject null or lenght 0")
        CallResult(CallResult.ResultType.ERROR, "IOException")
      }
    } catch (e: IOException) {
      Logger.e(TAG, "IOException", e)
      CallResult(CallResult.ResultType.ERROR, "Error : " + e.message)
    }
  }


  @Throws(IOException::class)
  fun handleAction(jsonObject: JSONObject): CallResult {
    val actionPaymentData = ActionComponentData.SERIALIZER.deserialize(jsonObject)

    val paymentData = actionPaymentData.paymentData
    val paymentDetail = actionPaymentData.details
    paymentDetail?.let {
      val newMap = JsonToReadableMap(paymentDetail).newMap
      val provideActionWithElement = mutableListOf(paymentData, newMap)
      //AdyenBridge.AdyenBridgeCallbacks.instance.didProvideAction.invoke(provideActionWithElement)
    }

    return CallResult(CallResult.ResultType.ACTION, jsonObject.get("threeDS2Fingerprint").toString())
  }

  private fun isAction(jsonObject: JSONObject): Boolean {
    return jsonObject.has(Action.TYPE) && jsonObject.has(Action.PAYMENT_METHOD_TYPE)
  }


}

```

**Comment by caiofaustino** [comment]
Yeah sorry but I don't have any knowledge of React Native, maybe the Service was killed by Android since you are doing the actual API call on a different place and the Service is no longer running? Just a wild guess. Try to put a log on the `onDestroy` method of the `AdyenDropInService` and check if it's being called after your `handleResponse` for some reason.

**Comment by badredaha** [comment]
Yes the onDrestroy is called !

**Comment by caiofaustino** [comment]
That shouldn't happen. You either have to keep something running on the Service so that it doesn't get killed, or start it again, but then you'll have to make some custom logic to override the onHadleWord
https://github.com/Adyen/adyen-android/blob/27c83da4160fde060aa4ad607785d8610108ed0d/drop-in/src/main/java/com/adyen/checkout/dropin/service/DropInService.kt#L94

**Comment by badredaha** [comment]
i return CallResult.Wait before i call asyncCallResult ! that mean the service always still running ! and wait for moving forward for an other state ?

**Comment by badredaha** [comment]
i override onHandleWork and started i set challenge with all works perfect **BUT**:  

```
fun setAction(action:String, context: Context){
    val intent = Intent(context,this.javaClass)
    intent.setAction(AdyenBridge.SET_ACTION)
    intent.putExtra("action", action)
    enqueueWork(context, this.javaClass, 11, intent)
  }
```

the problem is **_dropInJobId_** !! i get it from DropInService but the attribute is private :/ i copied value to works :/ CRUDE 👎  i know but what you propose ?

**Comment by caiofaustino** [comment]
Ahh no worries, I'll change that to public for the next release. But other than that your solution is working now right? 👍

**Comment by badredaha** [comment]
yess thx 🙏 . When you go to make it public ?

**Comment by caiofaustino** [comment]
This week or the next.

**Comment by badredaha** [comment]
thx 🕺🕺🕺  if you can give me feedback please.

**Comment by caiofaustino** [comment]
Just follow the repo and you'll get notified of new versions :)

**Comment by badredaha** [comment]
you rock. thx keep in touch and give a hi5 to the team 🥇

**Comment by badredaha** [comment]
Hi @caiofaustino,

i reopened issue beause i have a problem with redirection ! all works good, but when the webview is opened and i click to confirm transaction, the "onActivityResult" is called ! with RESULT_CANCELED ! and makeDetailsCall is not called (like in normal action).

**Comment by caiofaustino** [comment]
Confirm transaction where? I assume that's the part where the `returnUrl` would be called and link back to the Activity instead of closing itself. Where are you seeing the RESULT_CANCELED? On the Activity that started the Drop-in?

**Comment by badredaha** [comment]
Yes ! in my Activity where i started DropIn  (i need onActivityResult to handle the cancel of DropIn to do stuff)

**Comment by caiofaustino** [comment]
this is jumping a few steps, try to add this line before calling the Drop-in and get some Logs
`Logger.setLogcatLevel(Log.DEBUG)`
it will enable some debug logs and you can read what happens after you click on confirm transaction

**Comment by badredaha** [comment]
when i click to confirm "WebView" i see 
D/CO.Adyen3DS2Component: onCleared
D/CO.DropInActivity: onDestroy

**Comment by badredaha** [comment]
Hi,

i was in vacation I'm back 😄  . Any news ?

**Comment by caiofaustino** [comment]
Hi, no sorry, we did release a new version today with the `dropInJobId` made public for you.
`D/CO.Adyen3DS2Component: onCleared` this seems to be the 3DS2 SDK and not a webview.
Any chance you can have a video showing the flow?

**Comment by badredaha** [comment]
Yes ...

Because the size of the video is more than 10MB i put the video in my Drive : `https://drive.google.com/file/d/1tFmZFcGoZs-aQj0CO7J_r7IkCNSN73xV/view`

**Comment by caiofaustino** [comment]
Wow this is super weird. So you are starting the Drop-in and you handle the action afterwards like we discussed and that seems to work fine. Then you go to the redirect of iDeal which opens the CustomTab, so far so good.

What should happen next is that the website will call the `returnUrl` you specified on the `/payments` call, which should be the one handled by the Drop-in. You can get it with `RedirectComponent.getReturnUrl(context)`, which is a deep link back to the `DropInActivity` that will handle the result back. But it seems like it's deep linking to your own Activity and by doing that probably is sending you the `onActivityResult`.

Also the 3DS2 component Log there is misleading because actually all Action components are being cleared with the DropInActivity, but that one is the only one with the Log, sorry about that.

Can you check if the `returnUrl` you are sending is correct?

**Comment by badredaha** [comment]
i will. and also i will put all my code into a new activity and i will inform you. Thx a lot @caiofaustino  for your help 😃

**Comment by badredaha** [comment]
@caiofaustino dude, you're good in your approach of analyses 😃 

All works. my redirectURL not matched 💯 

Thx a lot

**Comment by caiofaustino** [comment]
Awesome! Glad you fixed it :) Feel free to open new issues if you have any more problems. Cheers.
