### ISSUE TITLE
Make Drop-in show directly a single payment method.

### ISSUE THREAD

**Issue by PhilippeBoisney** [Adyen/adyen-android#205]
**Is your feature request related to a problem? Please describe.**
When the drop-in contains **only one** payment method, it could be interesting to show directly it (instead of having the view that lists only one single payment method).

We could, of course, use the [Components integration](https://docs.adyen.com/checkout/android/components), but this solution forces us to implement by ourself a lot of other things (async calls, UI loading state, etc...).

Is there any other solutions I've missed?

**Describe the solution you'd like**
When launching the Drop-in, a `Boolean` property in order to enable/disable this option.

**Comment by caiofaustino** [comment]
No you are right, this is an improvement we considered, just haven't implemented it yet. We will put it in the backlog :)

**Comment by MariaTod** [comment]
@caiofaustino I thought this is possible with the drop-in, I only have Credit Card and I need the user to see directly the payment form without having to tap to select "Credit Card" as this is the only option.
On iOS it's possible, so there is no way to do this on Android?

**Comment by caiofaustino** [comment]
Not right now, unless they already have a stored card with us, in that case the stored card will show up separately.
But we will work on that for future releases.
![Screenshot_1600342281](https://user-images.githubusercontent.com/3094935/93465491-2a5d9300-f8eb-11ea-9d78-dafaa0c9076c.png)

**Comment by KenrickV-Hexaware** [comment]
Hi, any update when this will be prioritised in the backlog? Thank you

**Comment by BenedictP** [comment]
Would be really nice to have this feature!

**Comment by przan** [comment]
Also waiting for this, as we wanted to use Drop-in to tokenize user's cards only. There is no point in showing payment methods bottomsheet.

**Comment by BenedictP** [comment]
@przan They added this feature in the current release but not like I wanted/needed it (for example when you have Google Pay as the only Payment method it still shows a selection also when the only payment method is a stored one). Here is the information when the payment methods will NOT be skipped:

> This only applies to payment methods that require a component (user input). Which means redirect payment methods, SDK payment methods, etc will not be skipped even if this flag is set to true and a single payment method is present.

**Comment by przan** [comment]
@BenedictP Thanks for reply! Now I see `showPreselectedStoredPaymentMethod ` has been added in https://github.com/Adyen/adyen-android/releases/tag/4.1.0 However, it doesn't work as I would like it to - I can still see Payment methods bottom sheet with only one option - card. I would like it skip this screen and open the one for card input. I will test it a bit more, though

**Comment by jreij** [comment]
Hi @przan, this feature will be released soon with `4.3.0`. The method is called `DropInConfiguration.Builder.setSkipListWhenSinglePaymentMethod` and as @BenedictP replied (thanks!) it will only apply to payment methods that have components, card being one of those.
