### ISSUE TITLE
Paypal redirect randomly fails

### ISSUE THREAD

**Issue by ArthurSav** [Adyen/adyen-android#208]
**Describe the bug**
Hi, i'm currently adding Paypal integration through Adyen in our (android) app. The issue is that sometimes the webview opened through Adyen quits in the midst of redirecting to Paypal with an obscure error  `No package ID ff found for ID 0xffffffff.`
The cause seems random, sometimes it will load the paypal page with the first try and sometimes it fails a few times before it actually works.

**To Reproduce**

This is done in an **adyen test environment** with **paypal sandbox**.

Craft an adyen redirect action with Paypal as a payment method.

Use action with [RedirectComponent.makeRedirect](https://github.com/Adyen/adyen-android/blob/57301f4ef1d040fa854dad928e432797e03db858/redirect/src/main/java/com/adyen/checkout/redirect/RedirectComponent.java#L64) from an android device with a chrome browser.

When the `CustomTabsIntent` is created and launched, a webview opens with the message "Redirect", as expected. After that i get 2 different behaviours:

- During the redirect the webview quits unexpectedly with no Adyen onNewIntent response or any verbose error. Just this message in my console `No package ID ff found for ID 0xffffffff.`
- Redirect completes and the paypal site is loaded.

**Expected behavior**
Redirect should load the Paypal payment view and not quit unexpectedly.

**Images**

What you see here is the following:
- A form that communicates with our backend and gets a redirect action.
- 2 successful redirects, 1 failed.

![ezgif-7-1b2cb2bec79d](https://user-images.githubusercontent.com/2115575/90822774-3af30b80-e335-11ea-806b-fb44e866f838.gif)
**

**Smartphone 1**
 - Device: Pixel 3a **emulator**
 - OS: Android 10 (API level 29) x86

**Smartphone 2**
 - Device: Samsung Galaxy s8+ (physical device)
 - OS: Android 9

**Additional context**

My best guess is that it's a chrome + redirect issue. I found this bug [Chrome Custom Tabs redirect to Android app will close the app
](https://stackoverflow.com/questions/36084681/chrome-custom-tabs-redirect-to-android-app-will-close-the-app)  that is similar to this one and tried the suggested solution but it didn't work.

**Comment by caiofaustino** [comment]
Hi, so after some digging it is indeed an issue in the backend, maybe specific to your account configuration, so it would be better if you can contact [Adyen Support](https://support.adyen.com/hc/en-us/requests/new?ticket_form_id=360000705420), they can take a better look and contact the right people to help you best.

Good luck
