### ISSUE TITLE
There is no names of banks next to banks logos in IDEAL, in case of using Drop-in

### ISSUE THREAD

**Issue by MaxKomarenski** [Adyen/adyen-android#209]
Hi there,

Steps to reproduce:

1. Initialize drop-in configuration builder
2. DropIn.startPayment(context, paymentMethodsApiResponse, dropInConfigurationBuilder.build()) - to show Drop in
3. Then I choose IDEAL from the list of payment methods
4. I see the list of banks. But only the logos of these banks. If we compare it to iOS, they have also names of these banks next to logos.

By the way, IDEAL payment method works well, I can choose any bank, It will redirect me to WebView and I can pay there.

**Comment by caiofaustino** [comment]
Closing the issue since there is no more response. Hope you were able to find your way in the customisation. 
Feel free to reopen if you have more questions.
