### ISSUE TITLE
getting crash

### ISSUE THREAD

**Issue by anoopfoodepsa** [Adyen/adyen-android#210]
Hi Team I am using drop-in as a payment option but I am getting below issue.

**Describe the bug**
Caused by org.json.JSONException: Value null of type org.json.JSONObject$1 cannot be converted to JSONObject
       at org.json.JSON.typeMismatch(JSON.java:112)
       at org.json.JSONObject.<init>(JSONObject.java:168)
       at org.json.JSONObject.<init>(JSONObject.java:181)
       at com.adyen.checkout.dropin.ui.DropInActivity.handleCallResult(DropInActivity.kt:317)
       at com.adyen.checkout.dropin.ui.DropInActivity$callResultReceiver$1.onReceive(DropInActivity.kt:105)
       at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
       at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:228)
       at android.app.ActivityThread.main(ActivityThread.java:7782)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
**To Reproduce**

once I am getting a response (below is the res.) app is crashing 

{
  "additionalData": null,
  "details": null,
  "fraudResult": null,
  "paymentData": null,
  "pspReference": "883599500787849F",
  "redirect": null,
  "refusalReason": null,
  "refusalReasonCode": null,
  "resultCode": "AUTHORISED",
  "serviceError": null,
  "authResponse": null,
  "merchantReference": "TestOrder1",
  "outputDetails": null,
  "authentication": null,
  "threeDS2Result": null,
  "action": null,
  "amount": {
    "value": 500,
    "currency": "USD",
    "decimalValue": 5
  },
  "order": null,
  "paymentMethod": null,
  "cardBin": null,
  "cardHolderName": null,
  "cardSummary": null,
  "avsResult": null,
  "3DOffered": false,
  "3DAuthenticated": false,
  "boletoBarCodeReference": null,
  "boletoData": null,
  "authCode": null,
  "boletoDueDate": null,
  "boletoExpirationDate": null,
  "boletoUrl": null,
  "expiryDate": null
}

**Comment by anoopfoodepsa** [comment]
please take this on priority...

**Comment by caiofaustino** [comment]
Hi @anoopfoodepsa,

This seems related to your implementation of the `DropInService`, in this response there is no `action` object to be handled so the payment is completed. You should return something like `new CallResult(CallResult.ResultType.FINISHED, "AUTHORISED")` in that case.

Can you please check?

**Comment by anoopfoodepsa** [comment]
Hi Team,
I am using SimplifiedDropInService and after remove the null value crash issue is fixed but i am not getting a call back on onActivityResult:

please find the below code i am using:

 PaymentMethodsApiResponse paymentMethodsApiResponse = PaymentMethodsApiResponse.SERIALIZER.deserialize(jo2);


                                String pkey =MyKey;

                                CardConfiguration cardConfiguration = new CardConfiguration.Builder(SubscribeFlizActivity.this, pkey).build();
               Intent resultIntent = new Intent(SubscribeFlizActivity.this,SubscribeFlizActivity.class);
                                resultIntent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);

                                try {
                                    DropInConfiguration.Builder dropInConfiguration = new DropInConfiguration.Builder(
                                            SubscribeFlizActivity.this,
                                            resultIntent,
                                            FlizDropInService.class).
                                            setEnvironment(Environment.TEST).
                                            addCardConfiguration(cardConfiguration);

                                    DropIn.startPayment(SubscribeFlizActivity.this, paymentMethodsApiResponse, dropInConfiguration.build());

                                } catch (Exception CheckoutException) {
                                    Logger.e(TAG, "Amount $amount not valid", CheckoutException);
                                }

**Comment by anoopfoodepsa** [comment]
using     implementation "com.adyen.checkout:drop-in:3.6.6"

**Comment by caiofaustino** [comment]
The initialization looks fine to me, can you share your implementation of the `FlizDropInService`?
Just the part of how you parse the API response and return it should be enough.

**Comment by anoopfoodepsa** [comment]
Please below FlizDropInService code

import android.content.Intent;
import android.util.Log;


import com.adyen.checkout.dropin.service.CallResult;
import com.adyen.checkout.dropin.service.SimplifiedDropInService;
import com.cordova.flizmovies.core.profile.SubscribeFlizActivity;
import com.cordova.flizmovies.models.rest.user.Authenticate;
import com.cordova.flizmovies.rest.api.RestApiBase;
import com.cordova.flizmovies.rest.api.RestCall;
import com.cordova.flizmovies.rest.constants.RestConstants;
import com.cordova.flizmovies.rest.listeners.RestListener;
import com.cordova.flizmovies.utils.base.AppUtils;
import com.cordova.flizmovies.utils.constants.AppConstants;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonObject;

import org.json.JSONException;
import org.json.JSONObject;

import java.io.IOException;
import java.util.Locale;

import androidx.annotation.Nullable;

public class FlizDropInService extends SimplifiedDropInService {

    @Nullable
    @Override
    public JSONObject makePaymentsCallOrFail( JSONObject jsonObject) {
    
     JSONObject res =  null;
       try {

        JSONObject res =   RestCall.get().apiProcessExecute(RestApiBase.get().makePaymentAdyen(jsonObject));

         } catch (JSONException e) {
             e.printStackTrace();
         }
         return res;
    }

    @Nullable
    @Override
    public JSONObject makeDetailsCallOrFail( JSONObject jsonObject) {
       JSONObject res =  null;
       try {
            JSONObject res =   RestCall.get().apiProcessExecute(RestApiBase.get().submitAdditionalDetails(jsonObject));
         } catch (JSONException e) {
             e.printStackTrace();
         }
         return res;
    }



}

**Comment by caiofaustino** [comment]
So if I understand correctly now you don't see the crash anymore but you are expecting a result on the `onActivityResult` right? So if the flow finished successfully you will not get `onActivityResult`, you will receive the Intent you specified here:
` Intent resultIntent = new Intent(SubscribeFlizActivity.this,SubscribeFlizActivity.class);`
With the result in the `intent.getStringExtra(DropIn.RESULT_KEY)`.

**Comment by ozgur00** [comment]
Closing the issue since the discussion has been concluded.
