### ISSUE TITLE
Update proguard rules

### ISSUE THREAD

**Issue by DJuanan** [Adyen/adyen-android#214]
Hi!
After upgrading to the last version of the SDK, it was not enough with the ProGuard rules described in the README to make a 3DS flow.

I made it works after adding: `-keep class com.adyen.checkout.** { *; }`
Is it ok?
If not, could you tell me a more restrictive rule to make it work?

Thanks!

**Comment by caiofaustino** [comment]
Hey there,
Can you send me the error message you get with the previous ruleset? I'll see if I can find out the issue.

Cheers.

**Comment by DJuanan** [comment]
It was an error in the deserialization of an internal Adyen class (the name was obfuscated)
I will try to get the exact error because debugging with ProGuard is not easy.

**Comment by DJuanan** [comment]
java.lang.RuntimeException: Failed to create an instance of component: class c.b.a.a.a
Caused by: java.lang.NoSuchMethodException: c.b.a.a.a.<init> [class android.app.Application, class com.adyen.checkout.adyen3ds2.Adyen3DS2Configuration]

**Comment by caiofaustino** [comment]
Thanks,
Please add this extra rule and let me know if you still have issues:
```
-keepclassmembers public class * implements com.adyen.checkout.base.ActionComponent {
   public <init>(...);
}
```

**Comment by caiofaustino** [comment]
#218 seems to have worked so I'll close the issue. Feel free to reopen if you still have problems.
