### ISSUE TITLE
Ability to localise / customise the name of the Credit Card payment option

### ISSUE THREAD

**Issue by duncanpflaeger** [Adyen/adyen-android#216]
In the UK the Credit Card option is used for both Debit and Credit Cards, which has led to some customer confusion as the option is named "Credit Card" within the Drop-in. Typically other apps/websites/self service tills use the term "Card Payment"

The Web drop-in includes the ability to change the displayed name, hence the showcase here uses the title "Credit or debit card" https://docs.adyen.com/checkout/drop-in-web/customization#styling-examples

Could the same ability to rename be added to the Android drop-in too please?

**Comment by caiofaustino** [comment]
Hey Duncan,
Thanks for the suggestion. Currently on Android we are still in the process of adding some features regarding Debit cards so I think this will improve in the future.
For now the Drop-in uses the result of the `/paymentMethods/ ` call to get the strings with the names of the payment methods on the selection screen. What you can do is "trick" the Drop-in by changing the value on the `paymentMethodsApiResponse` before calling `DropIn.startPayment()`. You can set it manually on the object or on the JSON before it gets parsed, your choice.
Also override this String that's used internally as a fallback just in case. 
`<string name="credit_card">Credit Card</string>`
