### ISSUE TITLE
Migrate to AndroidX

### ISSUE THREAD

**Issue by kirillzh** [Adyen/adyen-android#217]
Support library APIs are deprecated https://developer.android.com/jetpack/androidx/migrate

**Comment by kirillzh** [comment]
Just found an existing ticket for this already #176 but it's closed for some reason. I think it's worth to keep an open ticket. Adyen is one of the few handful dependencies that prevents us from finally disabling Jetifier.

**Comment by caiofaustino** [comment]
Sure, it's good to keep track. We already have an internal working version of it with some other changes, but we are currently moving our workflow completely here to GitHub. We will probably release an alpha build after that.

**Comment by jrodbx** [comment]
Any estimated timeline for this @caiofaustino?  @kirillzh and I would love to disable Jetifier in our CI builds soon!

**Comment by caiofaustino** [comment]
soon™ 
Don't have a hard estimate but hopefully not more than a couple weeks.

**Comment by deividasstr** [comment]
Glad to see the PR being ready! 
Can't wait to disable jetifier for the performance boost 🚀

**Comment by caiofaustino** [comment]
Happy to announce that finally `4.0.0-alpha01` is released with AndroidX support and jetifier turned off.
Sorry for the delay, but I hope you can get the build and start running your own tests and let us know if you find any issues.
There are no major changes other that I think would break things, but we have some plans to make other changes that might impact the public API.

Your feedback is greatly appreciated!
