### ISSUE TITLE
Don't auto-select a bank in the iDEAL component

### ISSUE THREAD

**Issue by vitorhugods** [Adyen/adyen-android#221]
**Is your feature request related to a problem? Please describe.**
When opening iDEAL Spinner, the "IGN" bank (or whatever is in the first entry of available banks) comes pre-selected by default. 
Some users don't notice that it is possible to click on the drop-down arrow to select other banks.

**Describe the solution you'd like**
Don't pre-select the bank. Either transform the bank list into a recyclerview, selecting one of the banks before confirming, or add a placeholder saying "Please select a bank" instead of pre-selecting the bank.

**Describe alternatives you've considered**
Not use that Spinner? But I think this is a very important and simple change that would improve the component a lot.

I'm willing to develop and submit a PR, changing the iDEAL Drop-In UI following the discussion in here, if this is seen as a wanted feature.

**Comment by caiofaustino** [comment]
Hi Vitor,

This is strange, the Drop-in behavior is already a RecycleView, we have a picture of that in the readme of the repo.
We have an alternative Spinner view you can use in the components, but the one used in the Drop-in is the RecycleView.
You can check the code here:
https://github.com/Adyen/adyen-android/blob/ad096bc684e080280b4b3cc7a62a768e4f1659e9/drop-in/src/main/java/com/adyen/checkout/dropin/ComponentParsingProvider.kt#L298

Do you have a screenshot of that behavior? This seems weird.

**Comment by vitorhugods** [comment]
Oi Caio :) 

You're absolutely right.
I mixed-up Components/Drop-In here. I thought that the default view and components offered by the SDK would behave just like the drop-in. I was wrong.

The behaviour I'm describing is about Components. 
And the Spinner you refeered to is the one showing up pre-selected when using it with iDeal. 

I believe that the IssuerListSpinnerView, or the IdealSpinnerView should enable, or at least support, a prompt text instead of having a pre-selection.

**Comment by caiofaustino** [comment]
Ahh OK then, yeah I see what you mean. I can talk to our UX team about this and get their feedback.
But for now if you really want to have that behavior you can implement it yourself!

The `paymentMethod` object you pass to the `PROVIDER` has the API result that configures the Component.
If you add an item to the `paymentMethod.getDetails()` as the first on the list, either on the JSON that will be parsed or directly in the object afterwards. The component will treat the new entry as a valid Bank, so it will return the details as valid, but you can check that on your observer and know that entry is actually not a real bank.

**Comment by jreij** [comment]
With the new iDEAL flow in [5.5.0](https://github.com/Adyen/adyen-android/releases/tag/5.5.0), this enhancement is no longer applicable, as the bank selection will not happen on the SDK's side anymore.
