### ISSUE TITLE
Observer onChanged method called every time the fragment is replaced and restored

### ISSUE THREAD

**Issue by PiDyGB** [Adyen/adyen-android#226]
**Describe the bug**
The Observer onChanged method is called every time the fragment is recreated.

**To Reproduce**
1. An action is received from the /payments API and handled with the Adyen3DS2Component
2. The Observer onChanged method is called
3. The /payments/details API is called and the response is handled with the Adyen3DS2Component
4. The 3D Secure 2 page is opened
2. Cancel the payment tapping on the cancel button
3. Open a new fragment that replaces the current fragment where the Adyen3DS2Component is referenced
4. Press back
5. The Observer onChanged method is called again

**Expected behavior**
The Observer onChanged shouldn't be called

```kotlin
class CheckoutFragment : Fragment() {

    private val threeDs2Component by lazy {
        Adyen3DS2Component.PROVIDER.get(this, context?.let {
            Adyen3DS2Configuration.Builder(it).build()
        })
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        threeDs2Component.observe(viewLifecycleOwner) {
            checkoutViewModel.performPaymentsDetails(it)
        }
    }

}
```

I know that this is the normal LiveData behavior and should be Fragment's responsibility to ignore the unwanted events but seems that there isn't a method to understand if the LiveData event should be discarded or not (please refer to https://medium.com/androiddevelopers/livedata-with-snackbar-navigation-and-other-events-the-singleliveevent-case-ac2622673150).

**Comment by moia-zsolt** [comment]
I'm having the exact same issue which results failed purchases when e.g. config (e.g. font size) change is done while being on 3DS2 Challenge.

I'm in the process of building workarounds to de-duplicate data results and errors.

**Comment by caiofaustino** [comment]
@jreij could you help investigate this?

**Comment by jreij** [comment]
Reopening this discussion, I believe we can solve this problem now. Checkout API `v67` introduces a new 3DS2 [frictionless flow](https://docs.adyen.com/online-payments/3d-secure#frictionless-flow), so starting `4.0.0`, our [3DS2 component](https://docs.adyen.com/online-payments/3d-secure/native-3ds2/android-component) will only require you to make one call to `/payments/details` (provided your backend is using API `v67`). This means that `Adyen3DS2Component` will only emit its result once and after your backend responds, the 3DS2 flow will end so you won't have to keep observing the component anymore.

In addition, we are adding a way to remove any observers you already attached to a certain component. I think these 2 changes can help manage this issue, which is essentially a limitation of `LiveData`. Let me know your thoughts.
