### ISSUE TITLE
Amount as Double/Float

### ISSUE THREAD

**Issue by badredaha** [Adyen/adyen-android#227]
Hi,

The Amount Object has an attribute "value" type Int ! how i can passe my float/double to this value ? 

ex : our API return me a price like : "99.99"

P.S: in iOS i can because the Amout object has value attribut as a Decimal object

**Comment by caiofaustino** [comment]
Each currency has an amount of expected decimals per our API
https://docs.adyen.com/development-resources/currency-codes#page-introduction

So for example for 1 euro it would be 1.00 so the int value is 100.

**Comment by badredaha** [comment]
Hi @caiofaustino,

But when the price is "28,80 euros" and i pass to the sdk the app crash because the Amount value look for Int not float ?

**Comment by caiofaustino** [comment]
In that case you need to pass an int value of 2880.

**Comment by badredaha** [comment]
and if i have a price 2880 euros ? how the sdk can make a difference between two prices : 2880 euros and 28,80 euros ?

**Comment by caiofaustino** [comment]
If the price is 2880 euros then you should pass an int value of 288000

**Comment by badredaha** [comment]
i need to multip by 100 everytime?

**Comment by badredaha** [comment]
Sorry but i dont see my real amount if i'm not multiply by 100
`
val amount = "77.4" // -> Responses from our API and i don't like this :/ 

      // Add Amount - Optional
      val _amount = Amount()
      // Optional. 
      _amount.currency = currencyCode
      val amoutDouble = amount.toDoubleOrNull()
      amoutDouble?.let {
        _amount.value =  amoutDouble.toInt()*100;
        dropInConfiguration.setAmount(_amount)
      }
`

**Comment by badredaha** [comment]
Hi @caiofaustino ,

Any news pls ?

**Comment by caiofaustino** [comment]
Hey, sorry but this is not on Android side either, we are following the convention of Adyen API. If you don't want to take responsibility of multiplying by 100, maybe you should talk to your backend team about changing your API to follow the same patter as Adyen expects.

Again: https://docs.adyen.com/development-resources/currency-codes#page-introduction

You need to multiply by a different value depending on the currency you are using. The decimals on the docs page is the number of zeros you need to add. Majority of currencies uses 2 decimals, so it's multiply by 100.

You can also take a look at our utility class to see if there is anything there you want to use to help you with this.

https://github.com/Adyen/adyen-android/blob/ad096bc684e080280b4b3cc7a62a768e4f1659e9/base-v3/src/main/java/com/adyen/checkout/base/util/AmountFormat.java

Cheers

**Comment by badredaha** [comment]
Hi,

Thx @caiofaustino
