### ISSUE TITLE
Missing proguard rules

### ISSUE THREAD

**Issue by cernfr1993** [Adyen/adyen-android#228]
Hi, I am using version Adyen Components:

"com.adyen.checkout:redirect:3.7.0"
"com.adyen.checkout:3ds2:3.7.0"
"com.adyen.checkout:googlepay-base:3.7.0"
"com.adyen.checkout:card-ui:3.7.0"

I am also using proguard. Android app will crash when calling method:
com.adyen.checkout.base.component.lifecycle.ActionComponentViewModelFactory.create(ActionComponentViewModelFactory.java:44)

Crash is only happening on release build. I added updated proguard rules for Adyen like this an app starts to work.

# Adyen
-keep class com.adyen.checkout.** { *; }
-keep class com.adyen.checkout.base.model.** { *; }
-keep class com.adyen.threeds2.** { *; }
-keepclassmembers public class * implements com.adyen.checkout.base.PaymentComponent {
   public <init>(...);
}

![image](https://user-images.githubusercontent.com/4852900/95374400-932e9e80-08de-11eb-86dd-85199144e4bc.png)

**Comment by caiofaustino** [comment]
Can you please check if the solution in #218 works out for you? We will update the Readme file soon.
