### ISSUE TITLE
Is there a way to use adyen-cardcan in checkoutdemo?

### ISSUE THREAD

**Issue by georgij** [Adyen/adyen-android#23]
I'm looking for a way to have a credit card scanner while using adyen checkout like in checkoutdemo. In iOS you can set cardScanDelegate but I'm missing a similar connection here.

**Comment by timon-langlotz** [comment]
Hi @georgij,

We offer support for this with the 'adyen-cardscan' module. You have to implement your own `PaymentCardScanner ` and`PaymentCardScannerFactory` and declare it in your `AndroidManifest` as `meta-data`:

```
<meta-data
            android:name="CheckoutPaymentCardScannerFactory"
            android:value="[com.example.yourpaymentcardscannerfactory]" />
```

You can take a look at these classes here:
https://github.com/Adyen/adyen-android/tree/master/adyen-cardscan/src/main/java/com/adyen/cardscan

Let us know if this works for you!

Timon

**Comment by georgij** [comment]
Yes, it works.
