### ISSUE TITLE
Custom tabs do not handle cancellations

### ISSUE THREAD

**Issue by andrzejchm** [Adyen/adyen-android#24]
based on the examples, specifically: https://github.com/Adyen/adyen-android/blob/a6ffee5fee6d2f35e63e7c4289cfe40613322761/customuiapplication/src/main/java/com/adyen/customuiapplication/MainActivity.java

there is no code that would handle back presses on custom chrome tabs. When a back button is pressed, the tabs close and no intent nor activity result is returned to indicate the cancellation. 

Also, if I would start custom tabs with `startActivityForResult` rather than `tabsIntent. launchUrl(..)`, then whenever the tabs close (either due to successful payment flow or cancellation) I receive the `Activity.RESULT_CANCELED` result code, so no way for me to distinguish correctly if it was a cancellation or success flow. 

Do you have any suggestion as how to handle cancellations then? I'm out of options I think

**Comment by timon-langlotz** [comment]
Hi @andrzejchm,

This is a known issue to us, and I'd recommend you to use `startActivityForResult`. Once you receive the `onActivityResult` call, give the activity some time to handle the `onNewIntent` call. If you don't receive the call within a certain time, treat it as if the flow was cancelled by the user.

Hope this helps!
Timon

**Comment by andrzejchm** [comment]
Yeah, thats exactly what I did for now :) hopefully custom tabs will allow much more fine-grained solution in the future, thanks!

**Comment by Dipak26** [comment]
How you handle if CCT close either by web link scheme or back button  Action of CCT?

**Comment by caiofaustino** [comment]
Hey @Dipak26, check Timon's answer, there is not really a reliable way to handle that back with 100% certainty.

Cheers
