### ISSUE TITLE
UI issue: screen blinks black after payment

### ISSUE THREAD

**Issue by SemenovAlexander** [Adyen/adyen-android#25]
Hi guys, thanks for great and easy to use SDK!

We've experienced UI defect in the SDK. 
After a user makes payment - success/fail no matter, payment screen turns black for a while and then returns to the previous screen. 
Please, see attached video for more context.
https://youtu.be/uOU_WwVjndA

**Comment by timon-langlotz** [comment]
Hi @SemenovAlexander,

thanks for reporting this issue! We haven't seen this behavior before, could you give us some more details about the setup of your app (themes that you use, etc.) and verify that you don't have "Don't keep activites" enabled in the developer settings?

Cheers,
Timon

**Comment by SemenovAlexander** [comment]
Sure, 

app uses `Theme.AppCompat.Light.DarkActionBar` theme with only colors modifications, and that activity has only softInputMode flags in manifest. 
`android:windowSoftInputMode="stateAlwaysHidden|adjustResize"`.

For Adyen SDK - we use provided ui.
"Don't keep activites" is disabled, double checked.

**Comment by timon-langlotz** [comment]
Hi @SemenovAlexander,

could you let us know if you are still encountering this issue on 2.x? If so, please reopen this issue!

Cheers,
Timon
