### ISSUE TITLE
UI customization

### ISSUE THREAD

**Issue by SemenovAlexander** [Adyen/adyen-android#26]
It's not clear, how can I customize default provided UI, e.g. change colors.

For iOS, there is `AppearanceConfiguration` object, which allows such stuff.

**Comment by timon-langlotz** [comment]
Hi @SemenovAlexander,

there is currently no appearance configuration on Android, but we are working on an update of the SDK where this will be included. Keep you posted!

Timon

**Comment by SemenovAlexander** [comment]
Thanks for answer @timon-langlotz,

thats actually critical for our app integration, do you have any estimates for make this happen?

**Comment by timon-langlotz** [comment]
Hi @SemenovAlexander,

For our checkout mobile SDKs, we have two ways of integration: 
- The quick integration, where you take an out-of-the-box UI
- The custom integration, where you build your own UI. 

With the custom integration, generally everything is possible. So the answer I'm giving here is regarding the quick integration:

1.  Possible in the current SDK by overriding the resource `R.string.creditCard_title`, currently not possible in the upcoming SDK.
2. Possible in both SDKs by overriding resource.
3. Not possible in both SDKs, and not likely to be added.
4. Not possible in current SDK, upcoming SDK will use default AppTheme colors, and it will also be allowed to override the theme if the AppTheme colors do not match.
5. The upcoming SDKs will support removing one-click payment methods. Both SDKs support adding one-click payment methods. With the new SDK, you will be able to whitelist / blacklist payment methods from your backend when making the initial call per payment.

With your requirements, it looks like the custom integration will be more viable for you. 

You can also take a look at our direct API integration (https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v32/paymentMethods).

Hope this helps!
Cheers,
Timon

**Comment by SemenovAlexander** [comment]
@timon-langlotz thanks a lot for such detailed answer. 

Yes, it seems we should go with custom integration. 
I have one last question:

Is it possible (I guess not, can't see in resources) with quick integration to change payment method names, e.g. "Credit Card" -> "Credit or Debit Card"

**Comment by timon-langlotz** [comment]
You're welcome!

For credit card, we have a resource for the title of the details screen. The other strings are retrieved from Java objects.

Cheers,
Timon

**Comment by timon-langlotz** [comment]
Hi @SemenovAlexander,

we've just released version 2.0.0, and with that version you can skip the payment method selection by using `CheckoutController.getPaymentMethodHandler(Activity, StartPaymentParameters, PaymentMethod)`. Maybe useful for you!

Cheers,
Timon

**Comment by microsoftdeveloper999** [comment]
Hi @timon-langlotz , I need to change Pay button name from "Pay" to "Check Out". Please help me.

**Comment by caiofaustino** [comment]
hey @microsoftdeveloper999,

What version are you using?

**Comment by gustavomagalhaespereira** [comment]
> Hi @timon-langlotz , I need to change Pay button name from "Pay" to "Check Out". Please help me.

I have the same issue, I've tried changing resources but it does not change. Any clue?

**Comment by caiofaustino** [comment]
@gustavomagalhaespereira, this is only possible from version `3.4.1` onwards, where you can choose to not pass any value the amount, and override the default string of the pay button.

**Comment by gustavomagalhaespereira** [comment]
> @gustavomagalhaespereira, this is only possible from version `3.4.1` onwards, where you can choose to not pass any value the amount, and override the default string of the pay button.

It seems I'm using adyen-react-native@1.3.0 :/ So it's not possible to change the button text on Android, right? On iOS was not a problem

**Comment by caiofaustino** [comment]
`I'm using adyen-react-native@1.3.0` this is not an official Adyen library, we do not have support for that, sorry.

**Comment by Abhishekgarg727** [comment]
Read my answer for android adyen dropin customisation here : https://github.com/Adyen/adyen-android/issues/194#issuecomment-663880944

**Comment by ParagD-Hexaware** [comment]
> `I'm using adyen-react-native@1.3.0` this is not an official Adyen library, we do not have support for that, sorry.



> @gustavomagalhaespereira, this is only possible from version `3.4.1` onwards, where you can choose to not pass any value the amount, and override the default string of the pay button.

I am using latest one can you explain how can we override the string?

**Comment by caiofaustino** [comment]
@ParagD-Hexaware just add one of these strings in your strings.xml file and the localized files as well.
First is for no value provided, second one has the value placeholder.
```XML
<string name="pay_button">Pay</string>
<string name="pay_button_with_value">Pay %s</string>
```
