### ISSUE TITLE
Add/remove cards with SDK without payment

### ISSUE THREAD

**Issue by SemenovAlexander** [Adyen/adyen-android#27]
Hello. Is it possible to add/remove credit/debit cards for future usage with your SDK and without actual payment? We would like the user to be able to manage their cards in settings.

Maybe, by generating a fake payment request with 0 amount or something like that?

**Comment by timon-langlotz** [comment]
Hi @SemenovAlexander,

adding a card is possible with a zero authorization. You can override the pay button text by overriding the pay button string resource.
Removing a card is currently not supported by the SDK, but will be supported by the upcoming SDK.

Cheers,
Timon

**Comment by timon-langlotz** [comment]
Hi @SemenovAlexander,

we've just released version 2.0.0, so removing cards is now possible (however not without starting a payment).

Cheers,
Timon

**Comment by Trinkes** [comment]
Hello, 
Is there any documentation on how to remove the credit card?
Is there any development regarding removing the CC without starting a payment?

Best,
Fábio

**Comment by caiofaustino** [comment]
Hi @Trinkes,
You can achieve this by calling `deleteOneClickPaymentMethod` on `PaymentHandler`.
You need to start a PaymentSession to do this, which is not actually a payment yet. But it could potentially be done without user interaction if that's what you mean, although I'm not sure if that's ideal.
