### ISSUE TITLE
Adyen3DS2Component exposes LiveData

### ISSUE THREAD

**Issue by deividasstr** [Adyen/adyen-android#274]
**Is your feature request related to a problem? Please describe.**
Now observer (of error or `ActionComponentData`) passed into `Adyen3DS2Component` keeps emitting items until fragment is destroyed (also after fragment recreation #226 ). 
When using SDK I want to get the results I need (either error or `ActionComponentData`) and then stop observing the results. Especially if there is an error/cancellation and I want to retry - observe again. If I do so, I will get the latest values of error and/or `ActionComponentData`.

**Describe the solution you'd like**
`Adyen3DS2Component` exposing `LiveData` - then I can remove observers. 
Or at least provide methods for `Adyen3DS2Component` to remove error and `ActionComponentData` observers.

**Describe alternatives you've considered**
Now I use the same observers for all the checkout flow, but that made the development harder - I want to observe results only when I need it. Not being able,  made it harder to abstract the `Adyen3DS2Component`.

**Comment by caiofaustino** [comment]
Thanks for your suggestion, we will look into it during our `4.0.0` refactorings.

**Comment by moia-zsolt** [comment]
I'm having the exact same issue. Also commented on #226.

Little bit sad to see that only 4.0.0 would like to address it.

**Comment by jreij** [comment]
Reopening this discussion, I believe we can solve this problem now. Checkout API `v67` introduces a new 3DS2 [frictionless flow](https://docs.adyen.com/online-payments/3d-secure#frictionless-flow), so starting `4.0.0`, our [3DS2 component](https://docs.adyen.com/online-payments/3d-secure/native-3ds2/android-component) will only require you to make one call to `/payments/details` (provided your backend is using API `v67`). This means that `Adyen3DS2Component` will only emit its result once and after your backend responds, the 3DS2 flow will end so you won't have to keep observing the component anymore.

In addition, we are adding a way to remove any observers you already attached to a certain component. I think these 2 changes can help manage this issue, which is essentially a limitation of `LiveData`. Let me know your thoughts.
