### ISSUE TITLE
Enabling WeChat Pay and AliPay

### ISSUE THREAD

**Issue by markfili** [Adyen/adyen-android#277]
Why is there no AliPay or WeChat Pay SDK listed in the list of available payments received from the Adyen server with AP and WCP enabled in a Test account?

This is here is a list of available payment methods I receive from Adyen:

|name|type|
|--|--|
|Credit Card|scheme|
|UnionPay|unionpay|
|AliPay|alipay_wap|
|WeChat Pay|wechatpayQR|
|WeChat Pay|wechatpayWeb|

There's no AliPay menitoned in the supported payment methods found in `PaymentMethodTypes.java` class:
```
    // Type of the payment method as received by the paymentMethods/ API
    public static final String IDEAL = "ideal";
    public static final String MOLPAY_MALAYSIA = "molpay_ebanking_fpx_MY";
    public static final String MOLPAY_THAILAND = "molpay_ebanking_TH";
    public static final String MOLPAY_VIETNAM = "molpay_ebanking_VN";
    public static final String DOTPAY = "dotpay";
    public static final String EPS = "eps";
    public static final String ENTERCASH = "entercash";
    public static final String OPEN_BANKING = "openbanking_UK";
    public static final String SCHEME = "scheme";
    public static final String GOOGLE_PAY = "paywithgoogle";
    public static final String SEPA = "sepadirectdebit";
    public static final String AFTER_PAY = "afterpay_default";
    public static final String BCMC = "bcmc";
    public static final String WECHAT_PAY_SDK = "wechatpaySDK";
    public static final String MB_WAY = "mbway";
```

And all I get for WeChat Pay are these two options that are not supported:
```
    public static final String WECHAT_PAY_QR = "wechatpayQR";
    public static final String WECHAT_PAY_WEB = "wechatpayWeb";
```

Sorry if this is not a question for this repository

_Originally posted by @markfili in https://github.com/Adyen/adyen-android/issues/121#issuecomment-728131176_

**Comment by caiofaustino** [comment]
Hey there,

AliPay on mobile uses a redirect flow, so it doesn't need the SDK integration, WeChatPay is indeed `wechatpaySDK`.
To see them available depends on your account configuration and on the parameters you send to the `/paymentMethods` endpoint. Can you try setting the currency to CNY and the country to CN and see if that helps?

If not maybe send a message to adyen support, they would be more equipped to help you.

**Comment by markfili** [comment]
Hi!

Thank you for your quick response!

I'm testing with the Adyen Android Online Payments example app and I already changed to CN and CNY to get those methods mentioned above.

I've sent an email to support and will report back when they answer.

Thank you once more!
