### ISSUE TITLE
Google Pay environment is not properly set

### ISSUE THREAD

**Issue by Geschan** [Adyen/adyen-android#283]
**Describe the bug**
We created a cordova plugin for the Adyen mobile SDKs. As we went from test environment to production we had problems in getting Google Pay running.
The official Adyen documentation includes this code snippen to set the environment:
https://docs.adyen.com/payment-methods/google-pay/android-drop-in#show-google-pay-in-your-payment-form

That's what we did here:
https://github.com/foodji/cordova-plugin-adyen-sdk/blob/master/source/src/android/AdyenPlugin.java#L90

After deploying to Google Play, we got errors about an invalid token and a warning that our app is unkown.
We figured the Google Pay environment was not properly set, so we added this line and it worked:
https://github.com/foodji/cordova-plugin-adyen-sdk/blob/master/source/src/android/AdyenPlugin.java#L78

**Expected behavior**
We would expect that setting the environment on the drop in configuration would also set the environment for Google Pay accordingly.

**Additional context**
Maybe other won't run in this issue as the environment could also be set on build time depening on your build pipeline.

**Comment by caiofaustino** [comment]
Hmm interesting, maybe this needs to be better documented. It might still be interesting to have those two environments separated. Thanks for the feedback :)
