### ISSUE TITLE
Payment redirection blocked

### ISSUE THREAD

**Issue by realSJ30** [Adyen/adyen-android#285]
Payment redirection just suddenly got block stating something about cdn-psp.marmot-cloud.com, Chrome verified that RapidSSL RSA CA 2018 issued this website's certificate. Your connection to cdn-psp.marmot-cloud.com is encrypted using a modern cypher suite. The connection uses TLS 1.2.
![126610193_658426064776077_2568647971855480606_n](https://user-images.githubusercontent.com/40051655/100238565-52144b80-2f6b-11eb-8d59-c6fc4fb226c4.png)

**Comment by caiofaustino** [comment]
Hi, this looks like an issue with the provider of the payment method itself. Please contact Adyen Support for more information.
