### ISSUE TITLE
Documentation on Android Pay integration

### ISSUE THREAD

**Issue by tjerkw** [Adyen/adyen-android#3]
Hi, We want to integrate android-pay using the adyen-android SDK, but it seems it requires manual work. 

I did see this code: https://github.com/Adyen/adyen-android/tree/master/adyen-androidpay

How do we integrate it? Does it needs custom work? Where do i place the android pay certificate?

**Comment by timon-langlotz** [comment]
Hi @tjerkw,

First of all: Sorry for the late reply (here and in other issues). We'll make sure to respond quicker on GitHub in the future.

We will add Android Pay documentation shortly and post the link here once it's ready. Also we'll make sure to add the repository properly to JCenter.

Kind regards,
Timon

**Comment by timon-langlotz** [comment]
The Android Pay repository has been added to JCenter. Documentation is coming!

Cheers,
Timon

**Comment by timon-langlotz** [comment]
Closing since AndroidPay is deprecated by Google. We've however just released support for Google Pay in our quick integration.
