### ISSUE TITLE
Don't include support library

### ISSUE THREAD

**Issue by georgij** [Adyen/adyen-android#30]
Is it possible to not include support library 25.3.1? It creates a conflict in projects with different support library versions.

**Comment by timon-langlotz** [comment]
Hey @georgij,

what conflict are you getting? You can probably resolve this with [Gradle Dependency Resolution](https://docs.gradle.org/current/userguide/troubleshooting_dependency_resolution.html).

Cheers,
Timon

**Comment by georgij** [comment]
I get the usual "All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 27.1.1, 27.1.0, 25.3.1. ... " complain.

I know I can set the version I want to use in the manifest overriding others, but don't think this is an ideal solution. Just thought it wold be great if adyen would not include a particular support library version.

**Comment by timon-langlotz** [comment]
Hi @georgij,

thanks for your feedback. If we don't pinpoint a specific version, we would basically have to allow and support any version of the support library. Some of our merchants might be using version 22.0.1, while others are using 27.1.1. Then we either limit our merchants (by forcing them to use a minimum version that we choose) or ourself (by having to support version 22.0.1). So dependency resolution is the only solution.

Cheers,
Timon

**Comment by timon-langlotz** [comment]
Hey @georgij,
FYI: We've just published version 2.0.0. This version uses at least the latest support library!
Cheers,
Timon
