### ISSUE TITLE
Card Detail Capture Not showing

### ISSUE THREAD

**Issue by xmlwiz** [Adyen/adyen-android#304]
Android Drop-In integration.

I have successfully integrated the Drop-In into an iOS app.

With the Android app I can retrieve the payment methods from the server and call the DropIn.startPayments. Here is the code
in my Activity called Tariff

private void ShowPaymentDropIn(String strPaymentMethods , Integer AmountInt) {

        cardConfiguration = new CardConfiguration.Builder(getApplicationContext(),"xxxx")
                .setShopperLocale(Locale.UK)
                .build();

        Amount amount = new Amount();
        amount.setCurrency("GBP");
        amount.setValue(AmountInt);

        Intent intent = new Intent(this, Tariff.class);
        intent.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);

        dropInConfiguration = new DropInConfiguration.Builder(getApplicationContext(), intent, PoppayDropInService.class).setAmount(amount).setEnvironment(Environment.TEST).setShopperLocale(Locale.UK).addCardConfiguration(cardConfiguration).build();

        JSONObject jsonObject = null;
        try {
            jsonObject = new JSONObject(strPaymentMethods);
        } catch (JSONException e) {
            e.printStackTrace();
        }

        paymentMethodsApiResponse = PaymentMethodsApiResponse.SERIALIZER.deserialize(jsonObject);

        DropIn.startPayment(this,paymentMethodsApiResponse,dropInConfiguration);

    }

The payment methods show at the bottom of the screen but when an option is selected it crashes with the following error...

2020-12-15 15:50:16.248 14788-14788/online.bevis.poppay13 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: online.bevis.poppay13, PID: 14788
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.EditText com.google.android.material.textfield.TextInputLayout.getEditText()' on a null object reference
        at com.adyen.checkout.card.CardView.initCardNumberInput(CardView.java:283)
        at com.adyen.checkout.card.CardView.initView(CardView.java:107)
        at com.adyen.checkout.base.ui.view.AdyenLinearLayout.attach(AdyenLinearLayout.java:60)
        at com.adyen.checkout.card.DropInCardView.observeComponentChanges(DropInCardView.kt:52)
        at com.adyen.checkout.base.ui.view.AdyenLinearLayout.attach(AdyenLinearLayout.java:64)
        at com.adyen.checkout.dropin.ui.component.CardComponentDialogFragment.onViewCreated(CardComponentDialogFragment.kt:71)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:332)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8154)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

Something isn't being persisted, are you able to help?

Kind Regards

Andy.

**Comment by caiofaustino** [comment]
Hi there, can you provide a bit more information about this? Which version are you using? Does it happen on a specific API version?

**Comment by xmlwiz** [comment]
Hi,

I'm using Drop-in version 3.7.3, this is my first integration with the Adyen dropin for Android so I don't know if it is version specific , however I must be doing something wrong.

I can query my server from the client , my server gets the available payment methods from your server and passes them back to the client. When DropIn.StartPayment is called it successfully shows the options to the user. When an option is pressed it crashes with the above error when I would expect it to show the form to capture the card details. 

There is obviously a problem with my code but I'm not sure where to start. Do you have an example Android app in Java that uses your drop in component that I can study?

Kind Regards

Andy.

**Comment by caiofaustino** [comment]
Your code actually looks right to me, the NPE is happening on a part of the SDK that is not under your control in the Drop-in, so it would indicate an issue on our side, but I can't think of what could be causing it.

It looks like the inflated layout doesn't have the View it's expecting, can you maybe try to open the `CardView` class and put a break point in that `initCardNumberInput` method to see what's going on?

**Comment by xmlwiz** [comment]
Hi,

When looking at the CardView Class there are lots of symbols it can't resolve and it says that the Library source does not match the bytecode for class CardView.

I've cleaned the project and rebuilt it but the problem still persists.

Here's a screen shot in Android studio.
<img width="2560" alt="Screenshot 2020-12-16 at 15 26 27" src="https://user-images.githubusercontent.com/5020263/102368938-53a5c200-3fb3-11eb-90a4-0731cc3acfab.png">

**Comment by xmlwiz** [comment]
Hi,

Just to make sure there weren't any conflicts in my project , I created a new blank project in Android Studio the only import was the Adyen drop in and the http component to get the payment methods from the server. Exactly the same thing happened , with the same error messages as in the screenshot above.

Here is the whole of the MainActivity File.

package online.bevis.testadyen;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.util.Log;

import com.adyen.checkout.base.model.PaymentMethodsApiResponse;
import com.adyen.checkout.base.model.payments.Amount;
import com.adyen.checkout.card.CardConfiguration;
import com.adyen.checkout.core.api.Environment;
import com.adyen.checkout.dropin.DropIn;
import com.adyen.checkout.dropin.DropInConfiguration;

import org.json.JSONException;
import org.json.JSONObject;

import java.util.Locale;

import com.loopj.android.http.AsyncHttpClient;
import com.loopj.android.http.AsyncHttpResponseHandler;
import com.loopj.android.http.RequestParams;

import cz.msebera.android.httpclient.Header;

public class MainActivity extends AppCompatActivity {

    private DropInConfiguration dropInConfiguration;
    private DropIn dropIn;
    private CardConfiguration cardConfiguration;
    private PaymentMethodsApiResponse paymentMethodsApiResponse;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        StartAdyen();

    }

    public void StartAdyen(){

        String AmountToTake = "£1.50";

        Log.d("POPPAY","In function");

        if (AmountToTake.contains("p")) {
            AmountToTake = AmountToTake.replace("p","");
        } else if (AmountToTake.contains("£")) {
            AmountToTake = AmountToTake.replace("£","");
            AmountToTake = AmountToTake.replace(".","");
        }

        final Integer AmountInt = Integer.parseInt(AmountToTake);

        RequestParams params = new RequestParams();

        params.put("amount",AmountToTake);
        params.put("OS", "Android");

        AsyncHttpClient client = new AsyncHttpClient();

        client.post("http://andysky.hopto.org/poppay/getpaymentmethods.aspx", params,
                new AsyncHttpResponseHandler() {
                    @Override
                    public void onSuccess(int statusCode, Header[] headers, byte[] responseBody) {
                        String str = new String(responseBody);
                        Log.d("POPPAY","Response from Server " + str);
                        
                        if (str.equals("ERROR")){
                          
                        } else {

                            ShowPaymentDropIn(str,AmountInt);

                        }
                    }

                    @Override
                    public void onFailure(int statusCode, cz.msebera.android.httpclient.Header[] headers, byte[] responseBody, Throwable error) {
                       

                        Log.d("POPPAY","Payment Failed " + responseBody.toString());

                       
                    }

                }
        );

    }

    private void ShowPaymentDropIn(String strPaymentMethods , Integer AmountInt) {

        cardConfiguration = new CardConfiguration.Builder(this,"xxxx")
                .setShopperLocale(Locale.UK)
                .build();

        Amount amount = new Amount();
        amount.setCurrency("GBP");
        amount.setValue(AmountInt);

        Intent intent = new Intent(this, MainActivity.class);
        intent.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);

        dropInConfiguration = new DropInConfiguration.Builder(this, intent, PoppayDropInService.class).setAmount(amount).setEnvironment(Environment.TEST).setShopperLocale(Locale.UK).addCardConfiguration(cardConfiguration).build();

        JSONObject jsonObject = null;
        try {
            jsonObject = new JSONObject(strPaymentMethods);
        } catch (JSONException e) {
            e.printStackTrace();
        }

        paymentMethodsApiResponse = PaymentMethodsApiResponse.SERIALIZER.deserialize(jsonObject);

        dropIn.startPayment(this,paymentMethodsApiResponse,dropInConfiguration);

    }

}

Kind Regards

Andy.

**Comment by xmlwiz** [comment]
Hi. 

Is there any idea what is causing this problem? 

Do youn have a working android project on GitHub that uses the drop in component?

Kind regards

Andy

**Comment by caiofaustino** [comment]
Do you have jetifier enabled in your project?

**Comment by xmlwiz** [comment]
Yes, enablejetifier is set to true in the gradle.properties file.

That's OK, unfortunately my client has a tight deadline on this so sorry if I sound impatient.

**Comment by jreij** [comment]
Hi @xmlwiz, I'm trying to investigate more into your issue but I need some additional info:

- Which theme are you using for your app/activity?
- Do you have a dependency for `com.google.android.material:material` in your `build.gradle`? And if so, which version is it?
- Do you override `AdyenCheckout.TextInputLayout` or any of our styles in your app?

**Comment by xmlwiz** [comment]
Hi, 

Thanks for your help.

So that I didn't run into any conflicts I started a new project in Android Studio with a blank activity. The only dependencies are the Adyen drop in and an HTTP component so that I can get the payment methods from my server.

There is nothing overridden and I just used the MainActivity.java and activity_main.xml to display the dropin . The code for the activity is shown above. The payment methods are shown in the app but when selecting a method the app crashes with the errors also shown above. 

Are you able to start a blank app and replicate what I have seen?

Kind regards

Andy.

The Manifest.

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="online.bevis.testadyen">

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:theme="@style/Theme.MaterialComponents">
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <service
            android:name=".PoppayDropInService"
            android:permission="android.permission.BIND_JOB_SERVICE"/>

    </application>

</manifest>

The gradle.build.

plugins {
    id 'com.android.application'
}
apply plugin: 'kotlin-android'

android {
    compileSdkVersion 29

    defaultConfig {
        applicationId "online.bevis.testadyen"
        minSdkVersion 29
        targetSdkVersion 29
        versionCode 1
        versionName "1.1"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.2.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    implementation 'com.adyen.checkout:drop-in:3.7.3'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
    implementation "androidx.core:core-ktx:+"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.0.0"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.loopj.android:android-async-http:1.4.9'

}
repositories {
    mavenCentral()
}

**Comment by xmlwiz** [comment]
Hi, 

A little more information.

It would appear that Android Studio now sets up its' own theme for the project , the contents are below. 

<resources xmlns:tools="http://schemas.android.com/tools">
    
    <style name="Theme.TestAdyen" parent="Theme.MaterialComponents.DayNight.DarkActionBar">
        
        <item name="colorPrimary">@color/purple_500</item>
        <item name="colorPrimaryVariant">@color/purple_700</item>
        <item name="colorOnPrimary">@color/white</item>
        
        <item name="colorSecondary">@color/teal_200</item>
        <item name="colorSecondaryVariant">@color/teal_700</item>
        <item name="colorOnSecondary">@color/black</item>
        
        <item name="android:statusBarColor" tools:targetApi="l">?attr/colorPrimaryVariant</item>
        
    </style>
</resources>

After all of the errors about not being able to inflate the views there is this error.

Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).
        at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:243)
        at com.google.android.material.internal.ThemeEnforcement.checkMaterialTheme(ThemeEnforcement.java:217)
        at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:145)
        at com.google.android.material.internal.ThemeEnforcement.obtainTintedStyledAttributes(ThemeEnforcement.java:115)
        at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:460)
        at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:419)

So it would appear to be a theme problem. The theme does inherit from material components as follows 
 <style name="Theme.TestAdyen" parent="Theme.MaterialComponents.DayNight.DarkActionBar">

Do you have any idea how to rectify this? . I have changed the manifest and have put 

android:theme="@style/Theme.MaterialComponents">

instead of the default 

<android:theme="@style/Theme.TestAdyen">

But it still crashes.

Kind Regards

Andy.

**Comment by caiofaustino** [comment]
Hi Andy,

Maybe first try to use a Bridge theme like `Theme.MaterialComponents.DayNight.DarkActionBar.Bridge`.
Or override the style that causes the issue like this.
https://github.com/Adyen/adyen-android#common-issues

**Comment by xmlwiz** [comment]
Hi Faustino,

With your help I was able to get the Drop In component to capture the card
details, pass this to my server , process the payment with you which comes
back authorised, but now I don't know how to handle the response.

As per your documentation, I have a class that extends the drop in service.
The makePaymentsCall method gets correctly called and I complete the
payment, however then the final line of this method is.

return new CallResult(CallResult.ResultType.FINISHED, "Authorised");

That return result from the method finally ends up in your DropInService.kt
in the handleCallResult method.

At the end of this method is

if (callResult.type != CallResult.ResultType.WAIT) {
// send response back to activity
val resultIntent = Intent()

resultIntent.action = getServiceResultAction(this)
resultIntent.putExtra(API_CALL_RESULT_KEY, callResult)

val localBroadcastManager = LocalBroadcastManager.getInstance(this)
localBroadcastManager.sendBroadcast(resultIntent)}

So my question is , I must have to set up a broadcast listener in the
activity that called the Drop In component, so I can inform the user, but I
don't know how this should be done.

I'm sorry but I'm not as experienced with Android development as I am with
iOS.

Hoping you can help.

Kind Regards

Andy.

**Comment by caiofaustino** [comment]
No problems Andy, glad to help.

So actually the response to the Drop-in payment will be sent to you in the `Intent` that you passed to the `DropInConfiguration`. The Intent can point either to the Activity that started the Drop-in or to another one.

In our example app we use an Intent to the same Activity like this:
```kotlin
val resultIntent = Intent(this, MainActivity::class.java)
resultIntent.flags = Intent.FLAG_ACTIVITY_CLEAR_TOP

val dropInConfigurationBuilder = DropInConfiguration.Builder(
    this@MainActivity,
    resultIntent,
    ExampleDropInService::class.java
)
```

And is then handled like this:
```kotlin
override fun onNewIntent(intent: Intent?) {
    super.onNewIntent(intent)
    Logger.d(TAG, "onNewIntent")
    if (intent?.hasExtra(DropIn.RESULT_KEY) == true) {
        Toast.makeText(this, intent.getStringExtra(DropIn.RESULT_KEY), Toast.LENGTH_SHORT).show()
    }
}
```

**Comment by xmlwiz** [comment]
Hi,

Thanks for your quick reply.

This is great, my activity is being called on completion, however it is not
calling onNewIntent , just onCreate. From what I understand only one or the
other can be called . I have set the flag to FLAG_ACTIVITY_CLEAR_TOP like
in your example but it only ever calls onCreate.

The workaround is to call onNewIntent in onCreate and check for the value
but this is regarded as bad practice.

Do you have any ideas?

Thank you so much for your continued help.

Kind Regards

Andy.

**Comment by caiofaustino** [comment]
It will call `onCreate()` if the Intent is starting the activity for the first time, and `onNewIntent()` if it's being called again.
So you can check `if (intent.hasExtra(DropIn.RESULT_KEY)) {` on both places just in case. Which ever comes will be your result, but I assume in your case it will only call `onCreate()`, so it's fine to continue from there I guess.

**Comment by xmlwiz** [comment]
Sorry , it's me again.

Thanks to all of your help I'm almost there. I can successfully take a
payment. No problems.

What I want to do now is save that card details to stop the user having to
keep entering the card details.

I'm passing all of the fields in my payment request to store the payment
method but how do I get the client to show the previously used card details
in the drop in component?

Thanks again for your help.

Kind Regards

Andy.

**Comment by caiofaustino** [comment]
That should happen automatically, make sure you are sending the same shopper reference on the `/paymentMethods` call, and that on the result of that call there is a `storedPaymentMethods` array with the stored card present.
