### ISSUE TITLE
Error parsing payment session data.

### ISSUE THREAD

**Issue by georgij** [Adyen/adyen-android#31]
I tried version 2.0 and it fails with "Error parsing payment session data.". How can I find out what is going wrong?

**Comment by timon-langlotz** [comment]
Hi @georgij,

which endpoint are you using, `/setup` or `/paymentSession`?
Are you providing the SDK token from `PaymentSetupParameters` or `CheckoutSetupParameters`?

Cheers,
Timon

**Comment by timon-langlotz** [comment]
I looked through our logs, and it looks like your backend integration is using the `/setup` endpoint. You can keep using that endpoint, as long as you provide all mandatory data from the `/paymentSession` request. You can check our [documentation](https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v32/paymentSession) for details!

Cheers,
Timon

**Comment by georgij** [comment]
Seems I have found the problem in my response handling code. Is working now as far as I can go to the next step. Thanks for the response.
