### ISSUE TITLE
PayPal opens and closes imediately

### ISSUE THREAD

**Issue by georgij** [Adyen/adyen-android#32]
PayPal seems not to work for me. I can select it and a browser window becomes opened but it closes immediately afterwards without any message.

**Comment by timon-langlotz** [comment]
Hey @georgij,

I've checked the logs and it looks like something is not configured correctly for your merchant account regarding PayPal. Could you send an email to our support team at support@adyen.com? They have access to the configuration and can check it for you. You can give them the following additional information: 
Test PSP reference: 88X532099482037X

Cheers,
Timon

**Comment by georgij** [comment]
OK
