### ISSUE TITLE
CardView Component - Card Number Input - Card Icon Overlaps Error Icon

### ISSUE THREAD

**Issue by igortepavac** [Adyen/adyen-android#320]
Hello!

**Describe the bug**
In `CardView` component, the card number input field error icon is not clearly visible, it is overlapped by the generic card icon.

**To Reproduce**
1. Add and initialize the `CardView` component.
2. Force the card number input field to get into the error state by focusing it, writing some numbers, deleting them, and moving to the next input field.

**Expected behavior**
The error icon should be clearly shown.

**Screenshots**
![error-icon-overlap](https://user-images.githubusercontent.com/10145940/104587468-3eca5600-5667-11eb-8a88-86e14056cb53.png)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4
 - OS: Android 11
 - Browser: -
 - Version: 3.7.1 (of Adyen Components)

**Additional context**
We are using the `card-ui` dependency, version `3.7.1`. If I can provide any more details, please ask. Thank you!

**Comment by caiofaustino** [comment]
Thanks for the feedback, we will look into this asap.
