### ISSUE TITLE
CardConfiguration.Builder wrongful deprecation

### ISSUE THREAD

**Issue by tinsukE** [Adyen/adyen-android#327]
**Describe the bug** / **To Reproduce**
Constructors of `CardConfiguration.Builder` that receive a `publicKey` are now marked as deprecated with the explanation:
> Constructor deprecated since publicKey is no longer always required in favor of clientKey.

But creating a card configuration without a public key isn't possible since `CardConfiguration.Builder.build()` has this code ([3.8.0](https://github.com/Adyen/adyen-android/blob/3.8.0/card-base/src/main/java/com/adyen/checkout/card/CardConfiguration.java#L367), [4.0.0](https://github.com/Adyen/adyen-android/blob/4.0.0-alpha02/card-base/src/main/java/com/adyen/checkout/card/CardConfiguration.java#L338)):
```java
if (!CardValidationUtils.isPublicKeyValid(mBuilderPublicKey)) {
    throw new CheckoutException("Invalid Public Key. Please find the valid public key on the Customer Area.");
}
```

So, if you want to avoid the deprecated warning (call me picky, but that's what we strive for) and have working code, you need to call a constructor without a `publicKey` argument and then call both `CardConfiguration.Builder.setPublicKey()` and `CardConfiguration.Builder.setClientKey()`, even though supplying the client key should render the public key unnecessary:

https://docs.adyen.com/development-resources/client-side-authentication/migrate-from-origin-key-to-client-key#switch-to-using-the-client-key

**Expected behavior**
Public key isn't necessary when supplying a client key.

**Comment by caiofaustino** [comment]
Hey @tinsukE, sorry if this caused any confusion, and I realize now that this had been opened for a long time, so sorry for that as well.
This was a intermediate state in our implementation, the idea was to indeed make the `publicKey` unnecessary but there was a moment where it was still required. Latest versions don't have that requirement anymore.
