### ISSUE TITLE
Add payment methods only

### ISSUE THREAD

**Issue by georgij** [Adyen/adyen-android#33]
Is it possible to configure the SDK to be used to add methods only? 

1. If I have already a method I see a dialog which offers me to pay the amount (in my case 0€) with existing payment methods. This option does not make sense for us.

2. I don't want to pay 0€ but rather add a payment method for later. Can the UI be adjusted for that?

**Comment by timon-langlotz** [comment]
Hi @georgij,

1. Depending on what exact flow you would like to have, there are multiple options: Take a look at the [/paymentSession](https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v32/paymentSession) documentation, there is a parameter to disable one-click payments (see `enableOneClick`, defaults to true if not provided). Another potentially interesting parameter is `shopperReference`, if you don't include that parameter for a payment, shoppers won't see their stored payment methods. 

2. You can override our [string resources](https://github.com/Adyen/adyen-android/blob/master/checkout-ui/src/main/res/values/strings.xml) to customize text in the app.

Alternatively, you can also take a look at our custom integration. There you have the complete freedom to build your own UI.

If you are still not sure how to proceed, drop us another message and include a more detailed description of your flow. Then we'll try to find the right solution.

Cheers,
Timon
