### ISSUE TITLE
Migrate from JCenter

### ISSUE THREAD

**Issue by caiofaustino** [Adyen/adyen-android#337]
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by plastiv** [comment]
Please, include transitive `io.michaelrocks:paranoid-core:0.3.2` as well.

**Comment by jhonnyx2012** [comment]
Hi!, is there any updated in this issue?

**Comment by jreij** [comment]
Hi @jhonnyx2012, we're still working it, we'll update this issue when we have something!

**Comment by SzymonGrochowiak** [comment]
Hi, will checkout libraries also be migrated? I use `2.4.12` version. Here are my dependencies:
```
com.adyen.checkout:core:2.4.12
com.adyen.checkout:ui:2.4.12
com.adyen.checkout:core-card:2.4.12
com.adyen.checkout:threeds:2.4.12
com.adyen.checkout:nfc:2.4.12
```

**Comment by caiofaustino** [comment]
Hey @SzymonGrochowiak, yes we will also migrate v2 artifacts.

**Comment by anacicconi** [comment]
Hello 👋  I made a build scan two days ago and I was getting your libraries from Jcenter:

![Screenshot 2021-04-02 at 17 07 11](https://user-images.githubusercontent.com/6182071/113427844-0ddffe80-93d6-11eb-8810-4f9a85bbc5d7.png)

Today, I tried again and my build is failing with the following message:

`Could not find core-2.4.5.jar (com.adyen.checkout:core:2.4.5).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/com/adyen/checkout/core/2.4.5/core-2.4.5.jar`

The jar is indeed not available in this path: https://repo1.maven.org/maven2/com/adyen/checkout/core/2.4.5/

I tried a scan again and the only package coming from Jcenter is `adyen-cse`. 

![Screenshot 2021-04-02 at 17 07 23](https://user-images.githubusercontent.com/6182071/113427981-497ac880-93d6-11eb-91be-1fdc96b1500b.png)

I checked on Jcenter and the 2.4.5 version is not available anymore: https://bintray.com/adyen/adyen/adyen-checkout-core

Is this something related to the migration you're doing to maven central?

Thanks.

**Comment by anacicconi** [comment]
My code was configured to search for Maven Central first even if the jar is not ready yet. If I force to search for it on Jcenter it works again. 

jcenter {
            content {
                includeGroup "com.adyen.checkout"
            }
        }

**Comment by caiofaustino** [comment]
Hi @anacicconi, thx for the detailed information. Yes it could be related, we uploaded the artifacts to Maven Central on Friday, so there could have been an issue with that version, I'll double check to see what went wrong.

Is there any consideration on your side to update to Components/Drop-in?

**Comment by caiofaustino** [comment]
Yes indeed there were some versions which failed to upload properly. I'll try to track them down and reupload the missing files starting with your version. Although I would recommend updating to `2.4.12` if you think it's feasible as well.

**Comment by anacicconi** [comment]
Thanks for your reply @caiofaustino and for fixing the upload. The update to Components/Drop-in isn't planned right now. But we will check to update to `2.4.12` soon.

**Comment by paulinabls** [comment]
We're also having issue fetching 2.4.8 from maven.  there is no plain aar, only the one with `-sources` which we tried and results in:
```
Failed to transform ui-2.4.8-sources.aar (com.adyen.checkout:ui:2.4.8) to match attributes {artifactType=android-classes-jar, org.gradle.status=release, org.gradle.usage=java-api}.
Execution failed for AarToClassTransform: /home/runner/.gradle/caches/transforms-3/411f079c01b07b78faeea5b81cd77e6d/transformed/jetified-ui-2.4.8-sources.aar.````

We can see that all Maven artifacts were touched on 1st April 2021.
Please help, it's currently blocking our CI (and release process...).

**Comment by brahyam** [comment]
Hi @caiofaustino our CI is also failing with:
```
> Could not resolve all artifacts for configuration XXX
> Could not find ui-2.4.8.jar (com.adyen.checkout:ui:2.4.8).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/com/adyen/checkout/ui/2.4.8/ui-2.4.8.jar
   > Could not find core-2.4.8.jar (com.adyen.checkout:core:2.4.8).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/com/adyen/checkout/core/2.4.8/core-2.4.8.jar
```

We tried to use
```
jcenter {
    content {
        includeGroup "com.adyen.checkout"
    }
}
```
or force gradle to use the aar sources that are present but still get errors.

Do you have any suggestions on how to solve the issue? Or an estimated date on when the libraries will be back again?

**Comment by caiofaustino** [comment]
I'm working on the fix as we speak, I hope to be able to solve this still today if I don't get any more issues from Maven. 😅

**Comment by brahyam** [comment]
We managed to temporarily fix it using: 
```
mavenCentral {
  content {
      excludeModule "com.adyen.checkout", "core"
      excludeModule "com.adyen.checkout", "ui"
  }
}
maven {
  url "https://dl.bintray.com/adyen/adyen-v2"
}
```
But we would prefer a fix to be able to remove the exclusions and fetch all from mavenCentral

**Comment by PabblRepos** [comment]
This workaround works for us as well:
```
mavenCentral {
  content {
      excludeModule "com.adyen.checkout", "core"
      excludeModule "com.adyen.checkout", "ui"
  }
}
```
It makes sense since it forces gradle to skip mavenCentral (which doesn't contain the required `*.aar` files) and instead take the original jcenter repo.

**Comment by caiofaustino** [comment]
I've manually uploaded the missing AAR artifacts for version `2.4.12` for both `core` and `ui. 
If you are on that version, can you please try again and see if you face any other issues?

I've also uploaded the CSE module that was missing, so now all dependencies should be coming from Maven Central.

I'm trying to find a better approach to automatically upload the other missing artifacts, but if someone is also stuck let me know and I'll manually upload the necessary versions for you as well. For now I'll do `core 2.4.5`.

**Comment by PabblRepos** [comment]
I can confirm the missing AAR artifacts for version 2.4.12 for both core and ui are now available in the mavenCentral repo. I will remove the workaround in our pipelines and do a final check to see if all is well now.

**Comment by SzymonGrochowiak** [comment]
I have been trying to move to mavenCentral again today, but I still have some issue with threads dependency.
```
> Could not resolve all artifacts for configuration ':feature-impl-payment:releaseRuntimeClasspath'.
   > Could not find io.michaelrocks:paranoid-core:0.3.2.
     Required by:
         project :feature-impl-payment > com.adyen.checkout:threeds:2.4.12 > com.adyen.threeds:adyen-3ds2:2.1.0-rc08
```

**Comment by caiofaustino** [comment]
Yeah, I'm doing a follow up with the library maintainer, if he doesn't upload the old artifacts we will have to update our SDK to the latest version since that one is uploaded.
https://repo1.maven.org/maven2/io/michaelrocks/paranoid-core/0.3.3/
https://github.com/MichaelRocks/paranoid/issues/45#issuecomment-819546024

**Comment by caiofaustino** [comment]
Hey all, as of version `4.0.0-beta03` all dependencies should be available in Maven Central. 🎉 

If you need to stay on older versions, you might to manually add `io.michaelrocks:paranoid-core:0.3.2` after JCenter is down, since we don't have a way to embed it retroactively to older versions and we can't upload it to Maven Central ourselves either.
https://mvnrepository.com/artifact/io.michaelrocks/paranoid-core/0.3.2

If this is a problem to you I encourage you to reach out to Michael in the ticket linked above.
