### ISSUE TITLE
UI customization - Drop-In SDK

### ISSUE THREAD

**Issue by NunoPalma** [Adyen/adyen-android#341]
Is there any way to customize specific aspects about the Payment Methods listing or the Card Configurations? Such as introduce margins?

And as for the WebView, is there any way to control it? Such as interception its instantiation and redirect it to a fragment within the application?

If not, is there any plans for any of this features to be implemented?

Thanks in advance.

**Comment by jreij** [comment]
Thanks for reaching out.

You can override the styles to add the spacings you need. You can find the base styles [here](https://github.com/Adyen/adyen-android/blob/main/base-ui/src/main/res/values/styles.xml) and the Card component styles [here](https://github.com/Adyen/adyen-android/blob/main/card-ui-core/src/main/res/values/styles.xml).

As for the WebView question, I did not fully understand the question. Do you mean to intercept certain events while the drop-in redirects the shopper to an external web page to complete the payment? If so then I do not think this is doable now.
