### ISSUE TITLE
Toolbar color on 3DS2 Challenge.

### ISSUE THREAD

**Issue by jibraniqbal-careem** [Adyen/adyen-android#343]
**Describe the bug**
I Can't override toolbar theme on 3DS2 challenge, but it only show primary color as background.

**To Reproduce**

    <style name="ThreeDS2Theme" parent="Theme.AppCompat.Light">
        <item name="colorPrimary">@color/green100</item>
        <item name="colorPrimaryDark">@color/green120</item>
        <item name="colorAccent">@color/accent_green</item>
        <item name="android:statusBarColor" tools:targetApi="lollipop">@color/black50</item>
        <item name="android:windowLightStatusBar" tools:targetApi="23">true</item>
        <item name="actionBarStyle">@style/ThemeOverlay.App.Toolbar</item>
    </style>

    <style name="ThemeOverlay.App.Toolbar" parent="">
        <item name="android:colorBackground">@color/white</item>
    </style>

**Expected behavior**
- app bar background should be white but green(primaryColor)

**Smartphone (please complete the following information):**
 - Device: Emulator
 - OS: Android 10

**Comment by ozgur00** [comment]
Hi @jibraniqbal-careem can you try to customize the toolbar using our `UiCustomization` class as shown in the example [here](https://github.com/Adyen/adyen-3ds2-android#using-uicustomization-class)?
