### ISSUE TITLE
Android Stored Payment Methods - more setup options

### ISSUE THREAD

**Issue by MariaTod** [Adyen/adyen-android#346]
Before actually showing the list of stored payment methods there is this view:
![FirstScreen_StoredPaymentMethods](https://user-images.githubusercontent.com/13196535/108525819-2dfda780-72d9-11eb-946f-13e981173517.jpg)

Is there currently an option/setting to not show it (bypass it)? 
I want to show directly this screen: (that only shows when I tap on Change Payment Method button)
![SecondScreen_StoredPaymentMethods](https://user-images.githubusercontent.com/13196535/108525284-96985480-72d8-11eb-92c7-dbf84da1ccfe.jpg)
Please let me know if there is a way to show directly the second screen.
If there isn't can you add this option in the future?

**Describe alternatives you've considered**
Other alternative would be to remove the No button or at least to be able to change the text on the button to Pay.

(Pressing the No button actually select the card above it - I don't think this is intuitive, plus the same action happens when I tap the card item itself.)

**Additional context**
Android drop-in:3.8.2

**Comment by jreij** [comment]
Hey @MariaTod, unfortunately this is not supported at the moment. If the shopper decides to save a card, it will appear later in the first screen to enable them to do a quick payment. I don't think there are plans to change this behavior in the near future.

However, the `No` text on the button is totally not intended, the default text should be `Continue`. Can you double check that you are not overriding the string resource `R.string.continue_button` by mistake?

**Comment by jreij** [comment]
This is supported now, it will be included in the next release :)
