### ISSUE TITLE
Intent result code the same for user cancelled or successful transaction

### ISSUE THREAD

**Issue by andre-sonect** [Adyen/adyen-android#348]
When using drop-in if the user cancels by pressing back or if the transaction is successful the result code is always `0`.

**Comment by andre-sonect** [comment]
Is there a way of getting a different result depending on either user cancelled the flow or it was a successful transaction?

**Comment by jreij** [comment]
Hi Andre, currently the result code in `onActivityResult` will always be `RESULT_CANCELED` (or 0) regardless if the transaction is completed or not. However, the `resultHandlerIntent` you provide to the `DropIn.startPayment` method will only be launched if the transaction was completed, so you can rely on that to figure it out.

We are working on returning a different result code for each case with `onActivityResult` but unfortunately I don't have a specific date for when it will be ready and released.

**Comment by badredaha** [comment]
Also the cancel of 3DS 1 challenge (if user close the webview there is no event trigred). any suggestion ?

**Comment by nzakharchenko** [comment]
> Also the cancel of 3DS 1 challenge (if user close the webview there is no event trigred). any suggestion ?

We are facing the same issue. Any workaround how to implement it?

**Comment by caiofaustino** [comment]
There is no way to guarantee a cancelation has happened

**Comment by nzakharchenko** [comment]
@caiofaustino what is the expected behaviour in case when user just close WebView? Should we try to get latest payment status?

**Comment by caiofaustino** [comment]
Depends on the payment method and what kind of UX you want to provide, for cards, the payment is never completed until you call the `/payments/details` endpoint with the 3DS result, so for example in our Drop-in, if the user goes back to the app we just show the credit card form again in the state it was before, just a regular back press, if they intentionally wanted to cancel the flow they can go back to the payment methods list or try to pay again.

**Comment by nzakharchenko** [comment]
@caiofaustino I think, there is some misunderstanding with the initial question :) 
In my case, we are struggling with missing callback when user closes WebView for 3ds1 Challenge. Any ideas if we could handle it somehow?

**Comment by nzakharchenko** [comment]
@caiofaustino I've found your previous answer here https://github.com/Adyen/adyen-android/issues/98#issuecomment-524246317. I assume nothing has been changed since then?

**Comment by caiofaustino** [comment]
Yeah that's correct, nothing has changed.

**Comment by caiofaustino** [comment]
hey @andre-sonect, since version `4.0.0-beta01` we have refactored the Drop-in result to allow this canceled use case.
Refer to the example app and let me know if that solves your request.
https://github.com/Adyen/adyen-android/blob/develop/example-app/src/main/java/com/adyen/checkout/example/ui/main/MainActivity.kt#L129
