### ISSUE TITLE
PCI SAQ A Compliance if using react-native library

### ISSUE THREAD

**Issue by badoet** [Adyen/adyen-android#35]
Would like to check if we built a react-native wrapper around your library
like what this library: https://github.com/tipsi/tipsi-stripe did for stripe
will we still qualify under PCI SAQ A compliance?
and is it possible to share with me why?

**Comment by timon-langlotz** [comment]
Hi @badoet,

that will depend on how you use and integrate into our library. Generally, I would say it should be okay when only wrapping our public API of the SDK. Hope this helps!

Cheers,
Timon
