### ISSUE TITLE
Drop-in Save Card

### ISSUE THREAD

**Issue by badredaha** [Adyen/adyen-android#355]
**just to ask**

How i can handle a button save card (to get boolean value) ?

**Comment by caiofaustino** [comment]
what do you mean by handle? what is your goal with it?

**Comment by badredaha** [comment]
Get the value of the button remeber me next time ? (when the shopper switches on the Remember for next time)

**Comment by caiofaustino** [comment]
It will be automatically reflected on the JSON object you get on `makePaymentsCall` to send to Adyen, do you need it for something else?

**Comment by badredaha** [comment]
DONE Thx
