### ISSUE TITLE
Skip Payment Method Select and change EditText Colors in Quick Integration

### ISSUE THREAD

**Issue by Arthur-Tavais** [Adyen/adyen-android#36]
Hi! Is it possible to skip the Payment Method Select in the Quick Integration, going direct to the credit card screen? Also, i'm having trouble customizing the credit card screen, i can't change the edit text's text color. Is it possible to change it using Styles?

Thanks in advance!

**Comment by timon-langlotz** [comment]
Hi @Arthur-Tavais,

1. To skip the payment method selection, you can adjust your code in `StartPaymentParametersHandler.onPaymentInitialized()` to use `CheckoutController.getPaymentMethodHandler()` instead of `CheckoutController.getCheckoutHandler();` to retrieve an instance of a `PaymentMethodHandler`. I'd recommend to check whether there's more than one payment method in `startPaymentParameters.getPaymentSession().getPaymentMethods()` and `startPaymentParameters.getPaymentSession().getOneClickPaymentMethods()` (in case you add more payment methods to your app later). We might also make this the default behavior in the future.

2. By default we will use your AppTheme's text color for the EditText. You can adjust the color by overriding the `AppTheme.Checkout` theme.
```xml
<style name="AppTheme.Checkout" parent="Theme.AppCompat.Light.DarkActionBar">
    <item name="colorPrimary">@color/colorPrimaryOverride</item>
    <item name="colorPrimaryDark">@color/colorPrimaryDarkOverride</item>
    <item name="colorAccent">@color/colorAccentOverride</item>

    <item name="android:editTextStyle">@style/YourEditTextStyle</item>
    <item name="editTextStyle">@style/YourEditTextStyle</item>
</style>
```

**Comment by Arthur-Tavais** [comment]
@timon-langlotz , thanks for the quick awnser! I tried it, but i still have some issues:

1 - startPaymentParameters.getPaymentSession().getPaymentMethods() returns me a list with all the credit card flags we accept, and getPaymentMethodHandler() accepts only 1. I just want to skip the bottom fragment below where the user select the "CreditCard" method, but having all cards flags (Master, Visa, etc) available in the credit card input screeen:
![image](https://user-images.githubusercontent.com/17338355/45057146-41feb180-b06b-11e8-902c-f613b50718aa.png)

2 - I tried this, but didin't work. Am i doing somenthing wrong? i need the input text to be white, because i have a dark background on my app, and it stills black:

![image](https://user-images.githubusercontent.com/17338355/45057277-96099600-b06b-11e8-8069-126ad61af02f.png)

Here is my code in styles.xml:

    <style name="AppTheme.Checkout" parent="Theme.AppCompat.NoActionBar">

        <item name="colorPrimary">@color/blueDark2</item>
        <item name="android:windowBackground">@drawable/bg_register</item>
        <item name="colorControlNormal">@color/blueDark2</item>
        <item name="colorControlActivated">@color/blueDark3</item>
        <item name="colorControlHighlight">@color/blueDark3</item>
        <item name="colorPrimaryDark">@color/white</item>

        <item name="android:editTextStyle">@style/YourEditTextStyle</item>
        <item name="editTextStyle">@style/YourEditTextStyle</item>

    </style>


    <style name="YourEditTextStyle">
        <item name="android:textColor">@color/white</item>
        <item name="android:color">@color/white</item>
        <item name="android:colorFocusedHighlight">@color/white</item>
        <item name="android:colorAccent">@color/white</item>
        <item name="android:editTextColor">@color/white</item>
        <item name="android:fillColor">@color/white</item>
    </style>

**Comment by timon-langlotz** [comment]
Hey @Arthur-Tavais,

1. All these payment methods share the same `getGroup()` `PaymentMethod`, so if you pass this one to `CheckoutController.getPaymentMethodHandler()`, it will work!

2. Which version of the SDK are you on? With version [2.0.2](https://github.com/Adyen/adyen-android/releases/tag/2.0.2), we fixed a few theming issues.

**Comment by Arthur-Tavais** [comment]
I was on version 2.0.0. It's working now on 2.0.2! And the payment method issue is solved to with the paymentMethod.getGroup()!

Thanks!

**Comment by monwa12345678** [comment]
Hi! forgive me for my ignorance but I have been working on JavaScript and hence native android Java is still new to me. I just needed to check if the above answer is still relevant. I have used the answer and I get the below error;

> AdyenModule.java:135: error: incompatible types: List<PaymentMethod> cannot be converted to PaymentMethod
>                             paymentMethodHandler = CheckoutController.getPaymentMethodHandler(getCurrentActivity(),startPaymentParameters.getPaymentReference(), startPaymentParameters.getPaymentSession().getOneClickPaymentMethods());

If you could please provide some direction or even better an illustrating example.
Thanks!
