### ISSUE TITLE
How to override card icons to increase the icon size?

### ISSUE THREAD

**Issue by felipeajcarvalho** [Adyen/adyen-android#361]
I am trying to increase the icon size of brand card is displayed in card number field at com.adyen.checkout.card.CardView after type of card number.
I have created a style for that but is not working. It is my style:

    <style name="AdyenCheckout.Card.BrandRecognitionLogo" parent="AdyenCheckout.Image.CardLogo">
        <item name="android:layout_marginStart">24dp</item>
        <item name="android:layout_gravity">end|center_vertical</item>
        <item name="android:layout_marginEnd">24dp</item>
        <item name="android:layout_width">48dp</item>
        <item name="android:layout_height">32dp</item>
    </style>

Is there any way to increase it?

Thank you.

**Comment by jreij** [comment]
Hey @felipeajcarvalho, you cannot change the width and height by overriding the style, but you can override `@dimen/brand_logo_width` and `@dimen/brand_logo_height` instead.

**Comment by felipeajcarvalho** [comment]
Nice! It's working well now. Thanks a lot!
