### ISSUE TITLE
Adyen3DS2Component throws exception on 4.0.0-beta02

### ISSUE THREAD

**Issue by jibraniqbal-careem** [Adyen/adyen-android#372]
**Describe the bug**
initialization with null configuration gives error on Adyen3DS2Component

**To Reproduce**
initialization  Adyen3DS2Component with configuration null
`Adyen3DS2Component.PROVIDER.get(activity, activity.application, null)`

**Expected behavior**
configuration null shouldn't throw exception.

**Mobile:**
 - OS: Android All

**Additional context**
on PROVIDER.get(activity, activity.application, null) it is nullable but on internal library initialization throws this
`Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter configuration
`
Library Version : 4.0.0-beta02

**Comment by jreij** [comment]
Hi @jibraniqbal-careem, `Adyen3DS2Component.PROVIDER.get` should not allow a null configuration, we will fix this for the next release 👍 
For now you can just pass a `Adyen3DS2Configuration` instead of null, check out `Adyen3DS2Configuration.Builder`.

**Comment by caiofaustino** [comment]
Fixed by #385
