### ISSUE TITLE
Add a way to opt out from FLAG_SECURE on CardView

### ISSUE THREAD

**Issue by freszu** [Adyen/adyen-android#380]
**Is your feature request related to a problem? Please describe.**
While integrating the Adyen CardView i realized there is no way for me or other team members to take any screenshots. We have our own security util that is integrated on this screen and is inactive for our dev builds. 
**Describe the solution you'd like**
Add a way to disable FLAG_SECURE call in CardView:
https://github.com/Adyen/adyen-android/blob/ada45bdedd5f565208dc57d623b1b22d04509d11/card/src/main/java/com/adyen/checkout/card/CardView.kt#L57
Potentially this could be a simple boolean preventing this call if requested.
**Describe alternatives you've considered**

Edit: not possible view is final: 
Extending and overwriting
1. Not calling supper - not perfect call to super is expected by framework
2. Clearing the flag right after calling super - this is incompatible with our utils and overall not great approach

**Additional context**

**Comment by caiofaustino** [comment]
Would it be sufficient for you if the flag is not set on DEBUG builds?

**Comment by freszu** [comment]
@caiofaustino yes would be good for me - its quite debatable which approach is better having some bool property vs debug check i see both equal having with different pros and cons.

Overall its first time i came across widget playing with these flags usually i was responsible for setting them even when integrating other payment processors widgets in the past - not that i see anything wrong with adyen doing that 👍

**Comment by caiofaustino** [comment]
Thx for the feedback, I think the main philosophy in this decision was to provide security features by default where merchants might not know or care about. We would surely consider changing this approach if there is any relevant use case where someone would want to disable this.

We'll make a PR for this in the coming beta release.
