### ISSUE TITLE
Proguard rules for 2.0.2

### ISSUE THREAD

**Issue by tufyx** [Adyen/adyen-android#39]
Hi,

Could you please provide proguard rules for version 2.0.2 of the SDK? Thanks!

**Comment by timon-langlotz** [comment]
Hi @tufyx,

We have released version 2.0.3 on jCenter, and we'll shortly release an update here as well with new ProGuard rules. In the meanwhile, you can use these rules here:
```proguard
-keep class com.adyen.checkout.core.** { *; }
-dontwarn com.adyen.checkout.nfc.**
-dontwarn com.adyen.checkout.googlewallet.**
-dontwarn com.adyen.checkout.wechatpay.**
```

Regards,
Timon
