### ISSUE TITLE
RedirectHandlerActivity CustomTab doesnt work well with Banking Native Apps such as ING and Rabobank

### ISSUE THREAD

**Issue by tjerkw** [Adyen/adyen-android#4]
If i use the default RedirectHandlerActivity
for opening ideal pages to banks, then it doesnt open the natively installed apps for the following banks:
- Rabobank
- ING

It seems that the customTabs doesnt work well with opening the native banking apps.

I'm now using the following code:

`       // W're not using custom tabs, it doesnt work with native banking apps such as ING and RaboBank
                Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse(redirectUrl));
                intent.addCategory(Intent.CATEGORY_BROWSABLE);
                mContext.startActivity(intent);
`

Instead of the recommended code:

`
                CustomTabsIntent.Builder builder = new CustomTabsIntent.Builder();
                CustomTabsIntent customTabsIntent = builder.build();
                customTabsIntent.launchUrl(mContext, Uri.parse(redirectUrl));`

Could you update RedirectHandlerActivity to use this as well?

**Comment by timon-langlotz** [comment]
Hi Tjerk,

thank you for reporting this issue! We'll investigate and adapt the `RedirectHandlerActivity` to handle `Uri`s for installed apps with `Intent.ACTION_VIEW`, if applicable.

Have a good weekend,
Timon

**Comment by timon-langlotz** [comment]
Hi Tjerk,

this issue should be resolved when users have selected a default app (other than the default browser) for a given app URL.

Kind regards,
Timon
