### ISSUE TITLE
Issue in handling redirects or completing 3D Secure payments on Android

### ISSUE THREAD

**Issue by koklitheen** [Adyen/adyen-android#41]
Hi there,

We are in the midst of completing payment integration for an Android app (native Adyen checkout UI). 

We *urgently* need some direction on where we can find documentation either on handling redirects or completing 3D Secure payments on Android. We have tried looking for it at both your Android SDK Guide as well as your repository.

In the iOS SDK Guide, there is a section on handling redirects which would have the app call `Adyen.applicationDidOpen(url)` method. There is no such section in the Android SDK Guide.

Is there an equivalent on Android? Based on our experience dealing with other SDKs which require redirects handling, we minimally need to have an activity declared in the project's manifest with intent filters to handle incoming links. In our case, we would minimally have to have an entry in our app's `AndroidManifest.xml` to handle the link specified as the `return_url` parameter when preparing payment session.

I saw that there is a RedirectHandlerActivity in the checkout-ui package. In the `PaymentHandler` interface, there is also a method named `handleRedirectResult()` which takes in a URI. Should we be using any of these? If not, how can the Android app handle the response payload and result in the returning intent's data?

Thanks in advance for your help.

**Comment by koklitheen** [comment]
Alright, we figured it out (I think).

So it seems that the way to handle it is to observe the payment result using the payment reference's payment handler.

```
...

val paymentHandler = this.paymentReference?.getPaymentHandler(this) ?: return
paymentHandler.handleRedirectResult(this.intent.data)
paymentHandler.paymentResultObservable.observe(this) { paymentResult ->
    // TODO: Here's where we get to handle the payment result
}
```

Is this the way to do it...?

**Comment by timon-langlotz** [comment]
Hi @koklitheen,

In the quick integration (using our drop-in UI), you just need to forward the return URL from `CheckoutSetupParameters` that is generated  by `CheckoutController.startPayment()` together with the SDK token to your backend and create the payment session with that specific return URL.
 
I assume however that you are doing the custom integration where you build your own UI, is that correct? Then you need to:

- Select a custom return URL
- Create the payment session with that return URL
- Declare an Activity in the AndroidManifest that handles that return URL.
- On the PaymentHandler, set a redirect handler (`PaymentHandler.setRedirectHandler()`) that is responsible for performing the redirect to an external app.
- When the activity receives the redirect result Intent, call `PaymentHandler.handleRedirectResult()`.
- After that, you will get a callback to `PaymentResult Observable`

Hope this clarifies things?
Cheers,
Timon

**Comment by koklitheen** [comment]
Hi @timon-langlotz,

Thanks for your response. 

Are you saying that we do not need the extra steps if we are not building our own UI?

In fact, we are using the drop-in UI and not building our own. And because of that, we are already creating payment session with `CheckoutSetupParameters` and `CheckoutController.startPayment()`.

The issue we faced are only for cards that issue a 3D Secure challenge. What we have found is that even with using the drop-in UI, we still need to do the extra steps that you listed in your reply for the app to get the payment result from the return URI. 

If anything, I think perhaps the documentation/guide for using drop-in UI is missing a section on handling redirects? :)

**Comment by timon-langlotz** [comment]
Hi @koklitheen,

are you forwarding both the SDK token **and** return URL to your server to create the payment session?
- If that's the case, could you please send an email to support@adyen.com and, provide the merchant account that you're using, and mention my name? Then we can check the logs to see what's going on. 
- If not, please make sure to use both parameters when creating the payment session. That should solve the issue.

Regards,
Timon

**Comment by koklitheen** [comment]
Hi @timon-langlotz,

Somehow I think we might be talking about different things here. We have no issues creating the payment session.

My question was more of how the Android app should handle redirect returns from banks (e.g. 3D Secure) as the guide and documentation doesn’t mention explicitly like how the iOS version of the guide does. Based on what we know so far, regardless of whether we are using the drop-in UI or custom integration, we do have to set up the app to handle receiving of incoming links (return URL), etc.

I think at the end of the day, it’s more of the lack of documentation that is the real issue here. However, since we have already figured this out on our end, I think I’ll just close this for now. Thanks for your effort responding. :)

**Comment by timon-langlotz** [comment]
Hi @koklitheen,

the SDK is built in a way that you don't have to do anything for redirects in the quick integration, as long as you create the payment session with the return url that is generated by the SDK. Since you have to set up handling of return URLs, I assume that you currently specify the return URL manually. What return URL are you using? Just want to make sure that everything is working as expected! 🙂

It's true that our documentation is lagging a bit behind. The most recent documentation can be found in the README of our GitHub page. The documentation on [docs.adyen.com](https://docs.adyen.com/developers/checkout/android-sdk) will be updated shortly. Sorry for the delay.

Cheers,
Timon

**Comment by Kush88** [comment]
Hi @timon-langlotz ,

I'm having the same issue as koklitheen with android adyen sdk 2.4.3 (works fine on iOS) using quick integration. I pass up both token and return url fields that are generated by the sdk. Decoding the returned payment session i can see that the return url field is set (of format checkout://<app identifier>). Using the 3DS test cards results in a spinner being shown briefly on the card entry page and then nothing.

Don't know if this means anything, but, every time **checkDispatch** method in **BaseManager** class was called, the handlers list was always empty even if there was data available.

**Comment by caiofaustino** [comment]
Hi @Kush88 , could you please try to explain in more detail on which part of the flow that happens?

My understaning is that you: go to the card entry page, put the card details, click pay, get redirected to the bank page/app, make the 3DS authentication, then it comes back to the card entry page with a loader.

After that the loader keeps spinning and nothing happens? The loader shows briefly and disappears and you stay in the card page?

Cheers

**Comment by Kush88** [comment]
I don't get redirected to any page. I hit the pay button, spinner pops up and then disappears.

**Comment by caiofaustino** [comment]
And you don't see any error message on the Logcat either? That's weird, I'll investigate a bit and come back.

**Comment by Kush88** [comment]
Logcat was set to show selected app related messages only so i didn't see this :

duplicate layer name: changing {package name}/com.adyen.checkout.ui.internal.card.CardDetailsActivity to {package name}/com.adyen.checkout.ui.internal.card.CardDetailsActivity#1

**Comment by RuudBurger** [comment]
We are trying to implement 3DS and are having the same issue and see the exact same thing that @Kush88 is mentioning above (spinner for brief moment and then nothing). Using one of the non-3ds-testing credit cards, the payment goes through fine on both platforms.

While typing this comment a colleague of mine figured out the problem:
To test I was using one of the "3d secure 2" cards, which worked fine on iOS, but not on Android. So @Kush88 please check that you are using one of these cards: https://docs.adyen.com/developers/development-resources/test-cards/test-card-numbers?redirect#3dsecure1testcards

**Comment by taknuti** [comment]
Colleague here :). Note that additionally, for the 3d secure 1 cards it seems that only the ones with a matching country work, so the first one marked 'International' or one of the other ones if the country happens to match yours. Also, the Card Type 'International' is still limited to one country...

By the way, the 3ds2 cards might work with the specific amounts listed there, but we cannot easily test that currently.

**Comment by Kush88** [comment]
Well spotted. Yeah I was using the 3ds 2 test cards. Using 3ds 1 cards do redirect to me the auth web page provided, like you said, the country matches. I tried specific amounts with the 3ds2 cards but no luck.

**Comment by tlupo** [comment]
Hi !

I have the same issue : 3D Secure 1 test cards OK for iOS and Android (with redirection to the auth web page), 3D Secure 2 test cards only OK for iOS (on Android, spinner after filling the form and no redirection or error message). 

Is it only an issue with test cards or is it also an issue in production environment with real cards ? 

Thank you very much for your help

PS: I use Android SDK version 2.4.9 and I don’t plan to move to the new Drop-in implementation for now.

**Comment by tlupo** [comment]
Hello ! 

Here is a screen recording of my Android application with two tests : https://we.tl/t-5SvFbvN3XG

1/ 3DS Secure 1 test card (spinner and redirection OK)

2/ 3DS Secure 2 test card (spinner and no redirection, no error message)

Hope it helps. Thank you very much !

**Comment by caiofaustino** [comment]
hey @tlupo,
Do you have the 3DS2 dependency added to your project? It's an optional dependency so you have to add it manually.
`implementation "com.adyen.checkout:threeds:$versions.checkout_sdk"`

**Comment by tlupo** [comment]
Hey @caiofaustino 

I have added the 3DS2 dependency in my project 

`final checkoutVersion = "2.4.9"`
`implementation "com.adyen.checkout:ui:${checkoutVersion}"`
`implementation "com.adyen.checkout:threeds:${checkoutVersion}"`


3DS Secure 1 test cards are still OK but there is a now a crash for 3DS Secure 2 test card. Here is the stack trace:

`java.lang.RuntimeException: Unable to resume activity {com.package.name/com.adyen.checkout.ui.internal.common.activity.CheckoutActivity}: java.lang.RuntimeException: Class c does not declare constructor with arguments [class org.json.JSONObject].
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3828)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3860)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: java.lang.RuntimeException: Class c does not declare constructor with arguments [class org.json.JSONObject].
	at e.a.a.a.a.m.a(Unknown Source:142)
	at e.a.a.a.a.h.parseFrom(Unknown Source:6)
	at e.a.a.a.a.f.decodeFrom(Unknown Source:4)
	at e.a.a.a.a.b.a(Unknown Source:0)
	at e.a.a.a.a.b.a(Unknown Source:1)
	at e.a.a.b.b.a(Unknown Source:2)
	at com.adyen.checkout.ui.internal.common.activity.s.onAuthenticationDetailsRequired(Unknown Source:113)
	at com.adyen.checkout.core.internal.AuthenticationManager.dispatch(Unknown Source:0)
	at com.adyen.checkout.core.internal.AuthenticationManager.dispatch(Unknown Source:4)
	at com.adyen.checkout.core.internal.BaseManager.checkDispatch(Unknown Source:21)
	at com.adyen.checkout.core.internal.BaseManager.access$200(Unknown Source:0)
	at com.adyen.checkout.core.internal.BaseManager$ActivityScopedHandler.onActive(Unknown Source:14)
	at com.adyen.checkout.core.internal.lifecycle.LifecycleFragment.onResume(Unknown Source:30)
	at android.app.Fragment.performResume(Fragment.java:2568)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1341)
	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1642)
	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3051)
	at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3013)
	at android.app.FragmentController.dispatchResume(FragmentController.java:204)
	at android.app.Activity.performResume(Activity.java:7427)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3820)
	... 11 more
Caused by: java.lang.NoSuchMethodException: <init> [class org.json.JSONObject]
	at java.lang.Class.getConstructor0(Class.java:2327)
	at java.lang.Class.getDeclaredConstructor(Class.java:2166)
	at e.a.a.a.a.m.a(Unknown Source:20)
	... 32 more`

We are maybe on the right track with this new issue ! Thank you very much for your help !

**Comment by caiofaustino** [comment]
Is that in debug or release builds? Looks like a Proguard issue. Maybe you have any other dependency that comes obfuscated?

**Comment by tlupo** [comment]
You were right @caiofaustino It was a Proguard issue after adding the 3DS2 dependency in my project.

I solved this issue by adding this line in my proguard configuration (your comment saved me : https://github.com/Adyen/adyen-android/issues/82#issuecomment-510436323) :

`-keep class com.adyen.checkout.threeds.internal.model.** { *; }`

Thank you very much for your help :)

**Comment by okvaishakh21** [comment]
@koklitheen can you explain how you resolved this payment redirection issue
