### ISSUE TITLE
when release 4.0.0 version

### ISSUE THREAD

**Issue by forrestzhang234** [Adyen/adyen-android#412]
we should support android x and modify some drop-in part code custom ui.

so we base on beta03 code develop.

when  release 4.0.0 version

**Comment by caiofaustino** [comment]
Stable version 4.0.0 will be the next release, we are just finishing up the last changes. Hopefully release will be in a few weeks.

**Comment by trebouillon** [comment]
Hey, any updates on version 4.0.0 release date?

**Comment by jreij** [comment]
@trebouillon great timing! We're releasing today 🤞

**Comment by trebouillon** [comment]
Oh nice, then I will wait for it and skip the manual jetifying 😄

**Comment by caiofaustino** [comment]
Ahh I was gonna tease him to "keep an eye on your inbox" 😆

**Comment by trebouillon** [comment]
Ah, the release is there. Upload to Maven is in progress? :)

**Comment by caiofaustino** [comment]
Yeah the sync takes a bit, but seems to be live now :)
