### ISSUE TITLE
Dropin 3DS1 flow implementation

### ISSUE THREAD

**Issue by peterMonteer** [Adyen/adyen-android#414]
I'm working on implementing the 3DS1 using drop in. When I'm testing the implementation I'm being redirected to a browser that displays this:

<img width="316" alt="Captura de ecrã 2021-06-16, às 13 04 16" src="https://user-images.githubusercontent.com/28009502/122241024-22527400-ceba-11eb-94ec-5cce8c346173.png">

I can't figure out the root of this problem. For reference the flow i'm using is:

make the /payment call ---> return the call result (in this case, with a type ACTION and with the action object) --> the adyen SDK redirects to a browser (screenshot)

I'm pointing this out because from what I've read in the docs and the example app, the flow for 3DS2 is different, in that before redirecting to the browser, an additional call to /payment_details should be made.

Any help would be much appreciated

**Comment by caiofaustino** [comment]
hey there, 

>I'm pointing this out because from what I've read in the docs and the example app, the flow for 3DS2 is different, in that before redirecting to the browser, an additional call to /payment_details should be made.

Not really, the `/payment/details` call is made only after the redirect comes back from the browser.

I think the issue here might be in the `returnUrl`. Are you passing the one provided by us? `RedirectComponent.getReturnUrl(appContext)`

**Comment by peterMonteer** [comment]
The `returnUrl` seems fine, it currently is adyencheckout:// + the app package name and sent to our backend.

But since you mentioned I did some digging, and found out in the response we receive from adyen there is a `TermUrl` that should match the `returnUrl` we send right?

**Comment by caiofaustino** [comment]
No not really, can you please share the `action` object that you received? It should have type `redirect` and method `GET` but I think you might be getting `POST` for some reason.

**Comment by peterMonteer** [comment]
Yeah we are getting a `POST`

```
"action":
        {
            "paymentData": "Ab02b4c0!BQABAgB0besB0Gg90e6IKEno61wseKbTfhjSCG7zqI1tuyzYIiSn0riTAjm9G8d3a6Z6qPRszj+gFa6PzsEb5nijOy4fhk5GMAphJMY3k089fNIifeX/QsoJGhfxFIPSK2mlGGNP795MshXMRj1wieV8Ln7IFhNxZ7U9xvCd4f0N7+9rBZ/yhz+zdJJI8A+NxN7ugajKf37cF4CKMiBFsuO6c9bN68nTC56CJI0QK5Pvw6E8BnRPgc3GMMpiA5G3tdx1KYolgNMj0/vECx1v4JT8VsjwmRIvJFoxsoceKBHs+ZkH3A0M0lWjKRhBrQ49PDdZ4uv5fRV50uesexSUSsIvoGy1h536F0QSmKI+nfTQ26z01IxPjkfYCOAS/7VMc1Rzt32aFnPDvZbQpJI6y0QQiIL5WAZPO/NYrLPXpLXKsQUf7xcdujxD0YgFRb6UhHOsNRAxaNNZ6zkH2zABNjYDu2LqZo2LK395jD8nR4AQtx45OhfUJcyhxqakHZgnNKUxi5UvUafFc6g/UaIncppFY9s/vJ8sUOQwxM4D9hEbEHsA9+r8oQHB9uVlZYzJCEV5wePKBDEYw9fzQswAO2V8p3KC8KdV3cRezUaDtO54fK/FCxrZeFTMblQb9WcCYJB22fO0+GPPYVfrU/oW7PFX2w2aRFZ7izt1deneofO0biQbtBCRjHZ5OHYhXykJ3D/SeZdKAEp7ImtleSI6IkFGMEFBQTEwM0NBNTM3RUFFRDg3QzI0REQ1MzkwOUI4MEE3OEE5MjNFMzgyM0Q2OERBQ0M5NEI5RkY4MzA1REMifSr6dFAIyurvAtlBwRc7d1VRcq1xBiypE62pLIH7DoRcbXkLrJX9j2HPvH26cLqWciJ7ZkHTLz9tv6JrbZGh5AFIgfaszKjU22QY2H8W3rTaAqiGQUTc6mQXmMFSL1jUslTP0daFop490FSnsUJ/iuigFkXdzLxmw49CuEdD1OxooA7dD65tUmoDNN2uPN3RMz5EfTctbX2FEVPnRPF326Xyghr/sk+QYf2kwkYyq8SfvV9beT4dGp4eW8OLtGAYXd3OmgwFadOXHObriW5l+o+qOn6ZAbX8COjkHticSsg7LdzAEKkS1fiGC9mr9i+AyD9BKNsQeDvSOkwMlguPV3BPDP1PRxELbmJE1429hS0cqkoJRR/HQYfpvcPd9OpAPqyyNeSL0krs4M0Deul/qsyjnC+wVQ8sComprc96fG+kcFkldaCkt3c3g5iuGomx3dHXfy3kidf0jIxazKb2G4/9HmcdZLrbxQ+f52ccdZ3zd8riec1Iv/Bf9qEoq5v4kG8L2UW6put4z3ReQG03gAVdAsli62vQNEasEB/UQVUBbemXDeuzsuk1vEZoLMXMk30jJ8U2rWr0FrfWhXyg6hkg9yYmzaHUlWD548s0Jp+lg+RFZJksHEbnjFKm4XxxyT3+SUOmZV3TRm4AjfHVvrb1GB4OUvf+/eos81ZWqXykXqWBASvXfuv3/YPwbeIOJ+zWTptoAo1HRioPbElHkyaa5FiVb02QWcIXAY+tUtAL2GmSdxsQP3VpVGB1yMET7qIbaVanjxEFH4pd6sUtrCu82bfbRYrMsfkqP7uV1HVMcdoXvKlBlr6m1Lx2oGZpbUltG3tOe4HvfQyMZLItiIzre/glMLAkXU2fdt96Uny4sxgOpCYLhzIH4W8kqOpgptsQorhHrPirtwftbO28YJx/cXrKpljjgLt7opF86d8EGKeoUn8JWcCfMGmlk5unoqt+HuW9XoTw+V/1Ovk3ZKp4XMbz2ffxTH3ATB4fS5tHP0eKbEyQ4tT9maS3REFhknZ2YAJW8YZiVJlh79wMqPV2uA0M9lbBDhnfU1vN8jwpZiRj7zc6IMNqQd1xW6WY6VQpVV7ED17OSmpS4deJ3RVSQGl4J3xIk8DKbyEYrttw0un0JiSrNNXh1U/4fW+W+n7/NSyycoGkWqYw4bSEAUUU8mIjR6igzQV4/d21QDtrg8CW1f3RKOM/immkvo+N0BmArAbWy5aiIRV4D26g+ZHyYgO1dAJkOvV5itt3kPS1a+Kj+qC2kmuhhyxsg5tAxk+E5dJ+vsrmRQQydFDeEUURYzxtxYnmZqJis3I8gjWe7eg6cLLTA3ANL48cT0HIDnSG3Bm16saPQzFN+phf19T4DHbfdFHc2jE7W6d8b0LXuUs5SU+7IvA9yh+RiuEUc11jyrLIrimwuNluI+Siv7kbHYY4esvzppBPOOPZc3iv6wX15CTKGmMgXilUpYxKUi1Lss9S4ppWFtTjT190w6bhSlR5mdqdvM++lAGEW7WQetvZ3bnuOqF8JxFtEvgnkmOnD9/E+RDlSBV6JX+ebIN09LcGxqY/D5Gh9islS3i/c1uJTSRdufeJ3b69jEedAETy+DsWrToScWkld0Uo8dcJGM+edDsxpy4FZKF1yVO1d6EJmsXK6wJubKlp7Ro/w5M+F00whQZoid2qbf5XRdorOaLT8cUBOd6pKJkzMV1xyOSNQVhEfvHAngpv",
            "paymentMethodType": "scheme",
            "url": "https://test.adyen.com/hpp/3d/validate.shtml",
            "data":
            {
                "MD": "Z3VyOUx3MlBQNndvYnFQUUxsZ2FFUT09ISy_aVz-f2Nb6DwMXDdPo-tOd1pF4I2VUrVw6zxkfKYwdD6iyIG5IzC9TBF0_sdoI2mckN_EkllqpHgty6WSQNw2iSBXipASgUUY1UaQffc-XKGd5_3bYlyhCyUc2X0OMCbPlWX5hTVdQ84_OoQsJqGlVEIH2oqc9EF6-bcGAZ-2-MTGeXyWfu5l7zMpXVArg0ZaVUGK5Sdp1Fw82Nr8YHqeFq5OMcS4RtRWWDgqlXplUaI7v94jikMVE22y54MpttZrXPHtvd-Cay4G4urQ94e3AihExfWfgWSkipOi5oJ_owWxChCxDb9lCus1Fu-mEZFLr6bilN2NGav5tRZ1nItMUka8HDsh5P_WZqwBaIXpxIQdhfFa8qjJZDtAL66pMMbe-Xb0r5qzLb5HNKSDsQ",
                "PaReq": "eNpVUdtuwjAM/RXGBzRJUwJUJlKhk8YmLuPywNNUBQsKawtpu8K+fkkpY/OTz3GO7RzDaq8RwyWqUqOECeZ5tMNWvB20/Z5whct7HmWCCs5e2xLmwQLPEr5Q53GWSuZQxwVyh0au1T5KCwmROg/HU9lhLveANAgS1ONQrjAv5kkSqHMZa9RAbjSkUYJyHXwEoyf/Lc2Oo0jjcAGk5kFlZVroqxQuBXIHUOpPuS+KU+4TUlWVczQ6ZXSOyhIgtgrksdW8tFluul3irZyFm+v0MP6ehe/VZLWppofJZbkLbAyA2BewjQqULnUZFUy0GPU91/fM/JqHKLFryOf1osU7DjV8w8DJDgpugHds5S8DxmyNqbrKfrdnPnNHgJdTlqJ5YUz9zYE81h69WGtVYewS3S7rcdq3YVzuW5frgu0SG284pbxuYwEQKyXN/UhzZ5P9u/8Psnisvg==",
                "TermUrl": "https://backend-staging.knokcare.com/api/v3/patients/integrations/adyen/shopper_redirect?appointment_id=1&return_url=adyencheckout%3A%2F%2Fcom.knokcare.knok_patients.staging"
            },
            "method": "POST",
            "type": "redirect"
        }
```

**Comment by caiofaustino** [comment]
That shouldn't be the case, maybe there is something wrong in your `/payments` request or some configuration in your account. For that maybe you should contact our [Support](https://support.adyen.com/hc/en-us/requests/new?ticket_form_id=360000705420).

Or you can try to force this behavior by specifying the [redirectFromIssuerMethod](https://docs.adyen.com/api-explorer/#/CheckoutService/v67/post/payments__reqParam_redirectFromIssuerMethod) and [redirectToIssuerMethod](redirectToIssuerMethod) parameters in your call as well.

**Comment by peterMonteer** [comment]
It was a configuration from our side! Thanks for the help @caiofaustino, everything is working perfectly 👍
