### ISSUE TITLE
Stored payment card requires name but no field rendered

### ISSUE THREAD

**Issue by DaveBathnes** [Adyen/adyen-android#418]
Hello, we are integrating the Android DropIn components into an app. Payments with new card details work fine, we are also choosing to allow saving of card details.

We are not able to complete a payment using stored card details. This looks like it is due to passing true to setHolderNameRequired. 

```
cardConfigurationBuilder = cardConfigurationBuilder.setHolderNameRequired(true)
```

When we attempt to pay with a stored card the pay button is active but does nothing after entering the CVV/CVC code. Changing the setHolderNameRequired to false fixes the issue but I believe we need to collect the cardholders name. How do we get round this problem with stored cards?

Using v4 beta.

```
implementation 'com.adyen.checkout:drop-in:4.0.0-beta03'
```

Note, this looks almost identical to this issue from a couple of years ago, other than the fact the Pay button does remain active, it just doesn't do anything: https://github.com/Adyen/adyen-android/issues/95

**Comment by jreij** [comment]
Hi, thanks for reaching out! I can also reproduce the issue, I will make sure we fix it ASAP and include it in the next release.

**Comment by DaveBathnes** [comment]
Thanks very much @jreij I can see the fix was done very quickly.

We're just testing at the moment, we've temporarily changed to not using the holder name required option, to complete the majority of our tests. Do you have an idea of when this will go into a release though? Would be good to get ASAP!

**Comment by jreij** [comment]
@DaveBathnes sure! I don't have a specific date but we're releasing in the next few weeks 🙂
