### ISSUE TITLE
Fix deprecated onActivityResult API

### ISSUE THREAD

**Issue by kostya29-strikersoft** [Adyen/adyen-android#424]
Please fix deprecated onActivityResult API for Payment handle intent result call

override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        val dropInResult = DropIn.handleActivityResult(requestCode, resultCode, data)
.....
    }

  /**
     * {@inheritDoc}
     *
     * @deprecated use
     * {@link #registerForActivityResult(ActivityResultContract, ActivityResultCallback)}
     * with the appropriate {@link ActivityResultContract} and handling the result in the
     * {@link ActivityResultCallback#onActivityResult(Object) callback}.
     */

**Comment by caiofaustino** [comment]
Sorry but where do you see this deprecation? Which class is it? `onActivityResult` is not deprecated according to Android docs page.
https://developer.android.com/reference/android/app/Activity#onActivityResult(int,%20int,%20android.content.Intent)

**Comment by kostya29-strikersoft** [comment]
@caiofaustino it is deprecated on androidX activity (appcompatactivity), Google recommends uses result API
https://developer.android.com/training/basics/intents/result
