### ISSUE TITLE
No 2.4.9 release/tag/commit on github

### ISSUE THREAD

**Issue by pboos** [Adyen/adyen-android#425]
**Describe the bug**
The latest release on major version 2 was 2.4.9 (or just now saw 2.4.12 on maven), but according to Github it is 2.4.5.

**To Reproduce**
1. Go to https://github.com/Adyen/adyen-android/releases?after=3.1.0 or here https://github.com/Adyen/adyen-android/commits/916244c9f3b67c29f6883eedc03903f6f4702e2b
2. Search for version 2.4.9
3. No version 2.4.9 found
4. Go to https://mvnrepository.com/artifact/com.adyen.checkout/base
5. See there is even a version 2.4.12

**Expected behavior**
Have a release or at least tag for each version that is published to maven. It doesn't have to be in the main branch

**Additional context**
For a migration project at my company, we need the source for 2.4.9 (that we currently use in the android app) so we can rename the package to be able to use 2.4.9 at the same time as the newest version. This in order to switch back (via remote config) to the old version in case we have problems with our new implementation.

**Comment by caiofaustino** [comment]
Hey there. Sorry this was a decision made by our manager a few years ago, which in retrospect was not a very good decision.

When we moved from v2 to v3 we didn't branch out here on Github, so it would be just a new version upgrade. While we could still publish bugfixes to maven if they were needed. So unfortunately there is no git history to add these tags here in Github. 

I understand it's confusing, and we have changed that approach for the new v4 release. But it's not possible to add those backwards on v2.
