### ISSUE TITLE
Update 4.0.0 ProGuard rules in readme

### ISSUE THREAD

**Issue by ilians** [Adyen/adyen-android#431]
The readme is currently still showing the 3.8.x ProGuard rules. The 4.0.0 checkout seems to have updated packages so the old rules no longer work as expected.

When upgrading to the 4.0.0 beta version I updated the ProGuard file to:

```
-keep class com.adyen.checkout.core.model.** { * ;}
-keep class com.adyen.checkout.components.model.** { *; }
-keep class com.adyen.threeds2.** { *; }

-keepclassmembers public class * implements com.adyen.checkout.components.PaymentComponent {
   public <init>(...);
}
-keepclassmembers public class * implements com.adyen.checkout.components.ActionComponent {
   public <init>(...);
}
```

This seems to be working but it's hard to know if I missed anything.

Please update the ProGuard rules in the readme now that 4.0.0 is stable.

**Comment by caiofaustino** [comment]
Good catch, thanks for letting us know, we will update it asap.
