### ISSUE TITLE
Android 12 missing support for safer component exporting

### ISSUE THREAD

**Issue by MarioBoehmer** [Adyen/adyen-android#441]
**Describe the bug**
If the Adyen SDK is included into an app one can't target Android 12 / target sdk 31. The added Activities and Receivers which declare intent filters don't explicitly declare the exported attribute. Android 12 requires developers to explicitly set the exported attribute to components which declare intent filters. Builds for Android 12 won't compile due to errors in the manifest merger.

[Android 12 docs for safer component exporting](https://developer.android.com/about/versions/12/behavior-changes-12#exported
)
```
Manifest merger failed : Apps targeting Android 12 and higher are required \
to specify an explicit value for android:exported when the corresponding \
component has an intent filter defined.
```

**To Reproduce**
1. include Adyen SDK in your app
2. Target SDK level 31
3. Build project
4. Build error due to missing exported attribute
5. Since the build error is not very verbose you can revert to SDK level 30 and look into **build/intermediates/merged_manifest/** to discover the components with missing explicit export attributes

**Expected behavior**
Explicit declaration of exported attribute for components with declared intent filters.

**Comment by jreij** [comment]
Thanks for opening this, we are fixing it and it will be included in the next release 👍
