### ISSUE TITLE
Crash InvalidInputException 

### ISSUE THREAD

**Issue by Brian-mccabe** [Adyen/adyen-android#445]
We are seeing a crash when presenting a challenge, it seems to occur when a user puts the app in the background and then re opens it, we are using library: com.adyen.checkout:threeds:2.4.11

here is the stack trace of the crash:

 Caused by com.adyen.threeds2.exception.InvalidInputException
Invalid challengeParameters.
atd.y.a.a (a.java:44)
com.adyen.threeds2.internal.i.a (i.java:298)
com.adyen.threeds2.internal.i.doChallenge (i.java:110)
com.adyen.checkout.threeds.Card3DS2Authenticator.presentChallenge (Card3DS2Authenticator.java:171)
com.adyen.checkout.threeds.Card3DS2Authenticator.presentChallenge (Card3DS2Authenticator.java:151)

**Comment by jreij** [comment]
Hey there, we might be investigating this issue already. Can you check if you use Bouncy Castle in your app, or if you have any dependency that uses it?

**Comment by Brian-mccabe** [comment]
Yep we have a dependency using it

**Comment by jreij** [comment]
So far we believe this dependency is causing the issue, we will let you know once we have a fix. [This issue](https://github.com/Adyen/adyen-3ds2-android/issues/33) is probably the same as yours.

**Comment by lachudra87** [comment]
We have same issue but as I checked we have Bouncy Castle as dependency only in tests and lint tasks so nothing in production code

**Comment by Brian-mccabe** [comment]
Any update on this? We were able to reproduce this with a Banca Transilvania card

**Comment by caiofaustino** [comment]
We will make a release including this fix soon, but you can force the dependency update manually if you can't wait.
`implementation "com.adyen.threeds:adyen-3ds2:2.2.3"`
But we plan to release really soon.

**Comment by caiofaustino** [comment]
This is now released in `4.1.0`

**Comment by Brian-mccabe** [comment]
Great thanks, will there be an update to com.adyen.checkout:threeds or will we have to migrate to com.adyen.threeds:adyen-3ds2: ?

**Comment by caiofaustino** [comment]
`com.adyen.checkout:threeds` was also updated to `4.1.0` and it contains the new version of `com.adyen.threeds:adyen-3ds2` whith the fix.

**Comment by Brian-mccabe** [comment]
Could not find com.adyen.checkout:threeds:4.1.0. 

is this the right version?

**Comment by caiofaustino** [comment]
Ahh sorry, the package name is actually `com.adyen.checkout:3ds2`
https://repo1.maven.org/maven2/com/adyen/checkout/3ds2/

**Comment by Brian-mccabe** [comment]
is it possible to update this library with the fix: https://mvnrepository.com/artifact/com.adyen.checkout/threeds

This is the one we are using

**Comment by caiofaustino** [comment]
Unfortunately not, that old version is still using the old support libraries, and the new 3DS2 SDK is migrated to AndroidX, migrating the whole project would be a big effort and we are not developing new features for that anymore.
