### ISSUE TITLE
3DS2 `identifyShopper()` requires `directoryServerId` and `directoryServerPublicKey`

### ISSUE THREAD

**Issue by misterjunio** [Adyen/adyen-android#453]
**Describe the bug**
I'm not sure if this is just a consequence of using test cards, but the tokens that are emitted with the 3DS2 `IdentifyShopper` flow look something like this:

``` json
{
    "threeDSMessageVersion": "2.1.0",
    "threeDSMethodNotificationURL": "https:\/\/checkoutshopper-test.adyen.com\/checkoutshopper\/threeDSMethodNotification.shtml?originKey=pub.v2.7814286629520534.aHR0cHM6Ly95b3VyLWNvbXBhbnkuY29t.J3eXUlZenoQcjvENcGLEXQ5onn55AsievnyS6UWU_9A",
    "threeDSMethodUrl": "https:\/\/pal-test.adyen.com\/threeds2simulator\/acs\/startMethod.shtml",
    "threeDSServerTransID": "a963f582-14df-4499-9323-d5bb02814332"
}
```

However, the `identifyShopper()` method of the SDK throws an error when building the config parameters if the `directoryServerId` or `directoryServerPublicKey` properties are `null`.

**To Reproduce**
1. Retrieve any `IdentifyShopper` flow `action` response, for example by using the [API Explorer](https://docs.adyen.com/api-explorer/#/CheckoutService/v67/post/payments);
1. Call the `handleAction()` SDK method, passing in the above `action`;
1. Exception is thrown.

**Expected behavior**
I am probably misunderstanding something, but I can't understand what. If these missing properties are only populated in production scenarios, how am I supposed to test the code that I am developing? I've tried with multiple test cards and none of the emitted tokens worked.. Please enlighten me.

**Comment by caiofaustino** [comment]
Hi there, this looks like a response that is supposed to be handled by the Web instead of the app. Can you check with Support or with your IM if there is a configuration in your account or something in your request that is indicating this flow?

**Comment by misterjunio** [comment]
@caiofaustino I've tried with all the cards listed under the [App-based integration](https://docs.adyen.com/development-resources/test-cards/test-card-numbers#app-based-integration) heading. Would these still return this response that you say is intended for web? Would that mean that this is probably something misconfigured in the server side?

**Comment by caiofaustino** [comment]
Those cards will only route the type of challege that happens once the 3DS2 challenge is requested. But to signal that the payment is ready for 3DS2, and that it's on mobile, there are a few other things in the request and  probably in your account configuration as well.

For example the [`allow3DS2`](https://docs.adyen.com/api-explorer/#/CheckoutService/v67/post/payments__reqParam_additionalData-AdditionalData3DSecure-allow3DS2) flag inside `additionalData` should be set to true to signal that you are able to handle that. 
You can also pass [`channel` ](https://docs.adyen.com/api-explorer/#/CheckoutService/v67/post/payments__reqParam_channel) `android`.

I don't know for sure all the configurations that are needed, and I don't have access to your account so maybe contacting support in this case would be better for you.

**Comment by misterjunio** [comment]
Thanks mate. In that case it's probably something in our configuration and I'll reach out to support if we need further help. Cheers
