### ISSUE TITLE
Android 12 Support

### ISSUE THREAD

**Issue by ilyasdirin** [Adyen/adyen-android#454]
For android 12 support, activities that have intent filter must have export property flag otherwise IDE gives compilation error during manifest merging. Please see here; https://developer.android.com/about/versions/12/behavior-changes-12#exported

For dropIn 4.0.0 it still has the following activity without export flag. There are 2 other activities in 3DS2 package but they are being handled by the team but couldn't find any information about dropIn Android 12 support. Please evaluate this since Android 12 release is approaching and we are trying our apps to be adapted before it is released.

        <activity
            android:theme="@ref/0x7f120030"
            android:name="com.adyen.checkout.dropin.ui.DropInActivity"
            android:launchMode="2">

            <intent-filter>

                <action
                    android:name="android.intent.action.VIEW" />

                <category
                    android:name="android.intent.category.DEFAULT" />

                <category
                    android:name="android.intent.category.BROWSABLE" />

                <data
                    android:scheme="adyencheckout"
                    android:host="com.journiapp.book_stage" />
            </intent-filter>
        </activity>

**Comment by ozgur00** [comment]
Thanks @ilyasdirin for the input! We are aware of this and made the changes accordingly both in 3DS2 library and here. It will be included in the next release!

**Comment by caiofaustino** [comment]
Will keep it open until we make the release.

**Comment by caiofaustino** [comment]
This is release in `4.1.0`
