### ISSUE TITLE
Race Condition potentially delaying updates to NetworkingState

### ISSUE THREAD

**Issue by tinsukE** [Adyen/adyen-android#46]
I noticed this problem when writing Espresso tests that covered the 2.2.0 version of the Adyen SDK for the Tiqets App:

-----

The issue happens when performing a payment, let's take a Credit Card's first payment as an example, so via [`CardDetailsActivity`](https://github.com/Adyen/adyen-android/blob/c367280ac6a7b63140866bbd4381cc2cbbdc0901/checkout-ui/src/main/java/com/adyen/checkout/ui/internal/card/CardDetailsActivity.java) and pressing the button with ID [`R.id.button_pay`](https://github.com/Adyen/adyen-android/blob/c367280ac6a7b63140866bbd4381cc2cbbdc0901/checkout-ui/src/main/java/com/adyen/checkout/ui/internal/card/CardDetailsActivity.java#L133).

After filling out the needed info and tapping the pay button, some networking will take place and our test can tell Espresso to wait for the network call to finish before proceeding with its test instructions via an [`IdlingResource`](https://developer.android.com/reference/androidx/test/espresso/IdlingResource) that is updated according to [`PaymentHandler.getNetworkingStateObservable()`](https://github.com/Adyen/adyen-android/blob/caac65aee4dfc220979b21f43ed264b5c00db3eb/checkout-core/src/main/java/com/adyen/checkout/core/PaymentHandler.java#L36), which is notified of Adyen's SDK networking activity.

It'd be alright if only [`PaymentHandlerImpl.initiatePayment()`](https://github.com/Adyen/adyen-android/blob/caac65aee4dfc220979b21f43ed264b5c00db3eb/checkout-core/src/main/java/com/adyen/checkout/core/internal/PaymentHandlerImpl.java#L283) (the private one) wouldn't have an, IMO, incorrect implementation. This method updates the previously mentioned `NetworkingState` observable via [`handleRequestStarted()`](https://github.com/Adyen/adyen-android/blob/caac65aee4dfc220979b21f43ed264b5c00db3eb/checkout-core/src/main/java/com/adyen/checkout/core/internal/PaymentHandlerImpl.java#L344) and [`handleRequestFinished()`](https://github.com/Adyen/adyen-android/blob/caac65aee4dfc220979b21f43ed264b5c00db3eb/checkout-core/src/main/java/com/adyen/checkout/core/internal/PaymentHandlerImpl.java#L355) calls. The problem lies in having `handleRequestStarted()` called from within the `Runnable` instance that [is being sent](https://github.com/Adyen/adyen-android/blob/caac65aee4dfc220979b21f43ed264b5c00db3eb/checkout-core/src/main/java/com/adyen/checkout/core/internal/PaymentHandlerImpl.java#L298) to a `ExecutorService` (powered via a Thread Pool).

What quite often happens for us is that Espresso taps the buy button, the `ExecutorService` is not running the supplied `Runnable` right away, or quickly enough (there is no guarantee that it would do so) for the `NetworkingState` to get updated (and, consequently, for our `IdlingResource` to tell Espresso to wait because the App is not idle) before Espresso checks if the App is idle and resume with the test instructions, which will now fail because it is performing checks that should happen only once the payment networking finishes.

-----

This could be solved by moving the calls to `handleRequestStarted()` to before dispatching the Runnable to the ExecutorService for PaymentHandler's `initiatePayment()` **and** `deletePaymentMethod()`.

**Comment by timon-langlotz** [comment]
Hi @tinsukE,

thanks for your detailed report! The `NetworkingState` `Observable` is only intended to be used to display networking state in the UI, and is not an accurate representation (at least not to the millisecond) of when the networking call starts and finishes, as you noticed. This is due to the fact that we handle some of the networking complexity in the background. Even when moving the `handleRequestStarted()` and `handleRequestFinished()` into the `Runnable`, we still wouldn't have an immediate callback, since we are running in a background thread and need to dispatch the update into the main thread via a `Handler`.

Cheers,
Timon

**Comment by tinsukE** [comment]
Hey @timon-langlotz, thanks for the reply.

It is true that the callback of when the networking call starts or finishes wouldn't be that accurate, but at least the notification of the networking starting would happen before the actual networking starts, and the notification of the networking finishing would happen after the actual networking finishes.

This would allow us to depend on the callbacks for implementing an `AdyenNetworkingIdlingResource` to use during our Espresso tests. Some milliseconds might not sound a lot, but this had introduced quite some flakiness to our test suite.

**Comment by caiofaustino** [comment]
Hey @tinsukE,

We considered your request and agreed to call `handleRequestStarted()` before the runnable is submitted to the `ExecutorService`.
Should be available on the next release `2.3.1`

Hope it solves your issue,
Cheers :)
