### ISSUE TITLE
Allow disabling FLAG_SECURE in Debug for testing.

### ISSUE THREAD

**Issue by JoeCiou** [Adyen/adyen-android#463]
Hi, I am a new Android developer, when I add Adyen to dependencies of build.gradle, I found the BuildConfig.Debug is always false, are there anything I also need to do?

build.gradle
```
dependencies {
    implementation "com.adyen.checkout:drop-in:4.1.0"
    ...
}
```

com.adyen.checkout.card.BuildConfig
```
//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by FernFlower decompiler)
//

package com.adyen.checkout.card;

public final class BuildConfig {
    public static final boolean DEBUG = false;
    public static final String LIBRARY_PACKAGE_NAME = "com.adyen.checkout.card";
    public static final String BUILD_TYPE = "release";
    public static final String CHECKOUT_VERSION = "4.1.0";

    public BuildConfig() {
    }
}
```

Thanks in advance for any help.

**Comment by caiofaustino** [comment]
Hey Joe,

Yeah, so there are different `BuildConfig` classes for each module in the project basically, and since we release our library in a release build it will always have DEBUG = false, what you are probably looking for is the current build type of your own app, so you need to import the correct `BuildConfig` class from your apps package.

Hope that helps.

**Comment by JoeCiou** [comment]
I am trying to release a debug version of our app, including Adyen SDK with Debug BuildConfig, because I want the app can be testable on a testing tool based on recording screen, and I found the SDK only disable FLAG_SECURE on debug config(#394), if that, how can I do?

**Comment by caiofaustino** [comment]
Ahh good point, you are right you cannot do that at the moment. I'll leave this issue open and we can try to add some way for you to test that in the next release :)

**Comment by JoeCiou** [comment]
Thanks for your help, looking forward to next version. :)

**Comment by jreij** [comment]
Fixed by linked PR.
