### ISSUE TITLE
Issue in handling redirects or completing 3D Secure payments on Android by using Drop-In

### ISSUE THREAD

**Issue by aliazmat** [Adyen/adyen-android#466]
Hi, we are trying to implement our payment by using Drop-In. In case of redirect, I could not found a way to redirect by using Drop-In. While in iOS there is a section on handling redirects which would have the app call RedirectComponent.applicationDidOpen(from: url) method.
In Android when we are getting Redirect action, it's always showing a generic error. Is there any way to resolve this issue with Drop-In only.

Thanks In Advance.

**Comment by caiofaustino** [comment]
Hi there,

In Android Drop-in you don't need to handle the redirect specifically, any `action` type you receive, you can just return it in the `DropInService` implementation you have and we will handle the redirect automatically, just make sure you are using the correct `returnUrl` in your payments call.

As for the generic error, if you have more information I can take a look. You can enable logging in the SDK by calling:
`Logger.setLogcatLevel(Log.DEBUG)`

**Comment by aliazmat** [comment]
The error that is showing on popup widow is : There is an error while processing your payment. Please try again later.
Below json I'm passing in DropInService.
<img width="1074" alt="Screenshot 2021-08-25 at 2 52 50 PM" src="https://user-images.githubusercontent.com/15319722/130764939-1a0efe65-5ef7-43b2-af29-746feaddc82a.png">

**Comment by aliazmat** [comment]
Hi, Now I can redirect to the target payment app and can do the payment. But Not sure how to capture the payment result. For this I had added below lines in my Activity and after payment I can redirect back to this activity.
<intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:host="com.mypackage"
                    android:scheme="adyencheckout"/>
            </intent-filter>

But the question is how to get actionComponentData object to make /payments/details request call. As after redirecting back to my app, I'm not getting any callback to my DropInService.

**Comment by caiofaustino** [comment]
https://docs.adyen.com/online-payments/android/components#step-2-handle-the-redirect

**Comment by aliazmat** [comment]
@caiofaustino I already tried this but it not working. After below line, there is no callback in my service.
 redirectComponent.handleRedirectResponse(intent.data!!) //I'm using 3.8.3 version

I believe it's for Component not for Drop-In. I'm using Drop-In in my implementation

**Comment by caiofaustino** [comment]
Ah ok, for Drop-in the service should be called automatically, which `returnUrl` are you sending in your `/payments` request? It has to be the one the drop-in can handle as a deep link.

**Comment by aliazmat** [comment]
returnUrl we are passing as "adyencheckout://com.mypackage" 
and I had added a intent filter in my activity as below:
 <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data
                    android:host="com.mypackage"
                    android:scheme="adyencheckout"/>

            </intent-filter>
After adding this I'm redirecting to this activity after payment but my DropInService is not being called.
With Drop-In do we need to add this intent-filter in activity? If yes then what are the steps to get the control back to DropInservice ? If no then How to get a callback in DropInService. Please suggest really got stuck in this from a long time and there is documentation is available on developer portal.

**Comment by caiofaustino** [comment]
For Drop-in you don't need to add the `intent-filter`, it's already in the Drop-in Activity, but your `returnUrl` shouldn't be `mypackage`, it should actually be your apps mains package, you can also check what it should be by calling `RedirectComponent.getReturnUrl(context)`

**Comment by aliazmat** [comment]
@caiofaustino thanks for replying. my returnUrl is not mypackage, it's already the my apps main package. It mentioned here as mypackage as I don't want disclosed my package name in a public forum.

**Comment by caiofaustino** [comment]
Ah OK, then I think the only thing you have to do is remove the `intent-filter` from your own Activity so it doesn't clash with the Drop-in Activity and let it handle the result, that way you should get a call in the DropInService.

**Comment by aliazmat** [comment]
Also tried to remove the intent-filter but still not getting any callbacks :(

**Comment by caiofaustino** [comment]
What happens after the 3DS1 authentication? Does it redirect back to your app? Which Activity?

**Comment by aliazmat** [comment]
**Condition 1:** With No intent-fliter, whenever I receive RedirectShopper action type, can redirect to that app/page but after payment never can return to my app and DropInService never gets a callback.

**Condition 2:** If I add intent-filter to in an activity, then after payment it redirecting to my app to that activity. But DropInService never gets a callback.

**Comment by caiofaustino** [comment]
That doesn't seem right, Condition 1 is the correct one but the intent should trigger the Drop-in Activity since it's the one with the intent filter for the `returnUrl`.
https://github.com/Adyen/adyen-android/blob/develop/drop-in/src/main/AndroidManifest.xml#L13

Maybe you can check your final merged Manifest to see if there is any issues.
