### ISSUE TITLE
Get returnUrl  to complete 3D Secure payments on Android 

### ISSUE THREAD

**Issue by xiaoxiaohua333** [Adyen/adyen-android#47]
// Adyen SDK
    implementation 'com.adyen.checkout:core:1.14.1'
    implementation 'com.adyen.checkout:utils:1.14.1'
    implementation 'com.adyen.checkout:ui:1.14.1'
    implementation 'com.adyen.checkout:cardscan:1.14.1'

I want to get 【returnUrl】to  complete 3D Secure payments
Because we use the old version 1.14.1, so we can't get the returnUrl by CheckoutSetupParameters.

**Comment by caiofaustino** [comment]
Sorry but I'd need a bit more information. Do you mean 3DS or 3DS2? 
Where do you need to pass the returnUrl to?
