### ISSUE TITLE
Pay button not working since upgrade to 4.0.0

### ISSUE THREAD

**Issue by peterMonteer** [Adyen/adyen-android#474]
I've updated the SDK to 4.0.0 following the available guide.

When I try to pay for something in my app, the adyen pop up shows, I choose to pay with credit card, fill out the necessary information, but when I click 'Pay' nothing happens. I tried to log something inside makePaymentsCall but nothing shows up, any ideas?

**Comment by caiofaustino** [comment]
You can also check out the [migration guide](https://docs.adyen.com/online-payments/android/migrate-to-android-4-0-0) to see if you missed anything :)
