### ISSUE TITLE
Google Pay doesn't work in the example app unless your language is set to English

### ISSUE THREAD

**Issue by lbenedetto** [Adyen/adyen-android#48]
1. Set your phones language to a locale that uses commas in prices (ex $1,99)
2. Try to buy with Google Pay in the example app

"Request failed. Unexpected developer error, please try again later"

Most likely due to GooglePayUtil.java:156 where you are formatting the display amount. The code looks like it would format it as $1.99 but it is actually getting formatted to $1,99. If I edit the code in that method to replace the , with a . then Google Pay works.

**Comment by caiofaustino** [comment]
Hi Lars,

Thanks for catching this. Unfortunately we do not accept pull requests, but I made a similar fix and it should be part of the next release.

Cheers!

**Comment by lbenedetto** [comment]
Any idea when the next release is? 

Was planning on releasing an update to my app tomorrow, and would like for it to include this fix.
If its only a few days away, I might be able to delay my release.

**Comment by caiofaustino** [comment]
Sorry for the delay. The new release has just been published! Check for 2.3.2

Cheers :)

**Comment by riddhee** [comment]
@lbenedetto can you please help me to integrate G Pay
