### ISSUE TITLE
Saving payment method for BCMC

### ISSUE THREAD

**Issue by xanderdeseyn** [Adyen/adyen-android#481]
Storing payment method does not seem to be supported for BCMC. Is this on the roadmap or by design?

**Comment by caiofaustino** [comment]
Thanks for bring this up, we will make a task to add this feature.

**Comment by xanderdeseyn** [comment]
Is there something we can do in the meantime so we can patch this functionality in? Android is supporting it.

**Comment by caiofaustino** [comment]
You can send the flag in the payment manually to store the payment but you can't show the toggle to let the user choose if they want to save it or not. Unless you are using standalone Component, then you can add that UI element yourself below the component.

We will try to release this in the next release, shouldn't take too long to come out.

**Comment by caiofaustino** [comment]
Feature is merged in #483  and will be out on the next release 👍

**Comment by xanderdeseyn** [comment]
Thanks for the swift response!
