### ISSUE TITLE
Disable error modal on dropin

### ISSUE THREAD

**Issue by xanderdeseyn** [Adyen/adyen-android#484]
Is it possible to disable the native error modal that pops up when the dropin encounters an error? This iOS SDK does not do this. We would like to visualize these errors in our own way.

**Comment by jreij** [comment]
Hi, if you use `DropInServiceResult.Error` it is not possible to not show the error dialog. However, if you use `DropInServiceResult.Finished` and pass in the result string as `"error"` or something you will dismiss drop-in without showing a dialog. And when handling the result, you can check what string was used in the `DropInServiceResult.Finished` and handle accordingly.

Which version of the SDK are you using anyway?

**Comment by caiofaustino** [comment]
Also to add, since the Drop-in is an Activity outside of your control, differently from iOS, there is no way for you to display a custom error screen while the Drop-in is active, only after it finishes like @jreij mentioned.

**Comment by xanderdeseyn** [comment]
Ok got it working with that trick, thanks. We are on the latest SDK version btw!
