### ISSUE TITLE
Cannot override translations for Drop In

### ISSUE THREAD

**Issue by mohadian** [Adyen/adyen-android#489]
**Describe the bug**
It seems we cannot override the translations on Adyen Drop-in. More specifically, the "Credit Card" seems to be hardcoded and the SDK is not using the string resources for it. 
Also, the string "Credit card" in the string resources is the same for all the locales. I was wondering if this is intentional? 

**To Reproduce**
Open the online payment Drop in
try to add a new Card. 
Notice the title is always appear as Credit Card in all the languages. 

**Expected behavior**
The text should be translated for different locales or it should be possible to override it. 

**Screenshots**
<img width="359" alt="Screenshot 2021-09-16 at 11 54 00" src="https://user-images.githubusercontent.com/12498117/133600360-c4d4c917-3cfc-4bed-85a3-bc66932f1900.png">
<img width="355" alt="Screenshot 2021-09-16 at 11 53 46" src="https://user-images.githubusercontent.com/12498117/133600368-d10ab644-2a73-4d5c-9ded-5303e12fe6da.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device:  on Android and iOS devices
 - OS: All
 - Version 3.8.3

**Additional context**
Would you please direct me to place in the documentation which covers the Customising the DropIn? ( strings and colors)

**Comment by jreij** [comment]
Hi, there are 2 types of localization, native (overriding string resources in the app) and backend (localizing the API responses), both are completely possible. This "Credit Card" label, in both the payment methods and the credit card screen, actually comes from the API response.

To customize that, your backend needs to pass the [Shopper Locale](https://docs.adyen.com/api-explorer/#/CheckoutService/v67/post/paymentMethods__reqParam_shopperLocale) attribute in the request body.

As for other (non API) labels, you can override the string resources in xml but I see that you already did that 🙂  Same for the colors and styles.

**Comment by heikkihautala** [comment]
Is there any documentation on how to override string resources? 
I'd like to override the `pay_button` resource since we're only tokenizing the card and not actually paying anything yet.

We're using sdk version 4.3.0.

**Comment by jreij** [comment]
@heikkihautala there are no docs for this currently but it's an item in our queue, along with some general localization improvements.

At the moment what you can do is take a look at all the `strings.xml` files in each module and find what you need. For example:
Drop-in: https://github.com/Adyen/adyen-android/blob/develop/drop-in/src/main/res/values/strings.xml
Card: https://github.com/Adyen/adyen-android/blob/develop/card/src/main/res/values/strings.xml
And so on...

**Comment by caiofaustino** [comment]
I think what he means is just how to make the override.

You just need to define the `pay_button` string in your project, it will take priority over the one defined in the SDK.

**Comment by heikkihautala** [comment]
I tried adding the same resource on our strings.xml file: 
`<string name="pay_button">Submit</string>`
but the card component still shows "Pay" in the button ("Maksa" in finnish).

**Comment by jreij** [comment]
Does the button show `Pay` along with a certain amount, or just `Pay`?

**Comment by heikkihautala** [comment]
In `values/strings.xml` I have:
`<string name="pay_button">Submit</string>`

And in `values-fi/strings.xml` I have:
`<string name="pay_button">Lähetä</string>`

If the device language is set to english, the button says "Submit" correctly, but when I change the language to finnish, it says "Pay" and not "Lähetä".

**Comment by jreij** [comment]
Can you try to put it in `values-fi-rFI/strings.xml`?

**Comment by heikkihautala** [comment]
That worked. Thanks 👍

**Comment by heikkihautala** [comment]
How could we change the card form title `Credit card` to something else? That text comes from the `/paymentMethods` response, so I guess it cannot be overridden in the app. User could input **debit card** info also, so `Credit card` is no accurate. We's like to change it to "payment card".
