### ISSUE TITLE
Silent crashes on Android 7 and below

### ISSUE THREAD

**Issue by christianfindsen** [Adyen/adyen-android#495]
**Describe the bug**
We are getting reports that the app is crashing when the users are selecting a payment method.

We don't see the crashes anywhere unfortunately, so we have been trying to narrow it down.

It looks to us that it might be some Adyen component that crashes.

We are doing a two fragment architecture much like your drop-in. When we are navigating to the payment fragment we are initializing the Adyen3DS2Component and the RedirectComponent.

The RedirectComponent is initialized like this **RedirectComponent.PROVIDER.get(this)**  and the Adyen3DS2Component like this **Adyen3DS2Component.PROVIDER.get(requireActivity(), null)**

I believe it might be one of those components as it seems it does not matter what payment method the user selected.

I have attached some images for your reference.

![2021-09-17 (2)](https://user-images.githubusercontent.com/52277989/134317971-02da4580-abcb-4405-b335-8d5442aecf8b.png)

![01](https://user-images.githubusercontent.com/52277989/134317987-28ddfb34-2f6a-46b3-b76f-4e3147e470e7.png)
![02](https://user-images.githubusercontent.com/52277989/134317985-9323a5f9-34b4-4048-b831-a71a4f8923dc.png)
![03](https://user-images.githubusercontent.com/52277989/134317988-85dd8e59-b424-4ec2-9966-59ef2ed37c17.png)
![04](https://user-images.githubusercontent.com/52277989/134317981-ec0bbe2f-7480-4220-86d9-db44e06c7f1d.png)
![05](https://user-images.githubusercontent.com/52277989/134317980-564b1a2d-b08c-4aa2-9bed-62290adbdbde.png)
![06](https://user-images.githubusercontent.com/52277989/134317979-029abc9d-0eb8-45e8-840a-bdd0d4dc4a24.png)

https://user-images.githubusercontent.com/52277989/134317975-398427ed-34f5-49b1-b4ca-d3cde226ccf8.mp4

**To Reproduce**
Cant reproduce the issue.

**Expected behavior**
The user can continue with payments.

**Smartphone (please complete the following information):**
 - Device: [Android]
 - OS: [Android 7 and below]

**Additional context**
We are running components v 3.8.3

**Comment by jreij** [comment]
Hi, thank for reporting this. It might be a component of ours causing the issue but without logs or crash reports or some way to reproduce, we really have no way of figuring that out.

Do you have Crashlytics or some other kind of crash reporting tool set up for your app?

**Comment by christianfindsen** [comment]
Yes, we do have crashlytics set up but this crash unfortunately does not
show up.

All we have to go on is user reports  and some pictures or videos.

We have tried adding some tracking to see where it stops and it does not
get pass the initialization of the above mentioned components.

**Comment by jreij** [comment]
Then I guess the only thing we can do is to check the code, can you share code snippets of how you implemented this?

**Comment by christianfindsen** [comment]
Yes. 
This is the fragment with the onViewCreated

```
override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)


      btnBackArrow.setFilteredOnClickListener {
            cancelOrder()
        }

        btnCancel.setFilteredOnClickListener {
            cancelOrder()
        }

        EventTrackingManager.instance.trackEvent(
            TrackingEvent.DEBUG_PAYMENT_FRAG_CRASH, mapOf(
                "Function" to "onViewCreated",
                "OrderId" to viewModel.getOrderId()
            )
        )

        adyenComponents = AdyenComponents(requireActivity(), this)

        paymentViewModel =
            ViewModelProvider(
                this,
                PaymentViewModelFactory(
                    requireActivity().application, returnUrl!!
                )
            ).get(
                PaymentViewModel::class.java
            )

        setupAdyen()

        dialog?.setOnShowListener {
       
                showModalLoadingSpinner()
                paymentViewModel.placeOrder(selectedPaymentMethod!!)
                paidHasBeenCalled = true

                EventTrackingManager.instance.trackEvent(
                    TrackingEvent.DEBUG_PAYMENT_FRAG_CRASH, mapOf(
                        "Function" to "onShow",
                        "OrderId" to viewModel.getOrderId(),
                        "PaymentType" to selectedPaymentMethod?.paymentType?.name
                    )
                )         
        }
    }
```

And this is the setup function

 ```private fun setupAdyen() {

        val threedsComponent = Adyen3DS2Component.PROVIDER.get(requireActivity(), null)
        threedsComponent.observe(this, Observer {
            if (paymentViewModel.paymentId == null) {
                return@Observer
            }


            paymentViewModel.sendAdditionalAuthPayload(
                paymentViewModel.paymentId!!,
                EmbeddedCheckoutViewModel.PROVIDER_ADYEN,
                AuthorizationPayload(
                    payloadType = EmbeddedCheckoutViewModel.ADYEN_ADDITIONAL_AUTH_PAYLOAD,
                    detailsPayload = it.details.toString(),
                    paymentDataPayload = it.paymentData,
                    storePaymentCard = paymentViewModel.saveCard
                )
            )
        })

        val threeDSObserver = Observer<ThreeDSecureObject> { obj ->
            val action = Action.SERIALIZER.deserialize(JSONObject(obj.payload!!))
            threedsComponent.handleAction(requireActivity(), action)
        }

        redirectComponent = RedirectComponent.PROVIDER.get(this)

        redirectComponent?.observeErrors(this, {
            if (isInARedirect && it.errorMessage == RedirectComponent.REDIRECT_FAIL) {

                dismissWaitingDialog(false)
                paymentViewModel.cancel()

                Handler(Looper.getMainLooper()).postDelayed({
                    callback.providerAppNotInstalled(viewModel.getItem(), returnUrl)
                    dismiss()
                }, 100)
            }
        })

        redirectComponent!!.observe(this, Observer {
            showModalLoadingSpinner()
            if (paymentViewModel.paymentId == null) {
                return@Observer
            }

            paymentViewModel.cancelThirdPartyPolling()

            paymentViewModel.sendAdditionalAuthPayload(
                paymentViewModel.paymentId!!,
                EmbeddedCheckoutViewModel.PROVIDER_ADYEN,
                AuthorizationPayload(
                    payloadType = EmbeddedCheckoutViewModel.ADYEN_ADDITIONAL_AUTH_PAYLOAD,
                    detailsPayload = it.details.toString(),
                    paymentDataPayload = it.paymentData,
                    storePaymentCard = paymentViewModel.saveCard
                )
            )
        })
}
```

**Comment by jreij** [comment]
I can't see where the issue is, but there are two things that might help:
* The same `Adyen3DS2Component` should handle both `threeDS2Fingerprint` and `threeDS2Challenge` actions. If you create a new instance every time, the challenge will not work. Maybe try testing with a card number that causes both actions to be returned.
* Try using `threedsComponent.observeErrors`, you might find out something from it.

I will keep on looking into it but I don't think I can figure out much more than that without logs or a crash report.

**Comment by christianfindsen** [comment]
Okay, thanks for looking into it. It might be something unrelated. I will reopen it if I found something relevant.
