### ISSUE TITLE
Hi  when i use the  iDeal pay with  miui rom

### ISSUE THREAD

**Issue by dikeboy** [Adyen/adyen-android#50]
After i  jump  to the webview, it can't  back 
I kill my app and restart it , it also start the miui brownser

I download the source code and try it  ,
I find  in xiaomi   miui brownser  should  add the 
**redirectIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK)** 
before the 

            if (redirectIntent.resolveActivity(getPackageManager()) != null) {
                startActivityForResult(redirectIntent, REQUEST_CODE_REDIRECT);
            } else {
                Toast.makeText(getApplicationContext(), R.string.checkout_error_redirect_failed, Toast.LENGTH_LONG).show();
                finish();
            }

on the RedirectHandlerActivity to fix it 
Can you try and  solver the issues thanks

**Comment by caiofaustino** [comment]
Thanks for the tip, but this change might introduce other side effects. I'll try to get a MiUI device and test this.

**Comment by caiofaustino** [comment]
Hi,
We just moved to a new implementation of the Checkout process on version 3.
Please test it on the new version and reopen the issue if you still have same problem.

Cheers,
