### ISSUE TITLE
Not all recived Payment Methods types appear in the PaymentMethodTypes class

### ISSUE THREAD

**Issue by BenedictP** [Adyen/adyen-android#502]
From the adyen backend I recive Payment Methods with the type: "directEbanking", "bankTransfer_SE", "directdebit_NL" and so on. In the PaymentMethodTypes.kt class these types don't appear. Are these Payment Methods not supported or are they just missing?

Because the PaymentMethodTypes.kt doc says: "Helper class with a list of all the currently supported Payment Methods on Components and Drop-In." :)

**Comment by jreij** [comment]
Payment methods listed in the `PaymentMethodTypes.SUPPORTED_PAYMENT_METHODS` require some logic to work (showing a component, interacting with another SDK, handling an action, etc). If a payment method is not explicitly listed, we try to treat it as a redirect, so we call `/payments` without any extra user data. Some payment methods work, others won't.

So in the case of the 3 you listed above, it depends on whether they require any user input or special handling.

**Comment by BenedictP** [comment]
Ok, thanks for the clarification! Now it makes sense.
