### ISSUE TITLE
3DS with Google Pay

### ISSUE THREAD

**Issue by Findsen** [Adyen/adyen-android#51]
We have just updated our android SDK to 2.3 to be able to support the 3DS for Google Pay.

Works great but when you press continue in the Google Pay view, the view gets dismissed and you wait for 3 seconds with Adyen bottom sheet up and no loading indicators before the redirect is happening.

I feel that a loading state is required for the user.

**Comment by caiofaustino** [comment]
Thanks for the input, we will take a look into it.

**Comment by caiofaustino** [comment]
We just moved to a new implementation flow on version 3, Google Pay will be available soon, please reopen the issue if you still have any problems.
