### ISSUE TITLE
German bank codes CSV file?

### ISSUE THREAD

**Issue by tinsukE** [Adyen/adyen-android#52]
Is it really needed to embed this CSV file in the Apps that use Adyen's SDK?
https://github.com/Adyen/adyen-android/blob/master/checkout-ui/src/main/res/raw/bankcodes_de.csv

**Comment by caiofaustino** [comment]
It is being used for one specific payment method. I'll talk to my colleagues here and reevaluate if it's really necessary.

**Comment by caiofaustino** [comment]
Hi,
We just moved to a new payment flow on version 3. Maybe check it out and see if you like it.
Sorry but we will not be making this change on version 2.
