### ISSUE TITLE
PI102: Unknown response type. Response must be redirect or complete.

### ISSUE THREAD

**Issue by bulatgaleev** [Adyen/adyen-android#53]
Adyen version: 1.6.0
Using custom integration, add card flow.
`POST /checkoutshopper/services/PaymentInitiation/v1/initiate`
triggers me this response: 
`Unknown response type. Response must be redirect or complete
{"errorCode":"PI102","errorMessage":"An error occurred processing the payment","payload":"SOME_PAYLOAD","type":"validation"}`

Not able to add any card (test or real, 3ds or not, test environment or prod).

**Comment by caiofaustino** [comment]
Hi,

That error likely not specific to the SDK. Could you please contact Adyen Support instead so we can check the PSP Reference and account configuration?

Thanks
