### ISSUE TITLE
Ability to provide Logger instances

### ISSUE THREAD

**Issue by rahulsainani** [Adyen/adyen-android#530]
Sometimes while analysing payment issues in qa/release builds it might be useful to know what's happening inside the SDK. The logs are visible while debugging and developing but generally qa/release builds have logcat(`android.util.Log`) and Adyen logging disabled. Since Adyen uses it's own Logger instance it is hard to achieve this. 

An idea would be to use patterns used in libraries like [Timber](https://github.com/JakeWharton/timber) and [Beagle](https://github.com/pandulapeter/beagle) where there is a Logger [interface/abstract class](https://github.com/JakeWharton/timber/blob/trunk/timber/src/main/java/timber/log/Timber.kt#L20) that defines the contract and prepares the logs/ handle common functionality for all log levels. Clients could provide their own instance of Logger which might log to their own backend or services like Firebase or Sentry on release builds so issues can be solved better. Adyen SDK could include the default logger which might log to logcat for debugging builds and can still make sure all sensitive logs are handled by the default logger and other loggers won't get access to it. 

An example of how Timber is configured with a CrashReportingTree

```
class CrashReportingTree : Timber.Tree() {

    override fun log(priority: Int, tag: String?, message: String, t: Throwable?) {
        if (priority != Log.VERBOSE) {
            Firebase.crashlytics.log("${getPriorityLabel(priority)}/ $message")
        }
        t?.let {
            Firebase.crashlytics.recordException(it)
        }
    }

    private fun getPriorityLabel(priority: Int): String =
        when (priority) {
            Log.ASSERT -> "A"
            Log.DEBUG -> "D"
            Log.INFO -> "I"
            Log.WARN -> "W"
            Log.ERROR -> "E"
            else -> "X"
        }
}

// Setting up
    if (BuildConfig.DEBUG) {
            Timber.plant(Timber.DebugTree())
    } else {
            Timber.plant(CrashReportingTree())
    }

```

Adyen logger could also be theoretically setup similarly. This was originally discussed in #514 in a [comment](https://github.com/Adyen/adyen-android/issues/514#issuecomment-957441707).

**Comment by jreij** [comment]
Hi, thanks for the suggested! We discussed this internally following your comment on the other issue and we added this feature to the pipeline 🙂 

We don't have an ETA for it unfortunately but we will make sure we update this ticket when we have a PR.
