### ISSUE TITLE
Credit Card brand logos not shown correctly when there is a cold start of the SDK

### ISSUE THREAD

**Issue by BenedictP** [Adyen/adyen-android#535]
When I set the supported/allowed brands and start the SDK it randomly shows the credit card brands in a duplicate way:
![image](https://user-images.githubusercontent.com/5817002/142006528-3ac6227e-a3e0-4379-bdce-1ef24a08f7a8.png)
But when I start typing it updates the icons and I think now they are shown correctly:
![image](https://user-images.githubusercontent.com/5817002/142006659-fff516d1-7dc5-4019-aa54-3628e46cc1fc.png)
But when I now close the SDK and start it again the brands are also shown correctly. So it's only an issue when there is a "cold start".

**To Reproduce**
Set supported/allowed brands and start the SDK.

**Expected behavior**
The brands should always  be shown correctly

**Comment by ozgur00** [comment]
Hi @BenedictP! Thanks for bringing the issue to us. Can you provide the code segment where you build the `CardConfiguration` object?

**Comment by BenedictP** [comment]
I tried to reproduce it with the sample app but wasn't able to do it. So I will close this and try to find out what I'm doing wrong on my side.
