### ISSUE TITLE
Next field focus problem if postal code hidden

### ISSUE THREAD

**Issue by zerazeru** [Adyen/adyen-android#541]
I quote myself from #462
> the card holder field has its [nextFocus attribute](https://github.com/Adyen/adyen-android/blob/8e933e4a0f8b16ce31c3b4f982f799a0273f9179/card/src/main/res/layout/card_view.xml#L96) set to the postal code field. So if the postal code is hidden the keyboard is not dismissed on tapping Next/Done which is confusing on devices where the keyboard covers the submit button.

I tried to make a PR but not sure how to build, so I just opened an issue.

**Comment by jreij** [comment]
Hi, thanks for opening this! We'll work on providing a fix and update this ticket once we're done 🙂
