### ISSUE TITLE
makeDetailsCall and makePaymentsCall should be suspended

### ISSUE THREAD

**Issue by dryaz** [Adyen/adyen-android#542]
**Describe the bug**
Here in the javadoc for `makeDetailsCall` and `makePaymentsCall` 
```
In this method you should make the network call to tell your server to make a call to the payments/details/ endpoint.
```
`makeDetailsCall` is called in coroutine scope but it's not suspended so you can't make suspend network call.

**To Reproduce**
1. `override fun makeDetailsCall`
2. call suspend function

**Expected behavior**
Code should be compiled without error since makeDetailsCall already called in coroutine scope

```kotlin
    protected open fun onDetailsCallRequested(
        actionComponentData: ActionComponentData,
        actionComponentJson: JSONObject
    ) {
        launch(Dispatchers.IO) {
            // Merchant makes network call
            val result = makeDetailsCall(actionComponentJson)
            sendResult(result)
        }
    }
```

**Comment by jreij** [comment]
Hi, thanks for reaching out. We do support the behavior you're trying to achieve but not through `makePaymentsCall` and `makeDetailsCall`.

Instead you should remove these methods, and override `onPaymentsCallRequested` and `onDetailsCallRequested` instead. Inside these methods you can launch your own coroutines, and manage the calls as you will. Then once you have a result, you can use `sendResult` to send it back to drop-in.

Check out [ExampleAsyncDropInService](https://github.com/Adyen/adyen-android/blob/main/example-app/src/main/java/com/adyen/checkout/example/service/ExampleAsyncDropInService.kt) for an example implementation.
