### ISSUE TITLE
User can accidentally close the Drop-In screen

### ISSUE THREAD

**Issue by mariuszvimn** [Adyen/adyen-android#544]
**Describe the bug**
It is easy to close the Drop-In screen accidentally by tapping on the grayed out part of the host application screen underneath.

**To Reproduce**
1. Start DropIn 
2. During any part of the payment process click on the grayed out part of the host application 
3. Observe Drop-in being closed

**Expected behavior**
Tapping outside of the Drop-In screen should not close it.

**Comment by jreij** [comment]
Hi, thanks for the suggestion! We'll discuss this internally and provide an update once we have one.
