### ISSUE TITLE
Payment with saved card issue

### ISSUE THREAD

**Issue by badredaha** [Adyen/adyen-android#546]
**Paid with saved card**
When I paid with a saved card, I receive this error:

`{\"status\":422,\"errorCode\":\"101\",\"message\":\"Invalid card number\",\"errorType\":\"validation\",\"pspReference\":\"881638285392713F\"}`

**Desktop (please complete the following information):**
 - OS: Android
 - Version Adyen SDK : 4.2.0

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: Android 11

**Comment by jreij** [comment]
Hi, it seems like this is an API issue. Please reach out to support@adyen.com explaining the problem, they are better suited to help you with this 🙂
