### ISSUE TITLE
Giropay: Drop In does not call makeDetailCall

### ISSUE THREAD

**Issue by AF-jum** [Adyen/adyen-android#548]
**Describe the bug**
We are using Drop-in in our app. In Giropay, As stated in [Step 5. ](https://docs.adyen.com/online-payments/android/drop-in?tab=without_code_result_intent_code__2#step-5-additional-payment-details) makePaymentsCall returns action in case of GiroPay that is given to DropInServiceResult.Action.

As per Step 1.2 it returns return DropInServiceResult.Action and the action object. However it does not invoke makeDetailsCall.

App does not redirects, user is shown bank homepage. on back button, User is shown payment fail message.

![Screenshot_20211201_121213](https://user-images.githubusercontent.com/91950310/144382394-d9b4a996-3121-4509-ab4b-15bd0ecd622a.png)

**To Reproduce**
1. Go to Adyen Drop in, select Giropay 
2. Add account details and confirm
3. App does not redirects, user is shown bank homepage
4. on back button, payment method fails

Desktop (please complete the following information):

OS: Android
Version Adyen SDK : 4.0.0

Smartphone (please complete the following information):

Device: S21 Ultra
OS: Android 12

**Comment by jreij** [comment]
Hi, thanks for reaching out. This seems to be a redirect issue, can you check whether your `returnUrl` starts with `adyencheckout://your.package.name`?

**Comment by AF-jum** [comment]
Hey, return url is correct.

**Comment by jreij** [comment]
Can you enable logging by calling `com.adyen.checkout.core.log.Logger.Logger.setLogcatLevel(Log.DEBUG)` in your application class, then filter the logs by `CO.` and share them here?

**Comment by AF-jum** [comment]
https://user-images.githubusercontent.com/91950310/144406695-7f081e45-363b-4bad-a298-3ed4262606e0.mp4

**Comment by jreij** [comment]
This is definitely a redirect URL issue then, please reach out to support@adyen.com explaining the problem, they are better suited to help you with this 🙂
