### ISSUE TITLE
Changing borderless button style

### ISSUE THREAD

**Issue by katajona** [Adyen/adyen-android#554]
**Describe the bug**
I would like to change the borderless button's style on the 3ds2 challenge activity (ChallengeActivity).
I want to change the color of the text. Of course, this is doable with changing the colorPrimary inside the ThreeDS2Theme. But this will change also the color of the Toolbar.

Also related to this I would like to change the cornerRadius for the button, which is also not possible without using a drawable background.

Do you plan to migrate from AppCompat buttons to MaterialButtons? 
Also is there a way to fix my issue and adjust the buttons the way I would like to have them?

**Comment by caiofaustino** [comment]
Hey there, 
You can take a look on how to customize the 3DS2 screen [here](https://github.com/Adyen/adyen-3ds2-android#customizing-the-ui)
And then you can set the `setUiCustomization()` in the `Adyen3DS2Component`.
I'm afraid there is not too much that's possible, and I just noticed this will not work on Drop-in unfortunately.

**Comment by felipesaruhashi** [comment]
@caiofaustino About Drop-in customization in general, is not possible to customize the style then?
Is only possible to customize it with components?

**Comment by jreij** [comment]
Hi @felipesaruhashi, it's also possible to customise drop-in and components by overriding the styles in the `styles.xml` files, regardless of which integration you went for.

For example, here you can find the styles.xml for the card component: https://github.com/Adyen/adyen-android/blob/v4/card/src/main/res/values/styles.xml (for other components just replace `card` with the corresponding module name).
And this is the styles.xml for drop-in: https://github.com/Adyen/adyen-android/blob/v4/drop-in/src/main/res/values/styles.xml.
