### ISSUE TITLE
Device identifier question

### ISSUE THREAD

**Issue by dyshen** [Adyen/adyen-android#56]
https://github.com/Adyen/adyen-android/blob/af65ddd479d6d677a0fc5e326fcc1cd566f712a4/checkout-core/src/main/java/com/adyen/checkout/core/internal/model/DeviceFingerprint.java#L65

I assume it is trying to get a device-scoped identifier. However, after Android O, Android ID has a different value for each App. The identifier is only application-scoped in this case. My concern is that users might be facing unnecessary 2FA challenge although they are authenticated in other Apps on the same device.

**Comment by caiofaustino** [comment]
Sorry for the late response. This should not affect the triggering of 2FA.
Also we moved to a new payment flow on version 3 which does not contain this feature anymore.
Maybe check it out and let us know what you think.
