### ISSUE TITLE
Clarification needed for Checkout API version requirements

### ISSUE THREAD

**Issue by geertjan-tiqets** [Adyen/adyen-android#563]
Hi! I recently discovered this Adyen release notes page: https://docs.adyen.com/online-payments/release-notes. Before, I had only been checking the GitHub release notes: https://github.com/Adyen/adyen-android/releases

I noticed on the adyen.com release notes, some requirements of the Checkout API are listed. For the Android SDK 3.8.1 and 3.8.2 it says:

> This release requires Checkout API v52 or later.

For our product, on the backend we are still using the Checkout API v49, while our Android app is already using SDK 3.8.3. So this brings up some questions:

1. Android SDK 3.8.3 doesn't mention the Checkout API v52 requirement, but is it safe to assume that if 3.8.2 had it, 3.8.3 has it too?
2. What would the incompatibility between Android SDK 3.8.3 and Checkout API v49 be exactly? (We have not seen any problems with it in production.)
3. For the Android SDK 4.0.0, the documentation mentions it should be compatible with older Checkout API versions. Does this also have a lower limit of Checkout API v52?
4. If Android SDK 3.8.3 works with Checkout API v49 for us, would it be safe to upgrade to Android SDK 4.0.0 while staying on Checkout API v49?

Thanks in advance for any help you can give us!

**Comment by caiofaustino** [comment]
Hey there,

So these API recommendations are not really hard rules, some new functionalities might only be available only on new API versions for example, or it could be the case that there are hard requirements for the new API, but only on certain payment methods.

In general we would like for our merchants to stay up to date with our new releases, so we tell which is the oldest API version that is expected to work 100% with that version of the SDK, but if on your use case you haven't seen any issues then there is no need to update right away.
