### ISSUE TITLE
Payment_failed and other strings not translated in DropIn

### ISSUE THREAD

**Issue by przan** [Adyen/adyen-android#567]
**Describe the bug**
At least 3 strings are in locale specific strings.xml file, but are still in English. Please, check e.g. https://github.com/Adyen/adyen-android/blob/develop/drop-in/src/main/res/values-sv-rSE/strings.xml. DropIn 4.3

**To Reproduce**
Check `payment_failed`, `credit_card`,`time_out_error`  strings in the SDK's translations. Enter a wrong card date or CVC and get a default error message from DropIn and you should see untranslated `payment_failed` text.

**Expected behavior**
This string should be translated like other strings, e.g. `error_dialog_title`.

**Screenshots**
![Screenshot_20211221-083117_Circle K Charge SE TEST](https://user-images.githubusercontent.com/16773508/146889694-fa3fd3a5-df4b-4e0f-9b3f-1702a751eafb.jpg)

**Smartphone (please complete the following information):**
 - Device: Galaxy S8
 - OS: Android 9

**Comment by jreij** [comment]
Hi, thanks for pointing this out! We'll try to fix it for the next release.
