### ISSUE TITLE
3DS1 challenge not invoked in DropIn 4.3 and 3DS1 test card

### ISSUE THREAD

**Issue by przan** [Adyen/adyen-android#568]
**Describe the bug**
Not sure if it is a bug, but the same card from https://docs.adyen.com/development-resources/test-cards/test-card-numbers, e.r. 4212 3456 7890 1237, causes to require Redirect in old Checkout SDK 2.4.13, but in DropIn 4.3 there is no Redirect and card is successfully tokenized. How to test 3DS1 and Redirect when implementing DropIn 4.3?

**To Reproduce**
1. Tokenize 3DS1 card from https://docs.adyen.com/development-resources/test-cards/test-card-numbers with old SDK 2.4.13 - there is Redirect authentication request
2. Can't get 3DS1 Redirect with DropIn 4.3 using card from https://docs.adyen.com/development-resources/test-cards/test-card-numbers and the Adyen account and merchant

**Expected behavior**
Find a way to test 3DS1 with DropIn

**Smartphone (please complete the following information):**
 - Device: Galaxy S8
 - Android 9

**Comment by caiofaustino** [comment]
Hi, 

There could be several different reasons on the logic to trigger 3DS1. This is probably something related to you `/payments` request that could be missing a flag or something in your account config. It's better to reach out to [Adyen Support](https://www.adyen.help/hc/en-us) so they can look at your case an give you a more direct answer.

**Comment by przan** [comment]
Apparently we added `threeDSVersion = 2.1.0` https://docs.adyen.com/api-explorer/#/CheckoutService/v68/post/payments__reqParam_additionalData-AdditionalData3DSecure-threeDSVersion to backend call which resulted in such behavior. Now we stayed only with `allow3DS2 = true` and 3DS1 started working.
