### ISSUE TITLE
The pay button does not appear in the card view

### ISSUE THREAD

**Issue by mdorreh** [Adyen/adyen-android#577]
**Android Card Component**

I am going to integrate Card Component in our Android application. But it dosen't show the button inside the card view. 
   **Here are my codes**: 
```
class AddNewCardFragment : BottomSheetDialogFragment() {

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        return inflater.inflate(R.layout.add_new_card, container, false)
    }

    @RequiresApi(Build.VERSION_CODES.O)
    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        val activity = activity ?: return

        val adyenPaymentMethod = arguments?.get("payment_method") as AdyenPaymentMethodsData


        val paymentMethod =
            PaymentMethodsApiResponse.SERIALIZER.deserialize(JSONObject(Gson().toJson(adyenPaymentMethod))).paymentMethods?.get(
                0
            )

        val cardConfiguration = CardConfiguration.Builder(activity, ADYEN_KEY)
            .setEnvironment(Environment.TEST)
            .setHolderNameRequired(true)
            .setShowStorePaymentField(false)
            .build()

        val cardComponent = CardComponent.PROVIDER.get(activity, paymentMethod ?: PaymentMethod(), cardConfiguration)
        val cardView = dialog?.findViewById<CardView>(R.id.cardView)

        cardView?.attach(cardComponent, activity)
    }

    companion object {
        val TAG = AddNewCardFragment::class.java.simpleName
        fun newInstance(paymentMethod: AdyenPaymentMethodsData): AddNewCardFragment {
            val args = Bundle().apply {
                putParcelable("payment_method", paymentMethod)
            }
            return AddNewCardFragment().apply {
                arguments = args
            }
        }
    }
}
```
**and this is the ui**: 
<img src="https://user-images.githubusercontent.com/42037295/150095819-b1aa77d6-e55e-4911-ba61-7180c35ef8eb.jpg" width="300" height="600">

Also I had to make the background color amber to show the white place holder in edittexts. Is it a way to custom colors?

**Comment by caiofaustino** [comment]
Hi there, yes that is working as expected, since the Components are meant to be a part of your layout, on Android we decided to not include the Pay button, so you can add one yourself.
Then one thing you can do for example is only enable the button once the input is valid like this
```kotlin
cardComponent.observe(this@MainActivity) { state ->
    myPayButton.enabled = state?.isValid == true
}
```

**Comment by mdorreh** [comment]
@caiofaustino Thanks for your response. Is it possible to change the color of the placeholder's text and the content of the edit text in the card view?

**Comment by caiofaustino** [comment]
Yes, you can override our styles by declaring them yourself. You can check them [here for card](https://github.com/Adyen/adyen-android/blob/develop/card/src/main/res/values/styles.xml) and [here for common shared styles](https://github.com/Adyen/adyen-android/blob/develop/ui-core/src/main/res/values/styles.xml).

**Comment by mdorreh** [comment]
@caiofaustino Thank you for your response. can you please tell me how it is possible to realize that the card has the 3dscecure number?

**Comment by caiofaustino** [comment]
What do you mean by a 2dsecure number? The CVC? Or that the card will trigger a 3DS challenge?

**Comment by mdorreh** [comment]
My Bad!  3DS.

**Comment by caiofaustino** [comment]
There is no way of knowing beforehand that I'm aware of. Maybe there is some information in the API that you can call, but that's not part of the SDK. I would contact support about it.
From the SDK perspective, if 3DS is triggered, then the API call will return the `action` for the SDK to handle it.
