### ISSUE TITLE
Issue compiling with Gradle 5.3

### ISSUE THREAD

**Issue by leonardoxh** [Adyen/adyen-android#58]
Hi, I tried to migrate my app that uses the artefact `com.adyen.checkout:core-card:2.4.0` to the gradle version 5.3 but when I do it I get a compilation error, is this a known issue ?

```
> Task :app:compileDebugKotlin FAILED
e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class com.adyen.checkout.core.card.CardType, unresolved supertypes: com.adyen.checkout.base.TxVariantProvider
```

**Comment by caiofaustino** [comment]
That's weird. The TxVariantProvider is in a transient dependency from `com.adyen.checkout:core-base`, gradle should also get it by default. Doesn't seem related to Gradle 5.3 though.

**Comment by leonardoxh** [comment]
Yeah, when I try with gradle 4.10.3 it works.

**Comment by caiofaustino** [comment]
Can you try to manually add the ` implementation "com.adyen.checkout:core-base:2.4.0"` and see if that solves the issue? I'll take a look into it.

**Comment by leonardoxh** [comment]
Interesting, when I add this artefact `Could not find com.adyen.checkout:core-base:2.4.0` this can be something related with the problem.

**Comment by caiofaustino** [comment]
Sorry, I misstyped the package name, `implementation "com.adyen.checkout:base:2.4.0"`

**Comment by caiofaustino** [comment]
Indeed this issue was not known to us, I'll investigate more and get back to you.

**Comment by leonardoxh** [comment]
If I add the checkout base dependency it works fine

**Comment by caiofaustino** [comment]
Cool, you can do that for now, but this should not be necessary.

**Comment by leonardoxh** [comment]
Any news here ?

**Comment by caiofaustino** [comment]
Yes, we made a change to the release process where the pom.xml file will be create differently, that should solve the transient dependencies not being properly configured.

It will be out on the next release 2.4.3

**Comment by caiofaustino** [comment]
Hey Leonardo,

2.4.3 has just been release, could you please remove the dependency and check if the issue was solved?

Cheers :)

**Comment by leonardoxh** [comment]
I tested with gradle 5.4 and gradle 5.3.1 now and I got the same error... Debug build, no proguard

**Comment by leonardoxh** [comment]
I saw the changes from `implementation` to `api` (is what I thought when I opened the issue), and also when I download the pom file from https://jcenter.bintray.com/com/adyen/checkout/core-card/2.4.3/ it seams that the checkout base is there, but decompiling the aar file the classes are not there.

**Comment by caiofaustino** [comment]
I just noticed that on the pom file the dependencies are duplicated for some reason as both `compile` and `runtime`, I tested removing the runtime locally and it seems to have fixed it.  I'll check the build script again to figure out what happened there. 

Sorry for the inconvenience.

**Comment by leonardoxh** [comment]
Any news (I really want to remove the core-base checkout workaround 😂)

**Comment by caiofaustino** [comment]
Haha, yeah I fixed it this time, but you'll have to wait for the next release. No ETA.

**Comment by Josh1Dev** [comment]
Compiling with Gradle 5.1.1 also gave me issues. Checkout core was unresolved, refreshed dependencies, resync and did everything I could but nothing worked.

**Comment by TalSerenVia** [comment]
Same here. Having the same build error with Gradle 5.1.1. I need to upgrade gradle version but can't because of this issue.

**Comment by caiofaustino** [comment]
Hey all, version 2.4.4 was just released with a fix for that. Can you confirm that it works for you?

Thanks

**Comment by leonardoxh** [comment]
Works fine @caiofaustino tks!

**Comment by josh1dev** [comment]
Issue is resolved @caiofaustino 

Thanks :+1:
