### ISSUE TITLE
Unable to receive Challenge - 3D Secure 2 Native Authentication

### ISSUE THREAD

**Issue by NunoPalma** [Adyen/adyen-android#584]
**Describe the bug**
Using the test execution available here https://docs.adyen.com/api-explorer/#/CheckoutService/v67/post/payments__example_payments-card-3d-secure-2-web, routing the transaction through the Android channel gives different results than under the Web channel.
More precisely, any test card available here https://docs.adyen.com/development-resources/test-cards/test-card-numbers, that supports 3DS 2, returns a result code of "ChallengeShopper" under the Web channel, returns "IdentifyShopper" under the Android channel.

**To Reproduce**
1. Go to https://docs.adyen.com/api-explorer/#/CheckoutService/v67/post/payments__example_payments-card-3d-secure-2-web
2. Change the card number to: 4212345678910006
3. Execute the request
4. Change channel to 'android'
5. Execute the request

**Expected behavior**
<del>Same behavior for both channels</del>. Possibility to test a similar scenario where a transaction requests additional shopper interaction (ChallengeShopper - biometrics, 2FA, etc.)
 Is there any point that I may be missing? If not, is there any particular card that would enable a ChallengeShopper flow on Android?

Thanks in advance.

**Comment by caiofaustino** [comment]
Why would you expect the same behavior on both channels? The `android` channel is for payments initiated in a mobile app, so in that case we treat the 3DS2 flow using the native [3DS2 Component](https://docs.adyen.com/online-payments/3d-secure/native-3ds2/android-component#3ds2-component)
If you use the Compnent, you can just get the `action` object from the API response and pass it in, and we will handle the rest :)

**Comment by caiofaustino** [comment]
Oh and to clarify, there is different specifications and security measures for a 3DS2 challenge on the Web and on a native app. You can still perform a Web 3DS2 flow, but that should happen on a Browser.

**Comment by NunoPalma** [comment]
@caiofaustino My apologies, I expressed myself poorly. I'm not expecting the same behavior, but I was expecting to be able to test a similar flow where a transaction requires, for example, biometric authentication.
Our API is only routing for an Android channel, and the cards available for testing purposes only return IdentifyShopper requests.

Also, I'm using the native 3DS2 Component.

**Comment by caiofaustino** [comment]
Ahh OK, maybe reach out to our [support team](https://support.adyen.com/hc/en-us/requests/new?ticket_form_id=360000705420) then, they will be able to check what's going on, if the flow is going frictionless (fingerprint only, which is not biometric fingerprint), or if something else is going on.
