### ISSUE TITLE
APK file size

### ISSUE THREAD

**Issue by drewpitchford** [Adyen/adyen-android#59]
Hi there!

What is the overall file size of the SDKs APK?

**Comment by caiofaustino** [comment]
I'd say it varies a lot depending on our setup and implementation type. If you have progard setup or not, etc..

Easiest way to find out is to add the dependency to your project and check the diff.
`implementation "com.adyen.checkout:ui:2.3.3"`

The maven AAR file is about 500k but I don't think that's a good indication.
