### ISSUE TITLE
SDK Crash when user has a locale does not have ISO3 country

### ISSUE THREAD

**Issue by Ehab4290** [Adyen/adyen-android#598]
SDK is throwing `com.adyen.checkout.core.exception.CheckoutException` because `Locale.getISO3Country()` is throwing `java.util.MissingResourceException` 

So I am wondering if it is mandatory to have ISO3 country for the locale or not.

```
Fatal Exception: com.adyen.checkout.core.exception.CheckoutException: Invalid shopper locale: sq_XK.
       at com.adyen.checkout.components.base.BaseConfigurationBuilder.build(BaseConfigurationBuilder.java:63)
       ...
```

**Comment by jreij** [comment]
Hi, thanks for reaching out. How exactly are you fetching the locale before passing it to the Configuration Builder?

**Comment by jreij** [comment]
`sq_XK` is Albanian (Kosovo) and I think there's an issue with Kosovo specifically, as it doesn't seem to have an ISO3 code. I created a fix to improve the way we validate locales, it should solve your issue.

But in all cases bear in mind that Albanian is not among the languages we support, neither on the backend nor the SDK, so it will just revert to English.

**Comment by Ehab4290** [comment]
Great, thanks!
Regarding your first question, I'm using `com.adyen.checkout.core.util.LocaleUtil.getLocale()` to get locale
