### ISSUE TITLE
SDK crashes when pay button resource is overriden

### ISSUE THREAD

**Issue by przan** [Adyen/adyen-android#60]
Hi!

I would like to override resource for Pay button, so it would not contain the exact amount (%s part)
`<string name="checkout_pay_amount_format">Authorize</string>`

Unfortunately the app crashes then. Is it intentional?

Using version 2.4.2

**Comment by caiofaustino** [comment]
Hi, 

The text of the Pay button is expected to have a placeholder %s to replace with the amount of the payment. So this was not taken into account.

I'll provide a fix for this on the next release.

Cheers.

**Comment by caiofaustino** [comment]
Hey,

Version 2.4.3 was just release, should solve your issue. Could you please confirm?

Cheers.

**Comment by przan** [comment]
Hi,

The SDK doesn't crash when showing the `Pay` button with `Authorize` text on 2.4.3. Thanks!
