### ISSUE TITLE
Some translation keys not working when ugprading from 4.2.0 to 4.3.0

### ISSUE THREAD

**Issue by m-o** [Adyen/adyen-android#602]
**Describe the bug**
Hi, we use Dropin and set Locales to configs to translate it.
When upgrading from 4.2.0 to 4.3.0 (problem also persists at 4.4.0), some of the keys are not translated and instead show original english text.
Example of keys:
`pay_button_with_value`
`checkout_card_expiry_date_hint`

**To Reproduce**
Setup Dropin in app, set locale for example to cs_CZ and open Dropin for payment.

**Expected behavior**
All keys in czech translation files should be translated.

**Smartphone (please complete the following information):**
 - Device: does not matter
 - OS: Android (various versions)

**Comment by jreij** [comment]
Hi, thanks for reaching out. All these strings are available from way earlier than `4.2.0`. Can you share how are you creating your locale and how are you passing it to drop-in?

**Comment by m-o** [comment]
Creating locale manually:

`Locale("cs","CZ)`

Config of Adyen:
```
val cardConfiguration =
            CardConfiguration.Builder(Locale.getDefault(), environment, CLIENT_KEY)
                .setShopperLocale(Constants.International.DEFAULT_LOCALE)
                .setHolderNameRequired(false)
                .setHideCvcStoredCard(true)
                .build()

        val googlePayConfiguration = GooglePayConfiguration.Builder(
            Locale.getDefault(),
            environment,
            CLIENT_KEY
        )
            .setShopperLocale(Constants.International.DEFAULT_LOCALE)
            .setGooglePayEnvironment(gpEnvironment)
            .build()

        val dropInConfiguration =
            DropInConfiguration.Builder(requireContext(), serviceClass, CLIENT_KEY)
                .setEnvironment(environment)
                .setShopperLocale(Constants.International.DEFAULT_LOCALE)
                .addCardConfiguration(cardConfiguration)
                .addGooglePayConfiguration(googlePayConfiguration)
                .apply {
                    adyenPaymentMethodVo.price?.let {
                        setAmount(Amount().apply {
                            value = (it.amount * 100).toInt()
                            currency = it.currency
                        })
                    }
                }
                .build()
```

**Comment by jreij** [comment]
You are passing two different locales to the Builder, `Locale.getDefault()` in the constructor then `Constants.International.DEFAULT_LOCALE` in `setShopperLocale`. You don't need to explicitly call `setShopperLocale` if you are passing it in the constructor.

So try to remove all calls to `setShopperLocale` and replace `Locale.getDefault()` with `Locale("cs","CZ")`.

Can you also make sure `Constants.International.DEFAULT_LOCALE` is set to `Locale("cs","CZ")`?

**Comment by m-o** [comment]
Hi, thanks I will remote the shopperLocales and see what is going on.
The `Constants.International.DEFAULT_LOCALE` is `Locale("cs","CZ")`.

**Comment by jreij** [comment]
Sorry forgot to mention that you still need to use `setShopperLocale` in `DropInConfiguration.Builder` only.

**Comment by m-o** [comment]
So just to be sure I set it like this:
```

val cardConfiguration =
            CardConfiguration.Builder(
                Locale("cs", "CZ"),
                environment,
                CLIENT_KEY
            )
                .setHolderNameRequired(false)
                .setHideCvcStoredCard(true)
                .build()

        val googlePayConfiguration = GooglePayConfiguration.Builder(
            Locale("cs", "CZ"),
            environment,
            CLIENT_KEY
        )
            .setGooglePayEnvironment(gpEnvironment)
            .build()

        intent.flags += Intent.FLAG_ACTIVITY_REORDER_TO_FRONT
        val dropInConfiguration =
            DropInConfiguration.Builder(requireContext(), serviceClass, CLIENT_KEY)
                .setEnvironment(environment)
                .setShopperLocale(Locale("cs", "CZ"))
                .addCardConfiguration(cardConfiguration)
                .addGooglePayConfiguration(googlePayConfiguration)
                .apply {
                    ...
                }
                .build()

```

I still get the same czech/english string confusion...

**Comment by jreij** [comment]
This should work indeed. Can you share a screenshot of a string that's showing in English?

**Comment by m-o** [comment]
Yes, here they are:

![adyen_3](https://user-images.githubusercontent.com/720907/157227398-a2ab7411-8502-4ac2-9d1f-d092753f1fcd.jpg)
![adyen_2](https://user-images.githubusercontent.com/720907/157227403-4e96fbce-d036-48e5-82dd-116890b91a82.jpg)
![adyen_1](https://user-images.githubusercontent.com/720907/157227404-2a013fbe-d79e-4389-84b2-6ce2388ca7f6.jpg)

**Comment by m-o** [comment]
![adyen_3](https://user-images.githubusercontent.com/720907/157227821-b07450d0-2c3d-4355-be6a-5cc80909968f.jpg)

**Comment by jreij** [comment]
And just to confirm, this issue does not happen for you with `4.2.0` but it does with `4.3.0` and `4.4.0`?

**Comment by m-o** [comment]
Yes, exactly. But I will double check it, just to be sure.

**Comment by m-o** [comment]
Unfortunately upgrade to 4.5.0 didn't help. We will stick with the 4.2.0 for now and try to fix the issue in the meantime.

**Comment by jreij** [comment]
Hi again, can you try to type in your IDE some of the strings that are not working for you, then Ctrl+Click on it? For example:
![image](https://user-images.githubusercontent.com/9079915/158177937-eb31908b-0929-4b44-a88e-23350ec9dbb7.png)

This is from a sample project using 4.5.0 and I can see the Czech translation among others., wondering how it looks for you.

**Comment by jreij** [comment]
Hi @m-o , did you manage to solve this issue? And are you by any chance using React Native?
