### ISSUE TITLE
com.adyen.checkout:threeds not found.

### ISSUE THREAD

**Issue by AdriaBosch** [Adyen/adyen-android#61]
Hi,
We are trying to integrate the 3d secure payment in our application, but gradle can not find the library com.adyen.checkout:threeds:2.4.0.
I have looked at the Maven repository and it seems that it does not exist 
https://mvnrepository.com/artifact/com.adyen.checkout

Should we use the classic integration? com.adyen.threeds:adyen-3ds2:0.9.4

Regards.

**Comment by andreservidonigyg** [comment]
Same here :/

**Comment by ArmanSo** [comment]
Hi @AdriaBosch and @andreservidonigyg we sold the issue, now waiting for jcenter to approve`threeds:2.4.0` package it may be take 24 hours to get approve.

**Comment by ArmanSo** [comment]
@AdriaBosch it should be ok right now, can you please confirm it?

**Comment by AdriaBosch** [comment]
It works thanks.
