### ISSUE TITLE
[Android 12] Specify "android:exported"  in Manifest`s activity/receiver.

### ISSUE THREAD

**Issue by GNNikolov** [Adyen/adyen-android#613]
My app is targeting api 31, so "assembleDebug" fails because of the following files not having "android:exported" specified:

- com.adyen.threeds2.internal.ui.activity.ChallengeActivity
- com.adyen.checkout.dropin.ui.DropInActivity
- com.adyen.threeds2.internal.AppUpgradeBroadcastReceiver

A workaround was to predefine the activities and receiver in my app`s AndroidManifest.xml, and it`s fixed. Issue is reproducable with gradle verson - 7.1.2

**Comment by caiofaustino** [comment]
Which version of the SDK are you using? This has been done in version 4.1.0

**Comment by GNNikolov** [comment]
Sure, my fault. Sorry for that.
