### ISSUE TITLE
Add FLAG_SECURE in drop-in component

### ISSUE THREAD

**Issue by triay0** [Adyen/adyen-android#619]
Hi, Its possible to add FLAG_SECURE in DropInActivity? Our security tool found a critical issue in this class com.adyen.checkout.dropin.ui.DropInActivity.

I've tried to set this flag in container activity but it keeps appearing

Thanks in advance for any help you can give us!

**Comment by OscarSpruit** [comment]
Hi triay0, thanks for reaching out! `CardView` is currently setting this flag when it's attached to the window. As far as I know, that's the only view with sensitive information. 

What is the exact reason your security tool thinks this is a critical issue?

**Comment by triay0** [comment]
Hmm It seems security detects this issue in any activity of the app, I will close this issue, it's not a adyen thing.

Sorry for bothering

**Comment by OscarSpruit** [comment]
No worries, happy you figured it out!
