### ISSUE TITLE
ProGuard problem 2.4.1

### ISSUE THREAD

**Issue by vitorhor** [Adyen/adyen-android#62]
Im using exactly what is described in readme.txt, but its not working. I appreciate any help.

Using:
#### Adyen Checkout ####
-keep class com.adyen.checkout.core.** { *; }
-dontwarn com.adyen.checkout.nfc.**
-dontwarn com.adyen.checkout.googlepay.**
-dontwarn com.adyen.checkout.wechatpay.**

Here what im receiving:

Warning: com.adyen.checkout.ui.internal.card.CardDetailsActivity$2: can't find superclass or interface com.adyen.checkout.threeds.Card3DS2Authenticator$AuthenticationListener
Warning: com.adyen.checkout.ui.internal.card.CardDetailsActivity: can't find referenced class com.adyen.checkout.threeds.Card3DS2Authenticator
Warning: com.adyen.checkout.ui.internal.card.CardDetailsActivity: can't find referenced class com.adyen.checkout.threeds.Card3DS2Authenticator
Warning: com.adyen.checkout.ui.internal.card.CardDetailsActivity: can't find referenced class com.adyen.checkout.threeds.Card3DS2Authenticator
Warning: com.adyen.checkout.ui.internal.card.CardDetailsActivity: can't find referenced class com.adyen.checkout.threeds.Card3DS2Authenticator$AuthenticationListener
Warning: com.adyen.checkout.ui.internal.card.CardDetailsActivity: can't find referenced class com.adyen.checkout.threeds.Card3DS2Authenticator
Warning: com.adyen.checkout.ui.internal.card.CardDetailsActivity: can't find referenced class com.adyen.checkout.threeds.Card3DS2Authenticator
Warning: com.adyen.checkout.ui.internal.card.CardDetailsActivity$2: can't find referenced class com.adyen.checkout.threeds.Card3DS2Authenticator
Warning: com.adyen.checkout.ui.internal.card.CardDetailsActivity$2: can't find referenced class com.adyen.checkout.threeds.ChallengeResult
Warning: com.adyen.checkout.ui.internal.card.CardDetailsActivity$2: can't find referenced class com.adyen.checkout.threeds.Card3DS2Authenticator$AuthenticationListener
Warning: com.adyen.checkout.ui.internal.card.CardDetailsActivity$2: can't find referenced class com.adyen.checkout.threeds.Card3DS2Authenticator
Warning: com.adyen.checkout.ui.internal.card.CardDetailsActivity$2: can't find referenced class com.adyen.checkout.threeds.ChallengeResult
Warning: com.adyen.checkout.ui.internal.card.CardDetailsActivity$2: can't find referenced class com.adyen.checkout.threeds.ChallengeResult
Warning: com.adyen.checkout.ui.internal.card.CardDetailsActivity$2: can't find referenced class com.adyen.checkout.threeds.ChallengeResult
Warning: com.adyen.checkout.ui.internal.card.CardDetailsActivity$2: can't find referenced class com.adyen.checkout.threeds.ThreeDS2Exception
Warning: com.adyen.checkout.ui.internal.card.CardDetailsActivity$2: can't find referenced class com.adyen.checkout.threeds.ThreeDS2Exception
Warning: com.adyen.checkout.ui.internal.card.CardDetailsActivity$5: can't find referenced class com.adyen.checkout.threeds.Card3DS2Authenticator
Warning: com.adyen.checkout.ui.internal.card.CardDetailsActivity$5: can't find referenced class com.adyen.checkout.threeds.Card3DS2Authenticator
Warning: com.adyen.checkout.ui.internal.card.CardDetailsActivity$5: can't find referenced class com.adyen.checkout.threeds.ThreeDS2Exception
Warning: com.adyen.checkout.ui.internal.card.CardDetailsActivity$5: can't find referenced class com.adyen.checkout.threeds.Card3DS2Authenticator

**Comment by ArmanSo** [comment]
Hi @vitorhor 
please add this line `-dontwarn com.adyen.checkout.threeds.*` it should fix your problem.

**Comment by vitorhor** [comment]
Thanks, it worked.
