### ISSUE TITLE
'Card component' observer returns the previous fingerprint

### ISSUE THREAD

**Issue by sasindroid** [Adyen/adyen-android#620]
**Describe the bug**
Using Component integration for Card, I am in https://docs.adyen.com/online-payments/android/components#step-5-additional-client-app for threeds2 following the integration guide https://docs.adyen.com/online-payments/android/components#step-5-additional-client-app

On the first run, the 3DS2 challenge is shown and the transaction is a success. On the second run, the observer returns the **actionComponentData** automatically in the background while the 3DS2 challenge screen is shown. The returned **actionComponentData** is the previous value generated during the first transaction.

```
threedsComponent.observe(this) { actionComponentData ->
  sendPaymentDetails(actionComponentData)
}
```

**Environment & lib versions**
TST env
adyen-android: 4.5.0
react-native platform - testing on android
Component integration for Card

**To Reproduce**
1. Follow the guide https://docs.adyen.com/online-payments/android/components#step-5-additional-client-app for threeds2 following the integration guide https://docs.adyen.com/online-payments/android/components#step-5-additional-client-app.
2. Initiate a payment with a 3DS2 card 
-- | -- | -- | --
Visa | 4917 6100 0000 0000 | 03/2030 | 737
3. Initiate a second payment immediately, and you would notice the challenge response is automatically sent with the previous value.

**Expected behavior**
Expect the challenge response to be different for each iteration.

**My test code (In a react native module)**
```
      "threeDS2" -> {
        val adyen3DS2Configuration =
          Adyen3DS2Configuration.Builder(reactApplicationContext, clientKey)
            .setEnvironment(if (isTestEnvironment) Environment.TEST else Environment.LIVE)
            .build()

        mainThreadScope.launch {
          val threedsComponent =
            Adyen3DS2Component.PROVIDER.get(
              cActivity,
              currentActivity!!.application,
              adyen3DS2Configuration
            )

          threedsComponent.handleAction(currentActivity!!, action)
          threedsComponent.observe(cActivity) { actionComponentData ->
            val threeds2ActionData =
              ActionComponentData.SERIALIZER.serialize(actionComponentData).toString()
            promise.resolve(threeds2ActionData)
          }

          threedsComponent.observeErrors(cActivity, Observer {
            promise.reject("THREEDS2_CARD_PAYMENT_ERROR", it?.errorMessage ?: "3DS2 Error.")
          })
        }
      }
```

**Comment by OscarSpruit** [comment]
Thanks for reaching out @sasindroid ! Just tried to reproduce this and indeed I got weird behaviour. To work around this for now you can do something like this:

```
// Reference to component on the activity level
private var threedsComponent: Adyen3DS2Component? = null

private fun setupThreedsComponent Component(action: Action) {
    if (threedsComponent == null) {
        val adyen3DS2Configuration = 
            Adyen3DS2Configuration.Builder(reactApplicationContext, clientKey)
                .setEnvironment(if (isTestEnvironment) Environment.TEST else Environment.LIVE)
                .build()
    
        threedsComponent = Adyen3DS2Component.PROVIDER.get(
            this,
            application,
            checkoutConfigurationProvider.get3DS2Configuration()
        )

        threedsComponent?.observe(this) { ... }
        threedsComponent?.observeErrors(this) { ...  }
    }

    threedsComponent?.handleAction(this, action)
}

// Don't forget to remove the reference to avoid possible memory leaks
override fun onDestroy() {
        super.onDestroy()
        threeDS2Component = null
    }
}
```

Let me know if this works for you!

Also, why are you initiating multiple executive payments? I'm trying to understand the use case.

**Comment by sasindroid** [comment]
Hi @OscarSpruit thanks for your response.
This workaround does not work in my case as I am integrating the components in React native. In here, the MainActivity talks to other native modules which are basically java modules with basic lifecycle that extends the MainActivity's lifecycle. 

**Regarding my use case**
While testing in TST env, we run multiple tests one after the other which highlighted this issue.
I am aware I cannot test this on production. However, I am worried of an edge case this can popup in production. If it does, we would be in wild with no ability to debug.

**Comment by OscarSpruit** [comment]
Thanks for you answer! Let me explain the problem in more detail:

I'm assuming you execute the code you provided every time you get a response which has an action. This part will get the same instance of the `Adyen3DS2Component`, because it is bound to, in your case, `MainActivity`
```
val threedsComponent =
            Adyen3DS2Component.PROVIDER.get(
              cActivity,
              currentActivity!!.application,
              adyen3DS2Configuration
            )
```

Now this part is where to problem lies. This will create a new observer every time it is called. The new observer will get the latest value that the component holds. Let's say you have called this twice, not only will this lambda be executed with the old value once, but whenever a new value is emitted the lambda will be executed twice (once for every observer). 
```
threedsComponent.observe(cActivity) { actionComponentData ->
            val threeds2ActionData =
              ActionComponentData.SERIALIZER.serialize(actionComponentData).toString()
            promise.resolve(threeds2ActionData)
          }
```

This is default Android `LiveData` behaviour. The solution would be to only call `observe` once. For example, by calling it from `onCreate` in your Activity. I am not familiar with React Native, but there must be a way to do this

**Comment by sasindroid** [comment]
Thanks @OscarSpruit. 
I managed to fix it.

**Comment by OscarSpruit** [comment]
Great! Happy to hear it's solved

**Comment by ronie2812** [comment]
> Thanks @OscarSpruit. I managed to fix it.

Hi @OscarSpruit can you tell me how did you fix that, as I am facing the same issue.

**Comment by ronie2812** [comment]
**Android**
The Scenario is stated below:
First I enter the 3D secure card details but with wrong CVV number:
Card: 4917 6100 0000 0000
Exp: 03/30
CVV: 736 (which is a wrong CVV number)
Name: Test

Now after submitting these details to /payments API it will respond with action data with resultCode IdentifyShopper.
After which 3D security UI will be triggered and enter the test code 1234 and submit it.

Now this code will observe the "threeDSResult"

```
 threeDSComponent.observe(this) {componentData ->
               sendDataToServer(componentData)
            }

```

This will response with resultCode CVV Declined.

Now once CVV declined error comes and you try again with the right 3D secured card details, it will still respond with CVV declined.

**Comment by jreij** [comment]
Hi @ronie2812, thanks for reaching out. I have a few questions so I can investigate a bit more:
- Which version of the library are you using?
- Can you try using `threeDSComponent.observeErrors` and see what does that return?
- Do you use the same 3DS2 component within the same activity/fragment to handle both the first decline and the second decline? Or do you recreate the activity or fragment between the 2 attempts?
- Can you enable extensive logs by calling `com.adyen.checkout.core.log.Logger.setLogcatLevel(Log.VERBOSE)` in your application class and filter your logs by `CO.` to see the checkout logs only and send them here?

**Comment by pdaplyn** [comment]
> Thanks @OscarSpruit. I managed to fix it.

@sasindroid - Do you happen to remember or have your fix at hand from 2 years ago? 😃
