### ISSUE TITLE
Payment Modal is not closing in Android for UPI Payments

### ISSUE THREAD

**Issue by XI2359-PrashantRao** [Adyen/adyen-android#629]
**Describe the bug**
In Android Payment modal for UPI Payments is not closing, after successful payment. It get stuck on Payment Authorized screen for ever.

**Comment by jreij** [comment]
Thanks for reaching out. Can you share a few more details? Are you using Drop-in or Components, and which version? Do you have any logs/screenshots?

**Comment by XI2359-PrashantRao** [comment]
> Thanks for reaching out. Can you share a few more details? Are you using Drop-in or Components, and which version? Do you have any logs/screenshots?

@jreij We are using it as a Drop In Component in the app and current drop in component is 3.6.4. 

Attached Image:
<img width="471" alt="Screenshot 2022-03-28 at 1 52 13 PM" src="https://user-images.githubusercontent.com/82538139/160356784-02f3bda6-949a-41a5-a0b8-c81a08fdce7f.png">

Its not going back to the app after the successful transaction in case of UPI payments.

**Comment by jreij** [comment]
This seems to be a redirect issue, especially if this is the only payment method not working for you. It could simply be a misconfiguration in your account. Please reach out to [our support team](https://support.adyen.com/hc/en-us/requests/new?ticket_form_id=360000705420) and they should be able to help you troubleshoot this better.
