### ISSUE TITLE
SEPA Direct Debit UI 

### ISSUE THREAD

**Issue by josh1dev** [Adyen/adyen-android#64]
Hi Adyen! 

I love the checkout, however, I've got some feedback on the SEPA Direct Debit UI screen. I feel like it makes more sense to have the name field above the IBAN number field (by default), because most people do it like that and it's shown on (most) debit cards like that. 

And I think it just overall looks better and gives a better experience.

**Edit:** To clarify, I would think it would be a good idea to have the UI built up like this by default for the Checkout SDK.

Just thought I'd give some feedback!

**Comment by caiofaustino** [comment]
Thanks a lot for your feedback! We will discuss internally and I'll let you know if we go forward with that change.

**Comment by Josh1Dev** [comment]
@caiofaustino Cool! Keep me posted ; )

**Comment by caiofaustino** [comment]
Hey Josh,

Just an update, we won't be making changes on the UI of version 2, but we will take your feedback into consideration when developing the UI for SEPA when it' available on version 3.

Cheers,
