### ISSUE TITLE
Can't test adding card using Appium - SDK elements not seen by Appium inspector

### ISSUE THREAD

**Issue by przan** [Adyen/adyen-android#646]
**Describe the bug**
Can't add payment card for test purposes using Appium. Appium inspector doesn't see input fields in Adyen DropIn, where it could provide test card numbers. Checked both releae and debug build. Appium worked fine with old Adyen Quick integration 2.4.13.

**To Reproduce**
1. Use Appium to start the app
2. Choose option to add a card in the app
3. Adyen DropIn is launched on card details input screen
4. Appium can't proceed, because it can't input card details

**Expected behavior**
It should be possible to perform Appium tests with Adyen DropIn/Components

**Screenshots**
<img width="370" alt="Screenshot 2022-01-31 at 09 39 47" src="https://user-images.githubusercontent.com/16773508/161486577-b015cd7e-baa7-46c2-95d4-0447a8e958b8.png">

**Desktop (please complete the following information):**
- Appium Inspector
  App Version: 2022.2.1
  Electron: 13.6.3
  Node.js: 14.16.0
- Appium Server GUI
  App Version: 1.22.2
  Electron: 7.3.3
  Node.js: 12.8.1
- Adyen DropIn 4.5.0

**Comment by jreij** [comment]
Hi, thanks for reaching out. Does Appium provide you with any logs as to why it cannot fill the card inputs?

**Comment by przan** [comment]
Appium inspector can't give us the views from the SDK, so we can't tell appium: please, enter this number in this field. The inspector sees our own views, but not those from DropIn.

**Comment by sasindroid** [comment]
Try this lookup 
id = "<com.your.package>:id/editText_cardNumber"

You can use Appium inspector. Inspector doesn't help in the lookup directly.
Copy the xml and find the right Id. Use this Id and do a search on appium inspector.
Anyway, the above id should work for card number.

**Comment by jreij** [comment]
For the Pay button it should be `id = "<com.your.package>:id/payButton"`

**Comment by adaflo** [comment]
@jreij Works! Thank you all very much for help :)

**Comment by przan** [comment]
Thank you guys!
