### ISSUE TITLE
Stored payment method cell background is white in dark mode

### ISSUE THREAD

**Issue by BenoitManhesLunabee** [Adyen/adyen-android#651]
**Describe the bug**
 `drop-in version 4.5.0`
At the displaying of `fragment_stored_payment_method.xml` the background of `removable_payment_methods_list_item.xml` is white on dark mode. I override the DropInActivity theme to change it but nothing changes.

**To Reproduce**
1. Set drop-in in app
2. Set device them to dark mode
3. open drop-in payment method stored

**Expected behavior**
The card cell backgroung should be transparent or black in dark mode

**Screenshots**
| light mode ✔️ | dark mode ✖️ |
| - | - |
![adyen_card_light](https://user-images.githubusercontent.com/71757449/161970339-b0f1ea6b-faa8-4c57-9cb4-e0b0ab290fb5.jpg)|![adyen_card_dark](https://user-images.githubusercontent.com/71757449/161970335-d6253119-eee9-45d7-8563-66ffc48509d6.jpg)

**Smartphone**:
Device: does not matter
OS: Android (various versions)

**Comment by OscarSpruit** [comment]
Thank you for opening this issue! As you may have noticed we do not really support dark mode out of the box, but this is being worked on. As a workaround for now, you could override the bottom sheet theme to use the correct colors. Something like this:

```
<style name="AdyenCheckout.BottomSheetDialogTheme" parent="AdyenCheckout.BaseBottomSheetDialog">
    <item name="android:colorBackground">@color/black</item>
    <!-- Maybe add some other colors you want to override, e.g. text colors  -->
</style>
```

I'm not sure if elevation overlays will work correctly on this particular view, so you may have to adjust the `android:colorBackground` to match the color of the bottom sheet background.

Hope this helps!
