### ISSUE TITLE
3D Not Authenticated

### ISSUE THREAD

**Issue by sasindroid** [Adyen/adyen-android#652]
Hi guys, I have a "**Card Component**" integration and I have followed the integration guide for additional actions [here](https://docs.adyen.com/online-payments/3d-secure/native-3ds2/android-component#3ds2-component) and I am now testing in production. 

Randomly, the transaction gets declined with refusal code "3D Not Authenticated". The adyen console does not provide details for the **pspReference** number. Digging into this, found the failed transaction has the below response from the Card Component.

_Note: base64 decoded the below for readability_
```
`**threeDSResult**

// Failure transaction
{
  "paymentResultDetails": "payment-result-details-here"
}


// Successful transaction
{
  "transStatus": "Y",
  "authorisationToken": "authorisation-token-here"
}`
```

Can you pls shower thoughts on why the threeDSResult has **paymentResultDetails** instead of an **authorisationToken**? I believe this is why Adyen throws 3D Not Authenticated because of a missing authorisationToken. Am I missing a valid use case here?

**To Reproduce**
1. As this is live, I have tried with multiple bank cards - visa & mastercard.
2. On a release build pointing to a live client key.
3. Perform multiple transactions and randomly one of the transaction fails.

**Expected behavior**
Components SDK to return **threeDSResult** with an **authorisationToken**.

**Adyen Components SDK (please complete the following information):**
 - Version 4.5.0

**Smartphone**
 - Device: Android
 - OS: 10

**Comment by jreij** [comment]
Hi, thanks for reaching out. Can you check the `action` JSON you receive from the Adyen backend in both success and failure scenarios? Does it always have `type = threeDS2` and an `authorisationToken` field?

**Comment by jreij** [comment]
The action response seems fine to me, I don't think I can identify the issue with the current information. Please reach out to [our support team](https://support.adyen.com/hc/en-us/requests/new?ticket_form_id=360000705420) and they should be able to help you troubleshoot this better.
