### ISSUE TITLE
G pay Integration

### ISSUE THREAD

**Issue by riddhee** [Adyen/adyen-android#66]
How to integrate G Pay
And from where we can get payment Reference object in gpay

**Comment by caiofaustino** [comment]
For quick integration just add the dependency for GooglePay module:
`implementation "com.adyen.checkout:googlepay:${checkoutVersion}`

The PaymentReference question I'm not sure if I understand. It's the same as the other payment methods. Are you using Custom Integration?

**Comment by riddhee** [comment]
Yes because i didn't found any demo of g pay using adyen 

you have demo for this?
implementation "com.adyen.checkout:googlepay:${checkoutVersion}

**Comment by riddhee** [comment]
How to use this? -- > implementation "com.adyen.checkout:googlepay:${checkoutVersion}
Can you please guide me on this?

**Comment by caiofaustino** [comment]
Just add it to your build.gradle file with the same version you currently have for checkout.

So for example it would be like:
```
implementation "com.adyen.checkout:ui:2.4.3"
implementation "com.adyen.checkout:googlepay:2.4.3"
```

I don't think we have an example other than the example-app on this repo.

**Comment by riddhee** [comment]
In example app there is no demo for g pay

**Comment by riddhee** [comment]
403 Bad  request while calling /paymentSession
Type Status Report

Description The server understood the request but refuses to authorize it.

**Comment by andre-sonect** [comment]
Carefull with Google Pay when asking for production access they said to change the logo that appears on the checkout UI to the GPay mark instead of the one provided by the SDK.

**Comment by caiofaustino** [comment]
This issue is a bit confusing. 
@riddhee if you still have problems please contact Adyen support so we can discuss your specific implementation issues more privately.
@andre-sonect I believe we have updated the logo on the server to match Google's requirements, please open a new issue if you still have problems with that
