### ISSUE TITLE
Google Pay icon not the right one according to GPay team

### ISSUE THREAD

**Issue by andre-sonect** [Adyen/adyen-android#67]
Hello,
After asking the GPay team for production access we got a response back saying that the logo was not the right one (see screenshot ) according to this https://developers.google.com/pay/api/web/guides/brand-guidelines#logo-mark
![imagem](https://user-images.githubusercontent.com/45486808/57230169-a06f9b80-700f-11e9-8a82-8c53f8214339.png)

**Comment by caiofaustino** [comment]
Hi Andre,

I will investigate this with our Design team and get back to you.

**Comment by caiofaustino** [comment]
Hi Andre,

The logo has been updated on the server to match Google's weird requirements, let me know if you still have issues.
