### ISSUE TITLE
Unsupported stored payment method - paypal

### ISSUE THREAD

**Issue by ramses-i** [Adyen/adyen-android#676]
**Is your feature request related to a problem? Please describe.**
I am trying to setup PayPal as the default payment method using Adyen DropIn for Android but I could see that when I make a payment in PayPal the account does get stored but it is not shown as a first option like when you pay with a Credit Card directly. I could see in the logs: 

E/CO.PaymentMethodsListViewModel: Unsupported stored payment method - paypal : PayPal. 

This log comes from:

com.adyen.checkout.dropin.ui.paymentmethods

**Describe the solution you'd like**
Would be nice that whenever I make a payment with PayPal it shows it as a last payment first on the list.

**Describe alternatives you've considered**
I could see that this is possible with Adyen Components for Android but it would require to change all the payment system to that.

**Comment by jreij** [comment]
Hi, thanks for reaching out. Yes indeed currently only Cards are supported as a stored payment method in Drop-in. Unfortunately I don't know when are we planning to add other stored payment methods but I will reply to this ticket if we have any updates 👍
