### ISSUE TITLE
Different pay button texts for different prices

### ISSUE THREAD

**Issue by dogramacigokhan** [Adyen/adyen-android#68]
Hi,

With the version 2.4.3, it's easy to set pay button format with or without price. The problem is, if the price is zero (e.g free trials), it makes much more sense to hide the price and say "Free" or "Start Trial", but this means hiding price from the button no matter the amount is.

It could be useful to have different pay button formats for zero-price (free products) and non-zero prices.

**Comment by caiofaustino** [comment]
Thanks for the suggestion. Unfortunately our current SDK is a bit limited on customisation options on the quick implementation, and it was not build with that flow in mind.

For that specific use case depending on what you want to achieve it might not be necessary to even start the checkout flow.

**Comment by Joao360** [comment]
I would like to do the similar to what @dogramacigokhan mentioned. Is the current SDK still limited on customisation?

**Comment by caiofaustino** [comment]
No, in the current versions you can choose to not pass an Amount to the Drop-in and override the String to customize the button text.
https://github.com/Adyen/adyen-android/blob/develop/drop-in/src/main/res/values/strings.xml#L11
