### ISSUE TITLE
Issues completing 3DS payments in Android

### ISSUE THREAD

**Issue by nasirky** [Adyen/adyen-android#681]
We have integrated Adyen Drop-In in our application. In case of a 3D Secure payment, the challenge browser/window opens where user can enter the 3D Secure code from their credit card provider. Upon entering the code, the process succeeds but the Window stay. The link to close the window (in case it takes longer) also doesn't work. The only option is cancelling and in that case, the app cannot tell the user that payment was successful (even though the payment goes through). Also no payment details call is made by the SDK which is done in case of any 3DS transaction.

**Response of payments call**
```
method = "GET"
paymentData = null
paymentMethodType = "scheme"
type = "redirect"
url = "https://..../threeDS/redirect/...."
```
**Expected behavior**
- The popup dismisses once the payment is successful and also gives the right result to the calling application.
- The payment detail method gets called.

**Note**
- This is working as expected on iOS. The only difference is that on iOS, we have using 3DS2 SDK version 2.2.4 while in Android we are using 2.2.6.
- This doesn't work in both debug & release configuration. We have Proguard disabled for debug mode as a whole and we have this configuration for release: `-keep class com.adyen.** { *; }`

**Comment by nasirky** [comment]
You can find the checkout logs [here](https://github.com/Adyen/adyen-android/files/8601971/3ds-failure.log).

It is a 3DS2 challenge via the web browser (inside the app). Here is some more information about the card's 3DS

```
3DS version: 2.1.0
3DS requested: C: Challenged
3DS challenged: Y: Successful
3DS device channel browser
3DS RReq trans status Y
```

**Comment by jreij** [comment]
I just checked the logs, the last thing we receive on the SDK side is that we launched the challenge in the browser, after that there are no logs which means that the challenge web page totally failed to redirect back to the app.

Unfortunately I cannot investigate redirect issues so I would recommend you reach out to [our support team](https://support.adyen.com/hc/en-us/requests/new?ticket_form_id=360000705420) and they should be able to help you troubleshoot this better.
