### ISSUE TITLE
java.lang.NoSuchFieldError: No field editText_holderName of type I in class at com.adyen.checkout.ui.internal.card.CardDetailsActivity.onCreate(CardDetailsActivity.java:197)

### ISSUE THREAD

**Issue by NerdFaisal404** [Adyen/adyen-android#69]
Version 2.4.1
I used : 
minSdkVersion = 21
        targetSdkVersion = 28
        compileSdkVersion = 28
        buildToolsVersion = '28.0.3'
        supportLibVersion = '28.0.0'
        constantLayout = '1.1.3'
        glide = '4.9.0'
        glideTransform = '2.0.2'

        rxJavaVersion = '2.2.2'
        rxAndroidVersion = '2.1.1'
        retrofit_version = '2.4.0'

        multidexVersion = '1.0.3'

        lifeCycle = '1.1.1'
        objectboxVersion = '2.3.4'
java.lang.NoSuchFieldError: No field editText_holderName of type I in class Lcom/adyen/checkout/ui/R$id; or its superclasses (declaration of 'com.adyen.checkout.ui.R$id' appears in /data/app/fr.sushi.app-N0EWdTzoKbNk6NOpwtFn-Q==/base.apk!classes2.dex)
        at com.adyen.checkout.ui.internal.card.CardDetailsActivity.onCreate(CardDetailsActivity.java:197)

**Comment by caiofaustino** [comment]
Looks like an obfuscation issue, do you have proguard or R8 enabled?

**Comment by NerdFaisal404** [comment]
I was create same file Activity like CardDetailsActivity.java, CheckoutActivity.java that's why it's created problem. I changed the class name now it working perfect. Thanks for your support.
