### ISSUE TITLE
[NEED ASSIST] Usage of Android Components (support request follow-up)

### ISSUE THREAD

**Issue by denis-colliot** [Adyen/adyen-android#697]
**Describe the bug**

I'm opening an issue as a follow-up for a [support request](https://www.adyen.help/hc/en-us/requests/2988629) that has been left unanswered for the past 5 days:

> Hello Adyen Support Team,
>
> I'm an android developer working for BlaBlaCar. I'm currently upgrading Adyen SDK to its latest version (4.5.0) by using Android Components (no Drop-in usage).
> 
> I'm facing questions for which I haven't been able to find answers in the official documentation.
> 
> In order to support both **Redirect** and **3DS2**, I need to manipulate both components `RedirectComponent` & `Adyen3DS2Component` in my user flow, right?
> 
> Adyen official documentation (see [here](https://docs.adyen.com/online-payments/android/components?tab=codeBlockmethods_request_s8g6E_Java_3#step-2-handle-the-redirect) & [here](https://docs.adyen.com/online-payments/3d-secure/native-3ds2/android-component#handle-redirect)) also specifies that Intent-Filter should be set for both redirections. Am I supposed to invoke `handleIntent` on both components when processing Intent in `onNewIntent` or `onCreate`?
> 
> Thanks for your response!

I'd really love to get some help on how to properly manipulate these components with our custom API.

**Comment by jreij** [comment]
Hi, thanks for reaching out. Do you need to handle redirects from the 3DS flow or from another payment method?
If it's only for the 3DS flow you don't need `RedirectComponent`, you can just use `Adyen3DS2Component.handleIntent`.

**Comment by denis-colliot** [comment]
Thanks for your quick answer.

Just to be clear on terminology, this what I have in mind (feel free to correct me):
- Redirect ⬄ 3DS(1)
- 3DS2 ⬄ 3DS2 (no surprise)

I noticed that `com.adyen.checkout.adyen3ds2.Adyen3DS2ComponentProvider` contains following implementation:
```kotlin
override fun getSupportedActionTypes(): List<String> {
    // <=> return listOf("threeDS2Fingerprint", "threeDS2Challenge", "threeDS2")
    return listOf(Threeds2FingerprintAction.ACTION_TYPE, Threeds2ChallengeAction.ACTION_TYPE, Threeds2Action.ACTION_TYPE)
}

override fun canHandleAction(action: Action): Boolean {
    return supportedActionTypes.contains(action.type)
}
```

So, if my app receives a `redirect` action type (3DS1), `Adyen3DS2Component` will not be able to process such action, right?

**Comment by jreij** [comment]
Oh ok I understand where the confusion is coming from. Even though we do not have `redirect` as one of the values returned by `getSupportedActionTypes`, the `Adyen3DS2Component` is indeed able to handle the redirect in case of a 3DS1 flow. Check this method out, in the same component:

```kotlin
    /**
     * Call this method when receiving the return URL from the 3DS redirect with the result data.
     * This result will be in the [Intent.getData] and begins with the returnUrl you specified on the payments/ call.
     *
     * @param intent The received [Intent].
     */
    override fun handleIntent(intent: Intent)
```

**Comment by jreij** [comment]
Hmmm not really, I would use a shared view model between the activity and fragment to pass data between them but there are other ways and it's a question of personal preference.

The only thing to keep in mind is that our components are view models. If you initialize a component with a certain fragment it will be bound to the lifecycle of this fragment and therefore will not be destroyed until that lifecycle is finished. Which means you cannot use the same component in the same fragment for 2 different payments, you must ensure you destroy the fragment after each payment. Same goes for activities.

**Comment by denis-colliot** [comment]
> The only thing to keep in mind is that our components are view models. If you initialize a component with a certain fragment it will be bound to the lifecycle of this fragment and therefore will not be destroyed until that lifecycle is finished

Yes, I already had these constraints in mind, thanks for the reminder!

> I would use a shared view model between the activity and fragment to pass data between them but there are other ways and it's a question of personal preference.

Using a shred VM scoped to the parent Activity was also my first idea. However, this VM would expose data (through `LiveData` or `Flow`) that would require manual cleaning to avoid notifying fragment in charge of payment when navigating _back_ to this fragment. I think I'll try/test different approaches to ensure a "one time" notification to the fragment.

Thanks again for your feedback, I'm closing this issue!

**Comment by jreij** [comment]
Hi again @denis-colliot, I might have missed one specific use case. What API version is your backend using? And when you make the `/payments` call, does it return an action of `type` = `threeDS2` with a `subtype`? Or is it `type` =  `threeDS2Challenge` / `threeDS2Fingerprint`?

**Comment by jreij** [comment]
Actually I realize I was wrong earlier. If you get a `redirect` action from the backend, after a `/payments` or a `/payments/details` call, you cannot use the `Adyen3DS2Component` to make that redirect, and you will need the `RedirectComponent` as well indeed.
But you can use `Adyen3DS2Component.handleIntent` to handle the redirect after it is done and returned to the app. And since API v67, the redirect is done automatically by the `Adyen3DS2Component` so that's why you wouldn't need the `RedirectComponent` in that case.
Sorry for the confusion, we will work on updating the docs. Let me know if you have any more questions.

**Comment by denis-colliot** [comment]
Awesome! Thanks again for your time and implication on my questions! 👍🏻
