### ISSUE TITLE
Xamarin support

### ISSUE THREAD

**Issue by rodrigueslg** [Adyen/adyen-android#7]
Is there any plans to do a Xamarin official integration?

I need to implement Adyen in my Xamarin project, and I'm encountering a lot of trouble trying to do this.

I think we may need to change the payment hub because of the poor support, but we already spent a lot of time on this.

**Comment by timon-langlotz** [comment]
Hello @rodrigueslg,

At this time, Xamarin support is not in our roadmap. We are focusing our efforts on delivering the best native experience.

Nevertheless, what issues are you encountering?

Regards,
Timon

**Comment by Drutol** [comment]
Hello,
sorry for resurrecting this old issue. Any updates on the matter? Official Xamarin bindings would be really helpful.

**Comment by Drutol** [comment]
Okay, just to let you know. 
I've managed to create bindings, it took me about an hour or two. There were a few issues with how the code is structured in java but nothing major.
Everything seems to be working fine for now :)

**Comment by timon-langlotz** [comment]
Thanks for your feedback @Drutol, and great to hear that you could set up your own bindings!

Cheers,
Timon
