### ISSUE TITLE
Notch seems not to be properly supported by build-in checkout UI

### ISSUE THREAD

**Issue by igorwojda** [Adyen/adyen-android#72]
Android emulator `Pixel 3XL (API 28)`

![image](https://user-images.githubusercontent.com/530122/58337622-18c2c300-7e3e-11e9-8606-f0cc674a8964.png)

**Comment by igorwojda** [comment]
It looks like there is some general problem with the status bar

![image](https://user-images.githubusercontent.com/530122/58338286-655ace00-7e3f-11e9-9bc4-c46194e22722.png)

**Comment by caiofaustino** [comment]
Hey, can you check if there is some configuration on your app manifest that could be changing this behavior? For us it seems to work fine.

![Screen Shot 2019-06-06 at 15 12 39](https://user-images.githubusercontent.com/3094935/59035443-9ab6e100-886d-11e9-9025-f9004476b20c.png)
