### ISSUE TITLE
Input titles are hidden

### ISSUE THREAD

**Issue by clarissip** [Adyen/adyen-android#725]
**Describe the bug**
The title of input fields in the DropIn are not shown during they aren't in focus. The field description is only shown if field is in focus or input is not valid.

**To Reproduce**
1. Open the DropIn to insert a new credit card without an payment amount

**Expected behavior**
Shouldn't the title be shown during the whole time independently from the user focus ?

**Screenshots**
![Screenshot_20220628-160447](https://user-images.githubusercontent.com/108350338/176204953-5b880cac-4165-4ca3-8114-47c9455ffd83.jpg)

**Smartphone:**
 - Device: Huawei P20 Pro
 - OS: Android 8.1
 - Version DropIn Version 4.5.0

**Additional context**
Hope this is a bug, not a feature. It was very confusing not seeing which input has to be typed in the input fields

**Comment by OscarSpruit** [comment]
Thanks for opening an issue! This is certainly not a feature. I think the text color is somehow white/transparent. This is probably caused by the base theme you are extending from. To customise the color of this title you can add something like this to your `styles.xml`
```
<style name="AdyenCheckout.TextInputLayout" parent="Widget.MaterialComponents.TextInputLayout.OutlinedBox">
    <item name="boxStrokeColor">@color/primaryColor</item>
    <item name="hintTextColor">@color/primaryColor</item>
    <item name="android:minHeight">@dimen/input_layout_height</item>
    <!-- This line changes the color of the title  -->
    <item name="android:textColorHint">YOUR_COLOR</item>
</style>
```

**Comment by clarissip** [comment]
Thank you for your fast response . Your solution fix my problem in an excellent way.
