### ISSUE TITLE
Make postal code optional

### ISSUE THREAD

**Issue by christianfindsen** [Adyen/adyen-android#727]
We want to show the postal code/ zip code field within the card component but we want it to be an optional field. 

When we add the postal field with the `AddressConfiguration().PostalCode` in the `CardConfiguration.Builder` the field is validated so the `cardComponentState.isValid` is always false if the user do not enter their zip code.

We would like the AddressConfiguration could be more customizable, so we can decide what we think is required

**Comment by jreij** [comment]
Hi, thanks for the suggestion! We will discuss it internally and update this ticket if we have any news 🙂

**Comment by christianfindsen** [comment]
Issue has been fixed with the 4.9.0 release. Thanks!
