### ISSUE TITLE
Not working On SDK version 22

### ISSUE THREAD

**Issue by mohd999** [Adyen/adyen-android#74]
I am paying via credit card, Entered the test credit card info and click pay button. 
Nothing happens on Android  v22. Though its working on Android v27.

**Comment by caiofaustino** [comment]
This is a known issue related to 3DS2 authentication, is a server issue.
https://github.com/Adyen/adyen-3ds2-android/blob/master/TROUBLESHOOTING.md#the-3ds2-challenge-fails-acssignedcontent-cannot-be-verified
