### ISSUE TITLE
Country drop down design issue

### ISSUE THREAD

**Issue by VidhyaLakshmiPhoton** [Adyen/adyen-android#749]
For Card, Country drop down theme issue is happening

**To Reproduce**
1. Go to 'Payment
2. Click on Credit card
3. Scroll down to Country drop down
4. See the theme issue

**Expected behavior**
The theme must be customisable

Attached Screenshots
![screenshot-1658852683791](https://user-images.githubusercontent.com/105855445/181293813-f402890a-dc95-46f9-b9fe-4808882f6a48.png)

**Smartphone (please complete the following information):**
 - Device:All devices

**Additional context**
This happens for state dropdown also

**Comment by VidhyaLakshmiPhoton** [comment]
![screenshot-1658852683791](https://user-images.githubusercontent.com/105855445/181059922-1fd4e3cd-4823-4c62-a73d-b29c4313399e.png)

**Comment by OscarSpruit** [comment]
Hi @VidhyaLakshmiPhoton, thanks for opening an issue! Could you share how your app's styling is set up?

**Comment by OscarSpruit** [comment]
Closing this issue because it has been inactive for a while.

Please reopen if you still encounter this issue with the latest version.

Thank you!
