### ISSUE TITLE
AndroidX Support

### ISSUE THREAD

**Issue by mkharibalaji** [Adyen/adyen-android#76]
Hi Team,
         Any idea on when there would be a support for androidX ?

Thanks,
Hari

**Comment by caiofaustino** [comment]
We don't intend to switch to AndroidX lib any time soon for compatibility with people still using the old libraries on their projects. But you can enable compatibility for yourself on the `gradle.properties`.
https://developer.android.com/jetpack/androidx/#using_androidx

Is that what you mean?

**Comment by mkharibalaji** [comment]
Yes - Currently i am enabling the JetPack but was curious to know to have a separate branch which supports the latest androidx build

**Comment by kaserdan** [comment]
Any plans in near future to migrate to androidx?

**Comment by caiofaustino** [comment]
No sorry, not at this moment. We'd need to make sure that we don't have any more people using AppCompat because it wouldn't be compatible for them.

**Comment by Woren** [comment]
@caiofaustino This doesn't make sense and it's very very dangerous. You're dependent on almost 2 years old library which wasn't updated or bugfixed since then. Also each AndroidX user of your library is replacing your very outdated version of the support library because transitive dependency (Gradle needs to do it) and will be replaced for a newer version which was never tested against. So you're supporting developers who didn't make this change in almost two years and definitely hurting developers which did this transition. Not mentioning that those developers can't turn off Jettier to have faster builds.

**Comment by caiofaustino** [comment]
@Woren I understand your point, and we'd also like to update to latest libraries, but you'd be surprised to see how many companies still hold on to legacy code, and updating would mean total incompatibility for them, while developers who are more up to date can still make use of the Jetifier and have the latest libraries on their app. 

We do have internal tests on an App running AndroidX libraries with the Jetifier to ensure compatibility, and we are always responsive to any issues found by merchants.

Also, we are keeping an eye on the [Google Play API requirements](https://developer.android.com/distribute/best-practices/develop/target-sdk). Which means that soon Google will demand apps to target at least API 29, which would force people to update and allow us to do the same. So in that sense you can expect us to update the SDK later this year.

**Comment by jrodbx** [comment]
We would like to eliminate Jetifier from our builds.  Given that support libs are 2+ years old at this point and not getting updated (in favor of androidx), would it make sense to say that this library could help their consumers by forcing them to upgrade to the latest and greatest?  The "Migrate to AndroidX" tooling in Android Studio has improved greatly over time so migration isn't a pain point.

**Comment by Woren** [comment]
@caiofaustino I'm glad to hear that you are at least doing internal test with it. Good work. Thanks

Also, can you please exactly point how targetSdkVersion relates to if developer can or cannot use old support library? Afaik if developer is ok with behavior changes in particular Android version and application is functional there is no need for them to change old version of some library (in this case support library). 

I'm looking for example at link with [changes for Android 10](https://developer.android.com/about/versions/10/behavior-changes-10).

**Comment by caiofaustino** [comment]
You are right @Woren, I was under the impression that people had to match the major version of the support libraries with the target api version, so naturally if target api 29 was required they would have to go to AndroidX.

We are planning to make the transition to AndroidX soon, just pending on another thing, so you can expect that in the following months.
