### ISSUE TITLE
How to listen for Webview close with Ideal redirect  component

### ISSUE THREAD

**Issue by ranjith-thandayuthapani** [Adyen/adyen-android#777]
I am using Ideal and Redirect component for iDeal Pay. After the webview is launched, if user close the webview i need to perform certain action. now redirect component's observeErrors is not triggered. Where we can listen for the webview close.

**Comment by albinus-sc** [comment]
I think this might be the same issue as https://github.com/Adyen/adyen-android/issues/582

**Comment by jreij** [comment]
Hi, thanks for reaching out. Yes indeed this is a duplicate of #582, please check the discussion there for a detailed explanation.
