### ISSUE TITLE
Adyen Android 2.4.4 + Sofort/GiroPay Redirection back to App not working

### ISSUE THREAD

**Issue by mkharibalaji** [Adyen/adyen-android#78]
Hi Team,
         We are using the Direct checkout with Adyen Android 2.4.4 + Sofort/GiroPay and at the end not able to redirect back to the App.Do we have to configure somekind of Redirect URL in Manifest.xml

Thanks & regards,
Hari

**Comment by mkharibalaji** [comment]
Sorry it was my mistake on the return url.

**Comment by mkharibalaji** [comment]
@fschrofner - Pass the return url highlighted as follows in the params for paymentSession API,

amount: {
                    value: this.props.cartAmt*100,
                    currency: 'EUR'
                },
                reference: this.props.cartID,
                shopperReference : this.props.user._id,
                shopperEmail : this.props.user.email,
                channel: (Platform.OS === 'ios') ? "iOS" : "Android",
                countryCode: countryCode.toUpperCase(),
                shopperLocale: shopperLocale,
                **returnUrl: (Platform.OS === 'ios') ? 'iosAppName-app://' : "checkout://android Package Name",**
                token,
                merchantAccount: MERCHANT_ACCOUNT

**Example : 
Android - Package is com.test then return URL will be "checkout://com.test"**

**Comment by fschrofner** [comment]
@mkharibalaji thanks for the fast response! using the right return url fixed the problem for me as well!
weird that our previous sdk version was overriding that return url for klarna (using `adyencheckout://`) and therefore worked fine without setting it to any specific value..
