### ISSUE TITLE
Field 'brand' is missing in paymentComponentJson - DropInService

### ISSUE THREAD

**Issue by daviddelijn** [Adyen/adyen-android#811]
**Describe the bug**
Users reported that when checking out with a stored payment method (BNP paribas VISA Debit card), their payments kept failing. 

We tracked down, that it's due to the field 'brand' missing on our call to the /payments endpoint. The request body we send to this endpoint is made up of data coming from the DropInService. In our override of onPaymentsCallRequested we log the params from the paymentMethod map and notice brand is missing.

**To Reproduce**
1. Add a VISA debit card as stored payment method
2. Try paying with this card on next checkout

**Expected behavior**
Successful checkout using the stored payment method

**Screenshots**
![image](https://user-images.githubusercontent.com/92297283/193579935-6b021b87-9c38-432b-b037-d50483ac2996.png)

![image](https://user-images.githubusercontent.com/92297283/193578578-b2e8d683-5628-4887-a7e7-4dad53ed0993.png)

**Smartphone (please complete the following information):**
 - Device: OnePlus Nord AC2003 as well as iPhone 13
 - OS: Android 11 / iOS 16

**Additional context**
Also reproducable on iOS! Not sure if I need to report another bug on the adyen-ios repo?

**Comment by jreij** [comment]
Hi, thanks for reaching out. I don't think this is an expected behaviour, could be an issue on the API side.

Please reach out to [our support team](https://support.adyen.com/hc/en-us/requests/new?ticket_form_id=360000705420), include some PSP references and they should be able to help you troubleshoot this better.

**Comment by jreij** [comment]
Hi again, were you able to solve this issue or do you still need help?

**Comment by Lotzzz** [comment]
Hello, I met the same issue after inputting the card info, I want to get the `brand` info for the credit card, but I got these fields only, is there any way to check it? Thanks. SDK version: 4.8.0
<img width="442" alt="截屏2022-11-16 18 41 24" src="https://user-images.githubusercontent.com/53738396/202159130-73d9190f-8e2d-4c9b-98d6-0cb2cdf86266.png">

**Comment by ozgur00** [comment]
Hi @Lotzzz! Thanks for reaching out. Can you provide information about the following questions so we can understand the issue better?

1. Do you receive an error, if so can you provide details about the error? (Where do you get the error? Is it from the API, and if so which endpoint?)
2. What kind of card you're using while having this issue? (Is it a dual branded card or a regular card?)

**Comment by daviddelijn** [comment]
Issue is still ongoing for us as well, a collegue of mine was in contact with your support team.
They claim that it will be fixed on your end. 

Apparantely the payment call needs this brand field to successfully handle certain payment methods, however, the android and iOS libs don't expose this brand field so we're not able to append it to our request.

This happens with stored payment methods, I'd imagine adyen has enough information when we pass through the stored payment ID?

**Comment by Lotzzz** [comment]
> 2\. dual

Hello @ozgur00, thanks for the reply, I didn't receive an error when calling the SDK, and also I can pay successfully. I just want to know the brand info for the inputting credit card, and I can see the brand type is `AMEX` in the drop in UI, but how to know the brand info in the `makePaymentsCall` callback?

**Comment by ozgur00** [comment]
Hi again @Lotzzz! If you use `onPaymentsCallRequested(paymentComponentState: PaymentComponentState<*>, paymentComponentJson: JSONObject)` callback instead of `makePaymentsCall(paymentComponentJson: JSONObject)` you can access the brand via `PaymentComponentState` object like the following:
```kotlin
    override fun onPaymentsCallRequested(
        paymentComponentState: PaymentComponentState<*>,
        paymentComponentJson: JSONObject
    ) {
        // ...
        if (paymentComponentState is CardComponentState) {
            val cardType = paymentComponentState.cardType
        }
        // ...
    }
```

**Comment by Lotzzz** [comment]
> Hi again @Lotzzz! If you use `onPaymentsCallRequested(paymentComponentState: PaymentComponentState<*>, paymentComponentJson: JSONObject)` callback instead of `makePaymentsCall(paymentComponentJson: JSONObject)` you can access the brand via `PaymentComponentState` object like the following:
> 
> ```kotlin
>     override fun onPaymentsCallRequested(
>         paymentComponentState: PaymentComponentState<*>,
>         paymentComponentJson: JSONObject
>     ) {
>         // ...
>         if (paymentComponentState is CardComponentState) {
>             val cardType = paymentComponentState.cardType
>         }
>         // ...
>     }
> ```

Thanks, for now, we just remove this field 😄
