### ISSUE TITLE
3DS2 incompatibility with latest Play-Services-Location Library

### ISSUE THREAD

**Issue by mlilienberg** [Adyen/adyen-android#859]
**Bug description**
In our app module we recently updated our play-services-location dependency from version 20.0.0 to the latest 21.0.0. Afterwards 3DS2 challenges for `Threeds2FingerprintAction` are failing with following exception: 

`java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in ....dex)`

We fixed the issue by downgrading play-services-locatition dependency:
from 
`'com.google.android.gms:play-services-location:21.0.0'`
 to
`'com.google.android.gms:play-services-location:20.0.0'`

The issue is reproducable with adyen 4.3.0 and 4.8.0
`'com.adyen.checkout:3ds2:4.8.0'`

We tried to exclude the location module from adyen checkout but this did not help.

<img width="1865" alt="Screenshot 2022-11-04 at 11 34 33" src="https://user-images.githubusercontent.com/6872282/199952502-fb468a49-b920-458a-b5ec-09049c7e9428.png">

**Comment by jreij** [comment]
Hi, thanks for reaching out! Please check [this issue](https://github.com/Adyen/adyen-3ds2-android/issues/49) on our 3DS2 repo, I think it's the same as yours.

**Comment by mlilienberg** [comment]
Hi, thank you for the quick response. Yes, it is the same issue. I will follow that one instead and close this ticket.

**Comment by jreij** [comment]
I will reopen this issue for visibility, if you don't mind. We cannot fix it on our side but it does affect us so we'll need to make a release to include the fix once it's released on the 3DS2 SDK's side.

**Comment by jreij** [comment]
Issue should be fixed in the latest 3DS2 SDK, will be included in the next release.

**Comment by jreij** [comment]
Fix is released now with [4.9.0](https://github.com/Adyen/adyen-android/releases/tag/4.9.0).
