### ISSUE TITLE
Adyen Drop-in 3.0.0 crashes on app recreation

### ISSUE THREAD

**Issue by geertjan-tiqets** [Adyen/adyen-android#89]
**Steps to reproduce:**
- Implement the Adyen Drop-in SDK in an app and start a payment with `DropIn.INSTANCE.startPayment()`.
- With an Adyen screen in the foreground (e.g. `PaymentMethodPickerActivity`), put the app in the background by pressing Android's home button.
- Simulate Android killing the app, for example by running `adb shell am kill <packagename>`.
- Open the app again. Android will recreate the app, bringing the Adyen Activity to the foreground again.

**Expected result:**
The app is back in the same state as it was before putting it in the background, with the Adyen screen open.

**Actual result:**
The app crashes.

**Cause:**
`DropIn.INSTANCE` is a singleton. When `startPayment()` is called, it sets the fields `resultIntent` and `configuration`. The singleton is used from, for example, `PaymentMethodPickerActivity`. When the app is recreated, `resultIntent` and `configuration` are uninitialized again, causing an exception in the Activity.

**Real life scenario where this could be a problem:**
For example when a user makes an iDEAL payment, and leaves the app to complete the payment in their banking app. The Android system can, to free up memory, temporarily kill apps in the background. So if this happens, and the user comes back from their banking app, the app using the Adyen Drop-in SDK will be recreated and crash.

**Comment by caiofaustino** [comment]
Thanks a lot for your detailed bug report!

We are aware of that issue and are currently working on a refactor of the internal DropIn flow to be a single Activity, and on the next release we will make sure to save and recreate the DropIn configuration state on `saveInstanceState()` for those scenarios.

**Comment by caiofaustino** [comment]
We just released version `3.2.1` with a fix for this. Can you try to see if you can still reproduce it?

**Comment by geertjan-tiqets** [comment]
Thanks, it's not crashing anymore. I did find a bug related to this, but I will create a new issue for that.
