### ISSUE TITLE
Field `details` doesn't exist inside `ActionComponentData`

### ISSUE THREAD

**Issue by VladimirWrites** [Adyen/adyen-android#91]
According to [docs](https://docs.adyen.com/checkout/android/components) (Send a /payments/details/ call containing the `actionComponentData.details`) there should be field `details` inside `ActionComponentData`, but it's not there. Is this a mistake in the documentation or in the implementation?

**Comment by caiofaustino** [comment]
Hi Vladimir,
Thanks for pointing it out, indeed it's a mistake in the implementation. The object is currently `actionComponentData.data` which is a bit redundant and not aligned with the other platforms. 
We will change that for the next release, but you can use the object from `actionComponentData.data` in the mean time.
