### ISSUE TITLE
PaymentMethod's param supportsRecurring doesn't work

### ISSUE THREAD

**Issue by VladimirWrites** [Adyen/adyen-android#92]
If I execute the following code:
```kotlin
        val paymentMethod = PaymentMethod()
        ...
        paymentMethod.supportsRecurring = true <- not doing anything
        paymentMethod.type = CardPaymentMethod.PAYMENT_METHOD_TYPE
     
        val cardComponent = CardComponent.PROVIDER.get(this, paymentMethod, cardConfiguration)
        cardComponent.observe(this, Observer {
            if (it?.isValid == true) {
                Log.d("PAYMENT", it.toString())
            }
        })
```
`CardComponent` will return the same `PaymentComponentData` regardless of if `supportsRecurring` is set to `true` or `false`. How can I save a credit card as a recurring payment method?

**Comment by ArmanSo** [comment]
Hi @VladimirWrites 
Along side of `supportsRecurring` you need to pass `ShopperReference` in `CardConfiguration`
Also be sure that in `CardConfiguration`,  `showStorePaymentField` is true.
