### ISSUE TITLE
Pay button remains inactive when using stored card

### ISSUE THREAD

**Issue by andreeamicu** [Adyen/adyen-android#95]
![saved_cards_error_prtscr](https://user-images.githubusercontent.com/17706717/62466878-144e4b00-b79b-11e9-90d6-a4c7ec3c4a70.jpg)
I'm using version 3.1.0 of Drop-in. I also pass ShopperReference in CardConfiguration
and set showStorePaymentField to true. Using one of the test cards, the payment goes through, and the stored card appears as an available payment method, but when I try to use it to make a new payment the payment button remains inactive. This error message about an invalid card number appears on Android 5.1, but not on Android  9, amd neither works.

**Comment by ArmanSo** [comment]
Hi @andreeamicu, 

I think I found the issue, just be sure I want ask a question related to `CardConfiguration `: is `setHolderNameRequire` set as true in your apps `CardConfiguration`?

**Comment by andreeamicu** [comment]
Yes, the setHolderNameRequire is set to true

**Comment by ArmanSo** [comment]
Alright I fixed that, also I fixed the UI issue that I can see from the screen shot that you attached :)

Version 3.1.1 will publish tomorrow with those fixes.

**Comment by andreeamicu** [comment]
Thank you so much for your help, Arman!

**Comment by ArmanSo** [comment]
@andreeamicu we released version 3.1.1, FYI sometimes it take a day to be in jCenter.

**Comment by andreeamicu** [comment]
@ArmanSo All is working good on my end. Thanks again for the help!
