### ISSUE TITLE
Payment Methods showing not accepted

### ISSUE THREAD

**Issue by jennyvbrown** [Adyen/adyen-android#954]
Discover card payments are showing not supported in a test environment. 

I am passing the following card configuration into the DropInConfiguration. 
       val cardConfiguration = CardConfiguration.Builder(context, ADYEN_KEY_TEST)
                .setEnvironment(Environment.TEST)
                .setShopperLocale(Locale.US)
                .setAddressConfiguration(addressConfiguration)
                .setHolderNameRequired(true)
                .setShowStorePaymentField(true)
                .build()

When I try to enter a test Discover Card (6011 6011 6011 6611 exp 03/2030 cvc 737), I get the following log: 
Brands: [DetectedCardType(cardType=DISCOVER, isReliable=true, enableLuhnCheck=true, cvcPolicy=REQUIRED, expiryDatePolicy=REQUIRED, isSupported=false, isSelected=false)]

Our iOS app, using the same test account key is able to accept discover card test payments. 
![Screen Shot 2022-12-08 at 9 58 24 AM](https://user-images.githubusercontent.com/31461054/206515927-7eeae0ac-d0f8-426a-83b5-823140f9e0f0.png)

**Comment by onurkaragunlu** [comment]
Hi @jennyvbrown,
Thank you for reaching out to us.
 Could you share the `PaymentMethod` response from your backend? Also, could you share the code where you call `startPayment` method with `PaymentMethodsApiResponse` for `DropIn`?

**Comment by jennyvbrown** [comment]
That is the issue, we were not pulling this response. It is working now. Thank you.
