### ISSUE TITLE
Style is not applied

### ISSUE THREAD

**Issue by VladimirWrites** [Adyen/adyen-android#96]
After update from `3.0.0` to `3.1.0` style is not applied anymore to `CardView` as well as to 3DS2.0 component.
I am using the approach described [here](https://docs.adyen.com/checkout/android/components#customizing-the-ui-for-3d-secure-2).
FYI my app has `Theme.MaterialComponents.Light.NoActionBar` as a base theme?

**Comment by ArmanSo** [comment]
Hi @VladimirWrites, 

We have a plan to implement theme customization for whole drop-in and component, so unfortunately it's not possible to use that approach any more.

What you can do is to override card compoent's style that available [here](https://github.com/Adyen/adyen-android/blob/master/card-ui/src/main/res/values/styles.xml) in your app's style file(s).

Cheers.

**Comment by VladimirWrites** [comment]
Thank you for the fast answer! 😊
