### ISSUE TITLE
Text in Confirm Card Removal dialog can't be seen 

### ISSUE THREAD

**Issue by neil-showpo** [Adyen/adyen-android#966]
**Describe the bug**
The text in confirm card removal is white when the card is being removed from the change payment method bottom sheet.

**To Reproduce**
1. Initiate payment to show payment bottom sheet
2. Click on 'change payment method'
3. Remove a stored card
4. Confirm card removal dialog will pop-up but the text for the action buttons are white and can't be seen easily.

**Expected behavior**

**Screenshots**
- Confirm card removal dialog
- Issue
<img width="684" alt="Screenshot_20221215_104528" src="https://user-images.githubusercontent.com/58998000/207763794-d7b897c3-e40b-49a0-a420-70d5dd62b7c0.png">
- Expected
<img width="684" alt="Screenshot_20221215_105248" src="https://user-images.githubusercontent.com/58998000/207763779-bb3654c4-0ef4-4a33-8fda-a32aca1e0e35.png">

**Smartphone (please complete the following information):**
 - Device: Emulator and Xiaomi Mi 10T Pro
 - OS: Android 12, MiUI 13
 - SDK Version: 4.9.0, 4.9.1

The text color is okay for the initial Drop-in bottom sheet that appears but inside the change payment method bottom sheet the dialog begins to display a white text for the buttons inside the confirm card removal dialog box.

**Comment by OscarSpruit** [comment]
Hi @neil-showpo, thanks for reaching out! With the layout inspector in Android Studio you can see where the text color is coming from (see screenshot below). Maybe this will already be enough to help you fix it, but if not, could you share your theming setup?

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/17701279/208427862-939e7480-9c7d-4e2a-b4b1-7d29a63035bd.png">

**Comment by neil-showpo** [comment]
Hi @OscarSpruit , I tried the layout inspector in Android Studio but I can't seem to get the attributes for the dialog 
<img width="1754" alt="Screen Shot 2022-12-20 at 3 05 58 PM" src="https://user-images.githubusercontent.com/58998000/208604755-9dc9b9c1-83c8-43f9-9671-0489f0077108.png">


For the theme we are using the following style to edit the colors in the Drop-in SDK

<img width="677" alt="Screen Shot 2022-12-20 at 1 39 37 PM" src="https://user-images.githubusercontent.com/58998000/208605382-2a7f06db-87b1-461b-bf7c-e5994859a71a.png">

<img width="809" alt="Screen Shot 2022-12-20 at 1 39 51 PM" src="https://user-images.githubusercontent.com/58998000/208605430-7dc38207-d239-4280-9563-be07d76f8623.png">

**Comment by neil-showpo** [comment]
Hi @OscarSpruit, overriding <item name="colorOnPrimary"> solved our issue. Thanks!
