### ISSUE TITLE
Activity does not receive onNewIntent or any result when Redirect screen is closed

### ISSUE THREAD

**Issue by hakanbagci** [Adyen/adyen-android#98]
3DS2 Redirect component opens a web view when it is a redirect action and it works fine when you provide valid data and submit it. Then `onNewIntent` is called on activity. However, when the opened web view is dismissed neither `onNewIntent` nor `onActivityResult` is called. I also tried to receive by observing errors from redirect component like below. No errors are received. 

`        
redirectComponent.observeErrors(this, Observer {...})
`

For 3DS2 component when challenge screen is dismissed it is possible to observer as error using the similar method above.

Am I missing something? Is there any way to observe redirect challenge screen dismiss? It will be really nice if we can observe it through redirect component. Thanks.

**Comment by caiofaustino** [comment]
Hey @hakanbagci. 
There is no way for the Component to know what happened after starting a Redirect. The only thing we know for sure is that the flow finished correctly when you receive the `onNewIntent` from the `returnUrl`.

Depending on how you Activity stack is setup I think it's fairly safe to assume that if you started a Redirect and after that your Activity was resumed but never received an `onNewIntent`, that the Redirect flow was either canceled or failed for some reason. But the `RedirectComponent` doesn't have access to the Activity to know that.

**Comment by hakanbagci** [comment]
@caiofaustino Thanks for quick response. Actually I was also thinking that solution as a back up solution. So I will go for that. Thanks again.

**Comment by 2020gaurav** [comment]
@hakanbagci Can you please share some more details about your solution? As onResume()/onRestart() called way before onNewIntent() in my case. How we can be sure if onNewIntent() will going to be called in some time so we should not consider it as user canceled case in onResume() ?
