### ISSUE TITLE
Loading indicator while the text fields are loading

### ISSUE THREAD

**Issue by jvsena42** [Adyen/adyen-android#987]
**Is your feature request related to a problem? Please describe.**
The text fields are not displayed immediately. The lib displays only a white screen

**Describe the solution you'd like**
Display a loading indicator while the text fields are not displayed

**Describe alternatives you've considered**
A callback to indicate when the content is loading

**Additional context**
![image](https://user-images.githubusercontent.com/44164057/209677097-374498d8-1dea-4968-a209-955c7d545beb.png)
![image](https://user-images.githubusercontent.com/44164057/209677119-b32a6e44-8c78-46be-8c90-c80483253b7b.png)

**Comment by OscarSpruit** [comment]
Hi, thank you for the suggestion! After calling `attach()` on the `CardView` the content should be shown right away, meaning there is no loading on our side. Our you sure you are not loading something yourself before calling `attach()`?

**Comment by jvsena42** [comment]
Hi, Thanks for the reply! I make a request to get the available payment method. Now I know how to handle this loading state
