### ISSUE TITLE
Translation support for card ui

### ISSUE THREAD

**Issue by hakanbagci** [Adyen/adyen-android#99]
In card ui the only supported language is English. 

https://github.com/Adyen/adyen-android/blob/master/card-ui/src/main/res/values/strings.xml

Is there any plan to support other languages?

**Comment by caiofaustino** [comment]
Yes, we have plans to support more languages in the future. But for now you can ad your own translation files overriding the component strings.

https://github.com/Adyen/adyen-android/blob/master/card-ui/src/main/res/values/strings.xml

**Comment by hakanbagci** [comment]
Thanks for quick response.
